### ISSUE TITLE
ESP32 MG MQTT Broker Suback header issue

### ISSUE THREAD

**Issue by vinicius-cerebrasc** [cesanta/mongoose#1001]
Hi there,

I've been using mongoose as an IDF component for a while with no problem, using MQTT.fx and mosquitto to interact with my ESP32 working as a broker. Also, I've been working with the system.net.mqtt C# library on an Android application, and had no issues interacting with mosquitto broker and MQTTBox.
But when I tried to use the C# library to connect to the ESP32, I get the following error whenever I try and subscribe to any topic:

System.Net.Mqtt.MqttException: Header Flag 2 is invalid for SubscribeAck packet. Expected value: 0.

Took a look inside mongoose.c and at first it seemed that the issues was that the mg_mqtt_suback function would always send a header with QoS flag equal to QoS(1), as in:

```
void mg_mqtt_suback(struct mg_connection *nc, uint8_t *qoss, size_t qoss_len,
                    uint16_t message_id) {
  size_t i;
  uint16_t netbytes;

  mg_send_mqtt_header(nc, MG_MQTT_CMD_SUBACK, MG_MQTT_QOS(1), 2 + qoss_len);

  netbytes = htons(message_id);
  mg_send(nc, &netbytes, 2);

  for (i = 0; i < qoss_len; i++) {
    mg_send(nc, &qoss[i], 1);
  }
}
```

but the issue persisted even when I tried to subscribe with QoS(1) from the C# client. Any ideas on this matter?

**Comment by nopnop2002** [comment]
Fixed header of SUBACK is 0x90.
So You have to change mongoose.c.

	void mg_mqtt_suback(struct mg_connection *nc, uint8_t *qoss, size_t qoss_len,
	                    uint16_t message_id) {
	  size_t i;
	  uint16_t netbytes;

	  //Comment out
	  //mg_send_mqtt_header(nc, MG_MQTT_CMD_SUBACK, MG_MQTT_QOS(1), 2 + qoss_len);

	  //Add
	  mg_send_mqtt_header(nc, MG_MQTT_CMD_SUBACK, 0, 2 + qoss_len);

	  netbytes = htons(message_id);
	  mg_send(nc, &netbytes, 2);

	  for (i = 0; i < qoss_len; i++) {
	    mg_send(nc, &qoss[i], 1);
	  }
	}
