### ISSUE TITLE
How to use http Put-Methode

### ISSUE THREAD

**Issue by dimitrovfor** [cesanta/mongoose#1002]
Hi everyone,

There is no example or Function to send a HTTP Put-Method.
Has someone Put-Message in use to give an instruction or an example how to generate.
I want to control light via Philips Hue Hub.
All I have to do is, send a PUT Message with Message Body {"on":true} on the Ressource “http://192.168.0.55/api/User/lights/5/state” to change the state.
Suppose “http_client.c” is a good start Code for this job. But have no idea without better example. 
Thanks a lot!

` /*
     * Copyright (c) 2014 Cesanta Software Limited
     * All rights reserved
     *
     * This program fetches HTTP URLs.
     */

    #include "mongoose.h"

    static int s_exit_flag = 0;
    static int s_show_headers = 0;

    static void ev_handler(struct mg_connection *nc, int ev, void *ev_data) {
      struct http_message *hm = (struct http_message *) ev_data;

      switch (ev) {
        case MG_EV_CONNECT:
          if (*(int *) ev_data != 0) {
            fprintf(stderr, "connect() failed: %s\n", strerror(*(int *) ev_data));
            s_exit_flag = 1;
          }
          break;
        case MG_EV_HTTP_REPLY:
          nc->flags |= MG_F_CLOSE_IMMEDIATELY;
          if (s_show_headers) {
            fwrite(hm->message.p, 1, hm->message.len, stdout);
          } else {
            fwrite(hm->body.p, 1, hm->body.len, stdout);
          }
          putchar('\n');
          s_exit_flag = 1;
          break;
        case MG_EV_CLOSE:
          if(s_exit_flag == 0) {
            printf("Server closed connection\n");
            s_exit_flag = 1;
          }
          break;
        default:
          break;
      }
    }

    int main(int argc, char *argv[]) {
      struct mg_mgr mgr;
      int i;
      mg_mgr_init(&mgr, NULL);

      mg_connect_http(&mgr, ev_handler, "http://192.168.0.55/api/user/5", NULL, NULL);

      while (s_exit_flag == 0) {
        mg_mgr_poll(&mgr, 1000);
      }
      mg_mgr_free(&mgr);

      return 0;
    }`

**Comment by cpq** [comment]
Closing this.
Please be more specific with the question. What exactly do you try to achieve?
Isn't http-client example sufficient enough?
