### ISSUE TITLE
mg_socketpair not work, return 0

### ISSUE THREAD

**Issue by hellokandy** [cesanta/mongoose#1004]
mongoose surport multihtead by gen socketpair method, but the " mg_socketpair" not work, return 0;
my system os: win7

**Comment by PuKathy** [comment]
"my_socketpair" use tcp socket, check the implement in your system.
also, you can use origin "socketpair" instead.

**Comment by cpq** [comment]
Please use the latest code - and reopen if required.
See example at https://github.com/cesanta/mongoose/tree/master/examples/multi-threaded
