### ISSUE TITLE
UDP vs TCP on Esp32

### ISSUE THREAD

**Issue by snahmad** [cesanta/mongoose#1005]
Hi,

I am using mongoose socket/networking library. I do get UDP disconnect event when I join  station/client Access point and UDP stop working on my own Access point  and if I reconnect UDP port programmatic after gotIP address event. or restart device then It starts working for station/client Access point UDP behaviour is different from TCP. TCP still working for both its own Access Point and station Access point after station access point join.

Any idea? 

Any workaround?

**Comment by cpq** [comment]
Please use the latest codebase.
If you're still getting issues, please share the failing example.
