### ISSUE TITLE
Weboscket connection fails due to invalid HTTP upgrade request

### ISSUE THREAD

**Issue by zkauker** [cesanta/mongoose#1007]
https://github.com/cesanta/mongoose/blob/ab650ec5c99ceb52bb9dc59e8e8ec92a2724932b/mongoose.h#L4947

When we try to connect to a server using `mg_connect_ws` with URL like `ws://host:port` and the server uses strict HTTP message validation the connection attempt will fail. The cause is that the upgrade request will be invalid because of the missing path in the URL. 

The HTTP command's first line is going to be: `GET  HTTP/1.1`.  We can workaround the issue by using url like `ws://host:port/` which makes the HTTP command look like `GET / HTTP/1.1` so it passes the validation.

The suggestion is to check if the URL's path is empty and if so, use `/` in the HTTP GET instead of empty string.

**Comment by cpq** [comment]
Closing this - please use the latest code.
The WS API has changed a bit. See examples at https://github.com/cesanta/mongoose/tree/master/examples
