### ISSUE TITLE
mongoose-free-6.9.exe is actually v6.7

### ISSUE THREAD

**Issue by mica** [cesanta/mongoose#1010]
The Windows binary, a supposed v6.9 release, is stating that it's v6.7. 

Screenshot: https://i.imgur.com/884FbIV.png

**Comment by aktk47** [comment]
Yes.
And can we get source code of the binary?

**Comment by cpq** [comment]
Closing this.
We've open-sourced Mongoose binary. It's source is available at https://github.com/cesanta/mongoose/tree/master/examples/desktop-server
