### ISSUE TITLE
UDP packet was cut off when len larger than 1460

### ISSUE THREAD

**Issue by hzylmf** [cesanta/mongoose#1017]
I send one packet which length is 1472, however I just receive 1460 bytes because of MG_UDP_IO_SIZE setting, so how do I get completed packet?
thanks~

**Comment by nliviu** [comment]
[MG_UDP_IO_SIZE](https://github.com/cesanta/mongoose/blob/ab650ec5c99ceb52bb9dc59e8e8ec92a2724932b/mongoose.c#L2394-L2396)
You can modify the default value using, eg. `-DMG_UDP_IO_SIZE=1500` in the compiler command line or in the makefile.
