### ISSUE TITLE
reverse_proxy example not work?

### ISSUE THREAD

**Issue by doublegsoft** [cesanta/mongoose#1019]
I followed the instructions and built the example. and when i access http://localhost:8000/api, get the empty response using curl. i didn't change any code in reserve_proxy.c .

**Comment by dmundt** [comment]
Issue #1065 seems to be related and is being fixed with PR #1066

**Comment by cpq** [comment]
Please use the latest codebase and example at https://github.com/cesanta/mongoose/tree/master/examples/http-reverse-proxy
