### ISSUE TITLE
Force Mongoose to always compile with mbedTLS

### ISSUE THREAD

**Issue by IngwiePhoenix** [cesanta/mongoose#1022]
On Mac OS, OpenSSL has been removed and has to be obtained through Homebrew - and on Windows, its different as well. Therefore, I'd like to stick with a solution I am a little bit familiar with - which would be mbedTLS.

What `-D`s to I use in order to tell Mongoose that I want only mbedTLS support at any time?

Thanks! :)

**Comment by PuKathy** [comment]
-DMG_ENABLE_SSL=1 -DMG_SSL_IF=MG_SSL_IF_MBEDTLS
#/* Lazy RNG. Warning: it would be a bad idea to do this in production! */
LOCAL_CFLAGS += -DMG_SSL_MBED_DUMMY_RANDOM （if you do not define this, you should implement the function. )

**Comment by cpq** [comment]
Thank you @PuKathy
