### ISSUE TITLE
problem encountered

### ISSUE THREAD

**Issue by zmcoo9** [cesanta/mongoose#1026]
Hello, I have encountered an error message. Have you encountered it before?How can I avoid this problem? Because I cannot reproduce this problem, so I want to know where the problem may be caused by improper use. Thank you very much for your help.

"mongoose.c:1583: mbuf_insert: Assertion `a->len <= a->size' failed."

**Comment by cpq** [comment]
That's not enough.
Please provide a way to reproduce.
