### ISSUE TITLE
Use with ESP8266 NONOS SDK

### ISSUE THREAD

**Issue by psykokwak-com** [cesanta/mongoose#1028]
Hi all,
I would like to use that library with an ESP8266 with the Arduino environement.
The Arduino toolkit use the NONOS SDK that require mongoose application to implement the mg_lwip_mgr_schedule_poll() function.
On exemples, this function is empty and we loop over sys_check_timeouts(). But in that case, it does not work. I don't know why.
Is someone has a working exemple for this configuration ?

Best regards,

**Comment by cpq** [comment]
https://github.com/cesanta/mongoose-os/blob/2.14.0/platforms/esp8266/src/esp_main.c#L125
