### ISSUE TITLE
MQTT over SSL crash : Fix proposal

### ISSUE THREAD

**Issue by psykokwak-com** [cesanta/mongoose#1029]
Hi All,
I tried to have a working MQTTS (over openSSL) broker but it crashs in mqtt_handler() MG_EV_POLL event.

I just added a if(!pd) break; that solve the issue.

**Comment by cpq** [comment]
Could you sign a CLA at https://github.com/cesanta/mongoose#contributions and send a PR please?

**Comment by cpq** [comment]
No response, closing.
