### ISSUE TITLE
two `#ifdef CS_ENABLE_STDIO` in a row in cs_dbg.h

### ISSUE THREAD

**Issue by azadkuh** [cesanta/mongoose#1031]
in `cs_dbg.h` there are two `#ifdef`s for `CS_ENABLE_STDIO` in a row at:

- first [line 88](https://github.com/cesanta/mongoose/blob/d5beb7ba3f3767891f3d85945d7d33c1d8596e37/src/common/cs_dbg.h#L88)
- and [line 101](https://github.com/cesanta/mongoose/blob/d5beb7ba3f3767891f3d85945d7d33c1d8596e37/src/common/cs_dbg.h#L101).

it seems the second one is redundant. the definition of `LOG` and `DBG` macros look convoluted by these `#ifdef`s.

**Comment by cpq** [comment]
Thanks.

The `LOG()` macro has been refactored lately, closing this one.
