### ISSUE TITLE
How to specify a custom 404 web page in c?

### ISSUE THREAD

**Issue by Evi5** [cesanta/mongoose#1036]
I want to define 404 page for simplest_web_server, and there is no idea after google. thks~

**Comment by nliviu** [comment]
If the requested uri from `struct http_message` does not exist, serve your custom 404 file.

**Comment by Evi5** [comment]
Thks for help, nliviu.
some code like this for some laters with the same problem.

static void ev_handler(struct mg_connection * nc, int ev, void *p) {
    switch (ev) {
    case MG_EV_HTTP_REQUEST: {
        struct http_message *hm = (struct http_message *) p;
        if (mg_vcmp(&hm->uri, "/login") == 0) {
            login_handler(nc, ev, p);
            // handle_sum_call(nc, hm);
        } else if(mg_vcmp(&hm->uri, "/main") == 0){
            mg_serve_http(nc, (struct http_message *) p, s_http_server_opts);
        } else{
            404..
       }
   }
}
