### ISSUE TITLE
Mongoose does not build with latest esp-idf (CMake build system)

### ISSUE THREAD

**Issue by avanbremen** [cesanta/mongoose#1038]
**The issue**
Using the CMake-based build system, Mongoose 6.15 and latest ESP-IDF (v4.0-dev-1136-g28f1cdf5e), build will fail due to the following warning being treated as an error by default:

```
mongoose.c: In function 'mg_do_ssi_include':
mongoose.c:9512:40: error: 'snprintf' output may be truncated before the last format character [-Werror=format-truncation=]
```

The error can easily be suppressed by changing the `CMakeLists.txt` file, however preventing the warning altogether would be preferred.

```
# Suppress error.
set_source_files_properties(mongoose.c
   PROPERTIES COMPILE_FLAGS
   -Wno-format-truncation
)
```

**Example project**
Please find an example project [on GitHub here](https://github.com/avanbremen/esp-mg-issue-1034). A detailed description can be found under **Issue 2** in [mg_test_main.c](https://github.com/avanbremen/esp-mg-issue-1034/blob/master/main/mg_test_main.c).

Thank you and kind regards,
Arjan

**Comment by cpq** [comment]
Now it does - please see https://github.com/cesanta/mongoose/tree/master/examples/esp32
That one builds on every commit.
