### ISSUE TITLE
HTTP request with URL-parameters directly following domain extension fails

### ISSUE THREAD

**Issue by avanbremen** [cesanta/mongoose#1039]
**The issue**
An HTTP request with URL-parameters directly following the domain extension, like `.ext?param=`, will fail. A trailing slash is required (like `.ext/?param=`).

Many APIs and websites promote using the format without trailing slash. Perhaps this can be supported by Mongoose as well.

**Example project**
Please find an example project [on GitHub here](https://github.com/avanbremen/esp-mg-issue-1034). A detailed description can be found under **Issue 3** in [mg_test_main.c](https://github.com/avanbremen/esp-mg-issue-1034/blob/master/main/mg_test_main.c).

Thank you and kind regards,
Arjan

**Comment by cpq** [comment]
Added to the unit test:

https://github.com/cesanta/mongoose/commit/749326c83a97d30013bc1bc33763ffcbd6720120
