### ISSUE TITLE
Mongoose+mbedTLS will use >100kB RAM for a single https request (ESP32)

### ISSUE THREAD

**Issue by avanbremen** [cesanta/mongoose#1040]
**The issue**
When running a barebone example of Mongoose (6.15) + mbedTLS on ESP32 and latest ESP-IDF (v4.0-dev-1136-g28f1cdf5e), a single https request will consume >100kB of RAM. This leaves only ~93kB for user code, which is not much for larger projects.

The memory footprint can be optimized (by the user) by reducing memory allocated for incoming and outgoing fragments (16kB default) and reducing the ca.pem file size (unfortunately mbedTLS loads all CA certificates in RAM), however another 40kB of RAM is allocated.

Please note that both 'optimizations' are less than optimal. Unfortunately mbedTLS does not support dynamic buffers, several proposals to do so have not been successful.

- Is there a way to optimize (and explain) the remaining 40kB of memory usage?
  - Via Mongoose, ESP-IDF or mbedTLS config?
- Would Cesanta be willing to share their optimized mbedTLS library?
  - Which would be absolutely great!

**Example project**
Please find an example project [on GitHub here](https://github.com/avanbremen/esp-mg-issue-1034). A detailed description can be found under **Issue 4** in [mg_test_main.c](https://github.com/avanbremen/esp-mg-issue-1034/blob/master/main/mg_test_main.c).

Thank you and kind regards,
Arjan

**Comment by cpq** [comment]
mnedtls uses 32k for the buffer. Mongoose buffers are controlled by the MG_IO_SIZE macro.
Anyways, 100k is an overkill. PLease use the latest codebase.
We use ESP32 a lot, and haven't observed such a memory hog.
Closing - feel free to reopen, and share the example that manifests the issue.
