### ISSUE TITLE
mqtt broker not publishing to multiple clients

### ISSUE THREAD

**Issue by vinicius-cerebrasc** [cesanta/mongoose#1043]
Using mongoose with esp-idf, when using multiple clients (mqtt.fx) connected to the ESP32 running as a broker, and all of them subscribing to # topic, I faced two situations:

1. If one of the clients publishes something, all of them get the message, including the one who sent, itself. (Working as intended)
2. If the ESP32 (the broker) uses `mg_mqtt_publish(...)` as a response to a publish event, only the client that sent the message, receives the message sent by the ESP32.

The `mg_mqtt_publish(...)` is being called from inside the event handler, somewhere before the `mg_mqtt_broker` function, on a custom `MG_EV_MQTT_PUBLISH` event processing, something just like the example itself:
```
static void ev_handler(struct mg_connection *c, int ev, void *ev_data) {
  if (ev != MG_EV_POLL) printf("USER HANDLER GOT EVENT %d\n", ev);
  
  if (ev == MG_EV_MQTT_PUBLISH)
  {
    mg_mqtt_publish(...);
  }
  mg_mqtt_broker(c, ev, ev_data);
}
```
How can I get around this so case two will act like case one (aka correct functioning)?
Should I manually iterate through sessions like `mg_mqtt_broker_handle_publish` function does?

**Comment by cpq** [comment]
Please use the current codebase and https://github.com/cesanta/mongoose/tree/master/examples/mqtt-server
