### ISSUE TITLE
Of upgrading GPL license

### ISSUE THREAD

**Issue by KoltesDigital** [cesanta/mongoose#1044]
Hi,

I wanted to integrate your library in a GPLv3 project, but it's mutually exclusive with GPLv2 that you use. I see two solutions:

1. [It is recommended to upgrade to GPLv3.](http://www.gnu.org/licenses/rms-why-gplv3.html) However this will force all the projects that use your library to upgrade as well, which won't be convenient.
2. The Free Software Foundation advises to use the following phrasing, allowing to use your library in a GPLv3 project.
> You can redistribute it and/or modify [the work] under the terms of the GNU General Public License as published by the Free Software Foundation, either version [x] of the License, or (at your option) any later version.

Therefore I propose the second option.

Could you please consider upgrading the license?

Thanks

**Comment by cpq** [comment]
Thanks for the notice.

We will unlikely modify the license.
