### ISSUE TITLE
wss connection is failed if using socks5 proxy

### ISSUE THREAD

**Issue by JulianYoon** [cesanta/mongoose#1057]
Hello.

I am writing some codes with mongoose websocket.
When I tried to connect wss://ourhost with socks5 proxy, it was failed with the error -3 MGSSL_ERROR in ev_handler.

How can I fix it?

My codes are blow.

	struct mg_mgr mgr;
	struct mg_connection *nc;
	struct mg_connect_opts opts;

	string uri = "wss://ourhost";

	mg_mgr_init(&mgr, NULL);
	memset(&opts, NULL, sizeof(mg_connect_opts));

        opts.ssl_ca_cert = pem_path;
	opts.iface = mg_socks_mk_iface(&mgr, "socks5proxy_host:port");

	nc = mg_connect_ws_opt(&mgr, ev_handler, opts, uri.c_str(), "push", NULL);
    
	if (nc == NULL) {
		fprintf(stderr, "Invalid address\n");
		return AERROR::FAILED;
	}

	while (!s_done) {
		mg_mgr_poll(&mgr, 100);
	}
	mg_mgr_free(&mgr);

**Comment by cpq** [comment]
Please use https://github.com/cesanta/mongoose/tree/master/examples/socks5-server
