### ISSUE TITLE
documentations links broken on website

### ISSUE THREAD

**Issue by schmurfy** [cesanta/mongoose#1058]
When you click on documentation you only get an almost empty page:

https://cesanta.com/docs/overview/intro.html

**Comment by nliviu** [comment]
What do you mean by "almost empty"?
The menu on the left side takes to [Concept](https://cesanta.com/docs/overview/concept.html), [Memory buffers](https://cesanta.com/docs/overview/mbufs.html), etc.

**Comment by schmurfy** [comment]
nevermind, it was not like that when I checked it, it was fixed in the interval.
