### ISSUE TITLE
mg_http_is_authorized parameters differ between mongoose.h and mongoose.c causing compiler warnings

### ISSUE THREAD

**Issue by mayhewinator** [cesanta/mongoose#1059]
The header declaration for mg_http_is_authorized has the second parameter defined as "struct mg_str path", while the .c file has the implementation's second parameter as "const struct mg_str_path". This difference causes a compiler warning that can cause build breakages in projects that treat warnings as errors.

The fix is to simply make them consistent.

**Comment by cpq** [comment]
Thank you.
That is not an issue anymore in the latest codebase.
