### ISSUE TITLE
Bug in mg_send_ws_header?

### ISSUE THREAD

**Issue by pkomma** [cesanta/mongoose#1061]
Hi,

in mongoose, version 6.15, mongoose.c, function mg_send_ws_header, line 10204 the data length is compared to 65535. This made one of my autobahn tests failing where the data size is explicitly set to 65535. When comparing the data length to 65536, i.e. len < 65536, the issue is solved.

I quickly checked the websocket specs which indicate that 65536 should be the value to be compared to.

Is this a bug of mongoose 6.15?

Thank you for clarifying.

Regards,
Philippe

**Comment by cpq** [comment]
Thank you.

Pushed https://github.com/cesanta/mongoose/commit/abfd81cb9d507d4b0603623e0de0e894bb859dfa
