### ISSUE TITLE
SSL WebSocket connections dropped when one client try to access with non-ssl websocket 

### ISSUE THREAD

**Issue by imradzi** [cesanta/mongoose#1063]
Hi, I was writing a websocket server and client and found out that with SSL websocket server and client, all connections are disconnected if one of the client connect without SSL. I fixed the mongoose.c code by adding if MG_F_IS_WEBSOCKET in two places, and the problem fixed. I am not sure if there's other unintended complication with this modification. So far, in my simple applications, it's ok.

Index: Utility/mongoose.c
==================================================================
--- Utility/mongoose.c
+++ Utility/mongoose.c
@@ -2981,12 +2981,15 @@
       DBG(("%p <- %d bytes (SSL)", nc, n));
       if (n < 0) {
         if (n == MG_SSL_WANT_READ) {
           nc->flags |= MG_F_WANT_READ;
           n = 0;
-        } else {
-          nc->flags |= MG_F_CLOSE_IMMEDIATELY;
+		}
+		else {
+			if (!(nc->flags & MG_F_IS_WEBSOCKET))
+				nc->flags |= MG_F_CLOSE_IMMEDIATELY;
+	
         }
       } else if (n > 0) {
         nc->flags &= ~MG_F_WANT_READ;
       }
     } else {
@@ -3007,11 +3010,12 @@
     }
 #endif
     mbuf_trim(&nc->recv_mbuf);
     mg_call(nc, NULL, nc->user_data, MG_EV_RECV, &n);
   } else if (n < 0) {
-    nc->flags |= MG_F_CLOSE_IMMEDIATELY;
+	  if (!(nc->flags & MG_F_IS_WEBSOCKET))
+		nc->flags |= MG_F_CLOSE_IMMEDIATELY;
   }
   mbuf_trim(&nc->recv_mbuf);
   return n;
 }

**Comment by cpq** [comment]
I believe the issue is with the OpenSSL API usage.
Please try the latest codebase.
