### ISSUE TITLE
Multithreading patterns?

### ISSUE THREAD

**Issue by odonnellnoel** [cesanta/mongoose#1068]
Hi, 

First off, great library!
I have a question about multi-threading I hope one of the devs could help with. 

My application  accepts HTTP requests in one thread (Thread A, same one as I'm calling my `mg_mgr_poll`), and the callback which accepts new connections. When it gets a new connection it reads the data and puts it on a queue, along with the `mg_connection*` received in the callback.

Some time later, another thread (thread B) reads the queue and processes the request, then sends a response to the same `mg_connection*`.

When I do this, I notice there is a delay of a few seconds before the data gets flushed out on the socket, in fact, the delay is until `mg_mgr_poll` times out in thread A.

I have found a work-around, and it's simple and seems to work with no adverse side effects (but I can't be sure): if I call `mg_mgr_poll(conn->mgr, 10000)` in thread B, the data gets flushed immediately.

A few questions arise from this.

1. This is a temporary hack and not very pretty, but I'm happy to keep it like this if there are no adverse side-effects. Are there any potential side-effects?
2. What do you recommend as a pattern for multi-threaded producer-consumer apps where one thread reads requests and another sends responses?

Thanks for any help

**Comment by cpq** [comment]
All mg_* functions are not thread safe except one: mg_broadcast.
If you want to offload processing to some other thread, use mg_broadcast for notifications.
See examples/multithreaded
