### ISSUE TITLE
mongoose.c:1586: mbuf_insert: assertion "a->len <= a->size" failed

### ISSUE THREAD

**Issue by FusEcho** [cesanta/mongoose#1069]
I am using zhe latest version of mongoose as a websocket streaming server
while I send binary data to all the connected clients , my application crashed with the following error

`mongoose.c:1586: mbuf_insert: assertion "a->len <= a->size" failed`

**Comment by gbkr1991** [comment]
i am also facing this problem

**Comment by tianmax** [comment]
I am also facing this problem, I am using the last version. Sending large amounts of data continuously over a period of time can cause this problem.

**Comment by cpq** [comment]
@tianmax do you see the same with the latest code?

**Comment by cpq** [comment]
Closing this - feel free to reopen if you see it manifesting on the latest codebase.
