### ISSUE TITLE
[Feature request] MQTT 5

### ISSUE THREAD

**Issue by krombel** [cesanta/mongoose#1070]
To use MQTT 5 I was asked to create an issue here.

More details you can find in the mqtt-libs repo: https://github.com/mongoose-os-libs/mqtt/issues/12

**Comment by cpq** [comment]
Thank you.

Could you elaborate on your specific use case please - what project you're working on?
Or this request does not have an underlying project, but rather is a general upgrade request?

**Comment by cpq** [comment]
No response, closing this.

**Comment by krombel** [comment]
Sorry for the late response.
Regarding your questions: I was in the progress of working on an IoT-Project which involved pushing metrics via MQTT.
I wanted to run latest tech on that to not be in the position of running a migration in future.

In the meantime we went for MQTT 3.1.1 leaving this as general upgrade request.
