### ISSUE TITLE
Parsing of "If-Modified-Since" crashes the server

### ISSUE THREAD

**Issue by sebhub** [cesanta/mongoose#1076]
Parsing of a "If-Modified-Since" uses mg_parse_date_string() which in turn may use sscanf() on a non-NUL terminated string. This is an issue if the sscanf() implementation uses strlen() on the input string (non-NUL terminated). This can lead to exceptions if the strlen() reaches to read protected memory.

A comment in mg_http_parse_range_header() suggests that this is a known issue. Why is the same approach not done in mg_parse_date_string()?

**Comment by cpq** [comment]
Thank you.

The latest codebase now relies on the Etag (If-None-Match) only, for the local cache.
Closing this.
