### ISSUE TITLE
SSLException when uploading a file but missing Auth-Header

### ISSUE THREAD

**Issue by hardysim** [cesanta/mongoose#1077]
We're using `MONGOOSE_VERSION "5.6"` (no resources to update ☹️) and are running into a `SSLException ` (calling from java) when trying a file-upload without the auth-header.

Using a `POST` (using TLS) and adding a binary file as the body is working fine until the client is not sending the auth-header. When doing so, it'll receive an `SSLException`.

> javax.net.ssl.SSLException: Write error: ssl=0x7365e26008: I/O error during system call, Connection reset by peer

It seems like the client *sometimes* receives the (expected) 401 but it crashes every time. Sending the correct auth-header results in a correct 200 though.

---

I can think of a problem with the upload because it's split into multiple parts (2048 bytes I think) and the server checks for the auth-header on the first part. When its missing, it'll respond with a 401 but a following upload-part will cause an error and therefore a crash on the client-side.

Maybe the server needs to wait until all upload-parts have been received and only then return the 401.

Is this correct? Is this an error on the server which responds too quickly and causing the error on the client? Or is this normal (HTTP spec conform) behavior and my client needs to be fixed (using OkHttp and Retrofit).

**Comment by cpq** [comment]
Please use the latest version. We do not support, or fix, the earlier versions.
