### ISSUE TITLE
Way to limit server incoming connections

### ISSUE THREAD

**Issue by pgp** [cesanta/mongoose#1079]
Is there any way to set the **listen** backlog size (i.e. the maximum number of simultaneous incoming connections)? I need to restrict my example tcp server to allow only one incoming connection, and from the examples I am not able to find it...

**Comment by cpq** [comment]
The listen backlog won't do what you want. It has a completely different semantics.
If you want to restrict your server to 1 client only, keep a connection counter, and set `c->is_closing` in the `MG_EV_ACCEPT` handler if the counter is greater than 0.
