### ISSUE TITLE
SSL not working in any version from 6.6 upward

### ISSUE THREAD

**Issue by naiteon** [cesanta/mongoose#1082]
I'm having a very strange issue. 

I'm on a Mac Book, Mojave installed, got openssl / libressl installed. (Im trying on a linux box as well with the same result).

On Mac the server starts and i found out there is a LibreSSL SSL_CONNECT: SSL_ERROR_SYSCALL, on linux im getting  OpenSSL SSL_CONNECT: SSL_ERROR_SYSCAL

I'm using certbot (letsencrypt), they provide a cert.pem, chain.pem, fullchain.pem and a privkey.pem. On NGINX I only use fullchain.pem as the certificate as they also include the intermediate certs, and privkey.pem as the key...  In my example im trying all possible combinations, even downloaded the cacert from Letsencrypt to use with bind_opts.ssl_ca_cert

Nothing works! The certificates are valid and are working perfectly in my nginx configuration and are still valid. I defined MG_ENABLE_SSL, the certificates are in the same folder than my executable...

I'm using the simplest_web_ssl_server only changing the certificates. But im including here my source just in case. BTW my domain name used is set in /etc/hosts and i tested thru dig and ping so not even that seems to be the cause of the error.

Thank you in advance

// #define MG_ENABLE_THREADS  // usadas para ativas threads no mongoos

// usada para ativas ssl no mongoose
#define MG_ENABLE_SSL 1 

#include "mongoose.h"

static const char *s_http_port = "8443";
static const char *s_ssl_cert = "fullchain.pem";
static const char *s_ssl_key = "privkey.pem";

static struct mg_serve_http_opts s_http_server_opts;

static void ev_handler(struct mg_connection *nc, int ev, void *p) {
  if (ev == MG_EV_HTTP_REQUEST) {
    mg_serve_http(nc, (struct http_message *) p, s_http_server_opts);
  }
}

int main(void) {
  struct mg_mgr mgr;
  struct mg_connection *nc;
  struct mg_bind_opts bind_opts;
  const char *err;

  mg_mgr_init(&mgr, NULL);
  memset(&bind_opts, 0, sizeof(bind_opts));
  bind_opts.ssl_cert = s_ssl_cert;
  bind_opts.ssl_key = s_ssl_key;
  bind_opts.error_string = &err;
  //bind_opts.ssl_ca_cert = s_ssl_ca;

  printf("Starting SSL server on port %s, cert from %s, key from %s\n",
         s_http_port, bind_opts.ssl_cert, bind_opts.ssl_key);
  nc = mg_bind_opt(&mgr, s_http_port, ev_handler, bind_opts);
  if (nc == NULL) {
    printf("Failed to create listener: %s\n", err);
    return 1;
  }

  // Set up HTTP server parameters
  mg_set_protocol_http_websocket(nc);
  s_http_server_opts.document_root = ".";  // Serve current directory
  s_http_server_opts.enable_directory_listing = "yes";

  for (;;) {
    mg_mgr_poll(&mgr, 1000);
  }
  mg_mgr_free(&mgr);

  return 0;
}

**Comment by cpq** [comment]
The SSL enabled unit tests are actually running on every push to this repository, verifying both client and server code on MacOS and Linux. See https://github.com/cesanta/mongoose/actions

Please revisit your code.

Closing this.
