### ISSUE TITLE
missing stat.h types.h fcntl.h on some toolchains

### ISSUE THREAD

**Issue by Xeenych** [cesanta/mongoose#1086]
I'm trying to compile mongoose on IAR EWARM 8.31 but it misses sys/stat.h sys/types.h and fcntl.h so mongoose won't compile.
Some googling showed up that Keil MDK ARM also misses these headers.

How do I complie mongoose for my STM 32 board?

**Comment by RiccardoDalFiume** [comment]
You have to implement your custom header. Look in /src/common/platform.h.
Try to copy pieces from other platform implementation until compilation errors are gone.

```
#if CS_PLATFORM == CS_P_CUSTOM
#include <platform_custom.h>
#endif
```

**Comment by cpq** [comment]
The @RiccardoDalFiume 's suggestion is correct.
On the latest sources, set `-DMG_ARCH=MG_ARCH_CUSTOM`
