### ISSUE TITLE
mg_http_reverse_proxy() eats Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by dd1dd1** [cesanta/mongoose#1093]
The http proxy code fails with a funny problem: if the proxied web server returns a response with "chunked" encoding, mg_http_reverse_proxy() code decodes the chunking and replies with a complete non-chunked message, but leaves the "Transfer-Encoding: chunked" header. This confused the next guy: header says "chunked", but the data is non-chunked.

My solution is to doctor the header, replace "T" with "X":
<pre>
static void mg_reverse_proxy_handler(...) ...
...
case MG_EV_HTTP_REPLY:
       {
          char* s = strstr((char*)hm->message.p, "Transfer-Encoding: chunked");
          if (s) {
             *s = 'X';
          }
       }
...
</pre>

Not 100% good because we are missing the "Content-Length" header, but works because we close the connection after sending the reply.

K.O.

**Comment by cpq** [comment]
Please use the latest codebase and example at https://github.com/cesanta/mongoose/tree/master/examples/http-reverse-proxy
