### ISSUE TITLE
mg_http_reverse_proxy() eats incomplete data

### ISSUE THREAD

**Issue by dd1dd1** [cesanta/mongoose#1094]
I see some webservers reply to the proxy requests with strange data and MG_EV_HTTP_REPLY never gets called. At the MG_EV_CLOSE event, I see that the reply is stuck in the mbuf. In the cases I see, it looks like the reply status is good ("200 OK"), the reply headers are good, but the reply data is empty (the last \n\r are not there). (The apache httpd proxy is okey with this, also adds a "Content-Length: 0" header). (I do not care why those webservers do this, I just want the mongoose proxy to work "the same" as the apache httpd proxy).

My solution is to send out the stuck data in the MG_EV_CLOSE event handler:
<pre>
static void mg_reverse_proxy_handler(...)
...
  case MG_EV_CLOSE: {
     struct mbuf *io = &nc->recv_mbuf;
     //printf("proxy close: mbuf %p, bytes %d\n", io, (int)io->len); //, io->buf);
     if (io->len > 0) {
        mg_send(pd->reverse_proxy_data.linked_conn, io->buf, io->len);
     }
     pd->reverse_proxy_data.linked_conn->flags |= MG_F_SEND_AND_CLOSE;
     break;
  }
</pre>

This works for me. I am not sure if mbufs are chained and I need to loop over the mbuf chain here. Would like to have advice from mongoose developers.

With all these fixes, the mongoose proxy seems to work as well as the apache http proxy (minus the URL rewriting for doctoring the absolute URLs inside the proxied replies).

K.O.

**Comment by cpq** [comment]
Please use the latest codebase and example at https://github.com/cesanta/mongoose/tree/master/examples/http-reverse-proxy
