### ISSUE TITLE
cmake and travis-ci

### ISSUE THREAD

**Issue by mirkokiefer** [cesanta/mongoose#110]
Hi @valenok,
thanks for this great library!
Don't know if this of interest to you but I created a simple cmake script and a travis-ci config.
CMake allows you to generate makefiles for a whole range of platforms and IDEs.
With travis-ci you can test the build on a hosted platform:
https://travis-ci.org/mirkok/mongoose/builds

You can find my code here:
https://github.com/mirkok/mongoose

If you are interested I can put together a pull request.

Regards,
Mirko

**Comment by sanspace** [comment]
It'd have been helpful for users submitting tiny PRs from Github UI. Just to ensure their change doesn't break the build. @nitsel88
