### ISSUE TITLE
mg_bind_opts has no member called ssl_cert. Neither does it have ssl_key

### ISSUE THREAD

**Issue by agent-etienne** [cesanta/mongoose#1103]
version 6.17

**Comment by gegzy** [comment]
You need to compile your source with MG_ENABLE_SSL defined (use -DMG_ENABLE_SSL in your gcc flags)

**Comment by agent-etienne** [comment]
Fixed it by just enabling passing -D MB_ENABLE_SSL -lssl -lcrypto to g++ after having a closer look at mongoose.h myself.
