### ISSUE TITLE
Apparent regression between 6.14 and 6.15: segfaults in mg_vcmp

### ISSUE THREAD

**Issue by archaro** [cesanta/mongoose#1108]
I'm updating a little pet project I've been working on for a few years, and ran into a problem when going from version 6.11 to 6.17.  A bit of git bisecting has identified the problem commit as:
Deliver EV_CLOSE to the last endpoint handler (e510da)
...which happened between 6.14 and 6.15

I've tested the cookie_auth example in 6.15 and 6.17, and in both cases it shows exactly the same error that I'm getting in my project (I used the cookie_auth example as a guide for what I wanted to do).

It appears to be a problem with the loop being iterated over multiple times when servicing a http request, and on the last time around there is no header data to process - so when mg_vcmp() is called, it eventually barfs on a null http_message.

I'm not sure if this is a bug, or if the example is out of date, or if I need more tea.

**Comment by cpq** [comment]
Closing this - please use the latest codebase, which has auth API refactored.
See https://github.com/cesanta/mongoose/tree/master/examples/multiple-logins
