### ISSUE TITLE
concurrent http multipart post data with mongoose

### ISSUE THREAD

**Issue by ashokanand** [cesanta/mongoose#1110]
I m trying to see how to support concurrent http multipart post requests using mongoose. 
these are multiple large http mulitpart post data requests. In ideal case, both of these processing should happen in parallel, and it should not be the case that after one completes, second starts.

Looking at mongoose implementation, it looks like once it gets a socket connection and gets some data, it tries to recv data as long there is data from the socket (do loop - mg_do_recv) The concern here is that a new connection streaming would get blocked while the data is being collected from existing connection. I am going to followup on multi-threaded example, but looks like that we may face similar issue there as well - as long as there is data from one socket, it will continue to consume it, and the other connection data would get blocked.

**Comment by cpq** [comment]
The latest codebase does not provide multipart handling API anymore.
