### ISSUE TITLE
can websocket client receive close reason and close code from server?

### ISSUE THREAD

**Issue by deetchtoys** [cesanta/mongoose#1118]

**Comment by cpq** [comment]
The WS close message is described at https://tools.ietf.org/html/rfc6455#section-5.5.1
Could you elaborate on what do you mean by "close reason" and "close code", please?

**Comment by deetchtoys** [comment]
I use websocket_chat_client.c from examples.
When websocket server send close frame, client just run into `MG_EV_CLOSE`. How can i receive close frame in `MG_EV_WEBSOCKET_FRAME`?

**Comment by cpq** [comment]
Currently Mongoose does not send a frame message:

```
        case WEBSOCKET_OP_CLOSE:
          mg_ws_close(nc, wsm.data, wsm.size);
          break;
```

Could you elaborate on why `MG_EV_CLOSE` does not suit?

**Comment by deetchtoys** [comment]
Our websocket server may send close frame when it occurs error, and close frame contains some descriptions which imply the error, and my websocket client should log it and upload to bigdata platform.

**Comment by cpq** [comment]
Please use the latest codebase, which sends `MG_EV_WS_CTL` events: CLOSE, PING, PONG.
