### ISSUE TITLE
MQTT on a TM4C129EXL

### ISSUE THREAD

**Issue by Sinic98** [cesanta/mongoose#1120]
Hello,
I am trying to use the microcontroller TM4C129EXL as a MQTT Client.
I am using Code Composer Studio and I already imported the example projects for the TM4C.

Now I think I have to implement the "mqtt_client" example. I am not really sure about how to do that...

I would really appreciate your help, cause I am a beginner..

Thanks and Regards
Ben

**Comment by cpq** [comment]
Please follow https://github.com/cesanta/mongoose/tree/master/examples/mqtt-client 
If you have more specific questions, please ask, be more specific.
