### ISSUE TITLE
Rename struct mbuf

### ISSUE THREAD

**Issue by numo68** [cesanta/mongoose#1127]
The `struct mbuf` is a relatively common name for a memory buffer and is unfortunately also present in some operating systems' include headers causing conflicts. I would recommend to follow the mg_ naming convention, rename the structure to mg_mbuf and probably also prepend mg_ to the functions manipulating it.

Thanks

**Comment by cpq** [comment]
That's done in the latest codebase - `struct mg_iobuf`.
Thank you.
