### ISSUE TITLE
NULL pointer dereference caused by incorrect error handling of calloc in mg_if_create_iface (mongoose.c:3464)

### ISSUE THREAD

**Issue by cve-reporting** [cesanta/mongoose#1141]
Incorrect handling of the value returned by calloc may lead to NULL pointer dereference in case of an allocation error.

Vulnerable code (mongoose.c:3464-3465):
>   struct mg_iface *iface = (struct mg_iface *) MG_CALLOC(1, sizeof(*iface));
>   iface->mgr = mgr;

See following recommendations for details (especially the calloc example):
https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors

The issue can be reproduced and tested using ErrorSanitizer (https://github.com/Samsung/ErrorSanitizer).

Reproduction steps:

1. Download and compile ErrorSanitizer (https://github.com/Samsung/ErrorSanitizer#compilation)
2. Set ESAN_PATH to ErrorSanitizer directory
3. Download and unzip attached map esan_map_002
[esan_map_002.zip](https://github.com/cesanta/mongoose/files/5136896/esan_map_002.zip)
4. Compile Mongoose examples
5. Enable coredumps using: 
>     ulimit -c unlimited
6. Run tested application with ErrorSanitizer using:
> AFL_USE_STDIO=Y LD_PRELOAD=${ESAN_PATH}/error_sanitizer_preload.so ./examples/coap_server/coap_server < esan_map_002
7. Analyze crash using:
> gdb ./examples/coap_server/coap_server core

You should receive similar output:

> GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
> Copyright (C) 2016 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-linux-gnu".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> 
> Reading symbols from examples/coap_server/coap_server...done.
> [New LWP 18667]
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> Core was generated by `./examples/coap_server/coap_server'.
> Program terminated with signal SIGSEGV, Segmentation fault.
> #0  0x000000000040a961 in mg_if_create_iface (vtable=0x41d9e0 <mg_default_iface_vtable>, mgr=0x7ffdf955bc80) at ../../mongoose.c:3465
> 3465	  iface->mgr = mgr;
> 

8. You can obtain more information using 'backtrace' and 'backtrace full' commands:

> (gdb) backtrace
> #0  0x000000000040a961 in mg_if_create_iface (vtable=0x41d9e0 <mg_default_iface_vtable>, mgr=0x7ffdf955bc80) at ../../mongoose.c:3465
> #1  0x0000000000408428 in mg_mgr_init_opt (m=0x7ffdf955bc80, user_data=0x0, opts=...) at ../../mongoose.c:2437
> #2  0x000000000040831e in mg_mgr_init (m=0x7ffdf955bc80, user_data=0x0) at ../../mongoose.c:2402
> #3  0x00000000004020c9 in main () at coap_server.c:52
> 

> (gdb) backtrace full
> #0  0x000000000040a961 in mg_if_create_iface (vtable=0x41d9e0 <mg_default_iface_vtable>, mgr=0x7ffdf955bc80) at ../../mongoose.c:3465
>         iface = 0x0
> #1  0x0000000000408428 in mg_mgr_init_opt (m=0x7ffdf955bc80, user_data=0x0, opts=...) at ../../mongoose.c:2437
>         i = 0
> #2  0x000000000040831e in mg_mgr_init (m=0x7ffdf955bc80, user_data=0x0) at ../../mongoose.c:2402
>         opts = {main_iface = 0x0, num_ifaces = 0, ifaces = 0x0, nameserver = 0x0}
> #3  0x00000000004020c9 in main () at coap_server.c:52
>         mgr = {active_connections = 0x0, hexdump_file = 0x0, ctl = {-1, -1}, user_data = 0x0, num_ifaces = 1, num_calls = 0, ifaces = 0xeb60b0, nameserver = 0x0}
>         nc = 0x0
>

**Comment by cpq** [comment]
Closing this, as network interface API was refactored in 7.0
