### ISSUE TITLE
Conection to express (node.js server)

### ISSUE THREAD

**Issue by RGDaniel** [cesanta/mongoose#1145]
https://github.com/cesanta/mongoose/blob/9fe1c93c9b5aeb37409e032878b2a3b31b5c5721/mongoose.c#L10261

hi when i connect to node.js
i need to add / in header to make a connection with express node.js, because chrome make header with / to work.

` l"GET %.*s / HTTP/1.1\r\n"  `

**Comment by cpq** [comment]
Daniel,
It is hard to understand your question.
Please make sure it is clear, and reopen.
