### ISSUE TITLE
upload file in chunked using http，write file error 

### ISSUE THREAD

**Issue by niuzhenbo** [cesanta/mongoose#1147]
Some dirty data was written into the file in the process of writing the file, causing the file to be damaged，when i use mg_file_upload_handler() handle upload 

The specific reason is that the length of each chunk is written to the file in the process of writing the file

![image](https://user-images.githubusercontent.com/37788950/92850388-f4b63700-f41e-11ea-99b6-fc823d39daf3.png)

**Comment by cpq** [comment]
Please use the current codebase and it's upload mechanism, see
https://github.com/cesanta/mongoose/tree/master/examples/file-upload
