### ISSUE TITLE
mongoose upload file don't support chunked

### ISSUE THREAD

**Issue by niuzhenbo** [cesanta/mongoose#1148]
when i use 
 * void ev_handler(struct mg_connection *nc, int ev, void *ev_data) {
 *   switch (ev) {
 *     ...
 *     case MG_EV_HTTP_PART_BEGIN:
 *     case MG_EV_HTTP_PART_DATA:
 *     case MG_EV_HTTP_PART_END:
 *       mg_file_upload_handler(nc, ev, ev_data, upload_fname);
 *       break;
 *   }
 * }
handle upload file , The received file is  corrupt. because every time the file is written, the length before the block is written into the file

![image](https://user-images.githubusercontent.com/37788950/93304833-3cc6c680-f830-11ea-9f9b-7d2fdf29d9e8.png)

![image](https://user-images.githubusercontent.com/37788950/93304738-13a63600-f830-11ea-994a-4049d6d8ab08.png)

**Comment by xingyun86** [comment]
can you receive MG_EV_HTTP_PART_BEGIN message? I test it but I only receive ev=100.

**Comment by xingyun86** [comment]
I solve it with myself now . Also thanks very much.

**Comment by cpq** [comment]
Please use the latest code , which provides an alternative upload mechanism:
https://github.com/cesanta/mongoose/tree/master/examples/file-upload
