### ISSUE TITLE
aggregation isn't resolving/rejecting or firing the callback

### ISSUE THREAD

**Issue by laneme** [cesanta/mongoose#1149]
This could be because of my lack of understanding of the aggregation framework but here it is.

```
    const aggregateStage1 = {
        $match: {
            room_id: roomId, 'users.user_id': userId
        }
    }

    const aggregateStage2 = {
        $filter: {
            input: '$messages',
            as: 'msg',
            cond: {
                $lt: {"$$msg.timestamp": timestamp},
            }
        }
    }
```
These are my two stages. I ran them like this 
```
let res = ChatModel.aggregate([
        aggregateStage1, aggregateStage2
    ], (err, sum) => {
        console.log(err,sum);
    })
res.then(resFunc).catch(errLogger)
```
The problem is, this isn't returning anything. The promise is never being resolved, the callback is never being called. And program is just exiting(it usually hangs there for moment if there's a promise pending). Not even throwing any error.

I also tried using just one stage, tweaking the aggregation queries and also mongoose provided `aggerate().match(...) ...`
Nothing seem to work. Someone can assist me on this?

**Comment by cpq** [comment]
Wrong repo.
