### ISSUE TITLE
The HEAD method return a message-body in the response

### ISSUE THREAD

**Issue by alex-kalin** [cesanta/mongoose#1151]
The HEAD method return a message-body in the response, but according to rfc2616 (https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html) it should not: 

"The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response".

![Mongoose test](https://user-images.githubusercontent.com/14827348/93772129-21402f00-fc27-11ea-8002-eb763790208d.png)

**Comment by cpq** [comment]
Fixed in the latest codebase, closing.
