### ISSUE TITLE
Provide a way to get mg_serve_http_opts defaults without calling mg_serve_http

### ISSUE THREAD

**Issue by normanr** [cesanta/mongoose#1153]
`mg_serve_http` will set the defaults for the passed `mg_serve_http_opts` if they're NULL, but it would be useful to be able to get the default values without calling `mg_serve_http` (possibly because there's no active request, or because the code wants to do additional processing before calling `mg_serve_http`). This could be done by moving the setting of defaults to a dedicated function, or by moving them to a "static const struct" (or similar) that can be accessed from outside the mongoose library.

**Comment by cpq** [comment]
The latest codebase has been refactored.
The options structure is gone, now the only configurable parameter is the path to the web root directory.
See https://cesanta.com/docs/#mg_serve_dir
