### ISSUE TITLE
cgi_file_pattern is dangerously misdocumented

### ISSUE THREAD

**Issue by normanr** [cesanta/mongoose#1154]
`cgi_file_pattern` is currently documented as: `Set to non-NULL to enable CGI, e.g. **.cgi$|**.php$" ` but if it's left as `NULL`, then it defaults to `"**.cgi$|**.php$"` (similar to how `ssi_pattern` defaults to `"**.shtml$|**.shtm$"`). Either the documentation should be updated to reflect this, or the default behavior should be changed to match the documentation.

**Comment by cpq** [comment]
Hey Norman, great to hear from you!

CGI support has been ditched from the latest codebase, rendering this issue obsolete, not sure how acceptable this "fix" is.
