### ISSUE TITLE
"register" storage class specifier is deprecated

### ISSUE THREAD

**Issue by Jeija** [cesanta/mongoose#1158]
When trying to compile mongoose with C++17 or later, I get the following compiler warning:
```
src/mongoose.c:997:21: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  997 |   register uint32_t a, b, c, d;
      |                     ^
src/mongoose.c:997:24: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  997 |   register uint32_t a, b, c, d;
      |                        ^
src/mongoose.c:997:27: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  997 |   register uint32_t a, b, c, d;
      |                           ^
src/mongoose.c:997:30: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
  997 |   register uint32_t a, b, c, d;
```

This is because the `register` storage class specifier [was deprecated in C++17](https://en.cppreference.com/w/cpp/language/storage_duration).

I see two possible fixes:

* Remove `register`, since most modern compilers ignore it anyway; however, given that mongoose has so many supported platforms, I'm not sure that is the case for all possible targets though.
* Add something [like this](https://github.com/ARM-software/CMSIS_5/issues/345) to the header:
```
#if (__cplusplus - 0) >= 201703L
  #define __REGISTER
#else
  #define __REGISTER                             register
#endif
```
and then use
```
__REGISTER uint32_t a, b, c, d;
```

**Comment by cpq** [comment]
Pushed https://github.com/cesanta/mongoose/commit/4d123a15f9495e33eb0048a5d82d3da049393834

Thank you.
