### ISSUE TITLE
openssl 1.0.1

### ISSUE THREAD

**Issue by kashfi59** [cesanta/mongoose#1166]
when compile mongoose v7.0 project source code and want to use https, the 'SSL_use_certificate_chain_file' function is not defined in openssl 1.0.1. I solve this problem:

+ #if OPENSSL_VERSION_NUMBER > 0x10002000L
    else if ((rc = SSL_use_certificate_chain_file(tls->ssl, opts->cert)) != 1) {
      mg_error(c, "Invalid CA, err %d", mg_tls_err(tls, rc));
      goto fail;
    }
+#endif

**Comment by cpq** [comment]
Thank you,
pushed https://github.com/cesanta/mongoose/commit/4519ea568d035512baaba1bb2094b056cbdae4c4
