### ISSUE TITLE
Mongoose 6.15 mbuf resize leak?

### ISSUE THREAD

**Issue by pkomma** [cesanta/mongoose#1170]
Hi,

using the memory profiling tool Heaptrack memory leakage is shown in both the functions mbuf_resize and mbuf_insert - c.f. attached images below.
In our application, we set both, MG_UDP_IO_SIZE and MG_UDP_IO_SIZE to 1.048.576. Shrinking the sizes to 65536 reduces the leakage, but the leakage still remains.

Is this a known issue for 6.15? Will an update to 6.18 help?

As for the development environment, we use linux x64/gcc.

Any help is highly appreciated!

Regards
Philippe

![heaptrack_pratelPrg](https://user-images.githubusercontent.com/8381916/101837501-69dcf980-3b3f-11eb-94e0-acc2035613a6.png)
![heaptRack_pratelPrg2](https://user-images.githubusercontent.com/8381916/101837504-6b0e2680-3b3f-11eb-9b5a-e6e1252a669b.png)
![mongoose](https://user-images.githubusercontent.com/8381916/101837506-6c3f5380-3b3f-11eb-8d81-b72a064bc4f4.png)

**Comment by cpq** [comment]
Please use the latest version.
If you use UDP, then buffer cleanup is you app's responsibility.
Are you sure it is cleaned up properly?

Anyhow, please publish the reproducible test case, ideally a PR against the unit test.
So far, it looks like an issue in your code.
