### ISSUE TITLE
v7.0 won't compile for ESP8266

### ISSUE THREAD

**Issue by mill1000** [cesanta/mongoose#1173]
Looks like the newest release won't build for ESP8266 against the ESP8266_RTOS_SDK.

* MG_ARCH is not properly detected. It seems to be selecting MG_ARCH_ESP32 which seems incorrect.
* After overriding MG_ARCH=MG_ARCH_ESP8266 I get the following include error because I'm not using the Arduino ESP8266 stuff.

> mongoose.h:133:28: fatal error: user_interface.h: No such file or directory

**Comment by cpq** [comment]
Fixed that, and added ESP8266 example, see https://github.com/cesanta/mongoose/tree/master/examples/esp8266
