### ISSUE TITLE
v7.0mg_http_upload(),when write to file , the func didn't part http message and content of the file

### ISSUE THREAD

**Issue by erinliu0428** [cesanta/mongoose#1174]
The following code comes from the func mg_http_upload() of v7.0
`fwrite(hm->body.ptr, 1, hm->body.len, fp);`
hm->body is write to fp directly,as a result, there will be the following problems:
- If I wan't to upload a file,the content is:
`hahahaha`
- But when request is end,I got:
`----------------------------003448489173877085968575
Content-Disposition: form-data; name="file"; filename="README.md"
Content-Type: text/markdown
hahahaha
----------------------------003448489173877085968575--`
the message in http body was left in the file.

**Comment by cpq** [comment]
The upload mechanism has changed. See documentation:

https://cesanta.com/docs/#mg_http_upload
