### ISSUE TITLE
Is mongoose able to run on a specific NIC in an environment with multiple NICs?

### ISSUE THREAD

**Issue by eshangui** [cesanta/mongoose#1175]
for example, I have a board with several NICs, ethernet, wifi and 4G and all NICs are connected to network, now I want mongoose to connect to a http server via ethernet and a mongoose broker via 4G, is it possible to specify a NIC name such as eth0 to a mongoose connection?

**Comment by cpq** [comment]
Yes - just use a corresponding IP address to listen on, or to connect to.
