### ISSUE TITLE
v7.0 compile issues with MSVC++

### ISSUE THREAD

**Issue by paladin-t** [cesanta/mongoose#1176]
I found two issues:

1. the compiler complains about `#define inline __inline` in mongoose.h
2. the `#define sleep(x) Sleep((x) *1000)` conflicts with any other functions named `sleep`

**Comment by cpq** [comment]
Thanks. What's your environment - OS and compiler version ?

**Comment by paladin-t** [comment]
win7 64bit, visual studio 2015

**Comment by cpq** [comment]
Thank you. Could you take a look, what is the value of `_MSC_VER` constant in the SDK headers, please?

**Comment by paladin-t** [comment]
it's 1900

**Comment by cpq** [comment]
Pushed a change that removes those defines - please retry

**Comment by cpq** [comment]
Closing this - please reopen if required.
