### ISSUE TITLE
Question: Does mongoose run on MediaTek MT3620 / Arm Cortex-A7?

### ISSUE THREAD

**Issue by Busch** [cesanta/mongoose#1178]
Hello Community,

Is it possible to run mongoose on a Microsoft Azure Sphere Development Kit (based on MediaTek MT3620 / Arm Cortex-A7 CPU)?
Hardware details: https://www.mediatek.com/products/AIoT/mt3620

**Comment by cpq** [comment]
Most probably, yes.
What is the intended use of the Mongoose library on that platform, which MS SDK does not cover?

**Comment by cpq** [comment]
Closing this. Feel free to reopen - in that case, please provide more context and background information.
