### ISSUE TITLE
How can I handle the common multipart request without parameters 'name' and 'offset'?

### ISSUE THREAD

**Issue by CodeBiang** [cesanta/mongoose#1179]
Hello! I have a question about mongoose 7.0!
I used mongoose 6.X to handle multipart request with MG_EV_HTTP_MULTIPART_REQUEST, but I don't know how to solve the file uploading problem when I‘m using version 7.0

Is there some else methods to handle file uploading except the API `mg_http_upload`?

**Comment by cpq** [comment]
There is a file uploading example at https://github.com/cesanta/mongoose/tree/master/examples/file-upload

You could use a regular multipart upload, but you'd need to parse the body manually.
