### ISSUE TITLE
Example "http-restful-server" is not working on OPENSSL.

### ISSUE THREAD

**Issue by bobooboo** [cesanta/mongoose#1180]
Thanks you to update the example of http-restful-server for HTTPS.
The example works fine with mbedtls.

But it doesn't work with **openssl**.

In particular, the event_hander function does not receive ev "MG_EV_HTTP_MSG".
```c
static void fn(struct mg_connection *c, int ev, void *ev_data, void *fn_data) {
  if (ev == MG_EV_ACCEPT && mg_url_is_ssl(s_listen_on)) {
   ...
  } else if (ev == MG_EV_HTTP_MSG) {
    //
    // No event with openssl
    //
    ...
  }
  (void) fn_data;
}
```

When using mbedtle, I used your makefile of example.
```make
CFLAGS += -DMG_ENABLE_MBEDTLS=1 -I$(MBEDTLS_DIR)/include -I/usr/include
CFLAGS += -L$(MBEDTLS_DIR)/lib -lmbedtls -lmbedcrypto -lmbedx509
```

When using openssl I used the following code.
```make
CFLAGS += -DMG_ENABLE_OPENSSL=1 -I$(OPENSSLDIR)/include -I/usr/include
CFLAGS += -L$(OPENSSLDIR)/lib -lssl -lcrypto
```

The main.c source code is the same as your example "http-restful-server".

It was tested in the following environment.
- ubuntu 20.04 LTS
- openssl 1.1.1f

Could you please check this issue?

**Comment by cpq** [comment]
See latest commit - the openssl build was fixed, and added to the unit test.
