### ISSUE TITLE
Missing support for URI rewrites in 7.0

### ISSUE THREAD

**Issue by krame505** [cesanta/mongoose#1184]
The desktop server example still takes URI rewrites as an option, but these are ignored:
https://github.com/cesanta/mongoose/blob/master/examples/desktop-server/main.c#L10

Has this feature been permanently removed or is this an unintended omission?

**Comment by cpq** [comment]
The feature is removed from the example.
Pushed https://github.com/cesanta/mongoose/commit/2c1324dc0afa069628e916ab3d8f822bb5e48b31 .
Said that, the rewrite functionality is still possible to implement by:
- iterating over the rewrites, see https://cesanta.com/docs/#mg_next_comma_entry
- match requested URI against the currently iterated rewrite item
- if there is a match, call `mg_http_serve_dir()`
