### ISSUE TITLE
No way to serve a file with custom headers in v7.0

### ISSUE THREAD

**Issue by advancednavigation** [cesanta/mongoose#1187]
The headers argument has been removed from the mg_http_serve_file() function but there is no alternative way to set headers when serving a file.

Not being able to set custom headers means this web server cannot be used in cross-origin resource sharing applications.

Can you please look at some way to get this functionality back.

**Comment by cpq** [comment]
Pushed https://github.com/cesanta/mongoose/commit/b7a79a556a67bc7f64543e299adfa6c872ca1f3f

**Comment by lnksz** [comment]
https://github.com/cesanta/mongoose/commit/b7a79a556a67bc7f64543e299adfa6c872ca1f3f#r45735570
?
