### ISSUE TITLE
Dashboard Build Error with mos build ESP32 Platform?

### ISSUE THREAD

**Issue by vsltech** [cesanta/mongoose#1189]
https://github.com/cesanta/mongoose/tree/master/examples/dashboard
Trying to build dashboard example for ESP32 but dependencies error, please confirm if dashboard example will compile for ESP32?

Attached build log
[build.log](https://github.com/cesanta/mongoose/files/5790304/build.log)

App code merged!
[dashboard.zip](https://github.com/cesanta/mongoose/files/5790305/dashboard.zip)

**Comment by cpq** [comment]
You cannot simply build this example via `mos build`.
