### ISSUE TITLE
Multi Threading windows

### ISSUE THREAD

**Issue by toutant** [cesanta/mongoose#1193]
Your code provided for multi threading does not work on windows
 
there is an issue with if your example is (ev == MG_EV_POLL && c->fn_data != NULL)
while debugging i noticed this is never NULL - my work around was to use c->id and a flag in the params past into c->fn_data to identify when to get the data and to identify it is from thread ....

 
 do you have any other examples you can provide using multi threads

**Comment by cpq** [comment]
There was an issue with win32 multithreaded code, where a `close(sock)` was used.
That's fine on unix, where file descriptors and sockets can be used for `read()`, `write()`, and `close()`.
Not so on Windows, where a `closesocket()` should be used.
Pushed a fix in https://github.com/cesanta/mongoose/commit/51bc5f70c5e7d892d4fca8a0deee6e481eda0dfa
Verified manually by building a binary `make vc2017` and running on Windows 10 Home.

![image](https://user-images.githubusercontent.com/601816/105329806-78501380-5bc9-11eb-8af1-8d9103752937.png)
