### ISSUE TITLE
HTTP Restful server example issues

### ISSUE THREAD

**Issue by djpiper28** [cesanta/mongoose#1199]
The example at https://github.com/cesanta/mongoose/blob/master/examples/http-restful-server/main.c has the following code for http reply:
 ```C
 mg_http_reply(c, 200, "", "{\"result\": \"%.*s\"}\n", (int) hm->uri.len,
                    hm->uri.ptr);
```
in mongoose 7 the source code on line 583 of mongoose.c defining the `mg_http_reply` function. The example will send an empty reponse body. 
```C
void mg_http_reply(struct mg_connection *c, int code, const char *fmt, ...) {
  char mem[100], *buf = mem;
  va_list ap;
  int len;
  va_start(ap, fmt);
  len = mg_vasprintf(&buf, sizeof(mem), fmt, ap);
  va_end(ap);
  mg_printf(c,
            "HTTP/1.1 %d OK\r\nContent-Type: text/plain\r\n"
            "Content-Length: %d\r\n\r\n",
            code, len);
  mg_send(c, buf, len);
  if (buf != mem) free(buf);
}
```

The docs at https://github.com/cesanta/mongoose/tree/master/docs or the other site have the function definition as (below) which it might have been at one point.
```C
void mg_http_reply(struct mg_connection *c, int status_code, const char *headers,
                   const char *body_fmt, ...);
```

**Comment by cpq** [comment]
Release 7.0 does not have `const char *headers` parameter.
The current HEAD does.
So will 7.1 which is going to be cut soon.
