### ISSUE TITLE
When accessing the same link using https, it is possible that "correct data +0" is not returned until the timeout.

### ISSUE THREAD

**Issue by TwilightShaw** [cesanta/mongoose#1202]
version: Mongoose 6.18
Xcode 10.0
As Title says , When accessing the same link using https, it is possible that "correct data +0\n\n" is not returned until the timeout.
I logged **the value of hv** returned and reply data inside ev_value_handler.
```
 while (s_exit_flag == 0)
        {
            mg_mgr_poll(&mgr, 100);
         
        }
```
1. when using http, hv : 0->0->...->0->0->2(CONNECT)->0->4(SEND)->0->3(RECV)->102(CHUNK)->102->101(HTTPREPLY). Then I mg_mgr_free(&mgr);
2. when using https, It is possible that hv goes through the process of "3->102->102->3->102" and then becomes 0 again, and then remains 0 until it times out.

I **obtained the data** as follows
```
 case MG_EV_HTTP_REPLY:
        {
            if (hm->body.len > 0)
            {
                std::string tmp = hm->body.p;
                g_HttpRetData = tmp.substr(0, hm->body.len);
            }
            nc->flags |= MG_F_SEND_AND_CLOSE;
            s_exit_flag = 1;
            break;
        }
```
If the correct return data is "hello", the error return is "hello0\n\n".

**I changed the access link, which returned longer data, and found that it _timed out every time_.
On the penultimate chunk, the data was complete.
But the last chunk strangely increased in length by 5 bytes, which I estimate from the logs to be 0\n\n.**

**Comment by cpq** [comment]
Please use 7.0
