### ISSUE TITLE
ipv6 peer addresses not reported to callback

### ISSUE THREAD

**Issue by velartrill** [cesanta/mongoose#1205]
on x86-64 linux, when a peer connects to a mongoose-based server bound to ::0 over ipv6, the `mg_addr peer` struct in the callback function's `mg_connection` argument does not have its `is_ip6` flag set and `mg_ntoa` returns the string "0.0.0.0" (although the port number in the `peer` struct is correct). this does not seem to prevent mongoose from handling the connection correctly otherwise.

**Comment by cpq** [comment]
Cheers, pushed https://github.com/cesanta/mongoose/commit/eecf3d854bf2d6d62cac0ed5e3f0ebf020a08b2e

**Comment by cpq** [comment]
@velartrill great essays

**Comment by velartrill** [comment]
@cpq ahah thank you :)
