### ISSUE TITLE
[Examples] Basic example for serving a html web with some pictures/buttons/text

### ISSUE THREAD

**Issue by ihouses** [cesanta/mongoose#1206]
Hello,

I would like to use mongoose to create a web in ESP32 that shows some text/pictures and has some buttons.

I went around the examples but I can not find anything similar. The example called "complete" looks too much to start with.

In the past I used a microchip framework that just served html code with some hookup tags that later on I have to take care in the code.  Is there any other repository with some examples like that one that I am talking about?

**Comment by cpq** [comment]
Use https://github.com/cesanta/mongoose/tree/master/examples/http-restful-server
Create an FS on your ESP32 and point root directory to it.

See https://github.com/cesanta/mongoose/tree/master/examples/esp32 for a skeleton ESP32 project.
