### ISSUE TITLE
mongoose 7.1 build failure

### ISSUE THREAD

**Issue by chenrui333** [cesanta/mongoose#1207]
👋  it looks like [this commit](https://github.com/cesanta/mongoose/commit/89784ab90a12c2ec0ddfb87482f487a1466b6942) broke the [homebrew build](https://github.com/Homebrew/homebrew-core/pull/69970), not sure whether we want to add `mongoose_mac` target back? Thanks!

**Comment by cpq** [comment]
Please use the `example` target: `make example`.
