### ISSUE TITLE
mg_http_upload small issues (windows)

### ISSUE THREAD

**Issue by dicosky** [cesanta/mongoose#1210]
Hi 
i noticed that fwrite add extra bytes to the file in mg_http_upload and that corrupt the file. so i solved that by :
changing this line  -> if ((fp = fopen(path, oft == 0 ? "wb" : "a")) == NULL)
to                           ->if ((fp = fopen(path, oft == 0 ? "wb" : "ab")) == NULL)

i added extra b to fopen so it can read binary files and that solved the problem.
thanks

**Comment by cpq** [comment]
Thank you.
That happens only on Windows, as Windows adds and extra `\r` for the new lines unless `b` is present in mode.
Changed unit test to cover that case.
