### ISSUE TITLE
Question: How to manage XMLHttpRequest events.

### ISSUE THREAD

**Issue by ihouses** [cesanta/mongoose#1217]
I can serve a web (index.html) and now I am trying to send a XMLHttpRequest from the web to the server.
I see this print in the ternminal when I push the button in the web:
realpath   [/spiffs/web/setLED] -> [/spiffs/web/setLED]

I assume that when I execute the java scrip:

  xhttp.open("GET", "setLED?LEDstate="+led, true);
  xhttp.send();

 an MG_EV_HTTP_MSG event is generated in the microcontroller and I need to do 3 things:

1) Check the page name that generated the XMLHttpRequest 
2) Check the value that is requesting
3) Answer the request (if needed)

How can I do that with mongoose?

May be what I am asking is trivial but I dont see any example that is doing something similar or other repositories that use the mongoose library that I can use as example neither.

**Comment by cpq** [comment]
Please check the up-to-date ESP32 example.
