### ISSUE TITLE
OpenSSL TLS always sending peer auth.

### ISSUE THREAD

**Issue by oamc** [cesanta/mongoose#1218]
In the 7.1 release zip file mongoose.c has SSL_set_verify (line 3501) outside the opts->ca condition causing OpenSSL server to always ask for client certificates even if you omit the ca parameter in the TLS options. This line is correct in tls.c source however.

**Comment by cpq** [comment]
Ouch.
We'll release 7.2 soon - in the mean time, please use HEAD.

**Comment by PerfectSlayer** [comment]
Thanks for the issue report.

I was investigating why t[he internal web server of AdAway](https://github.com/AdAway/AdAway/issues/2588) was failing.
I notice the regression in 7.1 version (that was fine in 7.0) so I will wait for the next release then.

Regards

**Comment by cpq** [comment]
Released 7.2
