### ISSUE TITLE
Compiling mongoose library on Keil v5

### ISSUE THREAD

**Issue by gFavi93** [cesanta/mongoose#1219]
Hello,
I'm trying to integrate mongoose libraries in a project and I use uVision Keil v 5.10 as framework but I have some problems when I compile my code because the following header files are missing : 
<fcntl.h>
<sys/stat.h>
<sys/types.h>
Is there a possibility to compile these libraries in this environment ?

**Comment by cpq** [comment]
Could you describe your environment in more detail, please?
What OS, what is the target platform / device ?

**Comment by gFavi93** [comment]
The description of the environment is present in the attached image :
![ArmKeil](https://user-images.githubusercontent.com/78859849/107527914-9225ba80-6bb9-11eb-9fa6-d5c8f317afc3.PNG)
I'm trying to develop web socket communication on STM32 device

**Comment by cpq** [comment]
If still relevant - could you try the process described at https://cesanta.com/docs/#custom-build please?

**Comment by polluks** [comment]
Keil doesn't seem to support POSIX headers, see https://github.com/payne92/bare-metal-arm/issues/14#issue-248980859.

**Comment by cpq** [comment]
While not on Keil, but we've published a bunch on examples for STM32
https://github.com/mongoose-examples
