### ISSUE TITLE
User Data Pointer in mg_mgr

### ISSUE THREAD

**Issue by marcelwirtz** [cesanta/mongoose#1221]
Hey,

to get our C++ wrapper work with Mongoose 7.x again we would like to get back the

`void *user_data; /* User data */`

pointer in the mg_mgr struct. 

Is it possible you add this back again?

Thanks and kind regards.
Marcel Wirtz
MIDAN SOFTWARE GmbH

**Comment by cpq** [comment]
https://github.com/cesanta/mongoose/commit/374ab4ecf017353772defdaadb71fc6a10d63bb7

**Comment by jcorporation** [comment]
Greate, I missed this pointer also.
