### ISSUE TITLE
How to actively close a mg_connection.fd

### ISSUE THREAD

**Issue by tianguochun** [cesanta/mongoose#1225]
If I use the close() function to close a mg_connection.fd, then the polling time of mg_mgr_poll() will become 0 (although I set 10000), and the previously listened socket will not be able to be connected again.

**Comment by tianguochun** [comment]
I solved the problem by setting "is_closing=1".

**Comment by cpq** [comment]
Don't close is manually, you'll mess up polling. `c->is_closing =1;` is the way to go. There is no other way.
