### ISSUE TITLE
Not found TCP_KEEPCNT and TCP_KEEPINTVL in mongoose.cpp in compilation QNX

### ISSUE THREAD

**Issue by PiterYask** [cesanta/mongoose#1227]
When compiling on Qnx do not find 'optname' TCP_KEEPCNT and TCP_KEEPINTVL. If they are commented out the server works but I don't know what these parameters are and if they can be disabled.
![Screenshot_1](https://user-images.githubusercontent.com/31919886/109931062-6b026a80-7cd9-11eb-943b-4b34e9e0be9e.png)
How to fix it?

**Comment by cpq** [comment]
Change line 2840 to

```c
#if !defined(_WIN32) && !defined(__QNX__)
```

Would it build with that?

These options are for TCP keepalive params, it is OK to omit them.

**Comment by PiterYask** [comment]
Thank you, it works!
