### ISSUE TITLE
Parse certificate from disk

### ISSUE THREAD

**Issue by panosto** [cesanta/mongoose#1240]
In `mg_tls_init()` the `MBEDTLS_X509_CA_CHAIN_ON_DISK ` macro is provided in order to load the `opts->ca` certificate from a file or a buffer.

Why the same functionality is not offered for `opts->key` and `opts->cert` as well?

Thank you for your help
Panagiotis

**Comment by cpq** [comment]
@panosto no reason - feel free to file a PR
