### ISSUE TITLE
 The order in which the domain name resolution is performed

### ISSUE THREAD

**Issue by thanhtxt** [cesanta/mongoose#1242]
The order of domain name resolution in linux is defined in /etc/nsswitch.conf
hosts:          dns files
When I change to "dns files" but library still read ip from /etc/host before dns

**Comment by cpq** [comment]
The library does not use a standard synchronous resolver, so it does not matter what is in nsswitch or any other system config file.
Mongoose always uses DNS, it does not parse `/etc/hosts` or any other file.
