### ISSUE TITLE
Github CodeQL alert for mg_http_write_chunk

### ISSUE THREAD

**Issue by jcorporation** [cesanta/mongoose#1255]
Following code produces an CodeQL alert:
```
void mg_http_write_chunk(struct mg_connection *c, const char *buf, size_t len) {
  mg_printf(c, "%X\r\n", len);
  mg_send(c, buf, len);
  mg_send(c, "\r\n", 2);
}
```

len: This argument should be of type 'unsigned int' but is of type 'unsigned long'

`mg_printf(c, "%X\r\n", len);` I think this should be `mg_printf(c, "%lu\r\n", len);`

**Comment by lnksz** [comment]
`size_t` has different width on different platforms..., if decimal output is an option `%zu` is dedicated for size_t, but to keep the original formatting `%zX` would do the trick. (the %z is a C99 feature)

**Comment by cpq** [comment]
Some stdlibs do not like `%z` , so casting to `unsigned long` to squash the warning..
