### ISSUE TITLE
About the https connection handshake failure when using openssl

### ISSUE THREAD

**Issue by GhostHallyz** [cesanta/mongoose#1263]
When i use mongoose to build https server, it always fails the handshake.

```c
int mg_tls_handshake(struct mg_connection *c) {
  struct mg_tls *tls = (struct mg_tls *) c->tls;
  int rc;
  SSL_set_fd(tls->ssl, (long) c->fd);
  rc = c->is_client ? SSL_connect(tls->ssl) : SSL_accept(tls->ssl);
  if (rc == 1) {
    LOG(LL_DEBUG, ("%lu success", c->id));
    c->is_tls_hs = 0;
    return 1;
  } else {
    int code;
    ERR_print_errors_fp(stderr);
    code = mg_tls_err(tls, rc);
    if (code != 0) mg_error(c, "tls hs: rc %d, err %d", rc, code);
    return 0;
  }
}
```

In mongoose 7.2 version， at line 3690 of the mongoose.c file,  I found that ` rc = c->is_client ? SSL_connect(tls->ssl) : SSL_accept(tls->ssl);`  always return -1，it may crach when run to function ERR_print_errors_fp ().
Can I add `rc = c->is_client? SSL_connect(tls->ssl): SSL_accept(tls->ssl)` under `rc = c->is_client? SSL_connect(tls->ssl): SSL_accept(tls->ssl)`？

**Comment by cpq** [comment]
Could you provide a diff for your suggested change please?

**Comment by GhostHallyz** [comment]
An https client requests, SSL_accept fails for the first time, and succeeds for the second time.

**Comment by cpq** [comment]
That's expected thogh.
Since mongoose is non-blocking, the first call to handshake might fail.
As TLS layer receives handshake data, it succeeds.

**Comment by GhostHallyz** [comment]
i see，thanks

**Comment by hql420621** [comment]
i also run into this problem,is there a way to solve it,thanks
