### ISSUE TITLE
Partial Content, 'Range' HTTP header

### ISSUE THREAD

**Issue by simon987** [cesanta/mongoose#1264]
It looks like HTTP Partial Content, `Range` header, is no longer supported in 7.X. This is an essential feature for me, are there any plans to enable it in future releases? 

Or do you have pointers on how to implement it myself? It does not seem trivial to do it without modifying library code

Thanks

**Comment by cpq** [comment]
Here we go https://github.com/cesanta/mongoose/commit/79aad7fabfd1930665f09d12a99bdf6790ea5593

**Comment by simon987** [comment]
Thank you! :heart:
