### ISSUE TITLE
Feature Request: mg_http_reply() response reasons

### ISSUE THREAD

**Issue by oamc** [cesanta/mongoose#1266]
`  char *reason = "OK";

  switch (code) {
    case 100: reason = "Continue"; break;
    case 101: reason = "Switching Protocols"; break;
    case 102: reason = "Processing"; break;
    case 200: reason = "OK"; break;
    case 201: reason = "Created"; break;
    case 202: reason = "Accepted"; break;
    case 203: reason = "Non-authoritative Information"; break;
    case 204: reason = "No Content"; break;
    case 205: reason = "Reset Content"; break;
    case 206: reason = "Partial Content"; break;
    case 207: reason = "Multi-Status"; break;
    case 208: reason = "Already Reported"; break;
    case 226: reason = "IM Used"; break;
    case 300: reason = "Multiple Choices"; break;
    case 301: reason = "Moved Permanently"; break;
    case 302: reason = "Found"; break;
    case 303: reason = "See Other"; break;
    case 304: reason = "Not Modified"; break;
    case 305: reason = "Use Proxy"; break;
    case 307: reason = "Temporary Redirect"; break;
    case 308: reason = "Permanent Redirect"; break;
    case 400: reason = "Bad Request"; break;
    case 401: reason = "Unauthorized"; break;
    case 402: reason = "Payment Required"; break;
    case 403: reason = "Forbidden"; break;
    case 404: reason = "Not Found"; break;
    case 405: reason = "Method Not Allowed"; break;
    case 406: reason = "Not Acceptable"; break;
    case 407: reason = "Proxy Authentication Required"; break;
    case 408: reason = "Request Timeout"; break;
    case 409: reason = "Conflict"; break;
    case 410: reason = "Gone"; break;
    case 411: reason = "Length Required"; break;
    case 412: reason = "Precondition Failed"; break;
    case 413: reason = "Payload Too Large"; break;
    case 414: reason = "Request-URI Too Long"; break;
    case 415: reason = "Unsupported Media Type"; break;
    case 416: reason = "Requested Range Not Satisfiable"; break;
    case 417: reason = "Expectation Failed"; break;
    case 418: reason = "I'm a teapot"; break;
    case 421: reason = "Misdirected Request"; break;
    case 422: reason = "Unprocessable Entity"; break;
    case 423: reason = "Locked"; break;
    case 424: reason = "Failed Dependency"; break;
    case 426: reason = "Upgrade Required"; break;
    case 428: reason = "Precondition Required"; break;
    case 429: reason = "Too Many Requests"; break;
    case 431: reason = "Request Header Fields Too Large"; break;
    case 444: reason = "Connection Closed Without Response"; break;
    case 451: reason = "Unavailable For Legal Reasons"; break;
    case 499: reason = "Client Closed Request"; break;
    case 500: reason = "Internal Server Error"; break;
    case 501: reason = "Not Implemented"; break;
    case 502: reason = "Bad Gateway"; break;
    case 503: reason = "Service Unavailable"; break;
    case 504: reason = "Gateway Timeout"; break;
    case 505: reason = "HTTP Version Not Supported"; break;
    case 506: reason = "Variant Also Negotiates"; break;
    case 507: reason = "Insufficient Storage"; break;
    case 508: reason = "Loop Detected"; break;
    case 510: reason = "Not Extended"; break;
    case 511: reason = "Network Authentication Required"; break;
    case 599: reason = "Network Connect Timeout Error"; break;
  }

  mg_printf(c, "HTTP/1.1 %d %s\r\n%sContent-Length: %d\r\n\r\n", code,
            reason, headers == NULL ? "" : headers, len);`

**Comment by cpq** [comment]
@oamc thank you.
