### ISSUE TITLE
Custom random number generator function in v7 

### ISSUE THREAD

**Issue by panosto** [cesanta/mongoose#1269]
Hi

In v6, the `mg_ssl_if_mbed_random()` function was declared extern and each platform could provide a custom definition.

In v7, the `mg_random()` function is using `/dev/urandom` and a fall back to `rand()` if the first does not succeed.

How do you propose to use  a custom definition of `mg_random()` in v7?

Thank you very much in advance
Panagiotis

**Comment by cpq** [comment]
@panosto good question, thank you.

Please see the change that makes `mg_random` a weak symbol.
You can define your own `mg_random`, and a compiler should pick your implementation without linking conflict.
