### ISSUE TITLE
Misleading release notes about undocumented breaking changes from v6 ot v7

### ISSUE THREAD

**Issue by antoinep92** [cesanta/mongoose#1271]
The 7.0 changelog says

> Porting from the 6.x version is straightforward, as all concepts stayed intact, with the exception of CGI

But this is not true. The [diff](https://github.com/cesanta/mongoose/commit/f2fba1d2004c5ddf2fc0a7ca8dc75b5f78feed85#diff-0f96b129b059ad329b7239e581bf8d635f61524d6a89ace2378703681eb7497a) shows that many basic interfaces were changed, e.g. `mg_connection`, `mg_send_head`, etc. On my projects I have many errors, and fixing them is not just changing a function/field name, because function parameters/semantics have also changed.

A porting guide should be available, or at least the release notes should be changed to something like:

> Warning: the 7.x version changed most user-facing interfaces and porting is not trivial as documentation of the changes is not yet available.

**Comment by cpq** [comment]
The concepts and semantics stayed intact.
E.g. the event manager, connection structure, event mechanism, etc etc.
Yes, some field names and APIs changed - hence the major release number, as the changes are breaking.
