### ISSUE TITLE
How work multithread in mongoose?

### ISSUE THREAD

**Issue by PiterYask** [cesanta/mongoose#1278]
Good afternoon, I am trying to figure out how to build a mongoose server using multithreading.
I have looked at the implementation in the examples. But I am using c++ and there I would like to make an implementation with "workres" objects which for each new connection open a separate thread and stack everything in one queue. And at each iteration of ev== MG_EV_POLL the queue of prepared responses is parsed and sent to their connections.

Question 1: How is this a correct implementation of multithreading?
Question 2. What happens if you put "mg-mgr_poll(&mgr, 0)".

Thanks for your library. It's cool.
P.S. I don't know English very well.

**Comment by cpq** [comment]
TBH, your questions are not entirely clear.

Please refer to the multithreaded example. Also, this post https://github.com/cesanta/mongoose/issues/1257 could help.
