### ISSUE TITLE
err_t assumed to be a long int

### ISSUE THREAD

**Issue by ironstep** [cesanta/mongoose#1279]
In `src/lwip.c`, `err_t` is assumed to be a long int, which may not be true.

Example:
```
static void tcp_error_cb(void *arg, err_t err) {
  struct mg_connection *c = (struct mg_connection *) arg;
  mg_error(c, "%p err %ld", c->fd, err);
}
```

**Comment by cpq** [comment]
Only LWIP with the BSD sockets API support works at this moment.
The low level LWIP API is not yet supported. It is now removed from the codebase to avoid confusion.
