### ISSUE TITLE
too many arguments to function 'mg_resolve'

### ISSUE THREAD

**Issue by ironstep** [cesanta/mongoose#1280]
src/dns.h
```
void mg_resolve(struct mg_connection *, struct mg_str *, int);
```

src/lwip.c
```
mg_resolve(mgr, c, &host, mgr->dnstimeout);
```

**Comment by cpq** [comment]
Only LWIP with the BSD sockets API support works at this moment.
The low level LWIP API is not yet supported. It is now removed from the codebase to avoid confusion.
