### ISSUE TITLE
Casting length of the data to write to SOCKET type

### ISSUE THREAD

**Issue by GlebPlekhotko** [cesanta/mongoose#1282]
Function _ll_write_ has the following footprint:
`static int ll_write(struct mg_connection *c, const void *buf, int len, int *fail)`
Argument _len_ has _int_ type.

In function _write_conn_ it is invoked in the following way:
`int fail, rc = ll_write(c, c->send.buf, (SOCKET) c->send.len, &fail);`
Here _c->send.len_ is casted to _SOCKET_ type.

The problem is in some implementations _SOCKET_ may have different but _int_ base type. Specifically, in SDK for the [WINC1500](https://www.microchip.com/wwwproducts/en/ATWINC1500) WiFi module, _SOCKET_ is actually _int8_t_. So length of the data to send is implicitly truncated.

**Comment by cpq** [comment]
Thank you.
You're correct, the cast to SOCKET is completely unnecessary there.
That should have been fixed in the HEAD already
