### ISSUE TITLE
client cant recv reply...

### ISSUE THREAD

**Issue by hctym1995** [cesanta/mongoose#1296]
- My goal is: client can recv reply from server
- My actions were: when server recv http request("my url:/api/reboot"), this will reboot my process
- My expectation was: my process can run normally
- The result I saw: client cant recv my reply,but my process has be rebooted.
- My question is: why client cant recv reply?
my "reboot action" is using WINDOWS SYSTEM FUNC: my code:"::TerminateProcess(GetCurrentProcess, 1);"

when i use this func, client cant recv reply, i cant get the packets through Wireshark.
BUT
when i comment out this line of code, client can recv reply, and process will not restart of course.

this is my code:
if(mg_vcmp(&hm->uri, "/api/reboot") == 0)
{
    ::TerminateProcess(GetCurrentProcess(), 1);    //my daemon will start it again
}
else
{
    ...
}

# Environment

- mongoose version: i have used "6.7" and "6.18"
- custom changes?: n
  - If yes, provide the diff below, and the releavant commit:
- build environment:
  - OS: win10
  - Compiler/IDE: vs2008
- relevant example (see https://github.com/cesanta/mongoose/tree/master/examples) is: _?_
- relevant documentation topic (see https://cesanta.com/docs/) is: _?_

**Comment by cpq** [comment]
Your process gets closed, so it cannot send a response!
In your reboot handler, do not reboot immediately. Start a thread, in that thread wait for some time, like 1 second, and reboot.
