### ISSUE TITLE
Wrong version directive in mongoose.h 6.3

### ISSUE THREAD

**Issue by maitrebart** [cesanta/mongoose#1299]
- My goal is: _Use mongoose 6.3_
- My actions were: _Look at mongoose.h_
- My expectation was: _#define MG_VERSION "6.3"_
- The result I saw: _#define MG_VERSION "6.2"_
- My question is: _Is it normal?_

# Environment

- mongoose version: _6.3_
- custom changes?: _No_
  - If yes, provide the diff below, and the relevant commit:
- build environment:
  - OS: _All_
  - Compiler/IDE: _All_
- relevant example (see https://github.com/cesanta/mongoose/tree/master/examples) is: _N/A_
- relevant documentation topic (see https://cesanta.com/docs/) is: _N/A_

**Comment by cpq** [comment]
Please upgrade to the current version.
Older versions are not supported.
