### ISSUE TITLE
Missing multithreaded example with mg_broadcast()

### ISSUE THREAD

**Issue by maitrebart** [cesanta/mongoose#1300]
- My goal is: _Use mongoose lib in a multithreaded app_
- My actions were: _Look for some examples_
- My expectation was: _Find an example that uses mg_broadcast()_
- The result I saw: _The multi-thread example does not use mg_broadcast()_
- My question is: _Can a multi-thread example be added which would use the mg_broadcast() function?_

# Environment

- mongoose version: _7.*_
- custom changes?: _n_
  - If yes, provide the diff below, and the relevant commit:
- build environment:
  - OS: _All_
  - Compiler/IDE: _All_
- relevant example (see https://github.com/cesanta/mongoose/tree/master/examples) is: _multi-thread_
- relevant documentation topic (see https://cesanta.com/docs/) is: _https://ces.ap-folio.com/developers.html#_core_tcp_udp_ssl_

**Comment by cpq** [comment]
There is no `mg_broadcast()` function in 7.x. The multithreaded example does the job.
