### ISSUE TITLE
Incorrect OpenSSL version mentioned for SSL_use_certificate_chain_file in mongoose.c

### ISSUE THREAD

**Issue by Akshaykumar2002** [cesanta/mongoose#1301]
- My goal is: Build a transparent, intercepting proxy using the Mongoose networking library
- My actions were: Rewrite the HTTP-reverse-proxy example to support a transparent proxy with _OpenSSL version 1.0.2n_
- My expectation was: HTTPS requests through TLS to work without issues.
- The result I saw: Compilation error: **In function `mg_tls_init':
mongoose.c:(.text+0xb87e): undefined reference to `SSL_use_certificate_chain_file'**

Upon investigation, I noticed that the function was included only in OpenSSL versions 1.1.0_pre1 and above and was not present in the previous versions. However, the #define present in the code points to a minimum version of OpenSSL 1.0.2 and hence it is failing during compilation.

Thus, please update the following in mongoose.c from:
`#if OPENSSL_VERSION_NUMBER > 0x10002000L // This indicates OpenSSL version 1.0.2 version and above`
to:
`#if OPENSSL_VERSION_NUMBER > 0x10100000L // This indicates OpenSSL versions 1.1.0 versions and above`

# Environment
OS: Ubuntu Linux 16.04
- mongoose version: 7.2
- custom changes?: n

**Comment by xiaobai2017** [comment]
I found the same bug in version 7.3,  why this issue is closed?
