### ISSUE TITLE
Using this with XML transformation files (XML-XSL > HTML)

### ISSUE THREAD

**Issue by ajtruckle** [cesanta/mongoose#1304]
Is it possible to listen for XML files (which are transformed into HTML) using Mongoose?

Thank you.

**Comment by cpq** [comment]
I assume, the question is as follows:
- Does Mongoose provide a built-in capability to serve static XML files and transform them to HTML on the fly?

The answer on this question is "no", there is no built-in capability.
That said, it is possible to add a custom logic to do so.
