### ISSUE TITLE
Provide means to determine local port when listening on port 0

### ISSUE THREAD

**Issue by Bklyn** [cesanta/mongoose#1313]
- My goal is: To run mongoose on a dynamic (OS-allocated port)
- My actions were: Listen with an address string like "http://0.0.0.0:0"
- My expectation was:  Some API to access the address the OS gave us (notably the port)
- The result I saw: Mongoose does not call getsockname
- My question is: 

In 6.x mongoose would call `getsockname` after `listen` and update the `sa` argument to `mg_open_listening_socket`.  There was even a comment to the effect that this was supported: /* In case port was set to 0, get the real port number */

The new `mg_open_listener` function takes only a url string and returns only a SOCKET, so it can't do this w/o changing the interface.  Perhaps this could be added to `mg_listen`, calling `getsockname` and populating the returned connection's `c->peer` with the results.

My purpose here is to use mongoose to expose an HTTP endpoint in any number of applications which may be on the same host.  The actual endpoint will be registered with a naming service once the server is up and running.

# Environment

- mongoose version: 7.2-ish (7.2-126-g89757388)
- custom changes?: No
- build environment:
  - OS: Linux
  - Compiler/IDE: gcc
- relevant example (see https://github.com/cesanta/mongoose/tree/master/examples) is: _?_
- relevant documentation topic (see https://cesanta.com/docs/) is: _?_

**Comment by cpq** [comment]
Fixed, thank you.
