### ISSUE TITLE
Not all C compiler does supports `#pragma once`

### ISSUE THREAD

**Issue by edubart** [cesanta/mongoose#1315]
I am using a C compiler that does not support `#pragma once`, then when including `mongoose.h` twice I get compile errors due to double declarations. Please add ifdef guards in `mongoose.h`, that is:

```c
#ifndef MONGOOSE_H
#define MONGOOSE_H

/* header code */

#endif
```

**Comment by cpq** [comment]
@edubart thanks. Could you elaborate what is the toolchain you're using, the target platform and environment, please?

**Comment by edubart** [comment]
> @edubart thanks. Could you elaborate what is the toolchain you're using, the target platform and environment, please?

I'm using https://github.com/vnmakarov/mir for jiting C code.

**Comment by edubart** [comment]
I've just made the PR #1317 with a possible fix for this.
