### ISSUE TITLE
Latest mongoose executable detected as Trojan Program:Win32/Wacapew.C!ml

### ISSUE THREAD

**Issue by Jaifroid** [cesanta/mongoose#1322]
I'm sure this is a false positive, but you should know that mongoose 7.3.3 is detected by Windows Defender as Program:Win32/Wacapew.C!ml. Screenshot of detection message below. This was detected on a fresh Windows 11 (preview) install. I hope I didn't foolishly "allow" the app...

![image](https://user-images.githubusercontent.com/4304337/127190159-0760ba3b-d787-4013-a849-8436e97346b8.png)

**Comment by Jaifroid** [comment]
Could it have anything to do with https://github.com/pyinstaller/pyinstaller/issues/5668 (Python)?

**Comment by cpq** [comment]
Yes this is a false positive.
We do not create or distribute malware.

**Comment by Jaifroid** [comment]
Of course you don't, but maybe there are some steps you can take to ensure it's not flagged like this...
