### ISSUE TITLE
Per connection user data was removed in V7.

### ISSUE THREAD

**Issue by volanin** [cesanta/mongoose#1328]
Since I am coming from 6.18, this might have some V6 bias.
I am migrating a websocket server to V7.

In V6, I can set "global user data" in **struct mg_mgr** and also "per connection user data" in **struct mg_connection**. Both of them have _void *user_data_ fields.

In V7, I can still set "global user data" in **struct mg_mgr** (although setting it directly was removed from the **mg_mgr_init()** API)... but the "per connection user data" was removed from **struct mg_connection**.

It seems to have been replaced by _void *fn_data_, but it's not the same thing, since this field is meant to be set by the function **mg_http_listen()** and, by doing such, I cannot have each connection having its own separate user data pointer. Unless I am doing something wrong, in practice _fn_data_ will be just another global user data.

Of course, in MG_EV_ACCEPT, I can still force it with **connection->fn_data = malloc( sizeof( struct UserData ))**, but doing this, overriding this field value, doesn't feel like the right thing to do.

**Comment by cpq** [comment]
For accepted connections, it is fine to replace `c->fn_data` - in fact, it's fine to replace it for any connection.

**Comment by cpq** [comment]
Closing this - please use `c->fn_data`
