### ISSUE TITLE
Precompiled web server occasionally stops serving after few days

### ISSUE THREAD

**Issue by brianfromoregon** [cesanta/mongoose#1330]
- My goal is: mongoose lightweight web server stays running 24/7
- My actions were: keep computer on 24/7
- My expectation was: any time i'd browse to URLs served by mongoose, they would show up in browser
- The result I saw: after a week or so of running, seems like mongoose crashes. the pages are not served, eventually, the port did not seem open. to get it working again i had to kill mongoose.exe in task manager and relaunch it. 
- My question is: is this a known problem? i dont see any mongoose log files, how can i enable logging to debug the problem. 

# Environment

- mongoose version: 7.3.2
- OS: Win7
- Compiler/IDE: n/a

**Comment by cpq** [comment]
@brianfromoregon thank you.

Enabling the log is a good idea.

Does your computer go to sleep in some occasions? Could you trigger that behaviour by sleep/wake up?

If mongoose crashes, then mongoose.exe process would not be running - but it sounds like it is running. Apparently it stops serving for some reason. When that happens, maybe a settings dialog is showing up?

**Comment by brianfromoregon** [comment]
Hi

Afaik it never goes to sleep, and win7 power/sleep settings are disabled.

Yes mongoose.exe is still running when the "crash" behavior is observed. I saw no corresponding dialog. When it happens again I will share logs.

**Comment by brianfromoregon** [comment]
Hi

It happened again. I will attach logs with a <snip> to remove a few days' worth of redundancy. Does this reveal the reason for the crash? mongoose.exe is still running, but not serving pages.

I am not sure what is making these strange looking requests. Maybe it is some internal vulnerability checker that I'm not aware of.

[mongoose.txt](https://github.com/cesanta/mongoose/files/7001645/mongoose.txt)

**Comment by cpq** [comment]
@brianfromoregon thank you!

It is hard to tell something definite based on the log, it looks pretty much innocent.

The dialog I've mentioned, is a Mongoose settings dialog. If you right-click, a settings dialog appears - and until it is closed, processing stops.
