### ISSUE TITLE
how to write the debug log into specific file rather than output screen ?

### ISSUE THREAD

**Issue by hql420621** [cesanta/mongoose#1335]
when i use mongoose, is there a way to write the log into file? thanks in advance

**Comment by cpq** [comment]
@hql420621 are you talking about the webserver executable?

**Comment by hql420621** [comment]
thanks for replaying,i use mongoose.h and mongoose.c in my project  to build a httpserver, like in the example you give ,but i want output the error into local file ,i read the mongoose.c and dont know if the LOG() surpoort this

**Comment by cpq** [comment]
There are few options.

1. Redirect all stdout IO to a file: `freopen("mylog.txt", "a", stdout);`
2. Use mg_log_set_callback() to setup your own logging function.
