### ISSUE TITLE
Udp does not know how to use it?

### ISSUE THREAD

**Issue by huanxinmengmeng** [cesanta/mongoose#1338]
I have used UDP to test many methods that cannot communicate properly.  Is there a routine to tell me how to use it?

**Comment by xiaobai2017** [comment]
Maybe you can see this function:
test_udp() in master/test/unit_test.c

**Comment by huanxinmengmeng** [comment]
I found the reason. It did not use sendto and recvfrom, so the message could not be sent and received normally.

**Comment by huanxinmengmeng** [comment]
Finally, I solved it. I made some changes to the source code.
`
static long mg_sock_send(struct mg_connection *c, const void *buf, size_t len) {
  long n = 0; 
  if (c->is_udp) {
    union usa usa;
    usa.sin.sin_addr.s_addr = c->peer.ip;
    usa.sin.sin_port = c->peer.port;
    usa.sin.sin_family = AF_INET;
    n = sendto(FD(c), (char *) buf, len, 0, &usa.sa, sizeof(usa.sin));
  } else {
    n = send(FD(c), (char *) buf, len, MSG_NONBLOCKING);
  }
  return n == 0 ? -1 : n < 0 && mg_sock_would_block() ? 0 : n;
}
`

**Comment by huanxinmengmeng** [comment]
`static long mg_sock_send(struct mg_connection *c, const void *buf, size_t len) {
  long n = 0; 
  if (c->is_udp) {
    union usa usa;
    usa.sin.sin_addr.s_addr = c->peer.ip;
    usa.sin.sin_port = c->peer.port;
    usa.sin.sin_family = AF_INET;
    n = sendto(FD(c), (char *) buf, len, 0, &usa.sa, sizeof(usa.sin));
  } else {
    n = send(FD(c), (char *) buf, len, MSG_NONBLOCKING);
  }
  return n == 0 ? -1 : n < 0 && mg_sock_would_block() ? 0 : n;
}`

**Comment by huanxinmengmeng** [comment]
Finally, I solved it. I made some changes to the source code.
```
static long mg_sock_send(struct mg_connection *c, const void *buf, size_t len) {
  long n = 0; 
  if (c->is_udp) {
    union usa usa;
    usa.sin.sin_addr.s_addr = c->peer.ip;
    usa.sin.sin_port = c->peer.port;
    usa.sin.sin_family = AF_INET;
    n = sendto(FD(c), (char *) buf, len, 0, &usa.sa, sizeof(usa.sin));
  } else {
    n = send(FD(c), (char *) buf, len, MSG_NONBLOCKING);
  }
  return n == 0 ? -1 : n < 0 && mg_sock_would_block() ? 0 : n;
}
```
