### ISSUE TITLE
Error Compiling on Windows

### ISSUE THREAD

**Issue by 0xDani3l** [cesanta/mongoose#1348]
- My goal is: To get a simple C++ HTTP server
- My actions were: including the mongoose.h and mongoose.c files, then using this code

```c
#include "mongoose.h"

static void fn(struct mg_connection* c, int ev, void* ev_data, void* fn_data) {
	struct mg_http_serve_opts opts = { .root_dir = "." };   // Serve local dir
	if (ev == MG_EV_HTTP_MSG) mg_http_serve_dir(c, (struct mg_http_message *) ev_data, &opts);
}

int oots(int argc, char* argv[]) {
	struct mg_mgr mgr;
	mg_mgr_init(&mgr);                                        // Init manager
	mg_http_listen(&mgr, "http://localhost:8000", fn, &mgr);  // Setup listener
	for (;;) mg_mgr_poll(&mgr, 1000);                         // Event loop
	mg_mgr_free(&mgr);                                        // Cleanup
	return 0;
}
```

- My expectation was: Launching the server
- The result I saw: buffer 'mgr' of size 52 bytes will be overrun; 4 bytes will be written starting at offset 52 in mongoose.c
- My question is: Why is this happening?

# Environment

- mongoose version (e.g. 7.3): _7.3_
- Compiler/IDE (e.g. arm-none-eabi-gcc 9.3): Visual Studio 2019 x64 C++ 20
- Target OS (e.g. FreeRTOS 10.3.1, Linux 5.8): Windows 10
- Target hardware/board (e.g. STM32F411): _?_
- Connectivity chip/module (e.g. WizNet W5500): _?_
- Target SDK (e.g. STM32CubeF1 1.8.4): _?_

**Comment by cpq** [comment]
@0xDani3l could you share a full, exact message that you see, please?
