### ISSUE TITLE
Please document mongoose binary command line arguments

### ISSUE THREAD

**Issue by mailinglists35** [cesanta/mongoose#1362]
I have downloaded the mongoose_linux but it does not react to --help command line argument
what are the parameters it accepts?

**Comment by mailinglists35** [comment]
and no, I found nothing on the website link claiming to be documentation! :(

**Comment by cpq** [comment]
Config file params listed at https://mongoose.ws/ are the same as command line params.

**Comment by mailinglists35** [comment]
could you please add a --help parameter into the binary?
