### ISSUE TITLE
Files or directories starting with double dots are not served

### ISSUE THREAD

**Issue by jcorporation** [cesanta/mongoose#1391]
- My goal is: serve a directory or a file with beginning double dots
- My actions were: GET /..test/test.html
- My expectation was: file is served
- The result I saw: 404 not found - the double dots are removed in the "remove_double_dots" function
- My question is: could you enhance this functions?

# Environment

- mongoose version (e.g. 7.3): 7.3
- Compiler/IDE (e.g. arm-none-eabi-gcc 9.3): arm-linux-gnueabihf gcc 8.3.0-6+rpi1
- Target OS (e.g. FreeRTOS 10.3.1, Linux 5.8): Linux 5.10.17-v7l+

**Comment by cpq** [comment]
@jcorporation thanks.
Double-dots removal is a protection against directory traversal.
Could you elaborate please? Do you really have directories in your filesystem which start with double dot? If yes, why?

**Comment by jcorporation** [comment]
Yes, the users of myMPD that integrates mongoose have directories starting with double dots. The serve_dir function is used to browse through the directory hierarchy with albums. 

The dir traversal check should check for ../ and ..\ in my opinion.
