### ISSUE TITLE
errors on mg_tls_init when acting as a client

### ISSUE THREAD

**Issue by rafalsk** [cesanta/mongoose#1403]
When the library acts as a client, often we're faced with errors during TLS session negotiation ( invoked through mg_tls_init()) .

The errors look like the ones below:
```
tls hs: rc -1, err 5
tls hs: rc -1, err 6
```

Would you please advise where to find references in regards to the error codes above?

**Also,** 

- how to enable for multiple cipher-suites? ex. for both TLS_AES_256_GCM_SHA384 and TLS_CHACHA20_POLY1305_SHA256?
by default if we leave mg_tls_opts to an empty string we do not seem to be able to connect with anything. If we set it to  say opts.ciphers = "TLS_CHACHA20_POLY1305_SHA256" with some endpoints it works, on others the negotiation fails (error codes above).

- would it be possible to override and neglect  TLS negotiation issues, such as  ones occurring due to an expired certificate on the other endpoint?
- and last but not least; with Mongoose acting as a proxy; we've got an option of specifying a single CA. What if the remote server presents a certificate which is not an offspring of the CA used by Mongoose? Is it correct to presume that the negotiation would fail? How to make Mongoose accept any certificate? Set CA to nullptr when acting as client? Web-browsers typically have access to multiple CAs to cope with the topic.

Also note that the issue with Mongoose not firing events for HTTP messages when acting as client still remains. We've integrated LLHTTP HTTP stream-parser to cope with the issue and passing data on raw-read events from Mongoose.

**Comment by cpq** [comment]
@rafalsk thanks, but you've ignored issue template and your question is missing some important information about the environment. Also, what TLS lib / version you're using is missing.

**Comment by rafalsk** [comment]
It's Windows and OpenSSL.

pon., 15 lis 2021, 17:21 użytkownik Sergey Lyubka ***@***.***>
napisał:

**Comment by rafalsk** [comment]
Closing for now as more data is needed.
