### ISSUE TITLE
mg_error Segmentation

### ISSUE THREAD

**Issue by yujie1007** [cesanta/mongoose#1418]
Program terminated with signal 11, Segmentation fault.
#0  0x00007fef0c8f2f1a in mg_error () from /lib64/libmongoose.so
(gdb) bt
#0  0x00007fef0c8f2f1a in mg_error () from /lib64/libmongoose.so
#1  0x00007fef0c8f25ab in dns_cb () from /lib64/libmongoose.so
#2  0x00007fef0c8f2e09 in mg_call () from /lib64/libmongoose.so
#3  0x00007fef0c8fd74b in mg_mgr_poll () from /lib64/libmongoose.so
#4  0x0000000000401502 in houtai ()
#5  0x00007fef0cf6fe25 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fef0c62234d in clone () from /lib64/libc.so.6

# Environment

- mongoose version: 7.4
- Compiler/IDE and SDK: clion
- System: centos7.4

**Comment by cpq** [comment]
The problem is in your code.
