### ISSUE TITLE
[Question] Retry client TLS handshake with various configurations

### ISSUE THREAD

**Issue by rafalsk** [cesanta/mongoose#1420]
We've spent quite a lot of time on this; to no avail so far.
KeyPoints:

- We set the CA to nullptr as we **do not** need any endpoint's verification at all.
- we're using latest OpenSSL 1.1.1 LTS build
- OpenSSL-specific errors are not propagated to Mongoose's error events
- in many cases handshakes fail either due to improper SNI handling on remote endpoint (in such a case we need to retry the handhsake)

With Mongoose acting as client, in some cases, remote web-servers do not properly handle SNI requests.

In such a case, we would like to retry a TLS handshake (OpenSSL 1.1.1) using same mg_connection without killing it and specifying another (ex. empty hostname) during TLS handshake (we're well aware of opts->srvname option given to SSL_set_tlsext_host_name() ).

We can see mg_tls_handshake is called from connect_conn() and mg_tls_handshake_retry() the latter directly from mg_mgr_poll.
It usually gets called twice from both of the above functions and succeeds the second time (we didn't really get to understand why that is so, so far), or why both invocations need to happen.

We've been implementing sort of a proxy supporting persistent connections (with multiple endpoints multiplexed over a single client connection) thus we're trying to get around the asynchronous nature of Mongoose when handling TLS troubles (events polling) and would be most happy with the possibility of synchronous TLS handshakes invoked within a single Mongoose's poll) performed right after connect succeeds, while the client awaits a response. That's sort of important as since we support HTTP 1.1 persistent connections, the responses would need to be arriving in order and thus the proxy would need  to renegotiate a TLS handshake possibly during a single Mongoose's Poll. 

Anyway. You might get an idea of what we've tried by looking at the code-snippet below:
```
`void mg_tls_handshake_retry(struct mg_connection *c, int tries) {
  struct mg_tls *tls = (struct mg_tls *) c->tls;
  int rc;

  if (c->is_client && tries >= 2)
  {
      if(tries==2)
       {
          //SSL_clear(tls->ssl)
          mg_tls_free(c);
          CCORSConnCtx *ctx = reinterpret_cast<CCORSConnCtx *>(c->fn_data); 
          mg_tls_opts *opts = ctx->getClientTLSOpts();
          opts->srvname = mg_str("");
          c->is_resolving=1;
    
          mg_tls_init(c, opts);
          tls = (struct mg_tls *) c->tls;
        
       }

  }

  SSL_set_fd(tls->ssl, (int) (size_t) c->fd);
  rc = c->is_client ? SSL_connect(tls->ssl) : SSL_accept(tls->ssl);

  if (rc == -1 && c->is_client && tries<6) {
    mg_tls_handshake_retry(c,++tries);
    tls = (struct mg_tls *) c->tls;
  }
  if (!c->is_tls_hs)
   {
      rc=1;//it must have succeeded during recursion
   }

  if (rc == 1) {
    LOG(LL_DEBUG, ("%lu success", c->id));
    c->is_tls_hs = 0;
  } else {
    int code = mg_tls_err(tls, rc);
    if (code != 0) mg_error(c, "tls hs: rc %d, err %d", rc, code);
  }
}
```

The above modified `mg_tls_handshake manages to connect synchronously (without waiting for another poll) when remote server supports SNI just fine i.e. provides a proper response. But when it does not (the recursion gets above depth equal to 2 (the tries variable), that happens only in such cases, then we free the entire TLS related stuff associated with the connection and create it anew through mg_tls_init(), **this time with another approach to TLS handshake**, i.e. with the Hostname parameter cleared.

Then, for some reason, the TLS handshake does not work. **Had we specified a proper and/or supported by the remote-endpoint SNI hostname *in the first place* i.e. when establishing a connection for the first time, it would have worked just fine.**  Maybe, the remote state-machine lands in a state, requiring some lower level actions at the level of TLS protocol/state-machine for having the renegotiation process triggered during same TCP connection, just guessing.

**We just do not seem to be able to fully resurrect a TLS handshake with ANOTHER SNI hostname. That's what we're after.**

The top-priority from the client's perspective is having the contents delivered.

We've been testing a lot and we've been stumbling upon troubles when handling TLS connections through OpenSSL 1.1.1 like a lot. It happens very often that server does not handle the supposed SNI hostname and various errors arise.

You may want to try:
https://picsum.photos/ - can't get TLS handshake to work with that one.
https://i.picsum.photos/id/237/200/300.jpg?hmac=TmmQSbShHz9CdQm0NkEjx1Dyh_Y984R9LpNrpvH2D_U 
for the above the handshake works but one needs to specify https://i.picsum.photos/ hostname through SNI.
https://gridnet.org/logo1.png
above served through IIS, doesn't work with SNI hostname at all.
another one: showmyip.com

we've haven't been setting any CA. OpenSSL errors with code 40 suggesting invalid hostaname within TLS handshake.

Also curious what would be the best way to capture such events which are library specific. ex. OpenSSL returns error 40 in such a case. Mongoose has no knowledge about it. We can read MG_EV_ERROR but there's a string with no data indicating error 40. More about it:[https://stackoverflow.com/questions/53965049/handshake-failure-ssl-alert-number-40](url)
if Mongoose is to handle it all by itself then we would need a way to make it retry with various configurations just like for instance Chromium does on failure.

For now we've gotten around the issue by making the proxy maintain a local knowledge-base of what endpoints it failed with . Chromium and others do a pretty good job at resuming their requests thus on a next query another approach to TLS would be attempted and we manage to get around some of the troubles unnoticed.

Still, for instances such as https://picsum.photos/  we haven't arrived at a solution yet.

**Comment by cpq** [comment]
Thank you for the excellent description.
That seems subtle and deep.

What if Mongoose fetched more TLS error data in handshake, e.g. TLS error number, and fired a error which can be parsed by the error handler? E.g. the error message look like `TLS error 40: ...`

Then the Mongoose event handler can process it:
```c
static void fn(struct mg_connection *c, int ev, ...) {
  switch (ev) {
    case MG_EV_ERROR:
      if (strncmp((char *) ev_data, "TLS error 40", 12) == 0) {
         // Re-initialize the connection. Optionally, keep reconnection cound in c->label
        mg_iobuf_free(&c->send);
        mg_iobuf_free(&c->recv);
         ... clear other flags ..
         c->is_closing = 0;  // Clear error
         struct mg_tls_opts opts = {...};
         mg_tls_init(c, &opts);
      }
    break;
  }
}
```
Not sure that is going to work.

**Comment by rafalsk** [comment]
More data regarding TLS-handshake event passed to the event handler would be welcome!

It would surely enable for high-level inferring that some further customized processing might be needed.

I know you support more than 1 TLS library so adding customized flags/enums for each family of events and translating across these would be an overfill. 

To us, more data within a string is good enough.

Even if one feels up for some customized lower-level processing at the level of TLS library and/or looks at the TLS structures, having the possibility to retrieve hints from the event seems rational.

 Add mg_tls_init_modify_conf() #1426 ~ Great!

2. Amazing.

Closing this for now, I would allow myself to reopen once we get more data.
I shall also give you head-ups about our further results in any case.

Thank you so much.

**Comment by cpq** [comment]
@rafalsk if you have a diff that generates suitable handshake error string, please share - we'll integrate it.
