### ISSUE TITLE
How to parse URI Path Variables?

### ISSUE THREAD

**Issue by cwaldren-ld** [cesanta/mongoose#1459]
- My goal is: easily parse path variables using mongoose. By path variable, I mean something like `/people/{name}` similar to various other [libraries](https://pkg.go.dev/github.com/gorilla/mux#Router.Path).
- My actions were: look for path variable function in mongoose docs, look in github issues, look in github pull requests, and look through examples. I did find an existing issue from long ago [here](https://github.com/cesanta/mongoose/issues/487).
- My expectation was: that there would be a method to extract path variables, especially in the REST examples.
- The result I saw: There is a way to glob match, but I couldn't see a way to extract the path.
- My question is: Is there a simple method to extract path variables? 

I might be missing an obvious way to do this purely with the provided mongoose string methods. This might also be totally out of scope for mongoose, since it's more the responsibility of a higher level router component.

At first I was going to use `sscanf`, but the documentation explicitly says not to use `sscanf` on `mg_str`'s like the `uri`.

I'm looking for something (roughly) along the lines of:
```c
struct mg_uri_vars vars;
if (mg_http_match_uri_vars(hm, "/people/{name}/{age}", &vars)) {
    serve_profile(
        mg_uri_var_get(&vars, "name"), 
        mg_uri_var_get(&vars, "age")
    );
}
```
# Environment

- mongoose version: _7.6_

Thank you for any guidance or pointers.

**Comment by cpq** [comment]
See https://mongoose.ws/documentation/#mg_match
