### ISSUE TITLE
VULN: requesting server with `GET /.%2f` returns a directory listing, even if it's disabled.

### ISSUE THREAD

**Issue by binex-dsk** [cesanta/mongoose#1466]
- My goal is: To completely disable all directory listing
- My actions were: A user entered `/.%2f` into my website using mongoose, https://file.swurl.xyz
- My expectation was: For it to return 404.
- The result I saw: A directory listing, even with dirlist off
- My question is: Why? 

# Environment

- mongoose version: 7.4
- Compiler/IDE and SDK: gcc (GCC) 11.1.0
- Target hardware/board: standard amd64

**Comment by binex-dsk** [comment]
I realized it's probably because %2f is /, so it's requesting `./`. However, directory listing should be completely disabled regardless of circumstances.

**Comment by binex-dsk** [comment]
I disabled listing by setting `MG_ENABLE_DIRLIST` to 0.

The problem is that `listdir` is not `if`'ed under this macro.

**Comment by cpq** [comment]
Yeah, the `MG_ENABLE_DIRLIST` is actually never checked. The code always lists a directory. I'll remove this macro from the code and from the documentation. Please don't use it.
In order to avoid listing a directory, put an empty `index.html` inside.

**Comment by cpq** [comment]
You could retry with `-DMG_ENABLE_DIRLIST=0`
That should disable listing on FS level.
Pull recent sources.

**Comment by binex-dsk** [comment]
Yeah it doesn't seem to be a problem in the latest commit.
