### ISSUE TITLE
Error handling issues (CHECKED_RETURN) for getsockname

### ISSUE THREAD

**Issue by jameshilliard** [cesanta/mongoose#1470]
I'm seeing this get flagged by a static analysis tool:
https://github.com/cesanta/mongoose/blob/1b82aa02aa3d6fecfc23ed0a94c6917f139de1ad/src/sock.c#L122
```c
Calling "getsockname((SOCKET)(size_t)c->fd, __SOCKADDR_ARG({.__sockaddr__ = &[usa.sa](http://usa.sa/)}), &slen)" without checking return value. This library function may fail and return an error code.
```

**Comment by cpq** [comment]
Does your static analyzer shut up if the function call is prefixed with `(void)` , like this:

```c
  (void) getsockname(FD(c), &usa.sa, &slen);
```

**Comment by jameshilliard** [comment]
I don't think that would make it(coverity) stop reporting unchecked returns from what I read, you can see the full report [here](https://groups.google.com/g/swupdate/c/CTxwyaoJbmg/m/CyE0GM5nAQAJ) which was run against the 7.6 amalgamation as part of the [swupdate](https://sbabic.github.io/swupdate/swupdate.html) project(note that line offsets might be slightly off due to adding SPDX identifiers to the header but the amalgamation is otherwise unmodified).

**Comment by cpq** [comment]
Thank you @jameshilliard 
Does this shut up the analyzer?

```c
  if (getsockname(FD(c), &usa.sa, &slen) < 0) (void) 0;  // Ignore return code, calm static analyzers
```

**Comment by jameshilliard** [comment]
> Does this shut up the analyzer?

Looks like that probably would.
