### ISSUE TITLE
 Honor DNS server from DHCP

### ISSUE THREAD

**Issue by vrkansagara** [cesanta/mongoose#1478]
- mongoose version: 7.6

mos's DNS resolver implementation seems to explicitly use Google's 8.8.8.8 DNS server for lookups and doesn't honor DNS settings from DHCP. This doesn't work correctly in intranets or other environments where 8.8.8.8 is accessible. Moreover, local resolving doesn't work.

I am not sure this is bug or anything need to fix but this is something is not working where 8.8.8.8 is allowed.

~~~bash
root@ubuntu:~# /root/client
2022-02-23 15:16:40 2                            Pub topic -> 123/123
2022-02-23 15:16:40 2                            Sub topic -> 123/123
2022-02-23 15:16:41 2                            CREATED
2022-02-23 15:16:42 1                            stray DNS reply


root@ubuntu:~# telnet 8.8.8.8 53
Trying 8.8.8.8...
Connected to 8.8.8.8.
Escape character is '^]'.
Connection closed by foreign host.

root@ubuntu:~# telnet -4 8.8.8.8 53
Trying 8.8.8.8...
Connected to 8.8.8.8.
Escape character is '^]'.
Connection closed by foreign host.

root@ubuntu:~# telnet 192.168.1.1 53
Trying 192.168.1.1...
Connected to 192.168.1.1.
Escape character is '^]'.
~~~

**Comment by cpq** [comment]
If you want to use a different DNS server, just replace the IP address in `mgr->dns4`.
