### ISSUE TITLE
Https Client return TLS handshake: -0x4c

### ISSUE THREAD

**Issue by shu7734** [cesanta/mongoose#1482]
- My goal is: request https://www.microsoft.com/en-us/ and read response
- My actions were: I have copy test/data/ca.cer and http-client to vs project directory
- and change s_url ,#pragma comment(lib,"lib\\x64\\mbedTLS.lib"),and #define MG_ENABLE_MBEDTLS 1
- Debug project return
2022-03-02 10:29:35 3 mongoose.c:4041:mg_tls_ini 1 Setting TLS
2022-03-02 10:29:35 1 mongoose.c:405:mg_error    1 TLS handshake: -0x4c
2022-03-02 10:29:35 3 mongoose.c:3353:close_conn 1 closed

- My question is: what's wrong?

# Environment

- mongoose version: 7.6
- Compiler/IDE and SDK: visual stdio 2019
- Target hardware/board: PC
- Connectivity chip/module: Intel

**Comment by lifw555** [comment]
as the same error
