### ISSUE TITLE
Isn't this an out-of-bounds access?

### ISSUE THREAD

**Issue by trikko** [cesanta/mongoose#1493]
```c
&buf[sizeof(buf)] 
```

https://github.com/cesanta/mongoose/blob/870431dc1abfca60d79bdef8aad7efb154ea0214/src/mqtt.c#L26

**Comment by cpq** [comment]
It looks like it is not:

https://github.com/cesanta/mongoose/blob/870431dc1abfca60d79bdef8aad7efb154ea0214/src/mqtt.c#L25-L26

Can you elaborate on your concern please?

**Comment by trikko** [comment]
Ok, I got it. I missed you're doing a check on ```vlen < buf + sizeof(buf)```
