### ISSUE TITLE
[question] What is the correct way to timeout connection?

### ISSUE THREAD

**Issue by hatkidchan** [cesanta/mongoose#1496]
A while ago (looking in the issues), there was a way to timeout connection using `MG_EV_TIMER` and setting `MG_F_CLOSE_IMMEDIATELY` flag to drop connection after some time (#749), yet I can't find `MG_EV_TIMER` nor `MG_F_CLOSE_IMMEDIATELY` now. `MG_EV_TIMER` (I guess?) is replaced now with `mg_timer_*` functions, but I can't find any way to close connection in a portable manner, or to specify timeout itself somehow. There *is* a timeout value for DNS resolving (`mg_mgr.dnstimeout`), but not for connection itself.

So my question is: what is the correct way to set connection timeout *now*?

P.S. `void close_conn(struct mg_connection *c);` is not available in `mongoose.h`

Another related question, if I'm planning to re-use manager while reconnecting to websocket server, should I `mg_mgr_free()` it or do something else, or I can just start `mg_ws_connect`ing right after last one is closed?

**Comment by cpq** [comment]
See examples/http-client
