### ISSUE TITLE
Feature Request: Binding to Unix domain socket

### ISSUE THREAD

**Issue by dgcampea** [cesanta/mongoose#1498]
I'd like to request support for binding to a Unix socket instead of IP:port for dedicated reverse-proxy or backend scenarios. (lessened overhead and ease of local maintenance)
Ref: https://github.com/jcorporation/myMPD/discussions/713

**Comment by cpq** [comment]
There are no plans to implement things like this.

**Comment by cyberb** [comment]
Is it possible to explain the reason behind it?

**Comment by scaprile** [comment]
@cyberb : This is closed and two-years-old.
Please see our docs and if you have an actual issue then please open an issue.
https://mongoose.ws/documentation/tutorials/
