### ISSUE TITLE
when frequently fresh the websocket webpage, the server got an error

### ISSUE THREAD

**Issue by matthiashack** [cesanta/mongoose#1534]
![image](https://user-images.githubusercontent.com/102785454/164895047-9eeab4e1-304e-452b-ab1f-9d6f097fcb01.png)

![image](https://user-images.githubusercontent.com/102785454/164895082-36316de4-be57-4348-9d58-19e6c58412fb.png)

**Comment by matthiashack** [comment]
[test.zip](https://github.com/cesanta/mongoose/files/8546963/test.zip)

**Comment by cpq** [comment]
Why do you use a non-documented, internal method that is neither in the documentation nor in the examples?

**Comment by matthiashack** [comment]
for example ,two clients connect to the server, one force close the connection, I need to close the pair client manally

**Comment by cpq** [comment]
@matthiashack use `c->is_closing = 1` (immediate close) or `c->is_draining = 1` (send the rest of data and close)  to signal event manager to close the connection. Don't remote it from manager yourself.

**Comment by cpq** [comment]
Please see https://mongoose.ws/documentation/#best-practices
