### ISSUE TITLE
Mongoose keeps connection

### ISSUE THREAD

**Issue by whyte624** [cesanta/mongoose#1542]
- My goal is: 

Send requests from Linux backend to Windows which runs service on port 6543 with mongoose http server inside.

- My actions were: 
 
I send request to windows server port 6543 from linux and see with `netstat -nputw`

> tcp        0      0 10.0.0.4:54960         10.0.0.5:6543       ESTABLISHED

After a while this TCP connection disappears on linux side.

On windows side I see in powershell with `netstat -a`:

>   TCP    10.0.0.5:6543      10.0.0.4:54960    ESTABLISHED

I see that connection is established even when connection finished from linux side.

- My expectation was:
 
connection to disappear on windows side also.

- My question is: Why TCP connection shown as still established on Windows side?

# Environment

- mongoose version: 6.18

**Comment by matthiashack** [comment]
try set  is_drain or   is_closing =1 in your code

**Comment by cpq** [comment]
1. Use the latest code.
2. Add some more debugging - e.g. print all active connections, see https://github.com/cesanta/mongoose/blob/master/examples/http-restful-server/main.c#L33-L47
