### ISSUE TITLE
Event when full HTTP request or its header is received.

### ISSUE THREAD

**Issue by smilediver** [cesanta/mongoose#1545]
AFAIK, right now there are two situations you can get with HTTP requests:

1) You get one `MG_EV_HTTP_MSG` with full message;
2) You get one or more `MG_EV_HTTP_CHUNK` and finally `MG_EV_HTTP_MSG` when message receiving is complete.

This setup it's awkward if you want to start processing the message right away and deal with incoming chunks later, because you need to handle start of the request in both those events, and in `MG_EV_HTTP_MSG` you need to figure out if you already started processing this message or not. I think, in most cases, if you're dealing with chunked messages (like file uploads), you really want to start processing (say opening the file) after you have full headers, and process incoming chunks (write them to that file) as they arrive.

It would be nice if there was an event (say `MG_EV_HTTP_REQUEST`), that is raised after full HTTP message or its headers were received before any `MG_EV_HTTP_CHUNK` events are raised. And if `mg_http_message` had a flag indicating if this is a full or partial message, ie if any `MG_EV_HTTP_CHUNK` will follow. So essentially those two situations become like this:

1) You get one `MG_EV_HTTP_REQUEST` with full message and then `MG_EV_HTTP_MSG`;
2) You get one `MG_EV_HTTP_REQUEST`, one or more `MG_EV_HTTP_CHUNK` and finally `MG_EV_HTTP_MSG` when message receiving is complete.

**Comment by cpq** [comment]
At this moment, we either send 
- `MG_EV_HTTP_MSG` - if a full message was received
- a sequence of `MG_EV_HTTP_CHUNK`

If during processing we delete chunks, the whole message is never buffered. We cannot send a `MG_EV_HTTP_MSG` in this case - because the message itself is not present. We cannot have a different event semantics in different situations.

This is an example of `examples/file-upload`, and sending a 5k file via `curl --data-binary @file.txt http://localhost:8000/upload`:
```
274ffc24 3 mongoose.c:3531:accept_conn  3 accepted 127.0.0.1:51046
274ffc24 3 mongoose.c:3405:read_conn    3 0x4 0:0 2048 err 0 (Success)
274ffc24 2 main.c:17:cb                 Got chunk len 1892
274ffc24 2 main.c:18:cb                 Query string: []
274ffc24 3 mongoose.c:3405:read_conn    3 0x4 0:156 3665 err 0 (Success)
274ffc24 2 main.c:17:cb                 Got chunk len 3665
274ffc24 2 main.c:18:cb                 Query string: []
274ffc24 2 main.c:17:cb                 Got chunk len 0
274ffc24 2 main.c:18:cb                 Query string: []
274ffc24 2 main.c:22:cb                 Last chunk received, sending response
274ffc24 3 mongoose.c:3416:write_conn   3 0x4 52:0 52 err 0 (Success)
274ffc24 3 mongoose.c:3405:read_conn    3 0x4 0:0 -1 err 0 (Success)
274ffc24 3 mongoose.c:2738:mg_close_con 3 closed
```

As you can see, there is only a sequence of CHUNK messages. Now, sending a smaller file and fits into MG_IO_SIZE, shows one single MSG event, `curl --data-binary @file2.txt http://localhost:8000/upload`:
```
27578aa1 3 mongoose.c:3531:accept_conn  5 accepted 127.0.0.1:51078
27578aa1 3 mongoose.c:3405:read_conn    5 0x4 0:0 1118 err 0 (Success)
27578aa1 2 main.c:26:cb                 Got all 963 bytes!
27578aa1 2 main.c:27:cb                 Query string: []
27578aa1 3 mongoose.c:3416:write_conn   5 0x4 47:0 47 err 0 (Success)
27578aa1 3 mongoose.c:3405:read_conn    5 0x4 0:0 -1 err 0 (Success)
27578aa1 3 mongoose.c:2738:mg_close_con 5 closed
```

So the event handler must handle both situations - when a message is small, and `MG_EV_HTTP_MSG` gets received in that case, or the message is large, chunks gets deleted by the handler - and a sequence of `MG_EV_HTTP_CHUNK` gets received in that case.

What is awkward in that? Please note that your suggestion can't work - we can't send `MG_EV_HTTP_MSG` in the absence of the whole message.

**Comment by smilediver** [comment]
Are you saying that `MG_EV_HTTP_MSG` is not supposed to be sent if chunked message is being received and you're deleting chunks from the buffer? Because I'm getting that event as the last one after all chunks are processed and removed from the buffer. Example log of macOS Finder uploading a file through WebDAV:

```
MG_EV_HTTP_CHUNK: 0x600003b06840:40131 chunked:true  PUT /webdav/test/blending_test.jpg (body: -1, chunk: 0)
MG_EV_HTTP_CHUNK: 0x600003b06840:40131 chunked:true  PUT /webdav/test/blending_test.jpg (body: -1, chunk: 3817)
MG_EV_HTTP_CHUNK: 0x600003b06840:40131 chunked:true  PUT /webdav/test/blending_test.jpg (body: -1, chunk: 3817)
MG_EV_HTTP_CHUNK: 0x600003b06840:40131 chunked:true  PUT /webdav/test/blending_test.jpg (body: -1, chunk: 3664)
MG_EV_HTTP_CHUNK: 0x600003b06840:40131 chunked:true  PUT /webdav/test/blending_test.jpg (body: -1, chunk: 7)
MG_EV_HTTP_MSG:   0x600003b06840:40131 chunked:true  PUT /webdav/test/blending_test.jpg (body: 0, chunk: 0)
```

I'm using 7.6 version.

**Comment by cpq** [comment]
If you're not deleting the chunks, you'll get the `MG_EV_HTTP_MSG` at the end - because you actually have the whole body.
What's wrong with that?

**Comment by smilediver** [comment]
I'm saying that I'm deleting the chunks and I still get `MG_EV_HTTP_MSG` after all chunk events. See the log above. Is this an expected behavior?

**Comment by cpq** [comment]
I don't think it is.
Can you use the latest HEAD please?

**Comment by smilediver** [comment]
Tried latest, still the same problem. It seems this happens when `Transfer-Encoding: chunked` is used.

`curl -H "Transfer-Encoding: chunked" --data-binary ~/Desktop/TODO.md http://localhost:8000/upload`
```
1358422 3 mongoose.c:3532:accept_conn   3 accepted 127.0.0.1:52130
1358422 3 mongoose.c:3407:read_conn     3 0x4 0:0 202 err 0 (Undefined error: 0)
1358422 2 main.c:17:cb                  Got chunk len 29 <--------------------------- MG_EV_HTTP_CHUNK
1358422 2 main.c:18:cb                  Query string: []
1358422 2 main.c:17:cb                  Got chunk len 0  <--------------------------- MG_EV_HTTP_CHUNK
1358422 2 main.c:18:cb                  Query string: []
1358422 2 main.c:22:cb                  Last chunk received, sending response
1358422 2 main.c:26:cb                  Got all 0 bytes! <--------------------------- MG_EV_HTTP_MSG
1358422 2 main.c:27:cb                  Query string: []
1358422 3 mongoose.c:3418:write_conn    3 0x4 97:0 97 err 0 (Undefined error: 0)
1358422 3 mongoose.c:3407:read_conn     3 0x4 0:0 -1 err 0 (Undefined error: 0)
1358422 3 mongoose.c:2738:mg_close_conn 3 closed
```

In `http_cb()` after `walkchunks()` is done, `      } else if (n > 0 && (size_t) c->recv.len >= hm.message.len) {` is satisfied, because `n`, `c->recv.len`, `hm.message.len` are all equal to HTTP header size.
