### ISSUE TITLE
Possible leak in function mg_ws_send ?

### ISSUE THREAD

**Issue by rhymerjr** [cesanta/mongoose#1578]
- My goal is:  Send video frames converted (by opencv) to JPG through websocket to the browser.
It works fine, but the memory grows really fast... If the image distribution is in realtime, the memory grows hundreds of megabytes in minutes.  If the distribution is slower, sending every 10th frame for example, the memory still growing but much slower. 

I'm using this function to send the image to all websocket connections:

````
```
void ws_push_data_to_all_websocket_connections(struct mg_mgr *m,BYTE *pBuffer,ULONG BufferSize)
{
    const int width  = 1920; 
    const int height = 540;  
    cv::Mat mat_src = cv::Mat(height, width, CV_8UC(2), pBuffer);
    cv::Mat mat_dst = cv::Mat(height, width, CV_8UC2);
    cv::cvtColor(mat_src, mat_dst, cv::COLOR_YUV2BGR_Y422,0);
    cv::resize(mat_dst, mat_dst, cv::Size(640,360));
    std::vector<int> param(2);
    param[0] = cv::IMWRITE_JPEG_QUALITY;
    param[1] = 30;
    std::vector<uchar> buff; 
    cv::imencode(".jpg", mat_dst, buff, param);

    struct mg_connection *c;
    for (c = m->conns; c != NULL; c = c->next )
    {
        mg_ws_send(c,(char*)buff.data(),buff.size(), WEBSOCKET_OP_BINARY);
    }
    // free all allocated resources
    buff.clear();
    mat_src.release();
    mat_dst.release();
}
```
````

If I comment out the line  _mg_ws_send_  , the memory problem goes away!

- The result I saw: Continous memory consumption
- My question is: is there a possible leak somewhere under the function _mg_ws_send_

Other info: My _mg_mgr_poll_  runs in a seperate thread like this:

`while (running.load())
 {
            mg_mgr_poll(&mgr, 10);
  }`

Environment:

Debian 11.3
Linux version 5.10.0-14-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.113-1 (2022-04-29)

g++ (Debian 10.2.1-6) 10.2.1 20210110

g++ -m64 -g -std=c++17 -I/usr/local/include/opencv2 -I/usr/local/include/opencv4/opencv2/ -L/usr/local/lib/ -I../../../Include -D_C_DEBUG_ -DMG_IO_SIZE=524288 mongoose.c Sample_RXmTX.cpp -o Sample_RXmTX.out  -lpthread $(pkg-config --libs --cflags protobuf) -lstdc++fs  -Wl,-rpath,/usr/local/lib /usr/local/lib/libopencv_gapi.so.4.6.0 /usr/local/lib/libopencv_highgui.so.4.6.0 /usr/local/lib/libopencv_ml.so.4.6.0 /usr/local/lib/libopencv_objdetect.so.4.6.0 /usr/local/lib/libopencv_photo.so.4.6.0 /usr/local/lib/libopencv_stitching.so.4.6.0 /usr/local/lib/libopencv_video.so.4.6.0 /usr/local/lib/libopencv_videoio.so.4.6.0 /usr/local/lib/libopencv_imgcodecs.so.4.6.0 /usr/local/lib/libopencv_dnn.so.4.6.0 /usr/local/lib/libopencv_calib3d.so.4.6.0 /usr/local/lib/libopencv_features2d.so.4.6.0 /usr/local/lib/libopencv_flann.so.4.6.0 /usr/local/lib/libopencv_imgproc.so.4.6.0 /usr/local/lib/libopencv_core.so.4.6.0

- mongoose version: 7.7

**Comment by cpq** [comment]
It is unlikely that mg_ws_send() has a leak.
What is likely is that your code has a problem. In your loop, you send to all connections. Not just to websocket ones, but to all. Including the listening socket, HTTP connections, and not-yet-upgraded WS connections. This is a better way:

```c
    for (struct mg_connection *c = m->conns; c != NULL; c = c->next ) {
        if (c->is_websocket == false) continue; // Or, better, use c->label to mark your WS connections
        mg_ws_send(c,(char*)buff.data(),buff.size(), WEBSOCKET_OP_BINARY);
    }
```

**Comment by rhymerjr** [comment]
OK, your suggestion has solved my problem!
Thank you for putting me into the right direction!

**Comment by jcorporation** [comment]
> Or, better, use c->label to mark your WS connections

Could you please explain why ths is better than using `c->is_websocket`?

**Comment by cpq** [comment]
If every websocket connection should be broadcasted, then `c->is_websocket` can be used.
If an application uses websocket connections for some other purposes too, then `c->label` should be used.

**Comment by jcorporation** [comment]
Thanks for clarification!
