### ISSUE TITLE
websocket client does not automatically reconnect

### ISSUE THREAD

**Issue by romanholidaypancakes** [cesanta/mongoose#1588]
If the websocket client is started first before the websocket server is started, the client always loops in `fn`. At this time, we start the server, and the client will not try to connect with the server. I just use a simple test code: [examples/websocket-client/main.c](https://github.com/cesanta/mongoose/blob/master/examples/websocket-client/main.c) and [examples/websocket-server/main.c](https://github.com/cesanta/mongoose/blob/master/examples/websocket-server/main.c)

steps:
1. start client
2. start server

at this point the client is always unable to connect to the server, is this the expected behavior? Any suggestions on what mitigations I should use, thanks

**Comment by cpq** [comment]
Well, you need to start server first.
Or, you can add a reconnection logic to the client. Steal it from the mqtt client. Take a look at the tutorial:

https://mongoose.ws/tutorials/mqtt-client/
