### ISSUE TITLE
mg_calloc does not set all memory to zero

### ISSUE THREAD

**Issue by mavsw** [cesanta/mongoose#1599]
- My goal is:  N/A
- My actions were:  N/A
- My expectation was:  N/A
- The result I saw:  N/A
- My question is:  

mg_calloc only sets memory for the first element to zero, I'd expect it to zero out all allocated memory.

Line 195 in mongoose.h https://github.com/cesanta/mongoose/blob/4f9cfdf65db51290be2c86b66bf5f692158035b0/mongoose.h#L195

Full (original) context:
```
// Re-route calloc/free to the FreeRTOS's functions, don't use stdlib
static inline void *mg_calloc(int cnt, size_t size) {
  void *p = pvPortMalloc(cnt * size);
  if (p != NULL) memset(p, 0, size);     // <---- line 195
  return p;
}
```

Line 195 is currently: `if (p != NULL) memset(p, 0, size);`
But should probably be changed to something like: `if (p != NULL) memset(p, 0, (cnt * size));`
to ensure that all allocated memory has been set to zero.

# Environment

- mongoose version: master/7.7
- Compiler/IDE and SDK: N/A
- Target hardware/board:  N/A
- Connectivity chip/module:  N/A

**Comment by cpq** [comment]
thank you @mavsw
