### ISSUE TITLE
The current unit tests throws the error "certificate verify failed"

### ISSUE THREAD

**Issue by JamesMenetrey** [cesanta/mongoose#1623]
Dear Mongoose developers,

- My goal is: understand why the unit tests throw the error "certificate verify failed" when running the test `test_http_client`.
- My actions were: testing it locally and cross my results with the official unit tests results in the GitHub Actions, which also throw that error. The error is located [here](https://github.com/cesanta/mongoose/runs/7238361430?check_suite_focus=true#step:4:479).
- My expectation was: no error to be thrown, since the file `ca.pem` contains the root certificate of Let's Encrypt. 
- The result I saw: [see here](https://github.com/cesanta/mongoose/runs/7238361430?check_suite_focus=true#step:4:479)
- My question is: Why is this error raised, provided that the root certificate of Let's Encrypt is present in the file `ca.pem`. I note that the test domain (`cesanta.com`) is using Let's Encrypt.

# Environment
- Latest run of the unit tests on [linux test CC=gcc SSL=OPENSSL](https://github.com/cesanta/mongoose/runs/7238361430?check_suite_focus=true#logs)

Thanks!

**Comment by cpq** [comment]
@JamesMenetrey maybe you haven't looked well enough at the unit test.
The test is actually CHECKING that the verification fails, by setting a wrong domain in the options. Since the domains in the cert and opts are different, the verification MUST fail, which is checked by the unit test.
I hope I don't have to point to an appropriate line in the unit test  - leaving that as an exercise for you.

**Comment by JamesMenetrey** [comment]
Dear @cpq, many thanks for your answer and my apologies for the dumb question. You are right, I haven't looked carefully enough at the unit test and haven't noticed that a wrong domain name was set in the option.

Here is the line of code that sets the domain name in the unit test for future reference.

https://github.com/cesanta/mongoose/blob/f40b272eeb759af67e5557c3b1afeba1d80e47b2/test/unit_test.c#L970

Cheers

**Comment by cpq** [comment]
@JamesMenetrey no worries at all. Thanks for taking your time and filing the report, that's appreciated.
