### ISSUE TITLE
mg_http_serve_file() does not use root_dir of mg_http_serve_opts

### ISSUE THREAD

**Issue by sebhub** [cesanta/mongoose#1624]
In contrast to `mg_http_serve_dir()`, `mg_http_serve_file()` does not use the `root_dir` option of `mg_http_serve_opts`. This makes this function quite useless.

**Comment by scaprile** [comment]
Please tell us what you are trying to do that you can't do with the current API

**Comment by linuxguy123** [comment]
I've got the very same issue.
Using Version 7.7.  Compiler is gcc.  OS is Linux F36, KDE.

**Comment by scaprile** [comment]
> It does not work with a hard coded path, "/home/me/Development/project/serve", for example.

`path` - Path to file to serve

You have to specify the full path to the file:
`mg_http_serve_file(c, hm,"/home/me/Development/project/serve/thefileIwanttoserve", opts);`

What the OP mentions is just the way that function works; hence the question: 

> Please tell us what you are trying to do that you can't do with the current API

**Comment by linuxguy123** [comment]
Thanks for the reply.

You have to specify the full path to the file:
mg_http_serve_file(c, hm,"/home/me/Development/project/serve/thefileIwanttoserve", opts);

Then what is the purpose of mg_http_serve_opts.root_dir ?   Shouldn't mg_http_serve_file look in root_dir for the file ?

"opts.root_dir = "/var/www,/conf=/etc";  // Serve /var/www. URIs starting with /conf are served from /etc"
https://mongoose.ws/documentation/#struct-mg_http_serve_opts

How does one put a code block in this editor ?   And how does one quote from a previous message ?

**Comment by cpq** [comment]
@sebhub `mg_http_serve_dir()` actually calls `mg_http_serve_file()`, so I would not blame `mg_http_serve_file()` as useless. Can you elaborate, as @scaprile requested, on your use case, please?

Would you like `mg_http_serve_file()` to honor `opts->root_dir`, and why?

**Comment by cpq** [comment]
No response, closing this. @sebhub, feel free to reopen if you have more feedback.

**Comment by linuxguy123** [comment]
Why did you close this as completed when 2 users have pointed out a bug in the API ?

"Would you like mg_http_serve_file() to honor opts->root_dir, and why?"

So that one can set the dir from which the http_serve_file gets files once and not have to make up a complex path for every file that is served.   This is especially true for nested file requests. 

Why would the API have root_dir as an option if it doesn't work or there was no use for it ?
