### ISSUE TITLE
sorry unimplemented: non-trivial designated initializers not supported

### ISSUE THREAD

**Issue by afridali123** [cesanta/mongoose#1667]
getting this error while compiling code of http_client/ main.c

**Comment by scaprile** [comment]
What is your compiler ? What version ? On what machine ? Under which OS ? For what target platform ?
Which file ? What line number ?
Can you please paste your command and the relevant error ?
Did you google for that error ? You seem to be trying to compile C (Mongoose and the example are C code) with a very old C++ compiler. If you have _clang_ try `make clean all CC=clang` (or the equivalent in your environment)

**Comment by cpq** [comment]
@afridali123 an issue template is there for a reason. By neglecting it, you're causing extra time spent by everybody. Please don't.

**Comment by afridali123** [comment]
its solved by updating compiler
