### ISSUE TITLE
Upgrading to 7.7 causes ssl connection to fail

### ISSUE THREAD

**Issue by romanholidaypancakes** [cesanta/mongoose#1732]
- wss client
```C++
       opts.ca = "ca.pem";
```

- wss server
```C++
        opts.cert    = "crt.pem";
        opts.certkey = "key.pem";
```
The above code works fine in 7.6, but will report an error in 7.7:
- client(7.7)
```
4492:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl\statem\statem_clnt.c:1916:
337e1519 1 mongoose.c:404:mg_error      1 0x27c tls hs: rc -1, err 1
```
- server(7.7)
```
28304:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:ssl\record\rec_layer_s3.c:1544:SSL alert number 42
bd5fdfa 1 mongoose.c:404:mg_error       10 0x30c tls hs: rc -1, err 1
```

Test 7.8 still has connection errors

**Comment by scaprile** [comment]
There is 7.8 out already, you should move to that one.
Will you be so kind to tell us what is that error, where, when, on what platform, what OS, what compiler, with what code ? Did you check the [TLS tutorial](https://mongoose.ws/tutorials/tls/) (I infer that is what you are doing, am I right ?) and compared to your own code to catch the differences in the newer API ? Did you read the [release notes](https://github.com/cesanta/mongoose/releases) ?

**Comment by scaprile** [comment]
> I'm locating the cause of this change: [Honor hostname validation for openssl](https://github.com/cesanta/mongoose/commit/b78ced4fa9152ccfba06bda3df955fdb7eb9a9bf)

Maybe your hostname doesn't fit your certificate ?
