### ISSUE TITLE
Memory - corruptions  (OVERRUN) in mg_dtoa()

### ISSUE THREAD

**Issue by jameshilliard** [cesanta/mongoose#1733]
I'm seeing this get flagged by coverity:
https://github.com/cesanta/mongoose/blob/0a265e79a67d7bfcdca27f2ccb98ccb474677ec6/src/fmt.c#L150
```c
Overrunning array "buf" of 40 bytes at byte offset 40 using index "s + n" (which evaluates to 40).
```

**Comment by scaprile** [comment]
Correct, though the user must request a 40+ digit number and it only overwrites already used variable space in the stack
See #1746
