### ISSUE TITLE
Null pointer dereferences  (FORWARD_NULL) in mg_iobuf_init()

### ISSUE THREAD

**Issue by jameshilliard** [cesanta/mongoose#1734]
I'm seeing this get flagged by coverity:
https://github.com/cesanta/mongoose/blob/0a265e79a67d7bfcdca27f2ccb98ccb474677ec6/src/iobuf.c#L47
```c
Passing "io" to "mg_iobuf_resize", which dereferences null "io->buf".
```

**Comment by scaprile** [comment]
As the function is called with new_size=0, dereferencing occurs in zeromem(), which checks for null, and free(), which is safe. Nothing to worry about here.

**Comment by scaprile** [comment]
free() and memmove() are safe, but memmove() should not get a null pointer

**Comment by cpq** [comment]
Shall this issue be closed?
