### ISSUE TITLE
Null pointer dereferences  (NULL_RETURNS) in mg_timer_add()

### ISSUE THREAD

**Issue by jameshilliard** [cesanta/mongoose#1737]
I'm seeing this get flagged by coverity:
https://github.com/cesanta/mongoose/blob/0a265e79a67d7bfcdca27f2ccb98ccb474677ec6/src/net.c#L227
```c
Dereferencing a pointer that might be "NULL" "t" when calling "mg_timer_init".
```

**Comment by cpq** [comment]
Closing as fixed

**Comment by jameshilliard** [comment]
I think we might also need #1756 to prevent this from getting flagged.
