### ISSUE TITLE
(TAINTED_SCALAR) in mg_dns_parse()

### ISSUE THREAD

**Issue by jameshilliard** [cesanta/mongoose#1738]
I'm seeing this get flagged by coverity:
https://github.com/cesanta/mongoose/blob/0a265e79a67d7bfcdca27f2ccb98ccb474677ec6/src/dns.c#L113
```c
Using tainted variable "mg_ntohs(h->num_answers)" as a loop boundary.
```
https://github.com/cesanta/mongoose/blob/0a265e79a67d7bfcdca27f2ccb98ccb474677ec6/src/dns.c#L107
```c
Using tainted variable "mg_ntohs(h->num_questions)" as a loop boundary.
```

**Comment by scaprile** [comment]
There is already a sanity check in place before that:
https://github.com/cesanta/mongoose/blob/8ef8ee91e90448f1adc77ccaa35a8c3824975eb3/src/dns.c#L105-L106
