### ISSUE TITLE
wss connection is not opening by websocket client

### ISSUE THREAD

**Issue by NuclearRazor** [cesanta/mongoose#1778]
Hi to all of who use mongoose or develop. I have some good results with this library and I want to use it in production, but, I have some issues with wss connection. 

My example based on the next example (websocket client):
[example](https://github.com/cesanta/mongoose/tree/e5b0528aca2524d15bf421ce36c64afa8db137c8/examples/websocket-client)

```
#include "mongoose.h"

static const char *s_url = "wss://api.us-east.speech-to-text.watson.cloud.ibm.com/instances/<IBM_INSTANCE_ID>/v1/recognize?access_token=<ACCESS_IBM_TOKEN>";

static void fn(struct mg_connection *c, int ev, void *ev_data, void *fn_data) {
    fprintf(stderr, "\nDEBUG fn init\n");
   
    if (ev == MG_EV_OPEN) {
        c->is_hexdumping = 1;
        fprintf(stderr, "\nDEBUG MG_EV_OPEN is ok\n"); 
    } 
    else if(ev == MG_EV_CONNECT)
    {
        fprintf(stderr, "\nDEBUG MG_EV_CONNECT is ok\n"); 
    }
    else if (ev == MG_EV_ERROR) {
        // On error, log error message
        MG_ERROR(("%p %s", c->fd, (char *) ev_data));
    } 
    else if (ev == MG_EV_WS_OPEN) {
        // When websocket handshake is successful, send message

        fprintf(stderr, "\nDEBUG websocket handshake is successful, send message\n");

        const char * action_init_payload = "{\"action\":\"start\"}";

        mg_ws_send(c, action_init_payload, sizeof(action_init_payload), WEBSOCKET_OP_TEXT);
    } 
    else if (ev == MG_EV_WS_MSG) {

        fprintf(stderr, "\nDEBUG response\n");    
          
        // When we get echo response, print it
        //struct mg_ws_message *wm = (struct mg_ws_message *) ev_data;
        //void *value = malloc(wm->data.len);
        //memcpy(value, wm->data.ptr, wm->data.len);
        fprintf(stderr, "\nDEBUG websocket handshake is successful, send message\n");
    }
    if (ev == MG_EV_ERROR || ev == MG_EV_CLOSE || ev == MG_EV_WS_MSG) {
        fprintf(stderr, "\nDEBUG ws error\n");

        *(bool *) fn_data = true;  // Signal that we're done        
    }

}

int main(void) {
  struct mg_mgr mgr;        // Event manager
  bool done = false;        // Event handler flips it to true
  struct mg_connection *c;  // Client connection
  mg_mgr_init(&mgr);        // Initialise event manager
  
  //enum { MG_LL_NONE, MG_LL_ERROR, MG_LL_INFO, MG_LL_DEBUG, MG_LL_VERBOSE };
  
  mg_log_set(MG_LL_VERBOSE);  // Set log level
  
  //Warning:
  //Transfer-Encoding: chunked
  //only for streaming mode!
  
  c = mg_ws_connect(&mgr, s_url, fn, &done, "Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n");     // Create client
  while (c && done == false) mg_mgr_poll(&mgr, 1000);  // Wait for echo
  mg_mgr_free(&mgr);                                   // Deallocate resources
  return 0;
}

```

I have a next output:
DEBUG fn init

DEBUG MG_EV_OPEN is ok
43431124 3 net.c:184:mg_connect         2 -1 udp://8.8.8.8:53
43431124 4 dns.c:251:mg_sendnsreq       1 resolving api.us-east.speech-to-text.watson.cloud.ibm.com @ 8.8.8.8, txnid 1
43431124 3 sock.c:175:mg_send           2 0x4 0:0 65 err 0
4343114f 4 sock.c:664:mg_mgr_poll       2 r- tchrc
4343114f 3 sock.c:302:read_conn         2 0x4 snd 0/0 rcv 0/2048 n=204 err=9
4343114f 4 dns.c:155:dns_cb             e38668.b.akamaiedge.net 1
4343114f 3 dns.c:167:dns_cb             1 e38668.b.akamaiedge.net is ...

DEBUG fn init
43431150 3 sock.c:386:mg_connect_resolv 1 0x5 -> 17211d8c:443 pend

DEBUG fn init
43431150 4 sock.c:664:mg_mgr_poll       1 -- tChrc
43431165 4 sock.c:664:mg_mgr_poll       2 -- tchrc

DEBUG fn init
43431165 4 sock.c:664:mg_mgr_poll       1 -w tChrc

DEBUG fn init

DEBUG MG_EV_CONNECT is ok
43431165 4 sock.c:664:mg_mgr_poll       2 -- tchrc

DEBUG fn init
43431165 4 sock.c:664:mg_mgr_poll       1 -w tchrc
43431165 3 sock.c:313:write_conn        1 0x5 snd 2057/4096 rcv 0/0 n=2057 err=115
43431165 2 sock.c:136:iolog
-- 1 ... -> ...  2057
0000   47 45 54 20 2f 69 6e 73 74 61 6e 63 65 73 2f 65   GET /instances/
...
                                                         /v1/recognize
0040   3f 61 63 63 65 73 73 5f 74 6f 6b 65 6e 3d 65 79   ?access_token=
...                                                                      
0710   54 54 50 2f 31 2e 31 0d 0a 55 70 67 72 61 64 65   TTP/1.1..Upgrade
0720   3a 20 77 65 62 73 6f 63 6b 65 74 0d 0a 48 6f 73   : websocket..Hos
0730   74 3a 20 61 70 69 2e 75 73 2d 65 61 73 74 2e 73   t: api.us-east.s
0740   70 65 65 63 68 2d 74 6f 2d 74 65 78 74 2e 77 61   peech-to-text.wa
0750   74 73 6f 6e 2e 63 6c 6f 75 64 2e 69 62 6d 2e 63   tson.cloud.ibm.c
0760   6f 6d 0d 0a 43 6f 6e 6e 65 63 74 69 6f 6e 3a 20   om..Connection:
0770   55 70 67 72 61 64 65 0d 0a 53 65 63 2d 57 65 62   Upgrade..Sec-Web
0780   53 6f 63 6b 65 74 2d 56 65 72 73 69 6f 6e 3a 20   Socket-Version:
0790   31 33 0d 0a 53 65 63 2d 57 65 62 53 6f 63 6b 65   13..Sec-WebSocke
07a0   74 2d 4b 65 79 3a 20 6c 36 30 69 58 77 72 2b 44   t-Key: 
...
07c0   0a 53 65 63 2d 57 65 62 53 6f 63 6b 65 74 2d 45   .Sec-WebSocket-E
07d0   78 74 65 6e 73 69 6f 6e 73 3a 20 70 65 72 6d 65   xtensions: perme
07e0   73 73 61 67 65 2d 64 65 66 6c 61 74 65 3b 20 63   ssage-deflate; c
07f0   6c 69 65 6e 74 5f 6d 61 78 5f 77 69 6e 64 6f 77   lient_max_window
0800   5f 62 69 74 73 0d 0a 0d 0a                        _bits....

DEBUG fn init
4343117b 1 event.c:21:mg_error          1 0x5 socket error

DEBUG fn init
4343117b 1 main.c:18:fn                 0x5 socket error

DEBUG ws error
4343117b 4 sock.c:664:mg_mgr_poll       2 -- tchrc

DEBUG fn init
4343117b 4 sock.c:664:mg_mgr_poll       1 -- tchrC

DEBUG fn init

DEBUG ws error
4343117b 3 net.c:161:mg_close_conn      1 closed
4343117b 4 sock.c:664:mg_mgr_poll       2 -- tchrC
4343117b 3 net.c:161:mg_close_conn      2 closed
4343117b 3 net.c:244:mg_mgr_free        All connections closed

I have the same wss:// link in Postman, and all is working. But in code I can't get a same success result.

So, MG_EV_CONNECT is okay, but WS events are not handled yet...

Also, I tried to call ws:// but I have 301 "moved error".

**Comment by scaprile** [comment]
Please check what is the URL that the site uses for WS connections, use a working example first, then check your code, check it again, and if you still have issues please follow the posting guidelines.
