### ISSUE TITLE
How to suppress warnings from OpenSSL

### ISSUE THREAD

**Issue by rafalsk** [cesanta/mongoose#1784]
# Environment

- mongoose version: 7.4

Hey there! Long time no hear, just two small questions;
1) any idea how to suppress warnings from OpenSSL? 
`ex. "SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl\record\rec_layer_s3.c:1544:SSL alert number 46"`
Rationale: to save of CPU and synchronization usage (it all goes to console.. when many connections it can get messy quick).

2) lots of porting needed to 7.8 from 7.4?

And hey! Thanks a lot from Wizards. Great stuff.

We've integrated Mongoose heavily into GRIDNET OS (https://gridnet.org)... among many things the crypto-incentivized reverse CORS proxy apparatus is powered through it.. just take a look https://test.gridnet.org:444/https://wikipedia.org or  https://test.gridnet.org:444/https://google.com .. our recent research paper https://www.mdpi.com/2079-9292/11/19/3004

The proxy itself has full Http 1.1 support, persistent connections, supports all the encoding schemes on the planet, (de)multi plexing of connections from client web-browsers, association of relative requests with endpoints, smart-caching of contents, support of dynamic content retransmissions, lots of smart optimizations, full CORS mitigation, makes sure that 100% of contents referenced from any websites does go through the proxy (really), just to mention a few.

**Comment by cpq** [comment]
Great stuff, thanks!

1. That's not really a mongoose library question - more like an OpenSSL question
2. Not much - if you can be more specific, a more specific answer can be made

**Comment by rafalsk** [comment]
Understood, closing, no more questions for now.
