### ISSUE TITLE
What should Mongoose Server do when Websocket is unconventionally disconnected?

### ISSUE THREAD

**Issue by craigtao** [cesanta/mongoose#1799]
This does not occur in browsers (chrome, edge, IE), and when the browser is closed, the websocket disconnects normally.

But in .NET, when using webbrowser (based on the IE kernel), when the entire .NET application is closed, the js program inside webbrowser does not close websocket,  
This is actually the same principle as we directly unplug the network cable, which belongs to the abnormal disconnection of websocket.

At this point, if the mongoose server sends a message to the connection, the mongoose server crashes

**Comment by craigtao** [comment]
I hope I had described this issue clearly

**Comment by scaprile** [comment]
A WebSocket server must and should do what the respective RFC says it must and should do.
WebSocket runs on TCP and the server won't realize a client has disconnected until a timeout occurs, probably a keep-alive timeout. Once that happens, Mongoose will know the connection has closed and fire the proper event.
Of course crashing is not something a server should do, if you've found a scenario where that happens, please properly fill the issue template and provide enough information for the developers to reproduce it.

**Comment by craigtao** [comment]
@scaprile  thanks scaprile.

You are right, my application scenario is: a thread A1 pushes state data to the web frontend through the websocket, and when the client is unconventionally disconnected, thread A1 uses the connection in the list to send data, and it crashes.

Or is it a flag **_is_closing_** or **_is_draining_** to determine whether the current connection is valid?

**Comment by cpq** [comment]
@craigtao don't pass connection pointers to other threads, ever.

Make your thread just signal mongoose thread that data is there, and send data from mongoose thread.

**Comment by craigtao** [comment]
@cpq thanks 
I'm sorry, there is a problem with my description.
I don't pass connection

**thread A1** is a **timer** mongoose provide

**Comment by scaprile** [comment]
Are you checking your connection pointer is still valid ? Looks like you are dereferencing a NULL pointer
Things will be easier for both you and us if you would
- follow the issue template and properly describe your scenario (Mongoose version, OS, compiler, etc)
- provide minimum example code showing your point

As I've seen the word "thread" in your comments:
From [the docs](https://mongoose.ws/documentation/#2-minute-integration-guide)
> NOTE: Since Mongoose's core is not protected against concurrent accesses, make sure that all mg_* API functions are called from the same thread or RTOS task.

If you absolutely need multi-threading, take the time to go through the user guide (linked above) and [tutorials](https://mongoose.ws/tutorials/), there is one that shows you how to do [multi-threading](https://mongoose.ws/tutorials/multi-threaded/).

**Comment by craigtao** [comment]
@scaprile  many thanks.

**Comment by craigtao** [comment]
![image](https://user-images.githubusercontent.com/14227013/196316541-23d0f311-9dbf-4e6d-9b7d-599c59f1e114.png)
![image](https://user-images.githubusercontent.com/14227013/196316907-b1eb70f4-1d7d-474b-a658-0f0bc407f0ad.png)

checking connection pointer is still valid, Is this okay? Screenshot above

but the issue remains,

It may be that my code to judge the connection is valid is incorrect?

GBY.

**Comment by scaprile** [comment]
> Things will be easier for both you and us if you would
> 
>     * follow the issue template and properly describe your scenario (Mongoose version, OS, compiler, etc)
> 
>     * provide minimum example code showing your point

# Environment

- mongoose version: _X.Y_
- Compiler/IDE and SDK: ZZZ version _X.Y_
- Target hardware/board: _?_
- Connectivity chip/module: _?_-

Attach full example compilable code (minimum possible) where your issue can be reproduced. That means: someone here can compile your code and see what you claim

**Comment by cpq** [comment]
@craigtao can you share your code? Please clean up it to the minimum that reproduces a problem.

**Comment by cpq** [comment]
No response, closing

**Comment by scaprile** [comment]
A connection pointer (`c`) may have only two values: the address returned by your system's memory allocation function, or NULL. If it has a nonsense value, then either your system is returning that or you are trashing memory with runaway pointers, writing out of bounds, not following threading rules, etc.
Examples and tutorials check for `c == NULL`
https://mongoose.ws/tutorials/error-handling/#connection-retries
