### ISSUE TITLE
How to resolve "Client Renegotiation DoS Attack" from sslyze scanning

### ISSUE THREAD

**Issue by guangjung** [cesanta/mongoose#1800]
- My goal is: To  resolve "Client Renegotiation DoS Attack" from sslyze scanning
- My actions were: 
step1.  enter into examples/http-restful-server and modify Makefile to support https by linking openssl library.
step2.  execute make
step3.  install ssylze and execute the following command
python -m sslyze "webserver-address:8443"

- My expectation was:  NO any VULNERABLE  in sslyze scanning result
- The result I saw: 
_Session Renegotiation:
       Client Renegotiation DoS Attack:   VULNERABLE - Server honors client-initiated renegotiations_

more details  refer to 
[sslyze scan mongoose7.8 https.txt](https://github.com/cesanta/mongoose/files/9807875/sslyze.scan.mongoose7.8.https.txt)

- My question is: How to resolve "Client Renegotiation DoS Attack" from sslyze scanning
For example, add compile flag or  modify code, etc.

# Environment

- mongoose version: 6.7/6.16/6.18, 7.8
- Compiler/IDE and SDK: gcc (Ubuntu 16/20)
- Target hardware/board: N/A
- Connectivity chip/module: N/A

**Comment by cpq** [comment]
@guangjung that issue is not relevant to our library
