### ISSUE TITLE
mg_straddr returns always [0:0:0:0:0:0:0:0] as ip for rem in struct mg_addr for ipv6 enabled builds

### ISSUE THREAD

**Issue by jcorporation** [cesanta/mongoose#1801]
- My goal is: print the the remote address of the connection for ipv4 and ipv6 connections
- My actions were: mg_straddr(&nc->rem, buf, INET6_ADDRSTRLEN);
- My expectation was: the address of the peer ipv4 or ipv6
- The result I saw: always [0:0:0:0:0:0:0:0] for ipv6 enabled builds, the real address for builds with disabled ipv6
- My question is: bug or invalid usage?

# Environment

- mongoose version: 7.8

Code snippet:
```
static void ev_handler(struct mg_connection *nc, int ev, void *ev_data, void *fn_data) {
  case MG_EV_ACCEPT:
    char buf[INET6_ADDRSTRLEN];
    mg_straddr(&nc->rem, buf, INET6_ADDRSTRLEN);
```
BTW:
It seems that the usage example in the documentation is outdated, it references the old `peer` member in the `struct mg_addr`

**Comment by cpq** [comment]
I've modified examples/http-server with the following snippet:

```c
  if (ev == MG_EV_ACCEPT) {
    char buf[INET6_ADDRSTRLEN] = "";
    mg_straddr(&c->rem, buf, INET6_ADDRSTRLEN);
    MG_INFO(("--> %s", buf));
```

Starting server with a listening address of [::1]:8000 , and making a request with curl:

```sh
$ curl [::1]:8000
<!DOCTYPE html><ht ......
```

Server logs:

```sh
$ make -C examples/http-server/ ARGS="-l [::1]:8000"
./example -l [::1]:8000
820d83b0 2 main.c:100:main              Mongoose version : v7.8
820d83b0 2 main.c:101:main              Listening on     : [::1]:8000
820d83b0 2 main.c:102:main              Web root         : [/Users/cpq/src/mongoose/examples/http-server]
820d921b 2 main.c:25:cb                 --> [0:0:0:0:0:0:0:1]:54142
820d921b 2 main.c:38:cb                 GET / 200 1948
```

The IPv6 address is printed as expected.
Environment: MacOS 12.3

**Comment by jcorporation** [comment]
I use a listening address of 0.0.0.0 and access mongoose with a ipv4 address.
I get e.g. [0:0:0:0:0:0:0:0]:54178 in the log and not the ipv4 address.

**Comment by cpq** [comment]
What does the `netstat -an | grep 8000` output show?

**Comment by jcorporation** [comment]
```
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      15626/debug/mympd   
tcp        0      0 192.168.88.162:443      192.168.90.188:40584    ESTABLISHED 15626/debug/mympd 
```

**Comment by cpq** [comment]
Thank you @jcorporation 
I was expecting to see a tcp4/tcp6 marker. I don't see a listener on port 8000

**Comment by jcorporation** [comment]
Mongoose configuration is:
- Host: 0.0.0.0
- Port: 443

Log shows "[0:0:0:0:0:0:0:0]:34570" as remote ip
Tested with `curl https://localhost:443`

**Comment by cpq** [comment]
@jcorporation what if you use the same settings I've shown earlier - specifically, set listening address to IPv6: `[:1]:8000`

**Comment by jcorporation** [comment]
Mongoose configuration is:

    Host: [::1]
    Port: 80

Netstat ouptut: `tcp6       0      0 ::1:80                  :::*                    LISTEN      33823/debug/mympd`

Log shows "[0:0:0:0:0:0:0:1]:34570" as remote ip
Tested with `curl http://localhost:80`

With configured ipv6 and ipv6 connection it works. The issue occurs only with ipv4 connections if the build is with enabled ipv6, but ipv4 configured as listening address.

**Comment by cpq** [comment]
So apparently in your case, IPv4 is used but mongoose thinks it is IPv6 and prints it, but it is zero (expected).

**Comment by jcorporation** [comment]
> So apparently in your case, IPv4 is used but mongoose thinks it is IPv6 and prints it, but it is zero (expected).
Exactly
