### ISSUE TITLE
Fix and enable s390 unit test

### ISSUE THREAD

**Issue by cpq** [cesanta/mongoose#1848]
s390 is big endian arch, and `make s390` fails at the moment
It is disabled at GA: https://github.com/cesanta/mongoose/blob/a8bef964635804272ef6ed5eb8a354d73aaa5307/.github/workflows/test.yml#L26

Please fix the test and enable it on GA

**Comment by jfsimon1981** [comment]
Ok see PR 1887.

We need to use qemu, binfmt, docker, and init docker to use the correct runtime architectures.
