### ISSUE TITLE
Mongoose 7.7 is not compatible with Qos2 of Mosquitto v2.0.15 (MQTT Broker).

### ISSUE THREAD

**Issue by sunearthday** [cesanta/mongoose#1880]
Our team was developing a product that used this project. But now found an important issue that we can't fix:
Mongoose 7.7 is not compatible with Qos2 of Mosquitto v2.0.15 (MQTT Broker). If Mongoose subscribes to Qos2, it will disconnect every time it receives a Qos2 message. However, clients on other platforms (e.g., Android, iOS, Eclipse Paho) do not have this problem. Please check. Thank you.

**Comment by cpq** [comment]
Please use the latest code.
If the issue is still present there, file an issue. Don't forget to include all necessary information, like build logs, environment, etc. As it is now, your report is almost useless.
