### ISSUE TITLE
about mg_mqtt_next_sub

### ISSUE THREAD

**Issue by nopnop2002** [cesanta/mongoose#1892]
As of mongoose version 7.8, mongoose.c no longer has ```mg_mqtt_next_sub``` and ```mg_mqtt_next_unsub```.

I hope it will be revived.

```
$ grep -rn mg_mqtt_next_sub *
examples/mqtt-server/main.c:44:size_t mg_mqtt_next_sub(struct mg_mqtt_message *msg, struct mg_str *topic,
examples/mqtt-server/main.c:80:        while ((pos = mg_mqtt_next_sub(mm, &topic, &qos, pos)) > 0) {

$ grep -rn mg_mqtt_next_unsub *
examples/mqtt-server/main.c:50:size_t mg_mqtt_next_unsub(struct mg_mqtt_message *msg, struct mg_str *topic,
```

**Comment by scaprile** [comment]
The [example](https://github.com/cesanta/mongoose/blob/master/examples/mqtt-server/main.c) (where you probably took your greps from) shows you how to implement those functions yourself
