### ISSUE TITLE
How I can get the file upload completed event using file-upload-multiple-posts example

### ISSUE THREAD

**Issue by Vieufoux** [cesanta/mongoose#1893]
- My goal is: Implement upload feature and I want the mongoose server can get the completed event of file upload.

- My actions were: Run the [file-upload-multiple-posts](https://github.com/cesanta/mongoose/tree/master/examples/file-upload-multiple-posts) example

- My expectation was: mongoose server can get the file upload completed event
- The result I saw: mongoose server cannot get the file upload completed event

- My question is: How I can get the file upload completed event???

# Environment

- mongoose version: 7.8
- Compiler/IDE and SDK: Makefile
- Target hardware/board: Ubuntu 18.04.3 LTS
- hardware arch: x86_64

**Comment by scaprile** [comment]
https://mongoose.ws/tutorials/file-uploads/
There is no such event, this is an example of how to do something, prior examples in the tutorial show you ways to send filename and file size. Your connection will close when you stop sending, check file length then.
