### ISSUE TITLE
How to enable TCP keepalive option as https server?

### ISSUE THREAD

**Issue by guangjung** [cesanta/mongoose#1894]
- My goal is:  To enable TCP keepalive on Ubuntu 16+ (as build environment)
- My actions were:  
Simulation scenario: 
step1. The client and server normally establish a link, but client do not actively close the link.
step2.  repeat step1 several times
- My expectation was: 
Even if https client have no incorrect close tcp connection，mongoose server can close the session connections after TCP keepalive timeout.  
- The result I saw: 
Many tcp connections(ESTABLISHED state )    are not freed in mongoose server.  
$netstat -plant | grep 443
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      2097/mongoose   
tcp        0      0 172.16.166.221:443      172.16.161.103:39320    ESTABLISHED 2097/mongoose  
tcp        0      0 172.16.166.221:443      172.16.161.103:39420    ESTABLISHED 2097/mongoose
...... 
tcp        0      0 172.16.166.221:443      172.16.161.103:39411    ESTABLISHED 2097/mongoose 
tcp        0      0 172.16.166.221:443      172.16.161.103:39451     ESTABLISHED 2097/mongoose 
- My question is: 
In some abnormal scenarios， mongoose server do not automatically free  the invalid tcp connections after the https client did not actively close the tcp session.   Also I try to find some compile options  to control TCP keepalive in mongoose source code， but NOT found  for my build environment.
# Environment
Ubuntu 16+
- mongoose version:  6.18 or 6.7
- Compiler/IDE and SDK: gcc
- Target hardware/board:  x86_64
- Connectivity chip/module:  N/A
- Target RTOS/OS (if applicable):  ubuntu 16+

**Comment by scaprile** [comment]
A TCP connection will be closed after several keepalives fail. That is the OS task.
[setsockopt()](https://linux.die.net/man/3/setsockopt) is your friend. Use latest version or port from it.
https://github.com/cesanta/mongoose/blob/ce5e28554f2f6bd16c6fbf616357786dbfdefd66/mongoose.c#L4297
