### ISSUE TITLE
Websocket server send data

### ISSUE THREAD

**Issue by ventayol** [cesanta/mongoose#190]
This is not exactly a bug, but watching the documentation and the examples I cannot find how the server can send data to client using websockets.

All I can see is that the websockets callbacks are called when a websocket connection is started. But how is it possible to send data from the server to the client?

I need to send an information every second to the client.

**Comment by venkatesh-12345** [comment]
> Thanks for your fast feedback. I've tried to create a seperate thread that sends a ping to all registered websocket connection (maintained in a list). This works perfectly for me. Thanks!

can u send the source code
