### ISSUE TITLE
cannot free string returned by mg_strdup()

### ISSUE THREAD

**Issue by nirodho** [cesanta/mongoose#1902]
- My goal is:  free string returned by mg_strdup()
- My actions were:   struct mg_str str1 = mg_str("hello");
                                    struct mg_str str2 = mg_strdup(str1);
                                    free(str2.ptr);
- My expectation was: compile without errors
- The result I saw: 
- warning: passing argument 1 of ‘free’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
- ...
- /usr/include/stdlib.h:555:25: note: expected ‘void *’ but argument is of type ‘const char *’ 
-    555 | extern void free (void *__ptr) __THROW;
- My question is: can this be fixed?
# Environment

- mongoose version: 7.8
- Compiler/IDE and SDK: gcc version 11.3.0
- Target hardware/board: amd pc
- Connectivity chip/module: _?_
- Target RTOS/OS (if applicable): linux

**Comment by scaprile** [comment]
`free((void *) str2.ptr)`... `free((char *) str2.ptr)`... just get rid of the `const` as your compiler is instructing you to do.

**Comment by nirodho** [comment]
Thanks. I thought there might be some reason not to cast away the const
modifier.

I just started to use Mongoose to interact with the ESP32 board, by the
way. I'm loving it :)

Thanks again.

Jack
