### ISSUE TITLE
add Accept-Encoding:gzip support

### ISSUE THREAD

**Issue by kashfi59** [cesanta/mongoose#1923]
Hi
I add the 'Accept-Encoding:gzip support" and test it. if possible, please add these lines to monoose.c in function mg_http_serve_file()

void mg_http_serve_file(struct mg_connection *c, struct mg_http_message *hm,
                        const char *path,
                        const struct mg_http_serve_opts *opts) {
  char etag[64], tmp[MG_PATH_MAX];
  struct mg_fs *fs = opts->fs == NULL ? &mg_fs_posix : opts->fs;
  struct mg_fd *fd = NULL;
  size_t size = 0;
  time_t mtime = 0;
  struct mg_str *inm = NULL;
  struct mg_str mime = guess_content_type(mg_str(path), opts->mime_types);
  bool gzip = false;
  
  // try to load PATH.gz if supported by browse
  if (path != NULL) {
          mg_snprintf(tmp, sizeof(tmp), "%s.gz", path);
          
          struct mg_str *encode_header = mg_http_get_header(hm, "Accept-Encoding");
          if (encode_header)
                  if (strstr(encode_header->ptr, "gzip") != NULL)
                          fd = mg_fs_open(fs, tmp, MG_FS_READ);
          
          if (fd != NULL) {
                  gzip = true;
                  path = tmp;
          } else {
                  fd = mg_fs_open(fs, path, MG_FS_READ);
          }
  }
  
  if (fd == NULL) {
    MG_DEBUG(("NULL [%s]", path));
    if (opts->page404 != NULL) {
      // No precompressed file, serve 404
      fd = mg_fs_open(fs, opts->page404, MG_FS_READ);
      mime = guess_content_type(mg_str(path), opts->mime_types);
      path = opts->page404;
    }
  }
  
  if (fd == NULL || fs->st(path, &size, &mtime) == 0) {
    mg_http_reply(c, 404, opts->extra_headers, "Not found\n");
    mg_fs_close(fd);
    // NOTE: mg_http_etag() call should go first!
  } else if (mg_http_etag(etag, sizeof(etag), size, mtime) != NULL && ....
.....

**Comment by scaprile** [comment]
Mongoose already handles that
https://github.com/cesanta/mongoose/blob/6921227ec8a610abefb8698e66441e037438e442/mongoose.c#L1813-L1827
