### ISSUE TITLE
completely support of gzip compression

### ISSUE THREAD

**Issue by kashfi59** [cesanta/mongoose#1927]
Hi again
mongoose already handles the gzip compression in mg_http_serve_file(). but that function is not check the request header "Accept-Encoding:gzip", Also FILE.gz does not have priority over original File. The attached patch fix this issue.
Thanks
[mongoose-completely-support-file-gz.patch.gz](https://github.com/cesanta/mongoose/files/10251019/mongoose-completely-support-file-gz.patch.gz)

**Comment by cpq** [comment]
@kashfi59 our gzip support is aimed for the embedded usage with very constrained disk/flash space, to save not only of the transfer size, but on the disk/flash space too.
That means, both .gz and non-.gz files are not anticipated to be present at the same time. Either .gz, or non-.gz should.
If you'd like to use a .gz feature, please pre-process your web root before serving by deleting non-.gz files.
