### ISSUE TITLE
JSON Unescaspe

### ISSUE THREAD

**Issue by SkateScout** [cesanta/mongoose#1951]
Hi,

the escape sequence \/ which ist decoded as / is not included. (This is come from solar inverter api.)

Possible fix:

static const char *escapeseq(int esc) {
  return esc ? "\b\f\n\r\t\\\"/" : "bfnrt\\\"/";
}

**Comment by cpq** [comment]
@SkateScout Can you show a failing scenario for any of the JSON functions, please?

**Comment by cpq** [comment]
Unclear report, no response. Closing this.
