### ISSUE TITLE
[MIP stack] Bad TCP ACK handling on HTTP file upload

### ISSUE THREAD

**Issue by psykokwak-com** [cesanta/mongoose#1965]
- My goal is: make http file upload ("multipart/form-data") working (using MIP stack).
- My actions were: create a minimal test case (see below) to test the POST file upload with "multipart/form-data" format and get consistent chunks that represent the uploaded file.
- My expectation was: Get chunks up to the end of the uploaded file.
- The result I saw: The connection is reset by the device during the upload process.
- My question is: Why it does not work ?

# Environment

- mongoose version: latest "master" at the time I write this ticket.
- Compiler/IDE and SDK: Visual micro (or Arduino)
- Target hardware/board: Teensy 4.1 board with its MIP driver
- Connectivity chip/module: Ethernet
- Target RTOS/OS (if applicable): Bare metal (mangoose with MIP driver)

# Code

Following this minimal test case (sorry, I cannot do smaller) : 
```
#include "driver_teensy41.h"
#include "mongoose.h"

struct mg_mgr mgr;  // Mongoose event manager
struct mip_if mif;  // MIP network interface

static void handler(struct mg_connection *c, int ev, void *ev_data,
                    void *fn_data) {
  struct mg_http_message *hm = (struct mg_http_message *) ev_data;

  switch (ev) {
    case MG_EV_HTTP_MSG:
      // HANDLE /system/upgrade
      if (mg_http_match_uri(hm, "/")) {
        if (!mg_strcmp(hm->method, mg_str("GET"))) {
          const char *txt =
              "<form method=\"POST\" enctype=\"multipart/form-data\">"
              "<input type=\"file\" name=\"file\" />"
              "<input type=\"submit\" value=\"Upload\" />"
              "</form>";
          mg_http_reply(c, 200, "Content-Type: text/html\r\n", txt);
        }
      }
      break;

    case MG_EV_HTTP_CHUNK:
      // HANDLE /system/upgrade
      if (mg_http_match_uri(hm, "/")) {
        if (!mg_strcmp(hm->method, mg_str("POST"))) {
          MG_INFO(("Got chunk len %lu", (unsigned long) hm->chunk.len));

          totsize += hm->chunk.len;

          mg_http_delete_chunk(c, hm);
          if (hm->chunk.len == 0) {
            MG_INFO(
                ("Last chunk received. totsize=%d, sending response", totsize));
            mg_http_reply(c, 200, "", "Complete.\n");
            totsize = 0;
          }
        }
      }
      break;
  }
}

void setup() {
  Serial.begin(115200);

  // Set logging function to a serial print
  mg_log_set_fn([](char ch, void *) { Serial.print(ch); }, NULL);
  mg_log_set(MG_LL_INFO);
  mg_mgr_init(&mgr);

  MG_INFO(("Starting TCP/IP stack..."));

  mif.driver = &mip_driver_teensy41;

  IPAddress ip(192, 168, 123, 10);
  IPAddress mask(255, 255, 255, 0);

  mif.enable_dhcp_client = true;
  mif.enable_dhcp_server = false;
  mif.ip = ip;
  mif.mask = mask;

  mip_init(&mgr, &mif);

  mg_http_listen(&mgr, "http://0.0.0.0", handler, NULL);
}

void loop() {
  mg_mgr_poll(&mgr, 1);
}
```

During the upload process, On the console, I have some : 

> Opening port
> Port open
> 2f072 2 teensy41.ino:215:handler        Got chunk len 536
> 2f072 2 teensy41.ino:215:handler        Got chunk len 536
> 2f072 2 teensy41.ino:215:handler        Got chunk len 536
> 2f072 2 teensy41.ino:215:handler        Got chunk len 536
> 2f072 2 teensy41.ino:215:handler        Got chunk len 536
> 2f072 2 teensy41.ino:215:handler        Got chunk len 536
> 2f072 2 teensy41.ino:215:handler        Got chunk len 536
> 2f073 2 teensy41.ino:215:handler        Got chunk len 536
> 2f082 2 teensy41.ino:215:handler        Got chunk len 536
> 2f119 2 teensy41.ino:215:handler        Got chunk len 536
> 2f119 2 teensy41.ino:215:handler        Got chunk len 536
> 2f119 2 teensy41.ino:215:handler        Got chunk len 536
> 2f11a 2 teensy41.ino:215:handler        Got chunk len 536
> 2f11a 2 teensy41.ino:215:handler        Got chunk len 536
> 2f11a 2 teensy41.ino:215:handler        Got chunk len 536
> 2f11a 2 teensy41.ino:215:handler        Got chunk len 536
> 2f11a 2 teensy41.ino:215:handler        Got chunk len 536
> 2f11a 2 teensy41.ino:215:handler        Got chunk len 536
> 2f11a 2 teensy41.ino:215:handler        Got chunk len 536
> 2f11b 2 teensy41.ino:215:handler        Got chunk len 536
> 2f11b 2 teensy41.ino:215:handler        Got chunk len 536
> 2f11b 1 mongoose.c:403:mg_error         5 0x0 SEQ != ACK: 20799bcd 207999b5
> 2f11b 2 teensy41.ino:215:handler        Got chunk len 0
> 2f11b 2 teensy41.ino:222:handler        Last chunk received. totsize=11256, sending response
> 33b15 2 teensy41.ino:215:handler        Got chunk len 536
> 33b15 2 teensy41.ino:215:handler        Got chunk len 536
> 33b15 2 teensy41.ino:215:handler        Got chunk len 536
> 33b16 2 teensy41.ino:215:handler        Got chunk len 536
> 33b16 2 teensy41.ino:215:handler        Got chunk len 536
> 33b16 2 teensy41.ino:215:handler        Got chunk len 536
> 33b16 2 teensy41.ino:215:handler        Got chunk len 536
> 33b16 2 teensy41.ino:215:handler        Got chunk len 536
> 33b24 2 teensy41.ino:215:handler        Got chunk len 536
> 33bbb 2 teensy41.ino:215:handler        Got chunk len 536
> 33bbb 2 teensy41.ino:215:handler        Got chunk len 536
> 33bbb 2 teensy41.ino:215:handler        Got chunk len 536
> 33bbb 2 teensy41.ino:215:handler        Got chunk len 536
> 33bbc 2 teensy41.ino:215:handler        Got chunk len 536
> 33bbc 2 teensy41.ino:215:handler        Got chunk len 536
> 33bbc 2 teensy41.ino:215:handler        Got chunk len 536
> 33bbc 2 teensy41.ino:215:handler        Got chunk len 536
> 33bbc 2 teensy41.ino:215:handler        Got chunk len 536
> 33bbc 2 teensy41.ino:215:handler        Got chunk len 536
> 33bbc 2 teensy41.ino:215:handler        Got chunk len 536
> 33bbd 2 teensy41.ino:215:handler        Got chunk len 536
> 33bbd 1 mongoose.c:403:mg_error         6 0x0 SEQ != ACK: b4de4032 b4de3e1a
> 33bbd 2 teensy41.ino:215:handler        Got chunk len 0
> 33bbd 2 teensy41.ino:222:handler        Last chunk received. totsize=11256, sending response
> 385b5 2 teensy41.ino:215:handler        Got chunk len 536
> 385b5 2 teensy41.ino:215:handler        Got chunk len 536
> 385b5 2 teensy41.ino:215:handler        Got chunk len 536
> 385b5 2 teensy41.ino:215:handler        Got chunk len 536
> 385b5 2 teensy41.ino:215:handler        Got chunk len 536
> 385b5 2 teensy41.ino:215:handler        Got chunk len 536
> 385b5 2 teensy41.ino:215:handler        Got chunk len 536
> 385b6 2 teensy41.ino:215:handler        Got chunk len 536
> 385c1 2 teensy41.ino:215:handler        Got chunk len 536
> 38658 2 teensy41.ino:215:handler        Got chunk len 536
> 38658 2 teensy41.ino:215:handler        Got chunk len 536
> 38658 2 teensy41.ino:215:handler        Got chunk len 536
> 38659 2 teensy41.ino:215:handler        Got chunk len 536
> 38659 2 teensy41.ino:215:handler        Got chunk len 536
> 38659 2 teensy41.ino:215:handler        Got chunk len 536
> 38659 2 teensy41.ino:215:handler        Got chunk len 536
> 38659 2 teensy41.ino:215:handler        Got chunk len 536
> 38659 2 teensy41.ino:215:handler        Got chunk len 536
> 38659 2 teensy41.ino:215:handler        Got chunk len 536
> 3865a 2 teensy41.ino:215:handler        Got chunk len 536
> 3865a 2 teensy41.ino:215:handler        Got chunk len 536
> 3865a 1 mongoose.c:403:mg_error         7 0x0 SEQ != ACK: 5c5df628 5c5df410
> 3865a 2 teensy41.ino:215:handler        Got chunk len 0
> 3865a 2 teensy41.ino:222:handler        Last chunk received. totsize=11256, sending response
> 

That resets the connection (and corrupts the file).

Wireshark shows me some inconsistant data in the TCP communication.
You can download the wireshark dump from here : https://we.tl/t-cdSL2krZTy

For information : 
- 192.168.123.10 is the Teensy4.1 device
- 192.168.123.100 is my Windows 11 computer with Chrome.

**Comment by scaprile** [comment]
- Please honor the issue template
- Please run one of the examples, your code is too long and we can't afford the time to dig through it
- Please describe your scenario, who is 229 ? who is 120 ? If I guess correctly the device is 120
- Please don't paste pictures, attach capture files, we need to see what is actually going on from the start. In frame 644 the device is sending FIN and the client keeps sending data. That is consistent with the message indicating the end of the expected chunks. What happened before that ? Where did you take the capture, at 229 ?
- Start a capture with a blank Wireshark buffer, otherwise it may report anomalies based on prior traffic
- Please attach your complete Mongoose log for the very same network capture, so we can actually see the same sequence numbers
- If you have a way to check your free memory, please do
- MIP does not handle selective acknowledgements nor retransmissions

**Comment by psykokwak-com** [comment]
I added a "while(42) ;" just before the "mg_error(c, "SEQ != ACK: %x %x", seq, s->ack);" to block the program and see on wireshark.
You can download this wireshark dump from here : https://we.tl/t-jXsAGPBUO8
I'm not sure to understand. The client starts sending TCP retransmission for a Seq number that already have been ACKed.

**Comment by psykokwak-com** [comment]
Ok. It seems this is a performance issue of the Teensy41 driver https://github.com/cesanta/mongoose/pull/1954
it misses some rx frames.

I increased the driver RX buffer (something like 32/64) to fixes the issue.
But the overall rx throughput is low (average 300kbps).
On wireshark dump, I see that the device takes up to 200ms to send back an ACK to the client.
Reducing the MIP_TCP_ACK_MS to something like 10(ms) increase the rx throughput but it remains quite low (2Mbps).

**Comment by scaprile** [comment]
That timer is there to avoid sending unnecessary ACKs when they can be piggybacked on a response. Currently it is retriggered on every received frame, that could probably be improved. However, given that TCP has a window, the other end will keep sending at its will as long as it does not fill that window.

Frames 172-173: 19426 + 536 - 11922 = 8040. MIP advertises an 8K window and it has been filled by the sender, who apparently did not receive that ACK, that I see on frame 160.
MIP does not do selective ACKs, as said above, 

You are losing frames on the send side of your device. That is really weird, check your driver, it doesn't seem to be a performance issue given that you are almost not sending anything.
