### ISSUE TITLE
compile error in redhat7

### ISSUE THREAD

**Issue by kuangtu** [cesanta/mongoose#1985]
- My goal is: using the libary for webserver and monitor some application's data
- My actions were: using the libary for webserver and monitor some application's data
- My expectation was: compile examples successfully in Redhat7
- The result I saw: 
make -C examples/http-server

make[1]: Entering directory `/home/mxs/program/mongoose-master/examples/http-server'
cc ../../mongoose.c main.c -I../.. -I../.. -W -Wall -DMG_ENABLE_LINES=1 -DMG_ENABLE_IPV6=1 -DMG_ENABLE_SSI=1 -DMG_HTTP_DIRLIST_TIME=1  -o example
src/sock.c: In function ‘mg_iotest’:
src/sock.c:515:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
src/sock.c:515:3: note: use option -std=c99 or -std=gnu99 to compile your code
src/sock.c:523:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
main.c: In function ‘cb’:
main.c:23:12: warning: missing braces around initializer [-Wmissing-braces]
     struct mg_http_message *hm = ev_data, tmp = {0};
            ^
main.c:23:12: warning: (near initialization for ‘tmp.method’) [-Wmissing-braces]
main.c:23:12: warning: missing initializer for field ‘uri’ of ‘struct mg_http_message’ [-Wmissing-field-initializers]
In file included from main.c:5:0:
../../mongoose.h:1125:25: note: ‘uri’ declared here
   struct mg_str method, uri, query, proto;             // Request/response line
                         ^
make[1]: *** [example] Error 1
make[1]: Leaving directory `/home/mxs/program/mongoose-master/examples/http-server'
make: *** [all] Error 2
- My question is:  Is my solution appropriate?

# Environment
- mongoose version: master branch
- Compiler/IDE and SDK: redhat7 gcc 4.8.5 glibc 2.7

My solution:
from [Build options] section in https://github.com/cesanta/mongoose/tree/master/docs 

I modify the Makefile in examples/http-server. Add the MG_ARCH define and c99 flags.
DEFS ?= -DMG_ENABLE_LINES=1 -DMG_ENABLE_IPV6=1 -DMG_ENABLE_SSI=1 -DMG_HTTP_DIRLIST_TIME=1 -DMG_ARCH=MG_ARCH_UNIX
CFLAGS ?= -I../.. -W -Wall $(DEFS) $(EXTRA) -std=c99

recompile, it shows:
src/sock.c: In function ‘mg_iotest’:
src/sock.c:521:37: warning: implicit declaration of function ‘alloca’ [-Wimplicit-function-declaration]
src/sock.c:521:29: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
src/util.c: In function ‘mg_millis’:
src/util.c:124:3: warning: implicit declaration of function ‘clock_gettime’ [-Wimplicit-function-declaration]
src/util.c:124:17: error: ‘CLOCK_REALTIME’ undeclared (first use in this function)
src/util.c:124:17: note: each undeclared identifier is reported only once for each function it appears in
main.c: In function ‘cb’:
main.c:23:12: warning: missing braces around initializer [-Wmissing-braces]
     struct mg_http_message *hm = ev_data, tmp = {0};
            ^
main.c:23:12: warning: (near initialization for ‘tmp.method’) [-Wmissing-braces]
main.c:23:12: warning: missing initializer for field ‘uri’ of ‘struct mg_http_message’ [-Wmissing-field-initializers]
In file included from main.c:5:0:
../../mongoose.h:1125:25: note: ‘uri’ declared here
   struct mg_str method, uri, query, proto;             // Request/response line
                         ^
main.c: In function ‘main’:
main.c:79:5: warning: implicit declaration of function ‘realpath’ [-Wimplicit-function-declaration]
     realpath(s_root_dir, path);

The Error is:
 ‘CLOCK_REALTIME’ undeclared, from the clock_gettime(2) man page:Feature Test Macro Requirements for glibc,_POSIX_C_SOURCE >= 199309L
I need set a minimum value for _POSIX_C_SOURCE.

So I add the line "#define _GNU_SOURCE" in the beginning of the mongoose.c. Then compile successfully.

**Comment by scaprile** [comment]
The GCC  version in RHEL7 is too old, you need a modern C99 compiler taking C99 as default. You can use _clang_ and if your version of clang is also old, remove some of the unsupported _-f_ flags (that is what I do).
All examples compile just selecting _clang_ : `make clean all CC=clang`
There is no need to define an ARCH, it is automatically detected
