### ISSUE TITLE
MG_EV_TLS_HS no longer enumerated

### ISSUE THREAD

**Issue by maxvu** [cesanta/mongoose#1993]
The [documentation on the website](https://mongoose.ws/documentation/#events) names `MG_EV_TLS_HS` as an event but this identifier doesn't appear in my copy of the 7.8 header.

I see that it might've been added [here](https://github.com/cesanta/mongoose/commit/48800504be8314430fa315e72e5c4f73ff38f426#diff-0f96b129b059ad329b7239e581bf8d635f61524d6a89ace2378703681eb7497a) but I couldn't find where it might've been removed.

**Comment by scaprile** [comment]
Documentation is for *latest*, either use latest or the docs for your release https://github.com/cesanta/mongoose/blob/7.8/docs/README.md
