### ISSUE TITLE
Multithreading example Long running time with high CPU usage

### ISSUE THREAD

**Issue by xiaowulovenana** [cesanta/mongoose#2012]
HI 
Sorry to bother you!
- My question is: I use the sample code in Multireading to run for a long time, which causes high CPU consumption
- The result I saw: The stack information I captured using gstack is as follows
`#0  0x0000ffff8f3fdf44 in epoll_pwait () from /lib/libc.so.6
#1  0x000000000053bd84 in mg_iotest (mgr=0xffff78000b40, ms=1000) at /home/gaojie/RSU/common/net/mongoose/mongoose.c:4500
#2  0x000000000053bf08 in mg_mgr_poll (mgr=0xffff78000b40, ms=1000) at /home/gaojie/RSU/common/net/mongoose/mongoose.c:4604
#3  0x0000000000513e24 in HttpServer::Start (this=0xffff78000b20) at /home/gaojie/RSU/common/net/Http/Http.cpp:200
#4  0x0000000000508d2c in HttpServiceMain () at /home/gaojie/RSU/rsuStateProcess/TransportLayer/httpServer.cpp:162
#5  0x00000000004aa790 in CommunicationMonitorThr () at /home/gaojie/RSU/rsustate-process.cpp:38
#6  0x00000000004aaeb0 in std::__invoke_impl<void, void (*)()> (__f=@0x1c6b06d8: 0x4aa784 <CommunicationMonitorThr()>) at /opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/include/c++/7.3.0/bits/invoke.h:60
#7  0x00000000004aac18 in std::__invoke<void (*)()> (__fn=@0x1c6b06d8: 0x4aa784 <CommunicationMonitorThr()>) at /opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/include/c++/7.3.0/bits/invoke.h:95
#8  0x00000000004ab938 in std::thread::_Invoker<std::tuple<void (*)()> >::_M_invoke<0ul> (this=0x1c6b06d8) at /opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/include/c++/7.3.0/thread:234
#9  0x00000000004ab90c in std::thread::_Invoker<std::tuple<void (*)()> >::operator() (this=0x1c6b06d8) at /opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/include/c++/7.3.0/thread:243
#10 0x00000000004ab8ec in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)()> > >::_M_run (this=0x1c6b06d0) at /opt/fsl-imx-xwayland/4.14-sumo/sysroots/aarch64-poky-linux/usr/include/c++/`

# Environment

- mongoose version: 7.8

**Comment by scaprile** [comment]
#2013
