### ISSUE TITLE
invalid

### ISSUE THREAD

**Issue by romanholidaypancakes** [cesanta/mongoose#2019]
invalid

**Comment by scaprile** [comment]
Who is the server ? Who is the client ? Did you sniff the network ? Why "the server can not receive it", do you have any logs ? What is the reason ? Who closes the connection ? What do you do with the data ? How do you handle it, what is your event handler code like ? Did you try the example code in the repo ? Did you read the tutorials ?
7.7 is very old, did you try latest or at least 7.9 ?

**Comment by cpq** [comment]
@inaryart https://mongoose.ws/documentation/#build-options please check MG_MAX_RECV_SIZE

**Comment by cpq** [comment]
@inaryart so you're pushing 100 messages, each 5Mb in size, into the send buffer.
That's stupid on its own, but how is that related to your original question?
Please be concise and specific, and don't waste yours and our time.
