### ISSUE TITLE
Compling as a Library to port other language

### ISSUE THREAD

**Issue by yesilcimenahmet** [cesanta/mongoose#2091]
- My goal is: compiling as DLL to port Mongoose to other Language such as Delphi
- My actions were: I was only able to compile sample projects.
- My expectation was: Building as DLL.
- The result I saw: n/a
- My question is: How can I compile this library as DLL

# Environment

- mongoose version: 7.9 and newer
- Compiler/IDE and SDK: GCC / or MSVC++
- Target hardware/board:  firstly Windows, and then Mobile(IOS,Android)
- Connectivity chip/module:  N/A
- Target RTOS/OS (if applicable): N/A

**Comment by scaprile** [comment]
Will you please be so kind to honor the issue template and actually fill it ?

**Comment by yesilcimenahmet** [comment]
> Will you please be so kind to honor the issue template and actually fill it ?

Fixed, Thanks.

**Comment by yesilcimenahmet** [comment]
Any info any help? I could not find documents about compilation enough.

**Comment by scaprile** [comment]
Mongoose is just a single C source file and a .h header file. What compilation information do you need to compile a single C source ? Do you actually have a problem ? What exactly is it ?
Do you just want to know how to create a DLL ? Did you google that ? This is one of a dozen of possible answers: https://interviewsansar.com/dll-dynamic-link-library-in-c/

**Comment by yesilcimenahmet** [comment]
Hi, I mean compiling Mongoose as Shared Library (DLL) and thus I can use it in other programming language thanks by Mongoose.h I am working on it to compile as DLL

**Comment by karashiiro** [comment]
For anyone looking at this in the future, it's easy to do this with CMake on Windows ([example CMakeLists.txt](https://github.com/karashiiro/MongooseSharp/blob/6d8daeba541cace44d316e20d4125f85c18bbf5c/CMakeLists.txt))
