### ISSUE TITLE
printf vs fmt

### ISSUE THREAD

**Issue by scaprile** [cesanta/mongoose#2101]
Some functions are in `fmt.c`
Some other functions are in `printf.c`
There is no `printf.h`, all headers are in `fmt.h`
`log.c` includes a non-existent `printf.h`; all other files include `fmt.h`
`make unamalgamated` succeeds

Should we move corresponding headers to `printf.h` and change all files ?
#2051

**Comment by cpq** [comment]
@scaprile yes please, create `printf.h` to make things consistent
