### ISSUE TITLE
mg_http_printf_chunk format does not follow printf semantic

### ISSUE THREAD

**Issue by shunkica** [cesanta/mongoose#2104]
- My goal is:
- output a double as string with fixed decimal points

- My actions were:

```
double num = 0.14;
mg_http_printf_chunk(c, "%1.*f", 1, num);
mg_http_printf_chunk(c, "%1.*f", 2, num);
mg_http_printf_chunk(c, "%1.*f", 3, num);
```

- My expectation was: 

> 0.1
> 0.14
> 0.140

- The result I saw: 

> 1e-01
> 0.14
> 0.14

- My question is:
Why does this not produce the same result as printf fmt?

And a side question, I am calling mg_http_printf_chunk 300.000 times in a loop but obviously this function is not meant to be used in this way because it is taking forever (30+seconds), even though the actual transferred data is only 3MB, and the server is on localhost.
Is there some other function I can use for this?
I did a quick profile and 60% of the time is spent in mg_iobuf_resize, 20% of time in zeromem and 18% of time in mg_pfn_iobuf.

# Environment

- mongoose version: 7.9
- Compiler/IDE and SDK: gcc version 11.3.1
- Target hardware/board: x86_64
- Connectivity chip/module: _?_
- Target RTOS/OS (if applicable): _?_

**Comment by scaprile** [comment]
Yes, that looks like a bug affecting all `*printf()` derivatives https://mongoose.ws/documentation/#mg_snprintf-mg_vsnprintf

Wrt your side question:
30 secs / 300000 = 100us per iteration, you are sending chunks of 10 bytes where 40% is overhead
Yes, Mongoose will resize its TCP buffer everytime you keep adding more and more data but it should also be sending. Please sniff your network and open a question telling us your use case.

**Comment by shunkica** [comment]
The problem is not related to calling mg_http_printf_chunk many times. It is a general problem with sending large responses. The same thing happened when I buffered the entire thing and sent it with mg_http_reply.

I have opened issue #2105

**Comment by cpq** [comment]
@shunkica thanks for reporting this. We need to fix floating point print, and add a respective test (to the large list of existing tests).

W.r.t. second question. Set `MG_IO_SIZE` to 5 megabytes and it will be fast.
