### ISSUE TITLE
Sending large responses is slow

### ISSUE THREAD

**Issue by shunkica** [cesanta/mongoose#2105]
- My goal is: 
Send >3 MB using mg_http_reply or mg_http_printf_chunk.

I am reading a binary file (proprietary db), converting it into json, and placing the resulting string in a large buffer.
This entire process takes <1s.

- My actions were: _I put 3.63 MB of data in a buffer, and then sent it to the client (on localhost, so network speed is not a factor here)_

```
  fprintf(stderr,"%u\n", (unsigned)time(NULL));
  mg_http_reply(c,200,"",buffer);
  fprintf(stderr,"%u\n", (unsigned)time(NULL));

```
Output:
```
1678094323
1678094336
```

- My expectation was: _speed_
- The result I saw: _slow :( (13 seconds)_
- My question is: _how to speed it up?_

# Environment

- mongoose version: _7.9_
- Compiler/IDE and SDK: ZZZ version _gcc version 12.2.1 20221121 (Red Hat 12.2.1-4) (GCC) _
- Target hardware/board: x86_64
- Connectivity chip/module: _?_
- Target RTOS/OS (if applicable): _?_

![image](https://user-images.githubusercontent.com/11718584/223072059-d459438e-7afa-4f47-af46-ff4b3f57a864.png)

**Comment by scaprile** [comment]
`mg_http_reply()` is parsing your content as a format string and printing the result to the TCP buffer https://mongoose.ws/documentation/#mg_http_reply
If you are going to handle such amounts of data and want speed, you'll have to use lower level functions:
```
    mg_printf(c, "HTTP/1.1 %d %s\r\n%sContent-Length: %d \r\n\r\n", 200, "OK",
              "Content-Type: application/json\r\n", 3000000);
    mg_send(c, buffer, 3000000);
    c->is_resp = 0;
```
https://mongoose.ws/tutorials/http-server/#set-content-length
https://mongoose.ws/documentation/#mg_send
```
$ curl localhost:8000 > pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2929k  100 2929k    0     0   177M      0 --:--:-- --:--:-- --:--:--  190M
```
