### ISSUE TITLE
TLS host verification with no CA

### ISSUE THREAD

**Issue by cpq** [cesanta/mongoose#2140]
Setting TLS host verification, but using no CA, fails. It should (probably) not.

```c
struct mg_tls_opts opts = { .srvname = mg_url_host("host") };
  mg_tls_init(connection, &opts);
```

**Comment by scaprile** [comment]
Works for me changing examples/http-client:
```
    if (mg_url_is_ssl(s_url)) {
      struct mg_tls_opts opts = {/*.ca = "ca.pem",*/ .srvname = host};
      MG_INFO(("TLS ON"));
      mg_tls_init(c, &opts);
    }
```
with OS mbedtls, openssl, and building mbedtls

I guess is something with your config, are you fighting embedded ?
