### ISSUE TITLE
OPTIONS request with openssl connection more times and client can not recieve any results

### ISSUE THREAD

**Issue by zhanghuaifeng** [cesanta/mongoose#2146]
- My goal is: _describe_
- My actions were: _describe_
- My expectation was: _describe_
- The result I saw: 
-
![image](https://user-images.githubusercontent.com/55480187/230534065-12698f5c-8d11-4f01-90c9-d603ceeaacc2.png)

- My question is: OPTIONS request with openssl connection more times and client can not recieve any results

# Environment

- mongoose version:7.9
- Compiler/IDE and SDK: ZZZ version _X.Y_
- Target hardware/board: _?_
- Connectivity chip/module: _?_
- Target RTOS/OS (if applicable): _?_

**Comment by cpq** [comment]
@zhanghuaifeng appreciate your submission, but you have ignored all questions that help to reproduce an issue.
I am closing this. If you want your issue to be analyzed and fix, make an effort to describe it well and make reproducible.
