### ISSUE TITLE
Connection not disconnected

### ISSUE THREAD

**Issue by zhousongsong** [cesanta/mongoose#2152]
- My goal is: _describe_
- My actions were: mqtt client
- My expectation was: disconnect，clear cached
- The result I saw: _provide logs or description_
- My question is: 
- When the mqtt broker is connected and the Ethernet is unplugged, the mqtt client is not disconnected. The data is published and cached. When inserted into the Ethernet, the cached data is sent to the server

# Environment

- mongoose version: 7.9
- Compiler/IDE and SDK: gcc
- Target hardware/board: _?_
- Connectivity chip/module: _?_
- Target RTOS/OS (if applicable): linux

**Comment by scaprile** [comment]
Mongoose sends to the OS socket
The OS socket is stream oriented, TCP, it will buffer until it detects a disconnection.
Disconnections are detected using timeouts, layer 4 has no idea of what is going on in layer 1
