### ISSUE TITLE
where's  the mongoose  benchmark  report

### ISSUE THREAD

**Issue by iworkathz2017** [cesanta/mongoose#2189]
- My goal is: _describe_
- My actions were: _describe_
- My expectation was: _describe_
- The result I saw: _provide logs or description_
- My question is: _your question_

# Environment

- mongoose version: _X.Y_
- Compiler/IDE and SDK: ZZZ version _X.Y_
- Target hardware/board: _?_
- Connectivity chip/module: _?_
- Target RTOS/OS (if applicable): _?_

**Comment by scaprile** [comment]
Please don't open an issue to ask a simple question, there is the Discussion section for that. And if you do, then fill the template, it is there for a reason.
