### ISSUE TITLE
Question: await mg_send when there is pending data in the socket

### ISSUE THREAD

**Issue by berkutta** [cesanta/mongoose#2198]
- My goal is: Stream MJPEG over network with constrained resources
- My actions were: Implementing the video-stream example https://github.com/cesanta/mongoose/tree/master/examples/video-stream
- The result I saw: Stackoverflow on congested network situations/high framerate
- My question is:

It is clear to me that the function `mg_send()` puts the data in a queue which gets processed by `mg_mgr_poll()`. I'm asking myself now, if there is a way to check if there is pending data so I can drop the data as the network is not able to keep up. Queing up data is a behavior which is not wanted in a (live-)video-stream scenario, as we don't want a frame from ages ago. It is better to drop frames in such a scenario to keep the latency low.

# Environment

- mongoose version: 7.9
- Compiler/IDE and SDK: ESP-IDF v4.4.4
- Target hardware/board: ESP32-S3
- Connectivity chip/module: ESP32-S3
- Target RTOS/OS (if applicable): FreeRTOS

**Comment by scaprile** [comment]
The example is an example, it is not intended to provide a production-ready video camera but to offer an idea on how to stream moving images. Its aim is to be as simple and clear as possible.

You are using the ESP-IDF, that is based on lwIP, you can use whatever lwIP method you find suitable to check for network situations you don't like.
TCP will still send to an `mg_iobuf` https://mongoose.ws/documentation/#io-buffers and you can empty it when you want https://mongoose.ws/documentation/#mg_iobuf_del . Make sure the connection is still open so the buffer pointer is valid.
https://mongoose.ws/documentation/#struct-mg_connection
