### ISSUE TITLE
port from 6.11 to 7.10 : support for sending WebSocket fragmented frames

### ISSUE THREAD

**Issue by llange** [cesanta/mongoose#2206]
- My goal is: _to port an old codebase from 6.11 to 7.10_
- My actions were: _try to guess what the new API would be_
- My expectation was: _to find a corresponding flag for old `mg_send_websocket_frame(.., .. | WEBSOCKET_DONT_FIN, .., ..)`_
- The result I saw: _`mg_ws_send()` doesn't seem to support this behaviour_
- My question is: _What would be the suggested replacement ,_

# Environment

- mongoose version: _6.11_, _7.10_
- Compiler/IDE and SDK: ESP-IDF version _3.3.4_, _5.0.1_, ...
- Target hardware/board: _ESP-32_
- Connectivity chip/module: _?_
- Target RTOS/OS (if applicable): _FreeRTOS_

# Details
Hello !

To set the record straight, I'm no expert in Mongoose, nor am I in WebSockets.

When porting the codebase of https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3 from Mongoose 6.11 to 7.10, I've found an instance of our code trying to send fragmented frames, and for that using the `WEBSOCKET_DONT_FIN` flag:
```
...
          op |= WEBSOCKET_DONT_FIN;
...
        mg_send_websocket_frame(m_nc, op, msg.data(), msg.size());
...
```
(In fact it's a kind of always-on connection, sending events to a web browser. So we send a first frame with configuration informations, and each time an event occurs, we send a small update fragment with the event info. So we don't know in advance the size of the whole frame. Eventually we close the frame when all events have been sent.)

It seems that (at least by reading [some](https://www.rfc-editor.org/rfc/rfc6455) [documents](https://www.rfc-editor.org/rfc/inline-errata/rfc6455.html)) that there is a special handling of fragmentation, which is done by manipulation of the bit0 of the header (always 1, except for fragmented frames where only the last frame should be 1).

In previous 6.11, this handling was done [with a special flag `WEBSOCKET_DONT_FIN`](https://github.com/cesanta/mongoose/blob/6.11/src/mg_http_websocket.c#L251-L252).
I could not find any corresponding behaviour for sending fragmented frames in master / 7.10, and it [seems that the FIN flag is always set](https://github.com/cesanta/mongoose/blob/45e4b3c423c7ee0f378b1b8682eccc533bed3f0d/src/ws.c#L98).
While, strangely, in reception, [this FIN flag is tested](https://github.com/cesanta/mongoose/blob/45e4b3c423c7ee0f378b1b8682eccc533bed3f0d/src/ws.c#L176), and it seems [that fragmented frames are handled](https://github.com/cesanta/mongoose/blob/45e4b3c423c7ee0f378b1b8682eccc533bed3f0d/src/ws.c#L208-L227). 

Could someone explain me the logic behind what looks like a loss of functionality ?

Is it still mandatory for fragmented WS frames, or is it done differently now ?

Would you consider a PR to re-introduce this behaviour ? If so, any suggestion about the incremental change to the API ? A low-level `WEBSOCKET_DONT_FIN` like the 6.x ?

Thanks for any insight, and additionally  if there are porting guides from 6.x to 7.x I'll be happy to read these.

**Comment by cpq** [comment]
@llange sending fragmented frames is something very rare.

Currently, you can do the same trick to send fragmented frames as our unit test does.
It sends a message byte-by-byte. Our unit test also injects control frames in between, though you don't need to do it. See https://github.com/cesanta/mongoose/blob/38d7799ffa0f8241790ab562ca1e2a6985d0467a/test/unit_test.c#L2457-L2464

The idea is to memoize the current send buffer length, send a frame, and then manipulate the opcode - it would be at the memoized offset. Something like this:

```c
size_t ofs = c->send.len;  // Next message will go to this offset
mg_ws_printf(c, WEBSOCKET_OP_TEXT, "%s", "hi");   // Send a message
c->send.buf[ofs] &= ~128;  // Clear FIN flag

size_t ofs = c->send.len;  // Next message will go to this offset
mg_ws_printf(c, WEBSOCKET_OP_CONTINUE, "%s", "there");   // Continuation
c->send.buf[ofs] &= ~128;  // Clear FIN flag

size_t ofs = c->send.len;  // Next message will go to this offset
mg_ws_printf(c, WEBSOCKET_OP_CONTINUE, "%s", "!");   // Last fragment, keep FIN flag
```

At this point I am not sure this is worth an API change, considering you're the only one so far asked for this.

**Comment by llange** [comment]
Thank you, Sergey.
