### ISSUE TITLE
websocket client basic authentication

### ISSUE THREAD

**Issue by embetrix** [cesanta/mongoose#2226]
I didn't find any information how the websocket client  basic authentication is working ?

for the http this works without any problem:

`curl -X POST http://192.168.178.101:8080  --digest -u "myuser:p!ass123" -w "%{http_code}"`

But for websocket for example using wscat :

`wscat -c ws://192.168.178.101:8080  --auth "myuser:p!ass123"`

doesn't work !

any hints are welcome

**Comment by scaprile** [comment]
There is no authentication in WS but in HTTP
It is _you_ who has to write the code to check for authentication and upgrade the connection to WS after authenticating the URL.
https://mongoose.ws/documentation/tutorials/device-dashboard/

https://github.com/cesanta/mongoose/blob/b379816178abdcd59135aa32f990a4b3bbbfb54b/examples/device-dashboard/net.c#L223-L225
https://github.com/cesanta/mongoose/blob/b379816178abdcd59135aa32f990a4b3bbbfb54b/examples/device-dashboard/net.c#L263-L265

https://mongoose.ws/documentation/tutorials/webui-login/
