### ISSUE TITLE
WS MQTT Broker

### ISSUE THREAD

**Issue by JonRobo** [cesanta/mongoose#2237]
- My goal is: 

Build a functioning mqtt broker on an ESP32-WROVER-IE using websocket connections on host ws://IP:9001 to connect to web browser clients on the local network as well as other ESP32 boards

- My actions were: 

I successfully implemented an MQTT broker using standard mqtt/tcp. 
I modified the broker to listen on ws://192.168.4.1:9001
Validated that my client can connect to a public webscoket mqtt broker and publish/subscribe
Tried to connect to the modified local broker, but get these errors on the ESP32 client side

E (1270865) mqtt_client: Error transport connect
I (1270865) MQTTWS_EXAMPLE: MQTT_EVENT_ERROR
E (1270875) MQTTWS_EXAMPLE: Last error reported from esp-tls: 0x8008
I (1270885) MQTTWS_EXAMPLE: Last errno string (Success)
I (1270885) MQTTWS_EXAMPLE: MQTT_EVENT_DISCONNECTED
I (1280895) MQTTWS_EXAMPLE: Other event id:7
E (1281075) transport_ws: Error read response for Upgrade header GET / HTTP/1.1
Connection: Upgrade
Host: 192.168.4.1:9001
User-Agent: ESP32 Websocket Client
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: zX57zyD8X4eKQ5VqcuIx0w==
Sec-WebSocket-Protocol: mqtt

On the ws mqtt broker side I receive an MG_EV_OPEN event, MG_EV_ACCEPT event and a MG_EV_READ event.
Upon the MG_EV_OPEN event I set c->is_hexdumping = 1; and receive the following from the client

0000   47 45 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d 0a   GET / HTTP/1.1..
0010   43 6f 6e 6e 65 63 74 69 6f 6e 3a 20 55 70 67 72   Connection: Upgr
0020   61 64 65 0d 0a 48 6f 73 74 3a 20 31 39 32 2e 31   ade..Host: 192.1
0030   36 38 2e 34 2e 31 3a 39 30 30 31 0d 0a 55 73 65   68.4.1:9001..Use
0040   72 2d 41 67 65 6e 74 3a 20 45 53 50 33 32 20 57   r-Agent: ESP32 W
0050   65 62 73 6f 63 6b 65 74 20 43 6c 69 65 6e 74 0d   ebsocket Client.
0060   0a 55 70 67 72 61 64 65 3a 20 77 65 62 73 6f 63   .Upgrade: websoc
0070   6b 65 74 0d 0a 53 65 63 2d 57 65 62 53 6f 63 6b   ket..Sec-WebSock
0080   65 74 2d 56 65 72 73 69 6f 6e 3a 20 31 33 0d 0a   et-Version: 13..
0090   53 65 63 2d 57 65 62 53 6f 63 6b 65 74 2d 4b 65   Sec-WebSocket-Ke
00a0   79 3a 20 6e 66 63 59 53 6d 58 30 63 47 77 2b 2f   y: nfcYSmX0cGw+/
00b0   32 31 66 4d 48 6e 53 57 77 3d 3d 0d 0a 53 65 63   21fMHnSWw==..Sec
00c0   2d 57 65 62 53 6f 63 6b 65 74 2d 50 72 6f 74 6f   -WebSocket-Proto
00d0   63 6f 6c 3a 20 6d 71 74 74 0d 0a 0d 0a            col: mqtt....

- My expectation was: 
Expected to see a MG_EV_HTTP_MSG to then upgrade the connection in the following way (like in the websocket server example)

struct mg_http_message *hm = (struct mg_http_message *) ev_data;
    if (mg_http_match_uri(hm, "/websocket")) {
      // Upgrade to websocket. From now on, a connection is a full-duplex
      // Websocket connection, which will receive MG_EV_WS_MSG events.
      mg_ws_upgrade(c, hm, NULL);

- My question is: 

How can I upgrade the connection to websocket? once I do, what else is needed in order to operate as a webscoket mqtt broker?
Do I need to wrap each message before sending in a websocket? If so how would I do that?

Thanks

# Environment

- mongoose version: _7.9_
- Compiler/IDE and SDK: ESP IDF 5.0
- Target hardware/board: ESP32-WROVER-IE
- Target RTOS/OS (if applicable): FreeRTOS/ESP IDF

**Comment by scaprile** [comment]
Please read the tutorials and docs and if you still can't solve your problem please post what you are doing, we are unable to guess beyond perhaps you are not calling `mg_http_listen()`.
https://mongoose.ws/documentation/tutorials/mqtt-server/
https://mongoose.ws/documentation/tutorials/websocket-server/
https://mongoose.ws/documentation/tutorials/mqtt-over-ws-client/
https://mongoose.ws/documentation/#user-guide

**Comment by JonRobo** [comment]
Thank you for your response.

I just tried adding mg_http_listen() in parallel to mg_mqtt_listen() and can now get the expected MG_EV_HTTP_MSG event where I upgrade the connection. I am now getting an event on MG_EV_WS_MSG and need to develop further.

My main struggle is knowing how these WS messages can be handled by the mqtt listener to resemble what was working similar to the mqtt server tutorial.

It seems like there needs to be some sort of passing from MG_EV_WS_MSG events to the mqtt listener?
and I have stumbled upon a mg_ws_wrap function that I assume is needed. I am unsure of how to use mg_ws_wrap in conjunction with mqtt server functions.

Any guidance would be very much appreciated.

**Comment by scaprile** [comment]
Either you are quite a fast reader or you did not read the docs yet. Please do it, I just handed you an MQTT over WS tutorial that you seem to have overlooked.

**Comment by scaprile** [comment]
Besides reading the tutorials and examples, you should also see the most recent code and fundamentally the specs of the protocols you are trying to implement. What you are doing is incorrect, if the message QoS is 2 you have to respond with PUBREC, not PUBACK
https://github.com/cesanta/mongoose/blob/a7f1982d03ab3633fbd44f6355c90caaef003999/src/mqtt.c#L454-L465

**Comment by JonRobo** [comment]
Thank you for this, in my application we are only using QOS of 1 and MQTT version 3.1.1.
However it's useful to have if the use-case changes and for others to come here and find

**Comment by JonRobo** [comment]
This is what the mqtt_cb function looks like in mongoose 7.9, where I found the snippet.
Seems like in the v7.10 MQTT_CMD_PUBREC has been added.

![image](https://github.com/cesanta/mongoose/assets/39582212/3ff823d5-8354-4fd3-adc9-b2db5bf2a93b)
