### ISSUE TITLE
Unable to set mbedtls debug

### ISSUE THREAD

**Issue by JonRobo** [cesanta/mongoose#2258]
I would like to enable mbedtls debugging to see mbedtls logs because I am getting a TLS handshake: -0x7780 error which seems to indicate MBEDTLS_ERR_SSL_FATAL_ALERT_MESSAGE

In the CMakeLists.txt file in the mongoose folder I added
target_compile_definitions(${COMPONENT_LIB} PRIVATE MG_MBEDTLS_DEBUG_LEVEL=3)

The rest of my compile options are as follows 
target_compile_definitions(${COMPONENT_LIB} PRIVATE MG_ENABLE_MBEDTLS=1)
target_compile_definitions(${COMPONENT_LIB} PRIVATE MG_ARCH=MG_ARCH_ESP32)
target_compile_definitions(${COMPONENT_LIB} PRIVATE MG_ENABLE_FILE=0)
target_compile_definitions(${COMPONENT_LIB} PRIVATE MBEDTLS_PEM_PARSE_C=1)
target_compile_definitions(${COMPONENT_LIB} PRIVATE MBEDTLS_RSA_C=1)
target_compile_definitions(${COMPONENT_LIB} PRIVATE MBEDTLS_BASE64=1)
target_compile_definitions(${COMPONENT_LIB} PRIVATE MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED=1)
target_compile_definitions(${COMPONENT_LIB} PRIVATE MBEDTLS_DEBUG_C=1)
target_compile_definitions(${COMPONENT_LIB} PRIVATE MBEDTLS_SSL_DEBUG_ALL=1)

but when I compile I get /mongoose.c:5247: undefined reference to `mbedtls_debug_set_threshold'. 
When I comment out this MG_MBEDTLS_DEBUG_LEVEL line then everything compiles. I even see that in mongoose.h there is
#include <mbedtls/debug.h>
#include <mbedtls/net_sockets.h>
#include <mbedtls/ssl.h>

I'm very confused why mbedtls_debug_set_threshold cannot be found, I see it defined in mbedtls/debug.h

I am using ESP32-WROVER-IE, esp idf 5.0.2, and mongoose v7.9. I added the mbedtls library from [here](https://github.com/mongoose-os/mbedtls/tree/master) into the mongoose/src folder

**Comment by scaprile** [comment]
That is an IDF issue
You may see the header file but it is the IDF who decides what files to compile.
Check the IDF and MbedTLS documentation
