### ISSUE TITLE
Provide Security Issue Reporting Functionality

### ISSUE THREAD

**Issue by todb** [cesanta/mongoose#2269]
How do I disclose security vulnerabilities to this project? The [README](https://github.com/cesanta/mongoose#security) states this project is familiar with vulnerability reporting, but doesn't actually provide a mechanism. There's no [security policy](https://github.com/cesanta/mongoose/security), there's nothing at https://mongoose.ws/.well-known/security.txt, and I don't see anything appropriate on the contact page.

Feel free to reply here, or better, populate mongoose/security or .well-known/security.txt, or worse, write to me directly at todb@hugesuccess.org and I can get the details over. Thanks!

**Comment by scaprile** [comment]
- https://mongoose.ws/ -> Contact -> https://mongoose.ws/contact/
  - Fill the form
  - Send email to support@cesanta.com
- https://cesanta.com/ -> Contact -> https://cesanta.com/contact.html

**Comment by todb** [comment]
Seems odd to direct vuln reports to a regular support queue, but you're the boss! Thanks!

**Comment by scaprile** [comment]
> Seems odd to direct vuln reports to a regular support queue, but you're the boss! Thanks!

I'm not the boss, but I know that email account is read by trusted personnel, including the boss...
