### ISSUE TITLE
about void *fn_data update user-defined pointer for the connection

### ISSUE THREAD

**Issue by kuangtu** [cesanta/mongoose#2273]
- My goal is:  store the received data for  newly accepted connection
- My actions were: malloc a buffer for newly accepted connection 

// SERVER event handler
static void sfn(struct mg_connection *c, int ev, void *ev_data, void *fn_data) {
  if (ev == MG_EV_OPEN && c->is_listening == 1) {
    MG_INFO(("SERVER is listening"));
  } else if (ev == MG_EV_ACCEPT) {
    MG_INFO(("SERVER accepted a connection"));
  //malloc a buffer storing the received data for newly accepted connection

- My question is: 
from the documentation"https://mongoose.ws/documentation/#event-handler-function", it shows:
"void *fn_data - A user-defined pointer for the connection, which is a placeholder for application-specific data. This fn_data pointer is set during the *_listen() or *_connect() call, and it is stored in the c->fn_data. Listening connections copy the value of c->fn_data to the newly accepted connection, so all accepted connections initially share the same fn_data pointer. It is fine to update/replace that pointer for any connection at any time by setting c->fn_data = new_value;"

I udpate the pointer when MG_EV_ACCEPT, is it ok? Thanks!

**Comment by scaprile** [comment]
> * It is fine to update/replace that pointer for any connection at any time by setting c->fn_data = new_value;
