### ISSUE TITLE
MQTT - Error DNS Timeout

### ISSUE THREAD

**Issue by BrunoSilvaUM** [cesanta/mongoose#2291]
Good afternoon,

Referring to the closed issue #2287

I can now ping my IP address properly.

But I get this error when trying to connect to a public broker (broker.hivemq.com:1883):

![image](https://github.com/cesanta/mongoose/assets/62550297/49ea98eb-cbf8-4692-aac9-19975ed991b9)

What could it be about?

br

**Comment by scaprile** [comment]
Please do not open several issues, particularly when the problem is not a Mongoose issue.
If you consider your past issue has to be reopened, do it. However, I don't think so.
