### ISSUE TITLE
GitHub code scanning alert: Multiplication result converted to larger type 

### ISSUE THREAD

**Issue by jcorporation** [cesanta/mongoose#2303]
I got a GitHub code scanning alert "Multiplication result converted to larger type". I do not know If this is a real issue, but anyway I report it.

Mongoose version: Master, commit 1148ac0ae4770c980bed3395cd9ea839a4c5cfa1

It is in the function static size_t decode_varint().

```
  for (offset = 0; offset < 4 && offset < len; offset++) {
    uint8_t encoded_byte = buf[offset];
    *value += (encoded_byte & 0x7F) * multiplier;
# Multiplication result may overflow 'unsigned int' before it is converted to 'unsigned long'.
# CodeQL
    multiplier *= 128;

    if (!(encoded_byte & 0x80)) return offset + 1;
```

**Comment by scaprile** [comment]
Clearly it is not an issue because that loop will never be executed more than 4 times and that fits even 16-bitters.
We don't see such a warning, will you please let us know your environment ?
We'll see what we can do to keep all compilers happy, thanks for reporting

**Comment by jcorporation** [comment]
This does not occur in a specific environment. It is from the CodeQL workflow integrated in GitHub.

![image](https://github.com/cesanta/mongoose/assets/765844/b564b1f2-4008-4288-90b1-2b621180a02d)

This is the GitHub actions file: https://github.com/jcorporation/myMPD/blob/master/.github/workflows/codeql-analysis.yml

**Comment by scaprile** [comment]
#2306
