### ISSUE TITLE
Websocket ping telegram

### ISSUE THREAD

**Issue by mbrockme** [cesanta/mongoose#2315]
In 6.18 there was the configuration MG_WEBSOCKET_PING_INTERVAL_SECONDS, which defines the interval for the websocket ping telegram. This telegram was sent automatically by the mongoose server after a client connected.

In version 7.x the websocket ping isn't sent automatically and I couldn't find any configuration.

Is there an alternative?

**Comment by scaprile** [comment]
You can send whatever you wish from your event handler function.
https://mongoose.ws/documentation/#websocket-1
https://mongoose.ws/documentation/#mg_ws_send
You can use a timer or you can use the poll event
https://mongoose.ws/documentation/tutorials/timers/
https://mongoose.ws/documentation/#events
https://mongoose.ws/documentation/tutorials/tcp/
