### ISSUE TITLE
Error during flash esp32 tutorial: error gathering device information while adding custom device "/dev/cu.usbserial-020F4592": no such file or directory

### ISSUE THREAD

**Issue by amichalu** [cesanta/mongoose#2321]
- My goal is: to run https://mongoose.ws/documentation/tutorials/esp32/device-dashboard/
- My actions were: 

git clone https://github.com/cesanta/mongoose
cd mongoose/examples/esp32/device-dashboard
make build 
make flash PORT=/dev/cu.usbserial-020F4592

- My expectation was: board to be flashed
- The result I saw: 

make flash PORT=/dev/cu.usbserial-020F4592
docker run --rm --device /dev/cu.usbserial-020F4592 -v /Users/user1/projects/mongoose:/Users/user1/projects/mongoose -w /Users/user1/projects/mongoose/examples/esp32/device-dashboard espressif/idf idf.py flash
docker: Error response from daemon: error gathering device information while adding custom device "/dev/cu.usbserial-020F4592": no such file or directory.
make: *** [build] Error 127

- My question is: how to flash device properly ?

# Environment

- mongoose version: master
- Compiler/IDE and SDK: based on https://hub.docker.com/r/espressif/idf
- Target hardware/board: ESP32 D1 mini
- Connectivity chip/module: ESP32 D1 mini USB
- Target RTOS/OS (if applicable): FreeRTOS (esp-idf)

**Comment by scaprile** [comment]
> * My question is: how to flash device properly

Knowing the proper name for your device in your OS and passing the proper name when calling _make_. Clearly Docker is not able to access what you give as a port name:

> docker: Error response from daemon: error gathering device information while adding custom device "/dev/cu.usbserial-020F4592": no such file or directory.

Or, installing the IDF and avoiding Docker, in case there is some limitation in your OS to use Docker. This, as is, runs on Linux. You don't tell us what your OS is. Perhaps you need another Docker image for your platform, or any other configuration to access USB serial ports in your system

Or, manually flashing with any other program you know works for your OS. See other options in the very same _Makefile_
