### ISSUE TITLE
Can you provide an example of the latest version of wss? Because the interface has changed。thanks。

### ISSUE THREAD

**Issue by wc4410** [cesanta/mongoose#2356]
struct mg_tls_opts tls_opts {0};
    tls_opts.server_cert = mg_str(certIn);
    tls_opts.server_key = mg_str(KeyIn);
    tls_opts.client_cert = mg_str(certIn);;
    tls_opts.client_key = mg_str(KeyIn);
    tls_opts.client_ca = mg_str(pemIn);
    tls_opts.server_ca = mg_str(pemIn);

    mg_tls_ctx_init(&m_mgr, &tls_opts);

    mg_http_listen(&m_mgr, "wss://localhost:8905", fn, this);  // Create HTTP listener

I have tried this method before，web return “WebSocket connection to 'wss://localhost:8905/websocket1' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID”。

**Comment by scaprile** [comment]
#2341
