### ISSUE TITLE
Missing feature in mongoose v7: #call

### ISSUE THREAD

**Issue by kcozens** [cesanta/mongoose#2361]
In version 6 of mongoose I could have "<--#call some string-->" and mongoose would make a call back to my code with MG_EV_SSI_CALL with "some string" that I could process and output some other text to replace that entire "<--#call ...-->" block of text. This feature does not yet exist in version 7 as of the 7.11 version of mongoose. If there is some new way to do this in v7 I haven't found it and I didn't see anything in the provided examples to indicate how this can be done in v7.  File this under enhancement request.

**Comment by scaprile** [comment]
Just dynamically generate the page or use RPC
https://mongoose.ws/documentation/#web-ui
