### ISSUE TITLE
Build errors rp2040

### ISSUE THREAD

**Issue by Peter939** [cesanta/mongoose#2365]
Hi ty
Hi, trying to debug example pico-w5500 to test the library.
But compile errors? What am I doing wrong?

Using the following version of gcc on windows.
gcc (x86_64-posix-seh-rev1, Built by MinGW-Builds project) 13.1.0

make[3]: Leaving directory 'F:/_My2023/mongoose/examples/rp2040/pico-w5500/build'
[ 3%] Built target bs2_default_padded_checksummed_asm
make[3]: Entering directory 'F:/_My2023/mongoose/examples/rp2040/pico-w5500/build'
Scanning dependencies of target firmware
make[3]: Leaving directory 'F:/_My2023/mongoose/examples/rp2040/pico-w5500/build'
make[3]: Entering directory 'F:/_My2023/mongoose/examples/rp2040/pico-w5500/build'
[ 4%] Building C object CMakeFiles/firmware.dir/main.c.obj
In file included from F:/_My2023/mongoose/examples/rp2040/pico-w5500/main.c:11:
F:/_My2023/mongoose/examples/rp2040/pico-w5500/mongoose.h:1:1: error: expected identifier or '(' before '.' token
     1 | ../../../mongoose.h
       | ^
F:/_My2023/mongoose/examples/rp2040/pico-w5500/main.c: In function 'timer_fn':
F:/_My2023/mongoose/examples/rp2040/pico-w5500/main.c:41:3: warning: implicit declaration of function 'MG_INFO' [-Wimplicit-function-declaration]
    41 | MG_INFO(("Ethernet: %s, IP: %M, rx:%u, tx:%u, dr:%u, er:%u",
       | ^~~~~~~
F:/_My2023/mongoose/examples/rp2040/pico-w5500/main.c:42:21: error: invalid use of undefined type 'struct mg_tcpip_if'
    42 | names[ifp->state], mg_print_ip4, &ifp->ip, ifp->nrecv, ifp->nsent,
       | ^~
F:/_My2023/mongoose/examples/rp2040/pico-w5500/main.c:42:31: error: 'mg_print_ip4' undeclared (first use in this function)
    42 | names[ifp->state], mg_print_ip4, &ifp->ip, ifp->nrecv, ifp->nsent,
       | ^~~~~~~~~~~~
F:/_My2023/mongoose/examples/rp2040/pico-w5500/main.c:42:31: note: each undeclared identifier is reported only once for each function it appears in
F:/_My2023/mongoose/examples/rp2040/pico-w5500/main.c:42:49: error: invalid use of undefined type 'struct mg_tcpip_if'

**Comment by scaprile** [comment]
Our examples build perfectly and the Makefile shows how to build.
You need to install the tools as explained in our documents and follow the examples as explained in our tutorials
https://mongoose.ws/documentation/tutorials/rp2040/pico-w5500/
