### ISSUE TITLE
How can i stop the output in console by mongoose

### ISSUE THREAD

**Issue by a406749043** [cesanta/mongoose#2387]
when i run a http client with mongoose on windows10 ,it always print some byte stream and decode result on my console
![image](https://github.com/cesanta/mongoose/assets/73818853/f5d536b9-e36a-45ea-87bd-55facf8d05ae)
i've alreay set the log level as the document said, but it seemed not worked
```
bool HttpClient::Start()
{
    mg_mgr_init(&_mgr);
    mg_log_set(MG_LL_NONE);
    return true;
}
```

**Comment by cpq** [comment]
@a406749043 
Maybe something calls `mg_hexdump()` against the received data?
Please share the code you're using, or point to the exact example.

**Comment by cpq** [comment]
No response, closing
