### ISSUE TITLE
How can i stop the output in console by mongoose

### ISSUE THREAD

**Issue by a406749043** [cesanta/mongoose#2391]
@a406749043 
Maybe something calls `mg_hexdump()` against the received data?
Please share the code you're using, or point to the exact example.

_Originally posted by @cpq in https://github.com/cesanta/mongoose/issues/2387#issuecomment-1725105054_

Sorry i was busy on working so i forgot about this issuse.
And thank you for your response, here's the source code i'm using when got http response

> 
> else if (eventType == MG_EV_HTTP_MSG)
>     {
>         struct mg_http_message* hm = (struct mg_http_message*)eventData;
>         int statusCode = mg_http_status(hm);
>         LOG_DEBUG("HttpClient::Process: post {} status {}, reply body {}", postId, statusCode, std::string(hm->body.ptr, hm->body.len));
>         auto cbItr = s_rspCallbackMaps.find(postId);
>         if (cbItr != s_rspCallbackMaps.end())
>         {
>             if (cbItr->second == nullptr)
>             {
>                 goto Exit0;
>             }
>             HttpResponse newResponse(connection);
>             newResponse.SetStatus(statusCode);
>             newResponse.Write(hm->body.ptr, hm->body.len);
>             bool bResult = cbItr->second(*request, newResponse);
>             if (!bResult)
>             {
>                 LOG_ERROR("HttpClient::Process http reply callback failed, postId {}, response body {}", postId, newResponse.Data());
>             }
>         }
           

Is there anythis would lead the output?

**Comment by cpq** [comment]
@a406749043 please scan for `mg_hexdump()` calls everywhere and catch the one that prints the output.
And please do NOT open issues like this, this is not a mongoose issue.
