### ISSUE TITLE
Redirecting HTTP to HTTPS on the same port

### ISSUE THREAD

**Issue by dev31337** [cesanta/mongoose#2401]
- My goal is: Redirect an HTTP connection to a port to HTTPS connection to the same port
- My actions were: Listening on the HTTPS URL
- My expectation was: Ability to detect a HTTP connection/request and send/reply a 303 redirect response to HTTPS (same port)
- The result I saw: Inability to detect a HTTP connection/request while listening on a HTTPS URL
- My question is: How can I redirect a HTTP connection to a port to HTTPS on the same port ?

# Environment

- mongoose version: master
- Compiler/IDE and SDK: Gcc
- Target hardware/board: PC
- Connectivity chip/module: None
- Target RTOS/OS (if applicable): Ubuntu 22.04 LTS

**Comment by cpq** [comment]
@dev31337 I don't think you can easily do that.

To do what you want, one must accept a connection and try to read the request. If it is successful, then do redirect. If not, then treat the data as TLS. And that last point is a difficult one. Currently there is no clean way to "push" the read data back to the TLS so it treats it as a handshake.

A traditional way using two different ports (one for plain HTTP, one for HTTPS) is easily doable though.
