### ISSUE TITLE
Cant use esp-idf component manager to add mongoose to my project

### ISSUE THREAD

**Issue by noName2005** [cesanta/mongoose#2428]
- **My goal is:** Use the mongoose library using ESP-IDFs component manager on VsCode.

- **My actions were:** 
Used the command palette in VsCode to create a new ESP-IDF project. I created the project using the template provided by the extension "template-app". Then ran idf.py add-dependency "cesanta/mongoose^7.8.2" to add mongoose component with ESP-IDF component manager. Then built the project.

- **My expectation was:** To build the project without errors

- **The result I saw:** 
The important snippet of the log is:
"
In file included from D:/Code/sketches/Hydroponics/TheUltimate/Esp/using-mongoose-only/managed_components/cesanta__mongoose/mongoose/mongoose.c:20:
D:/Code/sketches/Hydroponics/TheUltimate/Esp/using-mongoose-only/managed_components/cesanta__mongoose/mongoose/mongoose.h:133:10: fatal error: esp_timer.h: No such file or directory   
  133 | #include <esp_timer.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
"
It looks like the esp_timer component is not registered as a requirement / dependency. As stated in the Espressif docs, some components like esp_timer were in previous versions always added as public requirements. This is not true for ESP-IDF v5.0.

reference: (https://docs.espressif.com/projects/esp-idf/en/v5.0/esp32s2/migration-guides/release-5.x/build-system.html#specify-component-requirements-explicitly)

- **My question is:** 
How, and where do i add this dependency, and any other dependencies that might not be included? Are there other factors contributing to this issue? Is my environment set up correctly with the correct versions?

# ESP-IDF v 5.1.1 on VsCode
- mongoose version: 7.8.2
- Target hardware/board: ESP32-WROOM-32

[logs.txt](https://github.com/cesanta/mongoose/files/12918180/logs.txt)

**Comment by scaprile** [comment]
That is not a Mongoose issue, that is not how Mongoose is used,
As told in response to your question, follow the documentation.
