### ISSUE TITLE
how to support setsockopt() on socket in mongoose connection?

### ISSUE THREAD

**Issue by freebendy** [cesanta/mongoose#2430]
- My goal is: use mongoose as nest web server and network library for client/server connection
- My question is: how to support setsockopt() on socket in mongoose connection?

My system has multiple network interfaces , e.g. a ethernet interface, a ppp interface and a RNDIS interface. The application acts a client and server at the same time and it needs the capability:
- The client connection only sends out packet through specific interface based on the configuration.
- The server accepts connection from specific interface based on configuration

I would use SO_BINDTODEVICE in socket but mongoose does not support this flags.

**Comment by scaprile** [comment]
Your socket is at c->fd
https://github.com/cesanta/mongoose/blob/c33fd6a7fb2e52502d2f4e86b1b8b9be485e6791/src/net.h#L48
Please follow the guidelines in the [documentation](https://mongoose.ws/documentation)
https://mongoose.ws/documentation/#struct-mg_connection
