### ISSUE TITLE
Override malloc() and free() macros in mongoose_custm.h

### ISSUE THREAD

**Issue by gdumee** [cesanta/mongoose#2431]
Hello,

- My goal is: overriding memory allocation functions. I use ESP32 with external PSRAM, and default function pvPortMalloc() allocates memory in embedded RAM, with is already filled with other data.
- My actions were: I modified macro malloc() and function mg_callloc() in mongoose.h, to call heap_caps_malloc() function
- My expectation was: I would like to specify theses functions in mongoose_custom.h, to keep mongoose.h untouched
- The result I saw: macro malloc() and free() are set in mongoose.h without "#ifndef malloc" or "#ifndef free" blocs, so I can't define mine before. 
- My question is: exactly like macro alloca() is defined, could it be possible to change these following lines?
     * "#define free(a) vPortFree(a)"  with
              #ifndef free
              #define free(a) vPortFree(a)
              #endif
     * "#define malloc(a) pvPortMalloc(a)" with
              #ifndef malloc
              #define malloc(a) pvPortMalloc(a)
              #endif
     * in function mg_calloc()  "void *p = pvPortMalloc(cnt * size);"   with "void *p = malloc(cnt * size);". The result is the same, but let me use my predefiend malloc() macro wich calls heap_caps_malloc()

# Environment

- mongoose version: 7.12
- Compiler/IDE and SDK: ESP-IDF v5.1.0
- Target hardware/board: ESP32-WROVER-E
- Connectivity chip/module: ESP32
- Target RTOS/OS (if applicable): FreeRTOS

**Comment by scaprile** [comment]
Please follow the guidelines in the [documentation](https://mongoose.ws/documentation)

mongoose_custom.h is not the place to do that, if you want to toy with the architecture then modify the architectural files and reamalgamate the sources

https://github.com/cesanta/mongoose/blob/master/src/arch_esp32.h
