### ISSUE TITLE
undefined reference to 'signal' with esp32

### ISSUE THREAD

**Issue by noName2005** [cesanta/mongoose#2434]
- My goal is: 
Set up an mqtt broker on an esp32.

- My actions were: 
I created a new esp-idf project using the template provided by the esp-idf extension on VsCode. Then downloaded the mongoose library as a component of the project using git. Then i replaced the main.c file content with the example project "MQTT server" to test it out. Tried to build the project, but the builder for some reason doesn't recognise the "signal" functions.

- The result I saw: 
The log from the build is attached below. It fails, because of "undefined reference to 'signal'".
Im also attaching the main.c file in .txt format in case it helps. I had to change the main function name from "int main(void)" to "int app_main(void)"

- My question is: 
I've diligently followed the documentation and even reinstalled everything multiple times, yet I consistently encounter an issue with signal.h. I came across information in another forum suggesting that signal.h isn't supported on ESP32 anymore. If this is the case, what alternative should I use for the current signal handler? But Mongoose is supposedly compatible with ESP32, so I'm somewhat perplexed.

My background is primarily in the Arduino environment, placing my skill set somewhere between beginner and intermediate. The ESP-IDF and Mongoose ecosystems are new territories for me, and I've found the setup quite challenging. I've attempted setups with the Espressif IDE and Mongoose OS, but to no avail.

Additionally, as I'm new to GitHub, I'd be grateful for any pointers if I'm not posting in the right spot or if I'm unintentionally overlooking community norms.

Please let me know if you need additional information.

# Environment

- mongoose version: 7.8
- Compiler/IDE and SDK: VsCode with the "Espressif IDF" extension version 1.6.5 running ESP-IDF version 5.1.1
- Target hardware/board: ESP32-WROOM-32

[logs.txt](https://github.com/cesanta/mongoose/files/13167771/logs.txt)
[main.txt](https://github.com/cesanta/mongoose/files/13168017/main.txt)

**Comment by scaprile** [comment]
Please stop opening new issues for the same problem of yours.
Mongoose 7.8 is more than a year old, please use the latest release or current git head
You can't just replace some random main file with some other random main file not intended for the embedded environment where you will run.
You have two examples of ESP32 working projects here: 
https://github.com/cesanta/mongoose/tree/master/examples/esp32
and their tutorials, that you should have followed:
https://mongoose.ws/documentation/#esp32-devkitc
These examples are built and tested again and again with the latest ESP-IDF by our CI/CD system. They do build, they do work.
The innards of your plugin and your IDE are beyond us, Mongoose is not "an ecosystem", is a simple C source code that can be compiled in supported platforms without hassle.
