### ISSUE TITLE
Issues when porting from mongoose 6.17 to 7.9 during build

### ISSUE THREAD

**Issue by devdatt9129** [cesanta/mongoose#2436]
- My goal is: I am porting from mongoose 6.17 to mongoose 7.9, and I am facing these errors when I am building my application
- My actions were: 
- My expectation was: Successful build
- The result I saw: 
```
error: invalid use of incomplete type struct http_message
error: forward declaration of struct http_message
error: invalid use of incomplete type struct http_message
error: forward declaration of struct http_message
error: MG_SOCK_STRINGIFY_IP was not declared in this scope
error: MG_SOCK_STRINGIFY_REMOTE was not declared in this scope
error: mg_conn_addr_to_str was not declared in this scope
error: MG_SOCK_STRINGIFY_PORT was not declared in this scope
error: invalid use of incomplete type struct http_message
error: forward declaration of struct http_message
error: invalid use of incomplete type struct http_message
error: forward declaration of struct http_message
error: struct mg_connection has no member named â€˜flags
error: MG_F_SSL was not declared in this scope
error: invalid use of incomplete type struct http_message
error: forward declaration of struct http_message
error: invalid use of incomplete type struct http_message
error: forward declaration of struct http_message
error: invalid use of incomplete type struct http_message
error: forward declaration of struct http_message
error: invalid use of incomplete type struct http_message
error: forward declaration of struct http_message
error: invalid use of incomplete type struct http_message
error: forward declaration of struct http_message
error: mg_get_http_header was not declared in this scope
error: struct mg_str has no member named p
 error: mg_send_head was not declared in this scope
error: mg_send_head was not declared in this scope
error: mg_send_head was not declared in this scope
error: mg_send_head was not declared in this scope
error: mg_send_head was not declared in this scope
```
- My question is: As it is quite clear to understand that a lot of functions have been deprecated in the 7.9 version, what are the replacements for such functions like mg_conn_addr_to_str and certain definitions like MG_SOCK_STRINGIFY_IP

# Environment

- mongoose version: 7.9
- Compiler/IDE and SDK: 
- Target hardware/board: RHEL 6
- Connectivity chip/module: 
- Target RTOS/OS (if applicable):

**Comment by scaprile** [comment]
The architecture in v7 is quite different from that in v6 (hence the change in major), there is no easy way to port.

To see how to implement something, please follow the guidelines in the [documentation](https://mongoose.ws/documentation), [examples](https://github.com/cesanta/mongoose/tree/master/examples) and [tutorials](https://mongoose.ws/tutorials/) available.

For specific cases, please search for similar issues, 6.17 is ages old and your case may have been asked and answered several times. 7.9 is also pretty old and we do not support obsolete versions. Use 7.12 or git head.
