### ISSUE TITLE
No ARP response from RASPBIAN

### ISSUE THREAD

**Issue by Mike0675** [cesanta/mongoose#2458]
Hi, I think this Problem is not mongoose-related, but can be interesting somehow.

I have Problems connecting to mosquitto on Raspbian.

Now I see that Raspbian dont give allways ARP-response to my mongoose-device.

When I get the response MQTT works; if I don´t get response it won´t work.

Any Ideas?

Thanks Mike

**Comment by scaprile** [comment]
You know, the issue template is there for a reason: to save yours and our time.
I'm terribly bad at guessing which one of the several network configuration options your device may be using, not to mention I can't guess what happens in your network.
So please, fill the issue template, provide all the necessary information, and yes, that includes network _capture files_ and of course an explanation of your networking scenario and actors.
https://github.com/cesanta/mongoose/blob/master/.github/issue_template.md
