### ISSUE TITLE
mg_ws_send()--->malloc(): unsorted double linked list corrupted

### ISSUE THREAD

**Issue by yys-bury** [cesanta/mongoose#2461]
I want to use websocket to connect to the server.
Due to poor network quality, I had to use mg_ws_connect several times to try to connect.
Often produces problems: "malloc(): unsorted double linked list corrupted".

debeg found that the problem occurred in the following places:
mg_alloc_conn()-->(struct mg_connection *) calloc(1, sizeof(*c) + mgr->extraconnsize);
mg_random()-->if (fread(buf, 1, len, fp) == len) done = true;
mg_iobuf_resize()-->    void *p =  calloc(1, new_size);

And, at this point, the heap space should be sufficient.
Should I use "mg_ws_send()" more than once if I want to try to connect to websocket multiple times?
Please give me some guidance.
Thank you very much.

# Environment

- mongoose version: 7.12
- PC linux

**Comment by scaprile** [comment]
It is extremely difficult for me to guess what you are doing, all I can imagine is that you are doing something wrong.
You know, we have docs, we have examples, we build our code on a CI/CD pipeline and check for memory leaks with ASAN, I suggest you follow the guidelines in the [documentation](https://mongoose.ws/documentation),  [examples](https://github.com/cesanta/mongoose/tree/master/examples) and [tutorials](https://mongoose.ws/tutorials/) available. Then, if you find an actual problem that is not yours, feel free to reopen this issue and paste the minimum piece of code that can reproduce your problem

https://mongoose.ws/documentation/tutorials/http-client/
https://mongoose.ws/documentation/tutorials/error-handling/
