### ISSUE TITLE
 Can't build NXP IMXRT1020 + FreeRTOS + LWIP in MCUXPresso IDE 

### ISSUE THREAD

**Issue by GanesanGuru** [cesanta/mongoose#2463]
Hi team,
I'm referring [this](https://mongoose.ws/documentation/tutorials/nxp/nxp-mimxrt1020-freertos/), and following Option 2 - MCUXpresso IDE.. Done as mentioned. After importing project - when went for building, I'm getting this following error. Please explain the where did I went wrong..
![Screenshot from 2023-11-07 18-11-27](https://github.com/cesanta/mongoose/assets/26476060/bc96443a-467b-42e7-b281-fc9814f9b0a0)

**Comment by scaprile** [comment]
#2462 
Please DO NOT crosspost nor open several issues for the same problem of yours
