### ISSUE TITLE
HTTPS Problem on Windows

### ISSUE THREAD

**Issue by ffreality** [cesanta/mongoose#2480]
I AM NOT ASKING YOU ABOUT THREADS. JUST DON'T WRITE SOMETHING MEANINGLESS LIKE "YOU WROTE THREADS !"
**FRunnableThread means, seperating GameThread with all Mongoose related functions.
So, mongoose will work on their own thread. It's not multi-threading for mongoose's aspect. So, being non-thread-safe won't be a problem for us.**

We need it because
```
while(true)
{
 mg_mgr_poll(&this->Mongoose_Manager, 1000);
}
```
shouldn't block GameThread. 
**If we don't do that, we can't use our virtual reality scenes.**

//
- My goal is:
I am doing some experiments about Unreal Engine 5 Async HTTP Server creation with mongoose and FRunnableThreads.
Plugin exposes HTTP message to a blueprint delegate. So, we can parse it and send reply with blueprints without touching C/C++ code. Currently HTTP Static Content Serving and Rest API features are working perfectly.

- My Problem:
When I use `if (ev == MG_EV_ACCEPT)` to support HTTPS, I can't receive any API request with either HTTP or HTTPS.
Also, I can't see any root directory contents.

- My actions were: 
1- I copied mongoose.c and .h to my Unreal Engine 5 plugin's source folder and do necessary binding operations.
2- My code : https://gist.github.com/ffreality/d0428ba3e1e021d82cf4245e36c14586#file-ue_mongoose-cpp-L131

I tried to build mongoose with these Windows instructions.
https://mongoose.ws/documentation/tutorials/tools/
and I used this `make MG_TLS=MG_TLS_OPENSSL`
It started `mongoose.exe` and I could `localhost:8000` but I didn't see any .lib file to integrate Unreal Engine and mongoose.c and .h file were just links.

So, what should I do to support HTTPS on Windows ?

# Environment
- mongoose version: Master from 17th November 2023
- Compiler/IDE and SDK: Visual Studio 2022
- Target hardware/board: Windows x64

**Comment by scaprile** [comment]
Please follow the guidelines in the [documentation](https://mongoose.ws/documentation),  [examples](https://github.com/cesanta/mongoose/tree/master/examples) and [tutorials](https://mongoose.ws/tutorials/) available.

https://mongoose.ws/documentation/tutorials/http-server/#tls-support
> The [TLS tutorial](https://mongoose.ws/documentation/tutorials/tls/) explains how to add TLS support to servers (and clients, by the way). Some of the examples cited here already have TLS support included, check the "[How to build](https://mongoose.ws/documentation/tutorials/tls/#how-to-build)" section in the TLS tutorial for specific information on building options for your OS.

https://mongoose.ws/documentation/tutorials/tls/#windows
> Only what the example provides in its Makefile is supported

https://github.com/cesanta/mongoose/tree/master/examples/http-restful-server

mbedtls is supported:
https://github.com/cesanta/mongoose/blob/6386cdff5037280e069e17dc456c93fd6003ca9e/examples/http-restful-server/Makefile#L10-L32

This explains what Mongoose needs to be built with one of the supported TLS libraries:
https://mongoose.ws/documentation/tutorials/tls/#how-to-build

How to build with that library in your system under your particular use is beyond us. Follow those tutorials, understand your system, understand your tools
