### ISSUE TITLE
Please follow the guidelines in the [documentation](https://mongoose.ws/documentation),  [examples](https://github.com/cesanta/mongoose/tree/master/examples) and [tutorials](https://mongoose.ws/tutorials/) available.

### ISSUE THREAD

**Issue by ondonadas** [cesanta/mongoose#2490]
Please follow the guidelines in the [documentation](https://mongoose.ws/documentation),  [examples](https://github.com/cesanta/mongoose/tree/master/examples) and [tutorials](https://mongoose.ws/tutorials/) available.

https://mongoose.ws/documentation/#mqtt-1

You seem to be doing what needs to be done, then, "doesn't work" is subjective, localized, and doesn't add anything that can help us solve your problem.
Please sniff your network (Wireshark), see what is going on, and then if necessary don't hesitate to open an issue, fill the issue template, and provide context and network _captures_ so we can help you fix the issue.

_Originally posted by @scaprile in https://github.com/cesanta/mongoose/discussions/2488#discussioncomment-7651060_

**Comment by scaprile** [comment]
#2488 #2489
I happen to know what I've written, please refrain from doing this
Please honor the issue template as requested
