### ISSUE TITLE
About running on a riscv-linux

### ISSUE THREAD

**Issue by hc161180051** [cesanta/mongoose#2553]
Hello, I want ro run mongoose on a riscv-based linux, but I didn't find any examples. I tried to modify mongoose.c as shown below, but it has a problem "undefined reference to 'clock_gettime' ". May I ask if you have any advice?
![image](https://github.com/cesanta/mongoose/assets/51509862/dcfc9356-51ef-4110-a58c-991c6dfbbd5d)

**Comment by scaprile** [comment]
Mongoose runs in Linux, you have tons of examples and ALL of them are run everyday in Linux on a CI/CD pipeline.
"Linux" includes several processor architectures, from the usual Intel to ARM Cortex-A like a Raspberry Pi.
Please follow the guidelines in the [documentation](https://mongoose.ws/documentation/),  [examples](https://github.com/cesanta/mongoose/tree/master/examples/) and [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples) available.
If something does not work _for you_:
- Please do not paste screenshots
- Please do not random modify and ask us to guess what you did.
- Please clearly explain what you do and what you get. You know what ? That is exactly what we ask in the issue template that you deliberately ignored. Please don't do that, it is there for a reason: to save yours and our time.

I'm closing this, if you have a specific comment on what does not work, where, and why, please feel free to reopen this issue and comment back with all the information needed to reproduce your issue.
