### ISSUE TITLE
MG_ARCH_FREERTOS_LWIP is not available in Mongoose 7.12

### ISSUE THREAD

**Issue by ex-fil** [cesanta/mongoose#2583]
I want to add Mongoose to my RP2040 and FreeRTOS project.
[Tutorial](https://mongoose.ws/documentation/tutorials/rp2040/pico-w/) require MG_ARCH=MG_ARCH_FREERTOS_LWIP but in Mongoose 7.12 this architecture is not available.

Should the tutorial use MG_ARCH_FREERTOS instead of MG_ARCH_FREERTOS_LWIP?

Thanks in advance.

**Comment by scaprile** [comment]
In the example itself:
https://github.com/mongoose-examples/raspberry-pi-pico-w/blob/d4f1ef40dfc9c16cde731e844de78c6b70097b6e/Makefile#L15
In the docs:
https://mongoose.ws/documentation/#build-options

```
-DMG_ARCH=MG_ARCH_FREERTOS -DMG_ENABLE_LWIP=1
```
The tutorial is outdated, fixing.

Please follow the guidelines in the [documentation](https://mongoose.ws/documentation/),  [examples](https://github.com/cesanta/mongoose/tree/master/examples/) and [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples) available.
