### ISSUE TITLE
Mongoose closes the connection without responding to POST requests that don't have explicit lengths

### ISSUE THREAD

**Issue by kenballus** [cesanta/mongoose#2593]
When Mongoose receives a POST request that doesn't have a `Transfer-Encoding` or `Content-Length` header set, it does not respond. It would be helpful if it responded 411 or 400 to indicate that a length is required.

**Comment by kenballus** [comment]
You can reproduce this issue by starting the `http-server` example, then running the following command:
```sh
printf 'POST / HTTP/1.1\r\n\r\n' | nc localhost 8000
```
There will be no output from `nc` because the server never responds.

**Comment by cpq** [comment]
@robertc2000 please take this one
