### ISSUE TITLE
Mbedtls error and memory leak when connecting through WebSocket

### ISSUE THREAD

**Issue by luisyague** [cesanta/mongoose#2602]
**- My goal is:** connect an ESP32 through WebSocket and free used memory when socket is closed
**- My actions were:** log free heap all the way through the connection process and then force a disconnection from the server. 
**- My expectation was:** the stack should not return any error and should free the used heap memory. 
**- The result I saw:** 
        E (23694) Dynamic Impl: mbedtls_ssl_fetch_input error=26752
                         E (23694) Dynamic Impl: mbedtls_ssl_fetch_input error=26752
E (27504) Dynamic Impl: mbedtls_ssl_fetch_input error=26752
 And around 10ks of heap lost during the reconnection

**- My question is:** is the any way to clear that error and free the used heap once the connection is closed? I am already calling mg_tls_free when the close event is invoked. 
The mbedtls only happens when the setting the CONFIG_MBEDTLS_DYNAMIC_BUFFER to true. 

# Environment
**- mongoose version:** 7.12
**- Compiler/IDE and SDK:** ESP IDF v4.4.6
**- Target hardware/board:** Custom
**- Connectivity chip/module:** ESP32 WROOM 32E
**- Target RTOS/OS (if applicable):** RTOS

**Comment by scaprile** [comment]
Unfortunately, I can't tell you how to solve your problem if you don't tell me _exactly_ what you are doing. We don't manage TLS, the IDF does, and BTW, you are using a rather old version of it; but, fundamentally, *we do not instruct to call mg_tls_free() anywhere in our dozens of examples*
Please follow the guidelines in the [documentation](https://mongoose.ws/documentation/),  [examples](https://github.com/cesanta/mongoose/tree/master/examples/) and [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples) available.
https://mongoose.ws/documentation/tutorials/tls/
If after you've done that, you still have an issue, feel free to reopen this one and provide all necessary info so we can know your scenario and reproduce the issue if needed, and let us know _exactly_ what you are doing
