### ISSUE TITLE
bind define conflict between "lwip/sockets.h" and c++ <functional>

### ISSUE THREAD

**Issue by ex-fil** [cesanta/mongoose#2605]
My setup is RP2040 + FreeRTOS + LWIP.

When I try to build a project in which i use both "mongoose.h" and <functional> headers there is a define conflict for the **bind** macro:

~~~
[build] pico-sdk/lib/lwip/src/include/lwip/sockets.h:635: note: macro "bind" defined here
[build]   635 | #define bind(s,name,namelen)                      lwip_bind(s,name,namelen)
[build]       | 
[build] /usr/include/newlib/c++/12.2.1/functional:895:45: error: macro "bind" requires 3 arguments, but only 2 given
[build]   895 |     bind(_Func&& __f, _BoundArgs&&... __args)
~~~

How I can manage this conflict in my project?

Thanks in advance!

**Comment by scaprile** [comment]
RP2040 does not have Ethernet nor WiFi. We do not support what you are doing as is.
Somewhere in your proyect you defined something in order for Mongoose to work with FreeRTOS and then to work with lwIP. The only way we support lwIP is working with sockets.
When you open an issue, there is an issue template that you should follow, so we don't have to guess or ask you a lot of questions.
The closest to your scenario is the Pico W example, see how it does what you want to do.
https://mongoose.ws/documentation/#pico-w
Please follow the guidelines in the [documentation](https://mongoose.ws/documentation/),  [examples](https://github.com/cesanta/mongoose/tree/master/examples/) and [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples) available.
