### ISSUE TITLE
[Question] How to protect server from OOM attack

### ISSUE THREAD

**Issue by JAremko** [cesanta/mongoose#2652]
I have a WebSocket server on a memory constrained system.  How can I prevent mongoose from allocating all the available memory and starving the system if a client sends huge payloads?

I guess it's a problem on TCP package queue level. I need a way to cap underlaying buffer size and provide some kind of a response to the client if we reach the cap.

**Comment by scaprile** [comment]
https://mongoose.ws/documentation/#best-practices

Please follow the guidelines in the [documentation](https://mongoose.ws/documentation/),  [examples](https://github.com/cesanta/mongoose/tree/master/examples/) and [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples) available.
