### ISSUE TITLE
Coverity - Unchecked return value, send may fail.

### ISSUE THREAD

**Issue by jtrack3d** [cesanta/mongoose#2671]
https://github.com/cesanta/mongoose/blob/7581229bbfd31ea739ff3a7b9a8a230458063c82/mongoose.c#L7793

**Comment by scaprile** [comment]
Hello,
do you have an actual problem ?
That is UDP. If that fails, the underlying system has bigger problems to take care of and there is nothing we can do about that.

Please honor the issue template.
