### ISSUE TITLE
visual studio compile mongoose.c report warning C4267: convert size_t to int

### ISSUE THREAD

**Issue by leitianjian** [cesanta/mongoose#2693]
- My goal is: integrate mongoose to my code
- My actions were: using msvc + cmake to compile mongoose with my code
- My expectation was: compile warning C4267: convert size_t to int

And I checked the most recent code in the master branch which hasn't explicitly converted size_t to int under msvc compiler

![image](https://github.com/cesanta/mongoose/assets/31007740/38e7f5ea-b151-4c95-a969-66426b559825)

# Environment

- mongoose version: 7.12
- Compiler/IDE and SDK: msvc v143 VS2022
- Target hardware/board: win 11 PC laptop
- Connectivity chip/module: Intel

**Comment by scaprile** [comment]
I'm sorry, I can't read chinese.
We build against several versions, see our Makefile and unit tests.
Use the latest version, we don't backport. Otherwise just cast that warning out.
