### ISSUE TITLE
how can we access fn_data from mg_http_listen's callback funtion (mg_event_handler_t) ?

### ISSUE THREAD

**Issue by ffreality** [cesanta/mongoose#2703]
I created a wrapper for Unreal Engine 5 and exposed all features to blueprints but in order to do that, I used `fn_data` to access / cast Unreal's actor class like this. But you deleted signature and this C type callback. So, we can't use lambda capture.
**How can we access fn_data from inside of callback ?**

If there is no way, you know there are people who use mongoose with C++ projects, right ?

```
auto Callback_Listen = [](struct mg_connection* Connection, int ev, void* ev_data, void* fn_data)
{
   FHTTP_Server_Mongoose_Actor* Owner = (FHTTP_Server_Mongoose_Actor*)fn_data;
   UHttpConnectionMng* Connection_Object = NewObject<UHttpConnectionMng>();
   Connection_Object->Connection = Connection;

   Owner->Parent_Actor->DelegateHttpMongooseMessage.Broadcast(Connection_Object);
   Owner->Parent_Actor->OnHttpMongooseMessage(Connection_Object);
}

mg_http_listen(&this->Mongoose_Manager, TCHAR_TO_UTF8(*this->Server_Address_HTTP), Callback_Listen, (void*)this);
```

**Comment by ffreality** [comment]
okay, you put it inside to struct mg_connection* Connection...

**Comment by scaprile** [comment]
It has always been there
https://mongoose.ws/documentation/#struct-mg_connection
and its usage is documented
https://mongoose.ws/documentation/#mg_http_listen

**Comment by ffreality** [comment]
yep, found it works as expected !
