### ISSUE TITLE
[Request feature] can you support wolfssl library

### ISSUE THREAD

**Issue by jerryokk** [cesanta/mongoose#2705]
I want to use smaller ssl library. Curl also supports wolfssl.

**Comment by cpq** [comment]
@jerryokk why not trying a built-in SSL?

**Comment by scaprile** [comment]
> I want to use smaller ssl library. Curl also supports wolfssl.

Our built-in library is not only "smaller", it is built-in...
https://mongoose.ws/documentation/tutorials/tls/

**Comment by cpq** [comment]
No response, closing this
