### ISSUE TITLE
Socket error after ota-updating the filesystem image

### ISSUE THREAD

**Issue by SlowTypist** [cesanta/mongoose#2716]
- My goal is: Serve files after updating the filesystem partition
- The result I saw: Socket error and no connection after updating the flash.
1dd60  3 mongoose.c:6601:read_conn 6 58 snd 0/2048 rcv 0/2048 n=-1 err=128
1d966  3 mongoose.c:6601:read_conn 7 59 snd 0/2048 rcv 0/2048 n=-1 err=128

I wrote a little routine to update filesystem image on ESP32 via websocket of Mongoose. First, the filesystem is unmounted, then the chunks are sent to websocket and written to flash. After that the filesystem is remounted. I can see that the mount is correct - right after remounting I list in UART all files and it works. But Mongoose stops serving http requests, with errors given above. Restarting the ESP32 helps, Mongoose works again, but it would be nice if I don't have to reset the ECU after flashing just the storage partition. Is there something I should do before unmounting the storage partition, like softly stop the Mongoose server? But I still need websocket to keep working. Or the error is somewhere else?

# Environment

- mongoose version: 7.12
- Compiler/IDE and SDK: ZZZ version esp-idf
- Target hardware/board: ESP32
- Connectivity chip/module: ESP32
- Target RTOS/OS (if applicable): freertos

**Comment by scaprile** [comment]
If you tell Mongoose to use your filesystem, and then you change your filesystem, what can Mongoose do ?
Besides that, your error seems to be a "socket not connected" error, the ESP is telling Mongoose that the socket is not working.
Whatever you are doing, your are breaking your system, and this is not a Mongoose issue
