### ISSUE TITLE
cannot connect MQTT to STM32F407

### ISSUE THREAD

**Issue by phu251099** [cesanta/mongoose#2741]
Currently, I am testing MQTT connection with a board using STM32F407 chip and LAN8720A ethernet decoder ic. When I try to connect to the MQTT server, it always returns the value "MG_EV_CLOSE". When I use the function "static void my_putchar(char ch, void *param)" I get the result as shown below. I wonder if anyone has encountered a similar situation like me?
![z5404507689518_f94d014a943cdcc6c89fb365f464d0d7](https://github.com/cesanta/mongoose/assets/133739987/158faa65-c087-48db-91d7-2ffd26f16adc)

**Comment by scaprile** [comment]
You did not honor the issue template, so I can't guess what you have and what you don't, what you do and what you don't
Please do NOT paste screen snapshots, use markdown for logs and code snippets.
We do not have examples for F407.
We do not have examples for your board, that you don't tell, whatever it is.
I can see clearly that you don't get an IP address, how do you expect MQTT to connect if you don't have an IP address ?
Is your network REALLY 10M half-duplex ?
You don't tell which Mongoose version you are using, I don't see the PHY logs, you probably didn't even communicate with the PHY. You can't load random code and expect it to work on your board just out of the blue, proper support needs proper configuration, and that requires that you know your hardware and be able to port code from supported platforms to yours.
