### ISSUE TITLE
The "mg_url_host" function is not work?

### ISSUE THREAD

**Issue by WaterFishJ** [cesanta/mongoose#2748]
- My goal is: _describe_
- My actions were: _describe_
- My expectation was: _describe_
- The result I saw: _provide logs or description_
- My question is: 
My test code is :
```
struct mg_str host = mg_url_host("http://12.123.124.234:8862/api/Device/GetActivePlatform.do");
printf("host: %s\n", host.ptr);
```
And I get : "host: 12.123.124.234:8862/api/Device/GetActivePlatform.do"

Maybe it shoule be "host: 12.123.124.234:8862" due to the docs?

# Environment

- mongoose version: _X.Y_
- Compiler/IDE and SDK: ZZZ version _X.Y_
- Target hardware/board: _?_
- Connectivity chip/module: _?_
- Target RTOS/OS (if applicable): _?_

**Comment by scaprile** [comment]
It does work, we have a CI/CD pipeline and unit tests in place.
The docs are also correct, `struct mg_str` has a `len` field that has to be honored.
You are not properly handling the `struct mg_str`, you are not properly printing it. You are not using the `len` field.
`printf("%.*s", host.len, host.buf)`. (or `ptr` in your case, as you seem to not be using HEAD, you did not properly fill the issue template)
