### ISSUE TITLE
Mongoose ignores `Connection: close` headers

### ISSUE THREAD

**Issue by kenballus** [cesanta/mongoose#2765]
To see this for yourself,

0. Compile and run the `http-restful-server` tutorial.

1. Send it a pipeline consisting of two `GET` requests in which the first request has a `Connection: close` header:
```
printf 'GET / HTTP/1.1\r\nHost: a\r\nConnection: close\r\n\r\nGET / HTTP/1.1\r\nHost: a\r\n\r\n' | nc localhost 8000
```

2. Observe that the server responds twice, even though the second request should be ignored because it was sent after the connection was closed.

# Environment

- mongoose version: master (6bb40e6ec96f95bfd36a816b430ea2726fac9d05)
- Compiler: GCC 13.2.0
- Platform: AMD64 Linux

**Comment by cpq** [comment]
@scaprile please handle this one. I believe the best way to fix it is to set `c->is_draining` flag if the `Connection: close` is specified.
