### ISSUE TITLE
[RST, ACK] frame when starting downloading file

### ISSUE THREAD

**Issue by chipsoft** [cesanta/mongoose#2774]
- My goal is: Successfully download file from embedded webserver
- My actions were: I am trying download file
- My expectation was: Successfully downloaded file
- The result I saw: Download started, but Mongoose Webserver responses with [RST, ACK] frame. As a result, browser can't see downloaded file
- My question is: How to fix it

# Environment

- mongoose version: 7.11
- Compiler/IDE and SDK: arm-none-eabi-gcc version 10.3.1 20210824 (release)
- Target hardware/board: STM32F7
- Connectivity chip/module: WILC1000
- Target RTOS/OS (if applicable): FreeRTOS

I encountered with problem when using Mongoose Server and downloading files. When downloading files, very often the server for some reason returns Ethernet Frame RST, ACK. However, the data transfer continues, but the browser does not see the downloaded file (probably because some Ethernet frame is lost).

This frame is generated by the function `static void rx_tcp(struct mg_tcpip_if *ifp, struct pkt *pkt)`
Namely this fragment:

```
  } else if (!c->is_accepted) {  // no peer
    tx_tcp_pkt(ifp, pkt, TH_RST | TH_ACK, pkt->tcp->ack, NULL, 0);
  } 
```

We use the WILC1000 WiFi module and driver that we developed ourselves.
In page display mode, Mongoose Server works fine. Problems only arise when trying to download a file.

Additionally, I attached Wireshark files so that the essence of the problem could be seen.

In the file wilc1000_ok_and_fail.pcapng there are two attempts to download the same file. At 
first it’s successful, and then it’s not.
The wilc1000_ok_and_fail.pcapng file contains one unsuccessful attempt to download the file.
This is zip file with log: [wilc1000.zip](https://github.com/user-attachments/files/15543989/wilc1000.zip)

**Comment by scaprile** [comment]
7.11 is ages old.
7.14 is our latest release.
Please try 7.14; our TCP/IP stack has been evolving during such a long time.
If you still have an issue with 7.14 or HEAD, we can reopen this issue and see what is going on
