### ISSUE TITLE
411 responses are delivered twice

### ISSUE THREAD

**Issue by kenballus** [cesanta/mongoose#2811]
When Mongoose receives an HTTP/1.1 POST request with no `Content-Length` or `Transfer-Encoding` header, it responds with two 411 responses instead of 1.

To see this for yourself,
- Clone and build the current `master` branch (bdfa0b302b3a7ec7dc0c750fb8357a651cf0fc2d)
- Start the `http-server` example under `tutorials/http/http-server`
- Send it a `POST` request with no headers:
```
POST / HTTP/1.1\r\n
\r\n
```
- Observe that you receive two responses:
```
HTTP/1.1 411 Length Required
Content-Length: 0

HTTP/1.1 411 Length Required
Content-Length: 0

```

**Comment by scaprile** [comment]
Thank you.
They are not delivered twice, they are delivered again and again as long as the connection is kept open, every time the event manager runs. It is a consequence of #2806.
We'll work on it.
