### ISSUE TITLE
Custom http websocket upgrade request

### ISSUE THREAD

**Issue by FabianTerhorst** [cesanta/mongoose#2859]
Having the possibility to dynamically set the host header field inside the http upgrade to websocket request is required for me under specific circumstances where the url contains a ip address instead of a domain. To have a correctly working behavior the host still needs to be set to the domain name in this case.
But mongoose does not allow specifying the host independently inside the websocket upgrade:
https://github.com/cesanta/mongoose/blob/d763fce8ed584530ebd1d4c15f69df05a7164379/src/ws.c#L247
Making it possible to build the websocket upgrade http request more dynamically while not having to reimplement the ´mg_ws_cb´ would be appreciated.

# Environment

- mongoose version: 7.1.4

**Comment by scaprile** [comment]
This not a Mongoose issue. It is something you request.
Mongoose 7.1.4 does not exist.
If you need a specific change, please clearly explain your use case and why it is needed.
If you are a paying customer, please contact Support as per your contract.
