### ISSUE TITLE
about send heartbeat message and TCP connection monitoring?

### ISSUE THREAD

**Issue by kuangtu** [cesanta/mongoose#2874]
- My goal is: 
I'm utilizing Mongoose to develop an application for receiving stock exchange quotes.
The core functionalities of this application encompass:
(1)Receiving and Processing TCP Data: 
(2)Heartbeat Messaging: To maintain a connection with the remote server, the application periodically sends heartbeat messages.
(3)TCP Connection Monitoring and Reconnection: In the event of a connection break, it swiftly initiates a reconnection process, minimizing disruption and ensuring continuous data flow.

The process flow of the application is as follows:
(1)Initialize Timers: Set up a heartbeat timer for sending periodic messages to maintain the server connection and a TCP connection monitoring timer to detect potential disruptions.
(2)Establish Connection: Initiate the TCP connection with the remote server to begin receiving stock quotes.
(3)Event Polling: Use mg_mgr_poll to continuously poll for and process incoming data and epoll events.

The scenario is:
(1)if the remote server is down connection will return -1 and set errno to EINPROGRESS or EWOULDBLOCK:
```
    rc = connect(FD(c), &usa.sa, slen);  // Attempt to connect
    if (rc == 0) {                       // Success
      setlocaddr(FD(c), &c->loc);
      mg_call(c, MG_EV_CONNECT, NULL);  // Send MG_EV_CONNECT to the user
    } else if (MG_SOCK_PENDING(rc)) {   // Need to wait for TCP handshake
      MG_DEBUG(("%lu %ld -> %M pend", c->id, c->fd, mg_print_ip_port, &c->rem));
      c->is_connecting = 1;
    } else {
      mg_error(c, "connect: %d", MG_SOCK_ERR(rc));
    }
```
process EPOLLERR event in mg_mgr_poll-->mg_iotest-->mg_error-->c->is_closing = 1.
In this now the connection is not  really closed.
```
   if (c->is_closing) close_conn(c);
```

(2)before close_conn(),
```
  mg_timer_poll(&mgr->timers, now);
 ```
 will execute timer:
 (1)In heartbeat timer func,  check is_closing = 1, if true,don't send heartbeat message.
 (2)In reconection timer func, also check is_closing = 1, if true, reconnection the remote server.
- My question is:  Is the above processing procedure correct and reasonable.

# Environment
- mongoose version: 7.14
- Target RTOS/OS (if applicable): *nix

**Comment by scaprile** [comment]
This is not a Mongoose issue. Please don't open issues to ask questions.
Let's  do this. Instead of me learning your application, understanding your design approach, and checking your code, why don't you read our docs and check our examples ? WDYT ?
Please see our [documentation](https://mongoose.ws/documentation/),  and follow the guidelines in our [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples).
https://mongoose.ws/documentation/#tcp
