### ISSUE TITLE
Use OPENSSL How to make this connection timeout? to close the mg_connection

### ISSUE THREAD

**Issue by gogoxx2024** [cesanta/mongoose#2887]
- My goal is: Use OPENSSL
- My actions were: Connect using TLS, process received data
- My expectation was: close the test tool[restclient.jar] 
- The result I saw: There is still one link that has not been released;  static void read_conn(struct mg_connection *c) 
-
- My question is: How to make this connection timeout? to close the mg_connection

# Environment

- mongoose version: 7.15
- Compiler/IDE and SDK: vs2015
- Target hardware/board: windows11
- Connectivity chip/module: mongoose-master\tutorials\http\http-restful-server
- Target RTOS/OS (if applicable): None

line:7523
static void read_conn(struct mg_connection *c)

n is MG_IO_RESET

c->is_tls_hs is 0

if (c->is_tls_hs) mg_tls_handshake(c);

How to make this connection timeout? to close the mg_connection

![1](https://github.com/user-attachments/assets/5f7ecfe8-1bd8-4626-9222-98a8d14737cc)
![2](https://github.com/user-attachments/assets/31633326-fbb8-4a8d-9e0f-df47e96e162b)
![3](https://github.com/user-attachments/assets/55490d4e-d6c6-492f-a816-e8f2d9366d36)
close the tool
![4](https://github.com/user-attachments/assets/33db7bc8-144c-4a96-8912-498279056086)
![5](https://github.com/user-attachments/assets/898615b4-5819-4040-b24c-8ce3fdf8e67b)
![6](https://github.com/user-attachments/assets/8874f7db-174d-4bdf-a723-3bd12919aa2f)

**Comment by scaprile** [comment]
I don't understand what you are doing.
Please don't post snapshots, refer to code and attach network captures (files)
Please don't mark our code, we already know it, it is yours that we don't know
Please correctly describe what you are doing, what is your code, what happens, where, and why
Minimum possible to reproduce your issue.
Please read https://mongoose.ws/documentation/#best-practices
Please see our [documentation](https://mongoose.ws/documentation/),  and follow the guidelines in our [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples).
When you have that, then we'll reopen this issue if necessary

**Comment by gogoxx2024** [comment]
What I want to say is that I use SSL HTTP server. When the client connects and communicates, the client closes and the server still has a connection pointer that has not been reclaimed, so it will not be released. What I want to ask is if there is any API that can handle timeouts to release such invalid links




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sergio R. ***@***.***&gt;; 
发送时间: 2024年9月7日(星期六) 晚上10:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cesanta/mongoose] Use OPENSSL How to make this connection timeout? to close the mg_connection (Issue #2887)














 
I don't understand what you are doing.
 Please don't post snapshots, refer to code and attach network captures (files)
 Please don't mark our code, we already know it, it is yours that we don't know
 Please correctly describe what you are doing, what is your code, what happens, where, and why
 Minimum possible to reproduce your issue.
 Please read https://mongoose.ws/documentation/#best-practices
 Please see our documentation,  and follow the guidelines in our tutorials.
 When you have that, then we'll reopen this issue if necessary

**Comment by scaprile** [comment]
> Please correctly describe what you are doing, what is your code, what happens, where, and why
> Minimum possible to reproduce your issue.
> Please read https://mongoose.ws/documentation/#best-practices
> Please see our [documentation](https://mongoose.ws/documentation/), and follow the guidelines in our [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples).
> When you have that, then we'll reopen this issue if necessary

**Comment by gogoxx2024** [comment]
I uploaded my test code to Baidu Cloud
Link: https://pan.baidu.com/s/1l8D6Cb1of4PK24E6qpreww&nbsp;&nbsp;
Extraction code: ol6u

HttpDemo. zip is the source code for the vs2015 code project, mongoose master \ tutorials \ http \ http critical server
openssl-x64.zip is the ssllib
Restclient. zip is a link testing tool for HTTPS
Recording. zip demo video






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cesanta/mongoose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月9日(星期一) 凌晨2:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cesanta/mongoose] Use OPENSSL How to make this connection timeout? to close the mg_connection (Issue #2887)





  
Please correctly describe what you are doing, what is your code, what happens, where, and why
 Minimum possible to reproduce your issue.
 Please read https://mongoose.ws/documentation/#best-practices
 Please see our documentation, and follow the guidelines in our tutorials.
 When you have that, then we'll reopen this issue if necessary

**Comment by scaprile** [comment]
If you would have read the tutorials as instructed: https://mongoose.ws/documentation/tutorials/tls/#windows
>Windows
Only what the example provides in its Makefile is supported 

We do not support custom openssl in Windows.
Whatever you want to submit to reproduce your issue must be posted here, clear and readable code, and build as standard. As we won't build nor link any third-party library, I will dismiss this.
