### ISSUE TITLE
mg_http_match_uri does not exist?

### ISSUE THREAD

**Issue by yves-chevallier** [cesanta/mongoose#2894]
In the README, an example is given to `mg_http_match_uri`, but this function does not exist. On the `https://mongoose.ws/documentation/`, it seems `mg_match(hm->uri, mg_str("/api/hello"), NULL)` would be the correct call. 

Where does this `mg_http_match_url` comes from?

**Comment by scaprile** [comment]
Please see our [documentation](https://mongoose.ws/documentation/),  and follow the guidelines in our [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples).

> [Mongoose 7.14](https://github.com/cesanta/mongoose/releases/tag/7.14)
    Deprecated mg_http_match_uri(), use mg_match() instead

https://mongoose.ws/documentation/#mg_match
https://mongoose.ws/documentation/#http
https://mongoose.ws/documentation/tutorials/http/http-server/

The "correct call" will depend on what you want to do, that is why we have an issue template, that, btw, you did not fill
If you refer to where I can see the call you mention in the README I guess you refer to, I would say it is as we just corrected. Thanks for pointing that out.
https://github.com/cesanta/mongoose/blob/3fa52d0d7dcdab8a9431f8a52931c09b981e0f6a/README.md?plain=1#L73
