### ISSUE TITLE
void *mg_start_thread(void *(*func)(void *), void *param);

### ISSUE THREAD

**Issue by guyongjian** [cesanta/mongoose#290]
can you introduce the function mg_start_thread(void _(_func)(void *),void *param) ?
what it work?

**Comment by igorojas** [comment]
Hello, I am using this function but 'func' is only called once.

I am running on Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-67-generic x86_64), gcc 4.8.4.

Any suggestions?

**Comment by cpq** [comment]
@igorojas what do you mean it's called once?
If you're starting only one thread, it's going to be called only once.
