### ISSUE TITLE
Defaults to 0.0.0.0:8000, which doesn't load. but 127.0.0.1:80 works

### ISSUE THREAD

**Issue by bryc** [cesanta/mongoose#2902]
Title pretty much says it. I'm using the Windows build under Windows 10.

Just doesn't work how I used to remember (used mongoose like 6+ years ago).

I had to manually open terminal, check `/?` for help, and type in `mongoose -l http://127.0.0.1:80` to get the desired effect. Would this not be a better default value?

**Comment by scaprile** [comment]
Do you know ? We have an issue template for a reason.
Do you know what 0.0.0.0 means ? It means "listen in all interfaces". Do you know who knows what an interface  is ? Your OS, your environment, Mongoose doesn't have the slightest idea of what is that, it just asks your OS to listen on what you tell it to.
Said that, that binary you are referring to, is just an example built on our library. There is the code for it in the repo, change it the way you like.
