### ISSUE TITLE
Sending large files uses a lot of memory

### ISSUE THREAD

**Issue by ghost** [cesanta/mongoose#292]
I'm trying to use Mongoose to replicate Amazon S3's query based authentication. I authenticate the query and then read the appropriate file and send it using mg_send_data. However while the client is downloading the file Mongoose is reported to be using a lot of memory - equivalent to the file's size. Is the entire response buffered in memory before being sent to the client?

Would it be possible to add support for some sort of streaming responses?

Or am I doing something wrong?

**Comment by pucmelda** [comment]
Is it possible to get the file (https://github.com/cesanta/mongoose/blob/master/examples/file.c - file does not exist). I need the same help. Thanks

**Comment by cpq** [comment]
See https://github.com/cesanta/mongoose/tree/master/examples

**Comment by pucmelda** [comment]
Sorry, but I cannot find example of sending large file (or large data from memory).
In fact, I have big array in RAM what I need send to client as JSON. I use mg_send_http_chunk, but there is not enough RAM for whole JSON, so next chunk I can put after sending the previous one. I do not know how, can you help me? Thanks

**Comment by cpq** [comment]
The simplest method is to save into file and serve that file.
Mongoose performs flow control for file data.

**Comment by pucmelda** [comment]
It is not possible - project is for ESP-WROOM-32 (4MB flash, 512kB RAM). Data is changing very often and JSON will be read every minute - so I cant write it to flash memory. So it must be sent directly from RAM.

**Comment by cpq** [comment]
esp32 is far less then 512k ram.
sdk init halves it, then user code eats more.
how big is the JSON string ?

**Comment by pucmelda** [comment]
my JSON is max about 300kB, I have now cca 140kB free RAM on module

**Comment by cpq** [comment]
There is no way you can keep 300k JSON in ESP32 RAM, IMO.
ESP32, as I said, does NOT give 512k of free RAM, but much less.

Did you actually test it and run on the live chip ?

**Comment by pucmelda** [comment]
Yes, I tried it. Now, for the first attempt, I have about 65kB of data in RAM - I read it through UART periodically. When web page ask for it by XMLHttpRequest, I need to serve this data - now I sent JSON array with numbers in text format, chunked mode - so it is about 260kB. But mongoose sent only cca 43kB and stop. I need sent it chunk by chunk directly, not through memory - maybe by some event CHUNK_SENT ??? I can split the array into several requests, but I strongly prefer sent it together.

Finally, I will serve bigger amount of data - now I am just testing ability of mongoose and trying to learn it. But this feature is necessary for me.
