### ISSUE TITLE
How does the websocket server proactively disconnect (including code)

### ISSUE THREAD

**Issue by cproape** [cesanta/mongoose#2941]
- My goal is: 
- My actions were:   c->is_closing=1;
- My expectation was: The websocket is actively disconnected and carries a code, such as 1000/1006
- The result I saw:   The disconnect code received by the client is 1006
- My question is: How does the websocket server proactively disconnect (including code)

# Environment

- mongoose version: 7.15
- Compiler/IDE and SDK: gcc
- Target hardware/board:  linux
- Connectivity chip/module: 
- Target RTOS/OS (if applicable):  linux

**Comment by scaprile** [comment]
Please see our [documentation](https://mongoose.ws/documentation/),  and follow the guidelines in our [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples).

Please read https://mongoose.ws/documentation/#best-practices

If there is an actual issue, please  _honor the issue template_ so we can know your scenario and reproduce the issue if necessary, and let us know _exactly_ what you are doing

I can't guess what you're doing wrong if you don't show what you do.
