### ISSUE TITLE
Fix floating point printing

### ISSUE THREAD

**Issue by cpq** [cesanta/mongoose#2943]
We have our own printf implementation, and right now it incorrectly handles floating point width and precision in 

What to do: re-enable [floating point tests in unit_test.c](https://github.com/cesanta/mongoose/blob/8eabf4352549295edc2a9e155f6cb9fa8806beb7/test/unit_test.c#L2156-L2160) and modify [mg_dtoa](https://github.com/cesanta/mongoose/blob/8eabf4352549295edc2a9e155f6cb9fa8806beb7/src/fmt.c#L40) function to execute these tests successfully.

Changes in mg_dtoa() should be minimal.

**Comment by scaprile** [comment]
#2954
