### ISSUE TITLE
https/ssl issues

### ISSUE THREAD

**Issue by erappaport** [cesanta/mongoose#295]
When using https, mongoose works every other time for each call - including for static assets. For instance, if I point the browser to a png image (with https), the first time, mongoose works, then it gives the following error:
An error occurred during a connection to 127.0.0.1:8005. 
SSL received a record with an incorrect Message Authentication Code. 
(Error code: ssl_error_bad_mac_read)
Then it works, then error, etc.

If I try to go back to http, nothing works unless I recompile without USE_SSL defined.

**Comment by cpq** [comment]
There have been multiple SSL related fixes committed since.
I assume the issue fixed - please reopen if still an issue.
