### ISSUE TITLE
how to do websocket auth

### ISSUE THREAD

**Issue by lovelypp777** [cesanta/mongoose#2958]
- My goal is: to do websocket auth

- mongoose version: 7.14
- Compiler/IDE and SDK: gcc
- Target hardware/board: x64

I use mg_ws_connect to connect to the websocket server, but the server needs cookie when connect. My question is: how to send cookie when connecting to server ?

thanks!

**Comment by scaprile** [comment]
Please see our [documentation](https://mongoose.ws/documentation/),  and follow the guidelines in our [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples).
Please understand the technology you are using, there is no authentication in WebSocket, there are no cookies in WebSocket, you do whatever you need to do in HTTP(S) and then upgrade to websocket
This is not a Mongoose issue. Please don't open issues to ask questions
