### ISSUE TITLE
Detecting Client Disconnection During Long-Running Responses Not Detectble

### ISSUE THREAD

**Issue by Ealireza** [cesanta/mongoose#2965]
I'm using Mongoose with libuv to handle non-blocking connections and manage long-running responses. In my setup, I write data chunks directly on the connection channel, passing a mg_connection *c struct to a callback. However, I'm encountering issues when a client disconnects mid-response. Specifically, if a client disconnects or shuts down during a response that could take up to 20 minutes, the server continues sending data even when there's no connected client. This seems to be related to keep-alive handling.

Code Example: Below is the code I'm currently using:

```
size_t weather_write_callback(void *contents, size_t size, size_t nmemb, struct mg_connection *c) {
    // Calculate the total size of data to be sent
    size_t total_size = size * nmemb;

    // Check if the connection is closing or has an error
    if (c->is_closing || c->is_draining || c->is_io_err) {
        LOGI("Connection is closing or encountered an error. Aborting write operation. Total data attempted: %zu bytes.", total_size);
        return 0;
    }

    // Send the data chunk
    mg_send(c, contents, total_size);

    // Log the amount of data sent successfully
    LOGI("Data chunk sent: %zu bytes.", total_size);

    return total_size;
}
```

Unfortunately, Mongoose does not have a built-in mg_is_connected function

**Comment by scaprile** [comment]
The issue template is there for a reason: to save yours and our time. Please honor the issue template and fill it as requested.
Please see our [documentation](https://mongoose.ws/documentation/),  and follow the guidelines in our [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples).
You don't seem to be using Mongoose properly, and you don't need that if you use it properly.
