### ISSUE TITLE
accessing invalid memory in should_keep_alive() when called form close_local_endpoint()

### ISSUE THREAD

**Issue by xant** [cesanta/mongoose#305]
valgrind reports: 

==21536== Invalid read of size 1
==21536==    at 0x408300: mg_get_header (mongoose.c:1458)
==21536==    by 0x40837D: should_keep_alive (mongoose.c:1590)
==21536==    by 0x40E0D4: close_local_endpoint (mongoose.c:3695)
==21536==    by 0x40FBC2: mg_poll_server (mongoose.c:1348)
==21536==    by 0x41257D: shcd_http_run (shcd_http.c:470)
==21536==    by 0x5039B4F: start_thread (pthread_create.c:304)
==21536==  Address 0x34009a6d is 45 bytes inside a block of size 146 free'd
==21536==    at 0x4C27D4E: free (vg_replace_malloc.c:427)
==21536==    by 0x40E301: close_local_endpoint (mongoose.c:3718)
==21536==    by 0x40DF33: process_request (mongoose.c:1939)
==21536==    by 0x40F124: read_from_socket (mongoose.c:3602)
==21536==    by 0x40FABF: mg_poll_server (mongoose.c:3818)
==21536==    by 0x41257D: shcd_http_run (shcd_http.c:470)
==21536==    by 0x5039B4F: start_thread (pthread_create.c:304)
==21536== 
==21536== Invalid read of size 1
==21536==    at 0x408387: should_keep_alive (mongoose.c:1591)
==21536==    by 0x40E0D4: close_local_endpoint (mongoose.c:3695)
==21536==    by 0x40FBC2: mg_poll_server (mongoose.c:1348)
==21536==    by 0x41257D: shcd_http_run (shcd_http.c:470)
==21536==    by 0x5039B4F: start_thread (pthread_create.c:304)
==21536==  Address 0x34009a40 is 0 bytes inside a block of size 146 free'd
==21536==    at 0x4C27D4E: free (vg_replace_malloc.c:427)
==21536==    by 0x40E301: close_local_endpoint (mongoose.c:3718)
==21536==    by 0x40DF33: process_request (mongoose.c:1939)
==21536==    by 0x40F124: read_from_socket (mongoose.c:3602)
==21536==    by 0x40FABF: mg_poll_server (mongoose.c:3818)
==21536==    by 0x41257D: shcd_http_run (shcd_http.c:470)
==21536==    by 0x5039B4F: start_thread (pthread_create.c:304)

This happens because we free the request in close_local_endpoint()

3714   discard_leading_iobuf_bytes(&conn->local_iobuf, conn->mg_conn.content_len);
3715   conn->endpoint_type = EP_NONE;
3716   conn->flags = conn->mg_conn.status_code = 0;
3717   conn->cl = conn->num_bytes_sent = conn->request_len = 0;
3718   free(conn->request);
3719   conn->request = NULL;

then we call process_request() which calls close_local_endpoint() which at the beginning does :
 
3695   int keep_alive = should_keep_alive(&conn->mg_conn) &&
3696     (conn->endpoint_type == EP_FILE || conn->endpoint_type == EP_USER);

should_keep_alive() tries to look at headers, but the problem is that headers are pointers
to the original buffer of the request which has been already freed, so it ends up accessing invalid memory.

I'm trying to see if I manage to fix it quickly ... let me know if you prefer to give a look at it yourself.

**Comment by cpq** [comment]
Assuming fixed, closing.
Please reopen if still an issue.
