### ISSUE TITLE
Add top level Makefile and targets for DLL

### ISSUE THREAD

**Issue by anatol** [cesanta/mongoose#326]
I see that mongoose 5.2 removed the Makefile. I believe that the idea that everyone should download sources and compile as embedded.

Although in some situation it would be great to distribute it as a shared library. Some distros (like Linux Arch) are in strong favor of this way. It would be great if mongoose could be distributed as a shared library.

So it would be nice to have Makefile that:
 - compiles *.so *.a with some predefined set of compile flag (enable all features by default is probably the best idea)
 - installs compiled binary files + header files
 - has 'check' targtet
 - *.pc file with compilation flags that are in sync with shared libraries

**Comment by cpq** [comment]
It has been a while since that issue was filed.
I assume there is no interest anymore to have Makefile target for DLLs.
Closing.

Please reopen and send the PR if still an issue.

**Comment by anatol** [comment]
We still interested in it. For now we just ignore the mongoose Makefile file and call gcc directly from our build script https://aur.archlinux.org/packages/mo/mongoose/PKGBUILD. And IMHO the project makefile should provide such basic functionality rather forcing users to copy-paste it.

**Comment by jpleau** [comment]
Hi, I'm currently looking at the possibility of packaging mongoose for Debian.

The ability to produce both a shared library as well as a standalone webserver in different targets would really be useful for me. Subscribing to this bug :)

Another project I'm considering packaging makes use of mongoose, which is why I would also need to package mongoose (we try to avoid including embedded copies of libraries when packaging software in Debian)

Cheers

**Comment by CurlyMoo** [comment]
> Hi, I'm currently looking at the possibility of packaging mongoose for Debian.

If you need help creating these packages you can always ask. Having lots of experience in apt servers and debian packaging.

**Comment by renatosilva** [comment]
I have recently contributed a libmongoose package for MSYS2 containing both a static library and a DLL. The [packaging recipe](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-libmongoose-git/PKGBUILD) is currently calling gcc directly though.

**Comment by jpleau** [comment]
Hi

Here are the Makefile and .pc files I made for my Debian package.

https://gist.github.com/jpleau/327b2653633e97d955fe

Any feedback appreciated !

**Comment by silvioprog** [comment]
Hello @anatol ,

Could you compile the DLL? I have interest to compile mongoose as .dll/.so libraries, but I can't understand C/C++ to do it.

Thank you!
