### ISSUE TITLE
ssl_read block at least 1 sec.

### ISSUE THREAD

**Issue by alt1972** [cesanta/mongoose#337]
Hello,

I'm using mongoose version 3.8 with ssl enabled.

When I send to mongoose server a json about 1600 bytes (by POST), the function  call chain is : mg_read() -> pull_all() -> pull() ->  and at the end : ssl_read() 

So, ssl_read() takes at least 1 second to complete the operation, and it's ugly.
This behavior happens  whether keepalive is enabled or not.

when the posted data to mongoose have small size (like 170 bytes) the call to ssl_read() function does not occur, and it works fine.

Have you any idea what is happening?

Thanks in advance.
Angel.

**Comment by cpq** [comment]
There were plenty of SSL related fixed coming in.
Closing, please reopen if still an issue.
