### ISSUE TITLE
file.c example does not work in master branch

### ISSUE THREAD

**Issue by oelbox** [cesanta/mongoose#342]
There seems to be an issue in the master branch with the file.c example. If the file > sizeof(buf) then the web-browser will just hang until timeout occurs. The issue is basically that upon return of MG_REQUEST_CALL_AGAIN from request_handler callback, the server does not call request_handler repeatedly until everything is transferred. This might have been reported prior, but I was unable to find anything directly regarding this issue.

A simple:

while (result == MG_REQUEST_CALL_AGAIN) {

} 

in call_request_handler would resolve the issue, although I do not have enough experience with mongoose to say if that is the correct solution for the library.

**Comment by cpq** [comment]
I believe that has been fixed. Closing. Please reopen if still an issue.
