### ISSUE TITLE
Sometimes static files are truncated when using SSL because SSL_Write returns -1 (SSL_ERROR_WANT_WRITE)

### ISSUE THREAD

**Issue by rjcoelho** [cesanta/mongoose#357]
Only occurs sometimes and only after a bunch of SSL_Writes have succeed. Basically everying is ok (a bunch of SSL_Writes 8192 bytes success) but then suddenly SSL_Write returns -1 (after calling SSL_get_error in the error I see SSL_ERROR_WANT_WRITE). I have a 5 sec poll period on the select. Can reproduce once every 10 requests (ctrl+f5 refresh) on Chrome/IE and on different files (js/css) of ~300KBs. Using self-signed certificated you provided and no proxies (browser and server are on same machine). Is it just me ? Could it be related to non-blocking sockets introduced in v5 ?

Googling for it I get the idea I need to call SSL_Write again (w/ same arguments) because negotiation wasnt finished. From Man pages:
"The operation did not complete; the same TLS/SSL I/O function should be called again later. If, by then, the underlying BIO has data available for reading (if the result code is SSL_ERROR_WANT_READ) or allows writing data (SSL_ERROR_WANT_WRITE), then some TLS/SSL protocol progress will take place, i.e. at least part of an TLS/SSL record will be read or written.  The retry may again lead to a SSL_ERROR_WANT_READ or SSL_ERROR_WANT_WRITE condition. There is no fixed upper limit for the number of iterations that may be necessary until progress becomes visible at application protocol level."

**Comment by cpq** [comment]
Change was integrated.
Closing this.
Thanks!
