### ISSUE TITLE
Get PUT body

### ISSUE THREAD

**Issue by abimaelmartell** [cesanta/mongoose#364]
¿How can get the body from a PUT request?

When i print the content of `conn->content` it also dumps the HTTP headers from the request, i need to get only the body.

I was using a previous version of mongoose, and i was doing it like this

https://github.com/abimaelmartell/todo/blob/master/src/actions.c#L57

I'm using mongoose from master.

Thanks!

**Comment by rojer** [comment]
this is about mongoose 5.x, please reopen if this still applies to 6.4+ю
