### ISSUE TITLE
Possible to bind two Mongoose instances to the same port

### ISSUE THREAD

**Issue by cry-inc** [cesanta/mongoose#370]
Platform: Win7 64 bit, compiled as 32 or 64 bit binary with VS 2012

I noticed that mg_set_option() does not return an error when the listening port of a second instance gets set to the same port as a first Mongoose instance. If the port is used by another process, the expected error "Cannot bind to port" is returned.

This is caused by mongoose.c in line 531 where setsockopt() is used to allow port reuse. I have created an example to illustrate the problem: https://gist.github.com/cry-inc/eb5c2d495c3751170881

I would expect that either an assertion is triggered or that the example works. But neither is the case. Why did you allow the port reuse?

**Comment by cpq** [comment]
I think this is OK to close.
