### ISSUE TITLE
Can't Close WebSocket connection

### ISSUE THREAD

**Issue by mahieddine** [cesanta/mongoose#373]
Hi,
First thank you for the great work, it's a real pleasure to work with this library. i use it as push notification server, 
Basically the client opens a websocket connection, then he sends a json message to authenticate.

The first problem was that i didn't found in this version of mongoose a method to read data from socket ! (mg_ws_socket_read) so basically i created one that just extract the message from connection->content  

if user credentials are ok, we send him data back if no i want to close the socket, is it possible ? thank you !

**Comment by gpravada** [comment]
Yes it is working
