### ISSUE TITLE
crashed in "transfer_file_data" function

### ISSUE THREAD

**Issue by Yorkey** [cesanta/mongoose#374]
when run the http server, sometimes it crashed in transfer_file_data,

static void transfer_file_data(struct connection *conn) {
  char buf[IOBUF_SIZE];
  int n = read(conn->endpoint.fd, buf, conn->cl < (int64_t) sizeof(buf) ?
               (int) conn->cl : (int) sizeof(buf));

and I found the "conn->cl" is a very big or a  negative number,

**Comment by cpq** [comment]
Closing this - fixed in subsequent commits.
Pls reopen if still an issue.
