### ISSUE TITLE
cppcheck 1.65 warnings

### ISSUE THREAD

**Issue by pavel-pimenov** [cesanta/mongoose#375]
http://cppcheck.sourceforge.net/
![cppcheck-165-mongoose](https://cloud.githubusercontent.com/assets/920705/2967654/3b3dfdd6-db33-11e3-921f-efab196a7b9c.png)

**Comment by cpq** [comment]
У меня warning не показываются, только стиль и portability

**Comment by Vadius** [comment]
Добрый.
У меня чек немножко таки ругается:
$ cppcheck --version
Cppcheck 1.61

$ cppcheck ./mongoose.c --force --enable=all
Checking mongoose.c...
...
[mongoose.c:4178]: (warning) scanf without field width limits can crash with huge input data.
[mongoose.c:4279]: (warning) scanf without field width limits can crash with huge input data.
[mongoose.c:4283]: (warning) scanf without field width limits can crash with huge input data.
[mongoose.c:4287]: (warning) scanf without field width limits can crash with huge input data.
[mongoose.c:4288]: (warning) scanf without field width limits can crash with huge input data.
[mongoose.c:4321]: (warning) scanf without field width limits can crash with huge input data.
...
Checking mongoose.c: _MSC_VER;_WIN32...
...
[mongoose.c:3535] -> [mongoose.c:3459]: (error) Mismatching allocation and deallocation: dir
[mongoose.c:3760] -> [mongoose.c:3459]: (error) Mismatching allocation and deallocation: dir

**Comment by Vadius** [comment]
Да, со scanf согласен, переполнения не будет.
Про каталоги под виндой оценить не могу, к сожалению, не знаток WinAPI

**Comment by pavel-pimenov** [comment]
Возможно это ложный детект (про эту ошибку cppcheck в GUI пишет пример - он ниже)
думаю тут ему не понравилось %s без лимита для ha1
и он не увидел что размер самого line = 256 и ha1 с таким-же размер просто не может переполниться - т.к. для него места зарезервировано даже в избытке.

char line[256], f_user[256], ha1[256], f_domain[256], user[100], nonce[100],
       uri[MAX_REQUEST_SIZE], cnonce[100], resp[100], qop[100], nc[100];

Кратко: scanf without field width limits can crash with huge input data.
Сообщение: scanf without field width limits can crash with huge input data. Add a field width specifier to fix this problem:
    %s => %20s

Sample program that can crash:

#include <stdio.h>
int main()
{
    char c[5];
    scanf("%s", c);
    return 0;
}

Typing in 5 or more characters may make the program crash. The correct usage here is 'scanf("%4s", c);', as the maximum field width does not include the terminating null byte.
Source: http://linux.die.net/man/3/scanf
Source: http://www.opensource.apple.com/source/xnu/xnu-1456.1.26/libkern/stdio/scanf.c

**Comment by cpq** [comment]
Ох уж этот cppcheck.
Я проверил warnings:

```
[~/dev/mongoose]$ cppcheck --version
Cppcheck 1.68
[~/dev/mongoose]$ cppcheck mongoose.c --force --enable=warning
Checking mongoose.c...
[mongoose.c:4283]: (warning) scanf without field width limits can crash with huge input data.
[mongoose.c:4287]: (warning) scanf without field width limits can crash with huge input data.
[mongoose.c:4291]: (warning) scanf without field width limits can crash with huge input data.
[mongoose.c:4292]: (warning) scanf without field width limits can crash with huge input data.
[mongoose.c:4325]: (warning) scanf without field width limits can crash with huge input data.
[mongoose.c:5086]: (warning) Comparison of identical string variables.
Checking mongoose.c: MONGOOSE_NO_FILESYSTEM...
Checking mongoose.c: MONGOOSE_NO_MMAP...
Checking mongoose.c: MONGOOSE_NO_POPEN...
Checking mongoose.c: MONGOOSE_NO_WEBSOCKET...
Checking mongoose.c: MONGOOSE_SEND_NS_EVENTS...
Checking mongoose.c: NOEMBED_NET_SKELETON...
Checking mongoose.c: NS_DISABLE_SOCKETPAIR...
Checking mongoose.c: NS_ENABLE_DEBUG...
[mongoose.c:558]: (warning) %d in format string (no. 2) requires 'int' but the argument type is 'unsigned int'.
[mongoose.c:991]: (warning) %d in format string (no. 2) requires 'int' but the argument type is 'unsigned int'.
[mongoose.c:1023]: (warning) %d in format string (no. 2) requires 'int' but the argument type is 'unsigned int'.
[mongoose.c:1058]: (warning) %d in format string (no. 2) requires 'int' but the argument type is 'ssize_t {aka long}'.
[mongoose.c:4725]: (warning) %d in format string (no. 2) requires 'int' but the argument type is 'ssize_t {aka long}'.
[mongoose.c:4748]: (warning) %d in format string (no. 2) requires 'int' but the argument type is 'ssize_t {aka long}'.
[mongoose.c:4748]: (warning) %d in format string (no. 4) requires 'int' but the argument type is 'unsigned int'.
[mongoose.c:4810]: (warning) %d in format string (no. 2) requires 'int' but the argument type is 'ssize_t {aka long}'.
[mongoose.c:4891]: (warning) %d in format string (no. 4) requires 'int' but the argument type is 'unsigned int'.
Checking mongoose.c: NS_ENABLE_GETADDRINFO...
[mongoose.c:642]: (warning) Size of pointer 'ina' used instead of size of its data.
Checking mongoose.c: NS_ENABLE_IPV6...
Checking mongoose.c: NS_ENABLE_SSL...
Checking mongoose.c: NS_ENABLE_SSL;__APPLE__...
Checking mongoose.c: NS_STACK_SIZE...
Checking mongoose.c: _MSC_VER...
Checking mongoose.c: _MSC_VER;_WIN32...
[mongoose.c:454]: (error) va_list 'ap_copy' used before va_start() was called.
[mongoose.c:455]: (error) va_list 'ap_copy' used before va_start() was called.
[mongoose.c:456]: (error) va_list 'ap_copy' used before va_start() was called.
[mongoose.c:467]: (error) va_list 'ap_copy' used before va_start() was called.
[mongoose.c:468]: (error) va_list 'ap_copy' used before va_start() was called.
[mongoose.c:469]: (error) va_list 'ap_copy' used before va_start() was called.
[mongoose.c:476]: (error) va_list 'ap_copy' used before va_start() was called.
[mongoose.c:477]: (error) va_list 'ap_copy' used before va_start() was called.
[mongoose.c:478]: (error) va_list 'ap_copy' used before va_start() was called.
Checking mongoose.c: _WIN32...
Checking mongoose.c: __Linux__...
Checking mongoose.c: __OS2__...
Checking mongoose.c: __cplusplus...
Checking mongoose.c: __sun...
```

False positives. 
Закрываю issue.
Спасибо Паша
