### ISSUE TITLE
Large file uploads exit with error code 400

### ISSUE THREAD

**Issue by marcelwirtz** [cesanta/mongoose#379]
I used the upload.c example (https://github.com/cesanta/mongoose/blob/master/examples/upload.c) and a normal Browser (FireFox, Chrome, IE)  to test it and for files smaller than 530 MB this works fine. With larger files, it uploads the file and response with a "400 Bad request" error.

I debuged this and found that after the upload the conn->content_len is set to -1 in mongoose.c line 2086 because re->request_method is filled with something like "------WebKitFormBoundarybZokRVDBKdAGemWa\r\nContent-Disposition:" or "------------------------bZokRVDBKdAGemWa\r\nContent-Disposition:" so there is no valid http method given and not "HTTP/".

**Comment by cpq** [comment]
Hi Max, please try to reproduce this & fix.

**Comment by gelraen** [comment]
Tried this on my Win 7 machine & MSVC6: after 9.5h of uploading a single 570M file Chrome said "No data received". @pyr0t0n, how long did it took for you to upload 530M+ files?

**Comment by gelraen** [comment]
@pyr0t0n, also, which compiler do you use? (and what flags, if any?)

**Comment by pyr0t0n** [comment]
Compiler is MinGW 4.8.2 32Bit without any flags. How long it took exactly i don't know anymore but not longer than 10 minutes.

**Comment by gelraen** [comment]
Thanks for the info, will try MinGW this evening.

**Comment by gelraen** [comment]
I can't reproduce it on my machine with MinGW or different gcc versions in Cygwin :( @pyr0t0n can you try more recent https://github.com/cesanta/mongoose/blob/master/examples/file_upload/file_upload.c to see if the problem is still there?

**Comment by rojer** [comment]
large file upload has been completely rewritten in 6.4.
please see [this blog post](https://blog.cesanta.com/big-upload-example-mongoose-more-than-an-embedded-web-server).
