### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by saketsurya** [cesanta/mongoose#394]
I have downloaded mongoose source from github repository. I am trying to enable ssl on mongoose which I am using on centos.I have set following options:

mg_set_option(mServer, "document_root", ".");
mg_set_option(mServer, "listening_port", "8080s");
mg_set_option(mServer, "ssl_certificate", "ssl_cert.pem");

http://192.168.0.151:8080 works fine but when I try reaching https://192.168.0.151:8080, I get following error:
"Unable to make a secure connection to the server. This may be a problem with the server or it may be requiring a client authentication certificate that you don't have.
Error code: ERR_SSL_PROTOCOL_ERROR"

I tried setting 
mg_set_option(mServer, "listening_port", "8080r,443s");
When I try to reach https://192.168.0.151:8080 or https://192.168.0.151:8080,I get following error:
"This web page is not available"
Trying to reach the same from curl gives connection refused error.http://192.168.0.151:8080 works fine 

Please help. What wrong I am doing?

Also, I am using ssl_cert.pem file from this link: https://github.com/cesanta/mongoose/blob/master/examples/ssl_cert.pem

**Comment by cpq** [comment]
Closing this, please reopen if still an issue.
