### ISSUE TITLE
Digest Authentication problem

### ISSUE THREAD

**Issue by PaulMaillet** [cesanta/mongoose#401]
Hi all,

I am running MONGOOSE_VERSION "5.3" and I managed to set the digest authentication on the server.

It is working great with Google Chrome (Version 36.0.1985.125 m).

But with IE (v11.0.9600.17126) I can see the authentication popup once when trying to connect to the server. But after entering the login password correctly, nothing happens, IE is waiting, but nothing is send to the server. I have seen using wireshark that only the GET request is sent, then answered by the 401 Unauthorized and thats all, IE does not try to connect again with the provided login information.

It is the same for Mozilla Firefox.

I generated the htpasswd file  with mongoose -A mydomain.com root password.

What I cannot understand is that it works great with Chrome. Is there something i am missing,?

**Comment by cpq** [comment]
Hi Paul, I am closing this. Please reopen if there is still an issue.
