### ISSUE TITLE
mg_wakup_server_ex() callback not getting called

### ISSUE THREAD

**Issue by bjswati** [cesanta/mongoose#404]
Hi,
I am using mg_wakup_server_ex()  and this has a corresponding callback.
this is working fine for certain cases. But under some situation the callback never gets called.
Also I observed that the websocket connection is getting closed without sending a MG_CLOSE event.
Could you specify , if the connection close is the reason for callback not getting called ? If yes, then Why isnt MG_CLOSE event not triggered? If No, what could be the other probable reason for mg_wakup_server_ex() callback not getting called.

To Be specific,
the recv() that is called from ns_server_wakeup_ex () is not returning. and blocked.
Could you please help ?
Your inputs are highly valued.

**Comment by cpq** [comment]
No feedback - closing this
