### ISSUE TITLE
 GET http://127.0.0.1:8080/packed_build/ammo.asm.js net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by makc** [cesanta/mongoose#438]
Chrome randomly does this, on Mac OS.

Response headers report correct length
```
HTTP/1.1 200 OK
Date: Sun, 16 Nov 2014 20:08:31 GMT
Last-Modified: Sun, 09 Nov 2014 03:57:13 GMT
Etag: "545ee619.3800928"
Content-Type: application/x-javascript
Content-Length: 3800928
Connection: close
Accept-Ranges: bytes
```
but for some reason it terminates after 2.3 MB:
![screen shot 2014-11-16 at 21 48 48](https://cloud.githubusercontent.com/assets/242577/5063152/007249c4-6ddb-11e4-9984-3e30dca2dc18.png)

I don't have any means to reproduce it, except random encounter. Posting just so you keep your eye on it.

**Comment by cpq** [comment]
Can't reproduce this.
Is it still happening? What is the setup?

**Comment by makc** [comment]
I don't use mongoose with that project any more, their node-based server now handles everything itself. And, in fact, 

> doesn't change during download

it might have been actually copied over by the script that was triggered by html request from node server.

**Comment by f00bard** [comment]
I'm seeing this behavior running the "simplest_web_server" example under Cygwin.  Pulled the latest from master and compiled.  This is with Chrome on Windows 7 x64.

![snip1](https://cloud.githubusercontent.com/assets/382860/12493885/601491c0-c055-11e5-85f4-62e45915f307.PNG)

![snip2](https://cloud.githubusercontent.com/assets/382860/12493887/64ad8ad4-c055-11e5-9a4b-7d8a632f412f.PNG)

Adding some additional debug out put I can see that when send() returns -1 errno is set to EAGAIN.

**Comment by cpq** [comment]
Rojer,
could you take a look at this please?

Premature connection drop on Windows, when send() returns -1 & errno set to
EAGAIN.
Is there any way to simulate that in unit test?

On 21 January 2016 at 20:43, Mack Hooper <notifications@github.com> wrote:

> I'm seeing this behavior running the "simplest_web_server" example under
> Cygwin. Pulled the latest from master and compiled. This is with Chrome on
> Windows 7 x64.
>
> [image: snip1]
> <https://cloud.githubusercontent.com/assets/382860/12493885/601491c0-c055-11e5-85f4-62e45915f307.PNG>
>
> [image: snip2]
> <https://cloud.githubusercontent.com/assets/382860/12493887/64ad8ad4-c055-11e5-9a4b-7d8a632f412f.PNG>
>
> Adding some additional debug out put I can see that when send() returns -1
> errno is set to EAGAIN.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cesanta/mongoose/issues/438#issuecomment-173702225>.
>



-- 
Sergey Lyubka        Founder, CTO                          Cesanta Software
www.cesanta.com   sergey.lyubka@cesanta.com   +353 86 043 45 19

**Comment by cpq** [comment]
hm. i wonder if the right thing to do would be to treat EAGAIN the same way
as EWOULDBLOCK, wdyt?

On Sat, Jan 23, 2016 at 12:13 AM Sergey Lyubka <sergey.lyubka@cesanta.com>
wrote:

> Rojer,
> could you take a look at this please?
>
> Premature connection drop on Windows, when send() returns -1 & errno set
> to EAGAIN.
> Is there any way to simulate that in unit test?
>
> On 21 January 2016 at 20:43, Mack Hooper <notifications@github.com> wrote:
>
>> I'm seeing this behavior running the "simplest_web_server" example under
>> Cygwin. Pulled the latest from master and compiled. This is with Chrome on
>> Windows 7 x64.
>>
>> [image: snip1]
>> <https://cloud.githubusercontent.com/assets/382860/12493885/601491c0-c055-11e5-85f4-62e45915f307.PNG>
>>
>> [image: snip2]
>> <https://cloud.githubusercontent.com/assets/382860/12493887/64ad8ad4-c055-11e5-9a4b-7d8a632f412f.PNG>
>>
>> Adding some additional debug out put I can see that when send() returns
>> -1 errno is set to EAGAIN.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cesanta/mongoose/issues/438#issuecomment-173702225>.
>>
>
>
>
> --
> Sergey Lyubka        Founder, CTO                          Cesanta Software
> www.cesanta.com   sergey.lyubka@cesanta.com   +353 86 043 45 19
>
-- 
Deomid "rojer" Ryabkov,
Software Engineer
Cesanta Software Ltd.

**Comment by cpq** [comment]
well, that's a silly question, because EWOULDBLOCK is defined as EAGAIN on
most platforms, including Cygwin, as far as i can tell.

On Sun, Jan 24, 2016 at 2:17 AM Deomid Ryabkov <rojer@cesanta.com> wrote:

> hm. i wonder if the right thing to do would be to treat EAGAIN the same
> way as EWOULDBLOCK, wdyt?
>
> On Sat, Jan 23, 2016 at 12:13 AM Sergey Lyubka <sergey.lyubka@cesanta.com>
> wrote:
>
>> Rojer,
>> could you take a look at this please?
>>
>> Premature connection drop on Windows, when send() returns -1 & errno set
>> to EAGAIN.
>> Is there any way to simulate that in unit test?
>>
>> On 21 January 2016 at 20:43, Mack Hooper <notifications@github.com>
>> wrote:
>>
>>> I'm seeing this behavior running the "simplest_web_server" example under
>>> Cygwin. Pulled the latest from master and compiled. This is with Chrome on
>>> Windows 7 x64.
>>>
>>> [image: snip1]
>>> <https://cloud.githubusercontent.com/assets/382860/12493885/601491c0-c055-11e5-85f4-62e45915f307.PNG>
>>>
>>> [image: snip2]
>>> <https://cloud.githubusercontent.com/assets/382860/12493887/64ad8ad4-c055-11e5-9a4b-7d8a632f412f.PNG>
>>>
>>> Adding some additional debug out put I can see that when send() returns
>>> -1 errno is set to EAGAIN.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/cesanta/mongoose/issues/438#issuecomment-173702225>.
>>>
>>
>>
>>
>> --
>> Sergey Lyubka        Founder, CTO                          Cesanta
>> Software
>> www.cesanta.com   sergey.lyubka@cesanta.com   +353 86 043 45 19
>>
> --
> Deomid "rojer" Ryabkov,
> Software Engineer
> Cesanta Software Ltd.
>
-- 
Deomid "rojer" Ryabkov,
Software Engineer
Cesanta Software Ltd.

**Comment by rojer** [comment]
this is ancient, transition to 6.0 changed all the relevant code. EAGAIN is the same as EWOULDBLOCK (including cygwin, as near as i can tell), so we should be handling that correctly.
