### ISSUE TITLE
Embedding V5.5 on ecos

### ISSUE THREAD

**Issue by PaulMaillet** [cesanta/mongoose#445]
Hi,

I'm trying to port the V5.5 on my system but I am encountering some problem with it.

I started with the basic HelloWorld example.

The server starts correctly, it catches the client GET request and fill the conn iosendbuf with the answer but it is never send the answer (ns_write_to_socket(conn); never reached)

My select function is not blocking, even if I give a timeout > 0, so i am calling it in loop like this :
```
  AG_BOOL bTimedOut = AG_FALSE;
  int	  select_return = 0;
  AG_UINT32 u32StartTime = ag_GetTimeMs();
  AG_UINT32 u32CurrentTime = u32StartTime;
  AG_UINT32 u32ElapsedTime = 0;

  while(!bTimedOut)
  {
	  select_return = t_select(&read_set, &write_set, NULL, 0);
	  if( select_return )
	  {
		  /* Break the loop */
		  bTimedOut = AG_TRUE;
	  }
	  else
	  {
		  u32CurrentTime = ag_GetTimeMs();
		  u32ElapsedTime = u32CurrentTime - u32StartTime;
		  if( u32ElapsedTime > milli)
		  {
			  /* break the loop */
			  bTimedOut = AG_TRUE;

		  }
		  else
		  {
			  /* timeout not reached, wait 100ms */
			  ag_Waitms(1);
		  }
	  }
  }
  if (select_return > 0 ) {
```

Here is the wireshark cap of the flow:
![mongoosegethelloworldcap](https://cloud.githubusercontent.com/assets/6582507/5412594/4e76f876-820e-11e4-83c1-ab6f1d40b99d.png)

Regards

**Comment by cpq** [comment]
Closing this - Paul please reopen if this is still an issue.
