### ISSUE TITLE
bug: big_upload example: MG_CLOSE never received

### ISSUE THREAD

**Issue by MathJud** [cesanta/mongoose#446]
The example big_upload does not work as expected.
The event MG_CLOSE is not received after file upload finishes.
The event MG_CLOSE is only received when the uploaders browser cancels the request.

**Comment by spuschhof** [comment]
Same/related problem here. My environment is:
Windows 7
Mongoose 5.5
MinGW 4.8.2
Connection is made on localhost

A MG_CLOSE event is received when the request handler returns with MG_MORE (like in big_upload), but not when MG_TRUE is returned (e.g. like in hello-world).

**Comment by spuschhof** [comment]
Found my problem. MG_CLOSE is only send when the socket connection is closed, not when the request is finished. As my tes clients use pipelining, the socket is only closed some time after the request has been handled.

**Comment by cpq** [comment]
Correct. MG_CLOSE is sent when TCP connection is closed.
