### ISSUE TITLE
high CPU on raspberry pi 

### ISSUE THREAD

**Issue by fuchsc** [cesanta/mongoose#453]
Hi,

I embedded mongoose 5.2 into my raspberry pi application and it basically works perfect.
Unfortunately it consumes high CPU.
I found out, that the select syscall in mg_poll_server call never blocks for the defined timeout (1000 ms) even if no traffic at all is going on because server->ctl[1] always seems to receive data.
Is there anything I have to configure when running mongoose on raspberry?

thx,
Clemens

**Comment by cpq** [comment]
Thanks.
What is the value of `server->ctl[1]` ?

Tip: you can add `-DNS_DISABLE_SOCKETPAIR` to your compile flags to disable socket pair. That will also make `mg_wakeup_server()` function.

**Comment by cpq** [comment]
Hi @fuchsc , any update on this issue?

**Comment by cpq** [comment]
No feedback, closing this.
Please reopen if still an issue.
