### ISSUE TITLE
http_client example with multiple requests not working

### ISSUE THREAD

**Issue by nrj** [cesanta/mongoose#455]
Hello,

I'm trying to work with the http_client example and having some trouble. For a simple test I've setup the `s_remote_addr = "www.linux.org:80"` and the `Host` parameter to `"/"`. After I compile and run it I see the HTML of linux.org returned as text in my browser as expected. However all subsequent requests simply hang and never finish. The problem seems to somehow be related to the `Connection` header. If I add this line:

          mg_send_header(orig, "Connection", "Close");

before sending the response the example works as expected and I can issue request after request and they all work. However I don't think this is the *right* way to fix the problem, I would prefer to keep the connection alive. I'm sure that I'm doing something else wrong but I'm just not sure what. Any ideas?

**Comment by cpq** [comment]
I suggest using Fossa, for it's HTTP support for keep-alive is cleaner then mongoose's.
Look at https://github.com/cesanta/fossa/blob/master/examples/restful_client/restful_client.c

**Comment by cpq** [comment]
Closing this.
