### ISSUE TITLE
On Linux, how To Create A PHP Website With Mongoose

### ISSUE THREAD

**Issue by TankAbraham** [cesanta/mongoose#458]
hi sir!
I am a senior in university. My graduation project is a web server on Linux.
I`m finding some example to study and I fund Mongoose.  
so, my question is there: On Linux, how To Create A PHP Website With Mongoose?

**Comment by cpq** [comment]
Download PHP bundle from http://cesanta.com/mongoose.shtml

**Comment by vijayant123** [comment]
Hi everyone,

The link is dead. Could someone please update it.

Thanks,
Vijayant

**Comment by cpq** [comment]
Updated

**Comment by kafene** [comment]
Looks like it moved again to https://cesanta.com/binary.html

However I'm not seeing Linux downloads.

Also just to clarify does the PHP dev bundle edition come with lifetime updates as the pro edition does?
