### ISSUE TITLE
Faulty implementation of mg_strdup

### ISSUE THREAD

**Issue by CurlyMoo** [cesanta/mongoose#460]
I'm currently investigating the function `mg_strdup`. 
```
static char *mg_strdup(const char *str) {
  char *copy = (char *) NS_MALLOC(strlen(str) + 1);
  if (copy != NULL) {
    strcpy(copy, str);
  }
  return copy;
}
```

You try to allocate memory in `char *copy`, but when it fails, you still return a NULL pointer. When i look at the various places you call the `mg_strdup` i don't see proper handling of the NULL pointer:

```
  *v = mg_strdup(value);
  DBG(("%s [%s]", name, *v));

  if (ind == LISTENING_PORT) {
    struct vec vec;
    while ((value = next_option(value, &vec, NULL)) != NULL) {
      struct ns_connection *c = ns_bind(&server->ns_mgr, vec.ptr,
                                        mg_ev_handler, NULL);
      if (c== NULL) {
        error_msg = "Cannot bind to port";
        break;
      } else {
        char buf[100];
        ns_sock_to_str(c->sock, buf, sizeof(buf), 2);
        NS_FREE(*v);
```
https://github.com/cesanta/mongoose/blob/master/mongoose.c#L5034-L5049

There could be some logic inside `NS_FREE` and `NS_MALLOC` but in a default embedded usage of the library they just wrap regular `free` and `malloc` calls. So no safegaurd exists to check for possibly freed NULLs returned from `mg_strdup`.

The same issue also applies on this line of code, where you directly call `strdup`, but also don't check for possible NULL pointer.
```
 (*arr)[arr_ind].file_name = strdup(dp->d_name);
```
https://github.com/cesanta/mongoose/blob/master/mongoose.c#L3412

========

And the same thing applies to your `NS_MALLOCs`:
```
 conn->request = (char *) NS_MALLOC(conn->request_len);
 memcpy(conn->request, io->buf, conn->request_len);
```
https://github.com/cesanta/mongoose/blob/master/mongoose.c#L4584-L4585

**Comment by cpq** [comment]
In places where mg_strdup is called, it is safe to keep NULL result.
