### ISSUE TITLE
Linking problems when MONGOOSE_NO_THREADS defined.

### ISSUE THREAD

**Issue by leg0** [cesanta/mongoose#468]
When building with MONGOOSE_NO_THREADS defined, linking fails with this error:

    mongoose.obj : error LNK2019: unresolved external symbol _mg_start_thread referenced in function _spawn_stdio_thread

Building with VS2013 update 4.

**Comment by cpq** [comment]
Pushed https://github.com/cesanta/mongoose/commit/4502dd0c86973aa8d6e3d650736209a0be585485

**Comment by AMDG2** [comment]
I would not go that way for correcting this error. 
Perhaps the [`spawn_stdio_thread`](https://github.com/cesanta/mongoose/blob/master/mongoose.c#L2010) should be disabled by MONGOOSE_NO_THREADS definition.
