### ISSUE TITLE
The conn->content is not end with 0

### ISSUE THREAD

**Issue by ListerTheTormentor** [cesanta/mongoose#469]
In request process, the conn->content is not end with 0, some function can't process it directly. such as printf. May you please add a 0 at the end of the content?

**Comment by leg0** [comment]
printf can easily handle non-zero terminated strings. You can write the content with printf like this:

     printf("%.*s", conn->content_len, conn->content);

**Comment by ListerTheTormentor** [comment]
I see, thanks.
