### ISSUE TITLE
mg_send_data(conn, nullptr, 0) causes HTTP violation

### ISSUE THREAD

**Issue by Vadius** [cesanta/mongoose#479]
Hi

I tried to workaround #477 trouble with:

	mg_send_data(conn, nullptr, 0)

But in this case mongoose sends chunk with len = 0 so remote side stops receiving response. But I can still continue sending chunks and even more, mongoose will add zero-len chunk by itself on end of request processing.

I think zero-len chunks should be skipped by mongoose to prevent protocol rules violation.

**Comment by cpq** [comment]
I've followed up on #477, please verify.
