### ISSUE TITLE
Is is possible to use path variables? (dynamic uri)

### ISSUE THREAD

**Issue by junyoungkim** [cesanta/mongoose#487]
Hi, 

As I mentioned already in the title, I need to use path variables to assign variable in dynamic.

The path variable is quite useful when we're implementing rest apps.

For example, when we want search an user info who has an unique id is 1.

We can view a info from '/customer/user/1' as a GET.

Is there any easy ways to use it ?

**Comment by cpq** [comment]
Could you elaborate on it please?
Maybe a real-life request/response example?

**Comment by cpq** [comment]
No reply - closing this.
