### ISSUE TITLE
Failed to upload multiple files with HTML form

### ISSUE THREAD

**Issue by hua-su** [cesanta/mongoose#496]
There is a bug in examples/file_upload/file_upload.c. It will failed to read multiple files.

One may consider examples/file_upload/file_upload.c as the standard usage of mongoose, and get frustrated after fail to parse multiple uploaded files.

To fix the bug, the original code in file_upload.c:

![image](https://cloud.githubusercontent.com/assets/7020530/6768669/cfebe3fe-d0b4-11e4-8ff9-2c71e1c7a1d9.png)

shoud be changed to:

![image](https://cloud.githubusercontent.com/assets/7020530/6768666/b1f7bce2-d0b4-11e4-979c-1520900c945a.png)

**Comment by cpq** [comment]
Thanks.
Mind sending a PR ?

**Comment by hua-su** [comment]
I'm sorry, I'm not a git user. Could you kindly make a PR for this issue?

**Comment by cpq** [comment]
I've just made a change to upload multiple files, https://github.com/cesanta/mongoose/commit/4cbd113d0117364e8cd1e5a0334a93f6ef21406a

It works as expected without your patch. Am I missing something?
