### ISSUE TITLE
Document_root parameter cannot be changed - v.5.6

### ISSUE THREAD

**Issue by fabiopagoti** [cesanta/mongoose#499]
I have just installed Mongoose v5.6 and when I try to change the path of document_root parameter, it doesn't work. Intead of allowing me to change the field the value is changed back to the default one (user's desktop as my exe is inside it).

Windows 8
Mongoose Free Edition

**Comment by cpq** [comment]
Will fix that, thanks for reporting.
In the mean time, please use context menu option "Set shared directory"

**Comment by cpq** [comment]
Also, `mongoose.conf` file can be edited by hands - just open it in the editor, change, save, restart mongoose.

**Comment by fabiopagoti** [comment]
Thanks! What I've done instead was changing exe location.

**Comment by rojer** [comment]
please reopen if this still applies to 6.4 and up.
