### ISSUE TITLE
Mongoose can't listen on port 80?

### ISSUE THREAD

**Issue by tfarina** [cesanta/mongoose#511]
I killed anything listening on port 80 with:

$ sudo fuser -k 80/tcp

Then checked with:
$ sudo netstat -tulpn | grep :80

The tried to start mongoose on port 80:
$ ./mongoose -listening_port 80
Failed to set option [listening_port] to [80]: Cannot bind to port
...

**Comment by cpq** [comment]
binding to port 80 needs root.

**Comment by tfarina** [comment]
That is it! Now it works when I run `sudo ./mongoose -listening_port 80`.

Thanks a lot for the tip Sergey!
