### ISSUE TITLE
WebDAV useless

### ISSUE THREAD

**Issue by javalama** [cesanta/mongoose#512]
WebDAV needs LOCK/UNLOCK support to be useful from most program, like office, OS X finder, etc.

Otherwise you'll end up with a file on the server on each save.

Who can I pay to get this implemented ASAP? :D

**Comment by cpq** [comment]
LOCK/UNLOCK was not implemented because of the complexity some native clients have (mac finder, windows explorer, etc).
But to answer a question about the implementation - sure, please send a message to support@cesanta.com with your requirements.

**Comment by javalama** [comment]
Well, the requirements is simply to make clients work, including mac finder. I have no idea what that entails.

**Comment by cpq** [comment]
Understood. Please send a list of the clients that are required to work to support@cesanta.com
