### ISSUE TITLE
Add server option to allow CORS

### ISSUE THREAD

**Issue by ListerTheTormentor** [cesanta/mongoose#516]
Can't config the server to allow CORS, The server need config options to allow the header include Access-Control-Allow-Origin and Access-Control-Allow-Credentials.

**Comment by cpq** [comment]
I think a generic option like "extra_headers" would do the job.

**Comment by cpq** [comment]
Pushed  https://github.com/cesanta/mongoose/commit/0c95290f932c33dad3c778c24a9428134ae90b8a
