### ISSUE TITLE
[Enhancement] uPnP broadcast request/respond handler

### ISSUE THREAD

**Issue by ghost** [cesanta/mongoose#527]
It would be very useful for IoT devices if a simple uPnP request/respond handler is added to the mongoose web server as an option. A list of services can be read by mongoose from an XML file and can be serviced to the broadcasters.

**Comment by younes424** [comment]
Any suggestions on how to achieve this?

**Comment by cpq** [comment]
Closing this.
There are no plans to support uPnP at this moment.
