### ISSUE TITLE
Configurable BUF size patch required!!

### ISSUE THREAD

**Issue by ywhwang** [cesanta/mongoose#532]
HERE is my patch..
////////////////////////////////////////
#ifndef NS_UDP_RECEIVE_BUFFER_SIZE
#warning "Default NS/MG CONTANT USED!!"
#define MG_WEBSOCKET_BUFFER_SIZE 4192
#define NS_CTL_MSG_MESSAGE_SIZE     (8 * 1024)
#define NS_READ_BUFFER_SIZE         2048
#define NS_UDP_RECEIVE_BUFFER_SIZE  2000
#define NS_VPRINTF_BUFFER_SIZE      500
#else
#warning "UserDefined NS/MG CONTANT USED!!"
#endif
//////////////////////////////
size_t mg_websocket_write(struct mg_connection *conn, int opcode,
                          const char *data, size_t data_len) {
    unsigned char mem[MG_WEBSOCKET_BUFFER_SIZE], *copy = mem;
/////////////////////////////
size_t mg_websocket_printf(struct mg_connection *conn, int opcode,
                           const char *fmt, ...) {
  char mem[MG_WEBSOCKET_BUFFER_SIZE], *buf = mem;

/////////////////////////////////////
#if USE_BIG_BUF_FEATURE
#define MAX_REQUEST_SIZE 131036
#define IOBUF_SIZE  131036
#else
#define MAX_REQUEST_SIZE 16384
#define IOBUF_SIZE 8192
#endif

**Comment by alashkin** [comment]
Sorry, but we accept patches as a PRs only, also you have to agree with https://github.com/cesanta/mongoose#contributions
