### ISSUE TITLE
mg_wakeup_server async broadcast support for prevent deadlock.

### ISSUE THREAD

**Issue by ywhwang** [cesanta/mongoose#535]
Here's my patch

///////////////////////////
void ns_broadcast_new(struct ns_mgr *mgr, ns_callback_t cb,void *data, size_t len) 
{
  struct ctl_msg ctl_msg;
  if (mgr->ctl[0] != INVALID_SOCKET && data != NULL &&
      len < sizeof(ctl_msg.message)) {
    ctl_msg.callback = cb;
    memcpy(ctl_msg.message, data, len);
    send(mgr->ctl[0], (char *) &ctl_msg,
         offsetof(struct ctl_msg, message) + len, 0);
    // recv(mgr->ctl[0], (char *) &len, 1, 0); //UNI-direction patch	
  }
}
/*static*/ void iter_new(struct ns_connection *nc, int ev, void *param) 
{
  const char *msg = (const char *) param;
  mg_handler_t func = NULL;
  if(ev==NS_CLOSE){// nc is ns_mgr!!
	  // printf("send MG_CLOSE for END-of-IPC\n");
  	if(sscanf(msg, "UNI %p ", &func)  && func != NULL && nc != NULL) {
	    func((struct mg_connection*)nc, MG_CLOSE);// indicate END-of-IPC
  	}
  }
  else if(ev==NS_POLL){
	  struct connection *conn = (struct connection *) nc->user_data;
	  int n;
	  (void) ev;

		struct mg_connection *c=NS_CONN_2_MG_CONN(nc);
		
	  if (c && sscanf(msg, "UNI %p %n", &func, &n) && func != NULL && conn != NULL) { //UNI-direction patch	
	    conn->mg_conn.callback_param = (void *) (msg + n);
	    func(&conn->mg_conn, MG_POLL);
	  }
  }
  else{
	  printf("iter-new unknown%d\n",ev);
    }
}
void mg_wakeup_server_new(struct mg_server *server, mg_handler_t cb,const char *fmt, ...) 
{
  va_list ap;
  char buf[NS_CTL_MSG_MESSAGE_SIZE];
  int len,len1;

  // printf("mg_wakeup_server_new: sizeof buf=%d\n",sizeof(buf));
  // Encode callback (cb) into a buffer
  len = snprintf(buf, sizeof(buf), "UNI %p ", cb); //UNI-direction patch	
  va_start(ap, fmt);
  len += (len1=vsnprintf(buf + len, sizeof(buf) - len, fmt, ap));
  va_end(ap);

  // printf("mg_wakeup_server_new: ctl size=%d,len1=%d\n",len + 1,len1);
  if(len1<0)return;
  // "len + 1" is to include terminating \0 in the message
  ns_broadcast_new(&server->ns_mgr, iter_new, buf, len + 1);
}
/////////////////////////////////////// in ns_mgr_poll
    // Read wakeup messages
    if (mgr->ctl[1] != INVALID_SOCKET &&
        FD_ISSET(mgr->ctl[1], &read_set)) {
      struct ctl_msg ctl_msg;
      int len = (int) recv(mgr->ctl[1], (char *) &ctl_msg, sizeof(ctl_msg), 0);
#if 1 //UNI-direction patch// for deadlock avoid!!	  
     if(memcmp(ctl_msg.message,"UNI ",4)!=0)
#endif	  	
      send(mgr->ctl[1], ctl_msg.message, 1, 0);
      if (len >= (int) sizeof(ctl_msg.callback) && ctl_msg.callback != NULL) {
        struct ns_connection *c;
        for (c = ns_next(mgr, NULL); c != NULL; c = ns_next(mgr, c)) {
          ctl_msg.callback(c, NS_POLL, ctl_msg.message);
        }
      }
#if 1 //UNI-direction patch// for End-callback	  
     if(memcmp(ctl_msg.message,"UNI ",4)==0)
	 ctl_msg.callback((struct ns_connection *)mgr, NS_CLOSE, ctl_msg.message);
#endif	  	
    }

**Comment by alashkin** [comment]
`mg_wakeup_server` does not longer exist, closing bug
