### ISSUE TITLE
Safari and Firefox wait about 5 minutes for the 302 response in example "cookie_authentication"

### ISSUE THREAD

**Issue by freeX1n** [cesanta/mongoose#539]
In example "cookie_authentication", when you use Safari and Firefox to post the login request, they will wait for the 302 response about 5 minutes (which I guess is the timeout time).
I used Charles to check the details and found out that in the post request status it said "Received response header. Waiting for response body…". But there is no body in the 302 response as far as I know. So I don't know why they want to wait for the "body". 

![1](https://cloud.githubusercontent.com/assets/5955409/7932709/d2f0d94e-094c-11e5-87c6-f86276240a78.png)

![2](https://cloud.githubusercontent.com/assets/5955409/7932728/f3699012-094c-11e5-94af-762c5abea725.png)

Chrome is totally ok with this. :(

I try to solve this problem and add a "fake body" like this:

mg_printf(conn,
                  "HTTP/1.1 302 Moved\r\n"
                  "Set-Cookie: ssid=%s; expire=\"%s\"; http-only; HttpOnly;\r\n"
                  "Location: /index.html\r\n\r\n"
                  "fake body",
                  ssid, expire);

To my surprise it works! 
I think this may be a bug. Looking forward to your reply：）

**Comment by cpq** [comment]
Fixed, https://github.com/cesanta/mongoose/commit/564683d25a6601087e8e936acfef240996425441
