### ISSUE TITLE
remove file caused 404

### ISSUE THREAD

**Issue by songtzu** [cesanta/mongoose#543]
here is my code
mg_send_file(conn, filepath, NULL); 
if( remove( filepath) != 0 ){
}

when network condition is not good, browser got 404.

**Comment by cpq** [comment]
mg_send_file() schedules file for sending, it does not send it immediately. You should remove the file when request is over.

**Comment by songtzu** [comment]
how could I know it finished sending?
any callback?
could you tell me where the function exactly send the file?

**Comment by cpq** [comment]
Actually, thinking more about it..

    mg_send_file(conn, filepath, NULL); 
    if( remove( filepath) != 0 ){
    }

That should work if you're on UNIX based system.
mg_send_file() opens   a file descriptor and remove() removes a reference to a file, so a file will be sent successfully.

What OS you're running on?
