### ISSUE TITLE
mg_iterate_over_connections()

### ISSUE THREAD

**Issue by doublex** [cesanta/mongoose#546]
The documentation recommends the use of "mg_iterate_over_connections()" to send data from a "worker-thread" to the "server-thread":
https://github.com/cesanta/mongoose/blob/master/docs/Internals.md
Can't find this function in "mongoose.h".

**Comment by alashkin** [comment]
`mg_iterate_over_connection` was deleted
`https://github.com/cesanta/mongoose/blob/master/docs/Internals.md` was deleted

I'm closing bug as too outdated.

PS: [mg_next](https://docs.cesanta.com/mongoose/master/#/c-api/net.h/mg_next.md/) exists
