### ISSUE TITLE
Is it possible to run on ucos?

### ISSUE THREAD

**Issue by linersheng** [cesanta/mongoose#551]
I want to run mongoose on ucos, who has done it?

**Comment by cpq** [comment]
I don't recall people mentioned ucos.
Do you have troubles compiling it under ucos?

**Comment by linersheng** [comment]
I just want to try, I think it is a good idea, maybe will be used in embedded products。

**Comment by cpq** [comment]
Sounds good @linersheng , please let us know how it works.
Closing this for now.
