### ISSUE TITLE
mg_set_option set "document_root" option does not work on windows

### ISSUE THREAD

**Issue by xiejiashu** [cesanta/mongoose#557]
we user mg_set_option(mongooseserver, "document_root", "./html/");function set document_root option,but it fails when we use mg_send_file(conn, "login.html", NULL), we try Relative Path and Absolute Path, all fail on windows,But this works on Linux, could you help us fix this problem?

**Comment by xiejiashu** [comment]
we create a sub thread to run mg_poll_server

**Comment by xiejiashu** [comment]
it works,my mistake,Thank you!

**Comment by cpq** [comment]
So what was the reason, why it didn't work in the first place?

**Comment by xiejiashu** [comment]
windows mg_send_file should combine local path & relative path
