### ISSUE TITLE
Compile Error "unknown type name´va_list`"

### ISSUE THREAD

**Issue by JustMeDaFaq** [cesanta/mongoose#560]
Hi, may someones able to help out?

C:\mongoose-master\examples\hello_world>gcc -g -o mongoose.exe mongoose.c hello_world.c -lpthread -lws2_32
gcc: error: unrecognized command line option '-stdio'

C:\mongoose-master\examples\hello_world>gcc -g -o mongoose.exe mongoose.c hello_world.c -lpthread -lws2_32
mongoose.c:1337:0: warning: "fileno" redefined [enabled by default]
 #define fileno(x) _fileno(x)
 ^
In file included from mongoose.c:91:0:
c:\mingw\include\stdio.h:595:0: note: this is the location of the previous definition
 #define fileno(__F) ((__F)->_file)
 ^
In file included from hello_world.c:9:0:
mongoose.h:107:68: error: unknown type name 'va_list'
 size_t mg_vprintf_data(struct mg_connection *, const char *format, va_list ap);
                                                                    ^
mongoose.h:110:64: error: unknown type name 'va_list'
 size_t mg_vprintf(struct mg_connection *conn, const char *fmt, va_list ap);
                                                                ^

**Comment by cpq** [comment]
```
#include <stdarg.h>
#include "mongoose.h"
```

before
