### ISSUE TITLE
Strange hang

### ISSUE THREAD

**Issue by erappaport** [cesanta/mongoose#565]
My web server works with the version of mongoose.c available on 12/1/2014 (Windows based, multi-threaded, mostly C++ code, 32-bit). If I swap out the latest mongoose.c and mongoose.h available today, I get very strange behavior. My initial login page only comes up about 25% of the time. The rest of the time, the browser just sits there spinning. When the page comes up, I can browse around my sight, but if I stop on a page with a 10 second reload timer, once the page reloads, the browser just sits there spinning. If I exit my web server, the page shows up - so the data was sent, but the browser must think more data is coming. This happens with Firefox, Chrome, and Edge. Again - if I go back to the 12/1/2014 version of mongoose and recompile just that file (and re-link) - the entire site works properly again. This is reproducible.

**Comment by Naav** [comment]
Have you tried doing a bisect to find which commit introduces this behavior?

**Comment by cpq** [comment]
Thanks Ethan.
Could you run this through the Chrome's developer tools and share what network requests are, and where it is stuck please?

**Comment by erappaport** [comment]
![initialload](https://cloud.githubusercontent.com/assets/4910185/9546432/ba67d726-4d60-11e5-8699-8da6ea676801.jpg)
![reloadpageafter10seconds](https://cloud.githubusercontent.com/assets/4910185/9546435/bf971522-4d60-11e5-9635-847d6a5f8c28.jpg)
Here are the initial load and then the reload after 10 seconds.
