### ISSUE TITLE
Handle URL rewrites bug

### ISSUE THREAD

**Issue by ralfischer** [cesanta/mongoose#566]
In function "convert_uri_to_file_name" when handling URL rewrites, the result of "mg_match_prefix" (which returns an int) is assigned to match_len (which is a size_t). Because size_t is unsigned, the -1 result of mg_match_prefix is not <0 as it ought to be.
To make a long story short: Change declaration of local variable "match_len" in function "convert_uri_to_file_name" from size_t to int

**Comment by cpq** [comment]
That's already has been done in the recent sources!
thank you.
