### ISSUE TITLE
per_connection_thread_function -> mg_mgr_poll not using user defined timeout

### ISSUE THREAD

**Issue by Lohkay** [cesanta/mongoose#570]
When enabling multithreading and passing a specific timeout to mg_mgr_poll, this timeout isn't passed down to the child threads. The mg_mgr_poll in the per_connection_thread_function uses a default of 1000ms.

**Comment by alashkin** [comment]
Fixed in https://github.com/cesanta/mongoose/commit/4cbf81da5989b389af0ccfd43e94d4ae38907e5f

Example:
```
struct mg_multithreading_opts opts;
opts.poll_timeout = 10;
mg_enable_multithreading_opt(..., opts);
```
