### ISSUE TITLE
VS2013: Compiling without MG_ENABLE_THREADS fails

### ISSUE THREAD

**Issue by Leandros** [cesanta/mongoose#572]
It fails due to the `spawn_stdio_thread` function referring to `mg_start_thread`, which is obviously not defined without the said flag.

Compilation results in this error:

```
mongoose.obj : error LNK2019: unresolved external symbol _mg_start_thread referenced in function _spawn_stdio_thread
```

Which, is the same as in this issue: https://github.com/cesanta/mongoose/issues/468

**Comment by rojer** [comment]
this has been fixed.
