### ISSUE TITLE
Remote IP missing

### ISSUE THREAD

**Issue by exmex** [cesanta/mongoose#573]
There is currently no way to get the remote IP and setting an env variable because remote_ip has been removed

```
#if 0
  addenv(blk, "REMOTE_ADDR=%s", ri->remote_ip);
  addenv(blk, "REMOTE_PORT=%d", ri->remote_port);
#endif
```

and 

```
addenv(blk, "REMOTE_ADDR=%s", inet_ntoa(nc->sa.sin.sin_addr));
```

returns
```
[REMOTE_ADDR] => 0.0.0.0
```

EDIT:
I don't know if temp or perm but here's a fix:

```
addenv(blk, "SERVER_PORT=%d", ntohs(nc->listener->sa.sin.sin_port));

char remoteAddr[100], remotePort[100];
mg_sock_to_str(nc->sock, remoteAddr, sizeof(remoteAddr), MG_SOCK_STRINGIFY_REMOTE | MG_SOCK_STRINGIFY_IP);
  addenv(blk, "REMOTE_ADDR=%s", remoteAddr);

  mg_sock_to_str(nc->sock, remotePort, sizeof(remotePort), MG_SOCK_STRINGIFY_REMOTE | MG_SOCK_STRINGIFY_PORT);
  addenv(blk, "REMOTE_PORT=%s", remotePort);
```

**Comment by exmex** [comment]
Also there is an issue with digest auth. If I use a global digest auth file, and request something like login.php?username=test it doesn't get through.

**Comment by havonz** [comment]
spawn_handling_thread func:
add line
'c[1]->sa = nc->sa;'
before
'mg_start_thread(per_connection_thread_function, c[1]);'
to fix it

**Comment by rojer** [comment]
fixed
