### ISSUE TITLE
Memory leak at function 'mg_destroy_conn()' when compiling with SSL (defining 'MG_ENABLE_SSL').

### ISSUE THREAD

**Issue by rantoniello** [cesanta/mongoose#579]
Memory leak at function 'mg_destroy_conn()' when compiling with SSL (defining 'MG_ENABLE_SSL').

Proposed solution:

Add the following remarked lines to 'mg_destroy_conn()' (modifications are marked by tag '//RAL')

> static void mg_destroy_conn(struct mg_connection *conn) {
>   if (conn->sock != INVALID_SOCKET) {
>     closesocket(conn->sock);
>     /*
>      * avoid users accidentally double close a socket
>      * because it can lead to difficult to debug situations.
>      * It would happen only if reusing a destroyed mg_connection
>      * but it's not always possible to run the code through an
>      * address sanitizer.
>      */
>     conn->sock = INVALID_SOCKET;
>   }
>   mbuf_free(&conn->recv_mbuf);
>   mbuf_free(&conn->send_mbuf);
> #ifdef MG_ENABLE_SSL
>   if (conn->ssl != NULL) {
>     SSL_free(conn->ssl);
>   }
>   if (conn->ssl_ctx != NULL) {
>     SSL_CTX_free(conn->ssl_ctx);
>   }
>   // { //RAL: Add to avoid leak
>   //SSL_COMP_free_compression_methods();
>   sk_SSL_COMP_free(SSL_COMP_get_compression_methods());
>   EVP_cleanup();
>   CRYPTO_cleanup_all_ex_data();
>   printf("Check point cleanup.\n");
>   // }
> #endif
>   MG_FREE(conn);
> }

Verification setting (Tested on Ubuntu 14.04 LTS):

Compile 'simplest_web_server' example with the following little modifications to add SSL support (modifications are marked by tag '//RAL').
Execute with VALGRIND or similar tool.

Makefile modifications (set '\<my_ssl_include_dir\>' and '\<my_ssl_lib_dir\>' accordingly):

> PROG = simplest_web_server
> SOURCES = $(PROG).c ../../mongoose.c
> CFLAGS = -W -Wall -I../.. $(CFLAGS_EXTRA)
> CFLAGS+= -I'\<my_ssl_include_dir\>' -L'\<my_ssl_lib_dir\>' -lssl -lcrypto -DMG_ENABLE_SSL #//RAL
>
> all: $(PROG)
>
> $(PROG): $(SOURCES)
>         $(CC) $(SOURCES) -o $@ $(CFLAGS)
>
> $(PROG).exe: $(SOURCES)
>         cl $(SOURCES) /I../.. /MD /Fe$@
>
> clean:
>         rm -rf *.gc* *.dSYM *.exe *.obj *.o a.out $(PROG)

Source file 'simplest_web_server.c' modifications 

(A signal handler is added for ctrl+C SIGINT):

> // Copyright (c) 2015 Cesanta Software Limited
> // All rights reserved
>
> #include "mongoose.h"
>
> static struct mg_mgr mgr; //RAL
> static const char *s_http_port = "8000";
> static struct mg_serve_http_opts s_http_server_opts;
>
> // { //RAL
> static void signal_handler()
> {
>   /* Release resources */
>   mg_mgr_free(&mgr);
>
>   printf("Application finalized.\n");
>   exit(EXIT_SUCCESS);
> }
> // }
>
> static void ev_handler(struct mg_connection *nc, int ev, void *p) {
>   if (ev == MG_EV_HTTP_REQUEST) {
>     mg_serve_http(nc, p, s_http_server_opts);
>   }
> }
>
> int main(void) {
>   //struct mg_mgr mgr; //RAL: moved to module's scope
>   struct mg_connection *nc;
>
>   signal(SIGINT, signal_handler); //RAL
>
>   mg_mgr_init(&mgr, NULL);
>   nc = mg_bind(&mgr, s_http_port, ev_handler);
>
>   // Set up HTTP server parameters
>   mg_set_protocol_http_websocket(nc);
>   s_http_server_opts.document_root = ".";  // Serve current directory
>   s_http_server_opts.enable_directory_listing = "yes";
>
>   printf("Starting web server on port %s\n", s_http_port);
>   for (;;) {
>     mg_mgr_poll(&mgr, 1000);
>   }
>   //mg_mgr_free(&mgr); //RAL: commented
>
>   return 0;
> }

Execute with VALGRIND (or similar); to quit from execution just press ctrl+C.

Thanks for your work!
Regards,
Rafael.

**Comment by rojer** [comment]
we run SSL tests with leak checks enabled (ASAN/MSAN). the PR you attached makes use of functions that are not part of the standarg OpenSSL API and thus cannot be merged.
