### ISSUE TITLE
How to transfer user_data to ev_handler

### ISSUE THREAD

**Issue by jimax2000** [cesanta/mongoose#584]
In 5.6 version, the server_param passed to mg_create_server() can be got in ev_handler() by conn->server_param. However, in 6.0 version, user_data passed to mg_mgr_init() can NOT be got in ev_handler() in nc->user_data, nc->user_data is always NULL. How to transfer it ? Thanks.

**Comment by mmikulicic** [comment]
Hi @jimax2000 .

User data passed to the manager via `mg_mgr_init` is available in connections via `nc->mgr->user_data`.

`nc->user_data` is used to hold connection specific user data. If you nee that, you can set it when creating a new connection (inside or outside a connection handler)
