### ISSUE TITLE
publish on clibs?

### ISSUE THREAD

**Issue by zhuangya** [cesanta/mongoose#585]
hey, there is a package manager for c programming language: [clib](https://github.com/clibs/clib)

any plan to publish to clib?

it would be much more convenient to use `mongoose` :smile:

**Comment by cpq** [comment]
mongoose comes as an amalgamated .c/.h , just like sqlite.
So it doesn't sound feasible to use a package manager for it.

**Comment by mmikulicic** [comment]
@cpq, but perhaps it doesn't hurt. People who already use clib might want to just pull in mongoose right?

@zhuangya ; how hard is to make sure the clib package stays up to date?

**Comment by cpq** [comment]
@mmikulicic true, but any sort of such effort, if requires our attention in the future, is a forever-ongoing tax

**Comment by mmikulicic** [comment]
not sure if it's such a big tax; the only downside is that our master repo would contain an `package.json` file:

```
{
  "name": "asprintf",
  "version": "6.3",
  "repo": "cesanta.com/mongoose",
  "description": "mongoose embedded web server",
  "keywords": ["mongoose", "web", "networking", "iot", "webserver", "mqtt"],
  "src": ["mongoose.h", "mongoose.c"]
}
```

and people will install it with:

```
clib install cesanta/mongoose
```

the sources will end up in `deps/mongoose/mongoose.{c,h}`

**Comment by mmikulicic** [comment]
ah, and we should have a tag matching the version number, which BTW we already have and want to keep it that way.

**Comment by zhuangya** [comment]
> the only downside is that our master repo would contain an package.json file

that's true and all you have to do :)
