### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [cesanta/mongoose#587]
I would like to point out that an identifier like "[`__DBG`](https://github.com/cesanta/mongoose/blob/e34747d1ad014b040993eb7dac25e3395508024a/mongoose.h#L263 "Update candidate")" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by rojer** [comment]
the code is not there anymore, but it was an inspiration to fix our header guards, a commit is about to land.
thanks for reporting!
