### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [cesanta/mongoose#588]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [connect_backend](https://github.com/cesanta/mongoose/blob/93beff3b65581306eac2034004563fc9a45cd752/examples/load_balancer/load_balancer.c#L264)
- [pthread_create](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_create.html "Thread creation") ⇒ [mg_start_thread](https://github.com/cesanta/mongoose/blob/e34747d1ad014b040993eb7dac25e3395508024a/mongoose.c#L6246)

**Comment by alashkin** [comment]
I'm not sure I understand rationale of this bug, but since it is a bit outdated (our fault), i'm closing it.
Feel free to close it with clarifications.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Would you like to detect every error situation as early as possible?
