### ISSUE TITLE
Missing docs for struct websocket_message

### ISSUE THREAD

**Issue by nkolban** [cesanta/mongoose#592]
While studying the docs for Mongoose found here:

https://www.cesanta.com/developer/mongoose#_http_websocket

I find reference to the data type called `struct websocket_message` but am unable to find any documentation on that data type at the developer centre.

**Comment by cpq** [comment]
Here it is:
https://docs.cesanta.com/mongoose/dev/#/c-api/http.h/struct_websocket_message/
