### ISSUE TITLE
Support for HTML5 pushState

### ISSUE THREAD

**Issue by rybon** [cesanta/mongoose#600]
HTML5 pushState is a relatively new API in web browsers that makes it possible to navigate to another URL without triggering a page load from the web server. For instance, a user can navigate from www.example.com/page1 to www.example.com/page2 by manipulating the address bar through the pushState API, while keeping the history stack and back button behaviour intact. This is great for single-page Javascript applications, as it allows them to behave the same as any other website with hyperlinks. Before pushState was added, a workaround for preventing the browser from doing a page load was to use `#` signs in the URLs, but this approach has several drawbacks and should be avoided. It is preferable to use real URLs.

A problem arises however when a user wants to reload a URL that was actually 'emulated' through the pushState API, or load an application from a URL that isn't the root path. A page (re)load triggers an actual HTTP request to the web server to fetch the data for that particular URL. If the web server is not aware of which URL paths are actually emulated through pushState, it will try to fetch the page belonging to that URL, which of course does not exist. This leads to unexpected behaviour in the application. The solution in Apache and Nginx is to configure the web server to ignore certain kinds of URL paths and always serve index.html for these paths. In other words, it should always treat these URLs as if they were requests for the root (`/`) path. Is that also possible in Mongoose? If so, from which version onwards? Should that be done in the configuration or does the C code need to be altered to get it to work? Does it support regular expressions for matching URL paths?

Example: http://readystate4.com/2012/05/17/nginx-and-apache-rewrite-to-support-html5-pushstate/

**Comment by mmikulicic** [comment]
Yes, mongoose does support URL rewrites.

1. if you're asking about the mongoose binary, read about `url_rewrites` at https://www.cesanta.com/developer/binary

2. if you're asking about the mongoose embedded C library, search for "URL rewrites" in  https://www.cesanta.com/developer/mongoose for the documentation about the corresponding option in `mg_serve_http_opts`.

That should be enough to always render `index.html` and thus support HTML5 pushState.

If for some reason it doesn't work for you, feel free to reopen the issue and post additional details.
