### ISSUE TITLE
cs_md5 always crash

### ISSUE THREAD

**Issue by Fightsea** [cesanta/mongoose#601]
-----
The value of variable 'len' is always wrong!
Refer to old version mg_md5(), it should be 'strlen(p)'.
-----

char *cs_md5(char buf[33], ...)

  while ((p = va_arg(ap, const unsigned char *) ) != NULL) {
    size_t len = va_arg(ap, size_t);
    MD5_Update(&ctx, p, len);
  }

**Comment by cpq** [comment]
`cs_md5` use case should be this:

`cs_md5(dest, "aa", 2, "bbb", 3, NULL)` - i.e. lengths must be passed explicitly.

**Comment by Fightsea** [comment]
Thanks for the clarification. That's my misunderstanding.
