### ISSUE TITLE
If system time changed, we may close connection wrongly

### ISSUE THREAD

**Issue by huojianying** [cesanta/mongoose#610]
On linux, cs_time is implemented by gettimeofday.

How ever, if we change system time, gettimeofday will be affected., also last_io_time.

Can we change to something as 
                               clock_gettime(CLOCK_MONOTONIC, ..)

**Comment by cpq** [comment]
IMO, the price to pay (less cross-platform code, confusing semantics) is too high to justify a rare use case of changing system time.
