### ISSUE TITLE
Websockets handshake is not working on MIPS (big endian) hardware.

### ISSUE THREAD

**Issue by Legich55555** [cesanta/mongoose#612]
Websockets handshake is not working on MIPS (big endian) hardware. Most likely the problem is in SHA1. I fixed it by using other SHA1 implementation. My fix is accessible here: https://github.com/Legich55555/mp710Ctrl/tree/master/thirdparty/mongoose

**Comment by cpq** [comment]
Reassigning to @alashkin

**Comment by alashkin** [comment]
I have no such HW, I thought PIC is like what, but i have "new PIC" which are little-endian.
Any ideas?

**Comment by Legich55555** [comment]
I used a router with OpenWrt. Most of them have MIPS CPU.

**Comment by cpq** [comment]
Switched to a different SHA - please reopen if required.
