### ISSUE TITLE
function "parse_http_headers" bug, platform: MAC OS, Safari 7.0.6

### ISSUE THREAD

**Issue by leonacwa** [cesanta/mongoose#614]
On the platform MAC OS, Safari 7.0.6，mongoose 6.0, function "parse_http_headers" can not parse empty value.
Safari 7.0.6 send empty Cookie value, like this : "Host: 127.0.0.1:18888\r\nCookie:\r\nX-PlayID: 45455···\r\nRange: 0-1\r\n"， "parse_http_headers" ignores all the key-values after Cookie . It leads to bad Range error or other bugs.
I modified function "parse_http_headers" 
before :
<pre>    if (k->len == 0 || v->len == 0) {
      k->p = v->p = NULL;
      k->len = v->len = 0;
      break;
    }
</pre>
after:
<pre>    if (k->len == 0) {
      k->p = v->p = NULL;
      k->len = v->len = 0;
      break;
    }
</pre>

the mg_str.len is 0.
I think the better ways is  parse all the key-values, ignore the empty key,   reseve empty value.

**Comment by alashkin** [comment]
Fixed in https://github.com/cesanta/mongoose/commit/0ec1a141f1710d7afb56d186c4d40b475d38e1a6
