### ISSUE TITLE
unable to dectect if incomming connection is SSL when multithreaded

### ISSUE THREAD

**Issue by bstromquist** [cesanta/mongoose#618]
spawn_handling_thread() make a copy of the mg_connection so that the stream can be forwarded across threads.  The copy contians none of the SSL state of the original.  In order to know that the original was HTTPS, I added the following line to spawn_handling_thread():

  /*
   * Dress c[1] as nc.
   * TODO(lsm): code in accept_conn() looks similar. Refactor.
   */
  c[1]->listener = nc->listener;
  c[1]->proto_handler = nc->proto_handler;
  c[1]->proto_data = nc->proto_data;
  c[1]->user_data = nc->user_data;
  c[1]->flags = nc->flags;  // NEW LINE - also copy flags e.g. MG_F_SSL_HANDSHAKE_DONE

Then my event handler code (which also forwards HTTPS to HTTP) can do this:
	if (conn->client.nc->flags & MG_F_SSL_HANDSHAKE_DONE)  // indicates client is HTTPS
	{
		// Add a header for HTTPS connected clients so WS can write response URLs as HTTPS
		mg_printf(dst, "Sn-Secure-Client: 1\r\n");
	}

**Comment by alashkin** [comment]
Fixed in https://github.com/cesanta/mongoose/commit/ffed9c4d8c338d4ef476089acded66cc23a62674
