### ISSUE TITLE
MQTT Client not pinging - Exceeds timeout and disconnects

### ISSUE THREAD

**Issue by aaron832** [cesanta/mongoose#619]
I have noticed that although mongoose.c implements a mg_mqtt_ping, it is not used.  It is also not used in any of the MQTT examples provided.  As is, ultimately after connecting to an MQTT server the connection will be lost due to keepalive.  
Noticing in code:  
`case MG_MQTT_CMD_CONNECT:
      /* TODO(mkm): parse keepalive and will */
      break;
`

**Comment by mmikulicic** [comment]
yeah, thanks for "pinging" us on this TODO :-)

**Comment by cpq** [comment]
Thanks @aaron832 . How urgent it is for you? Do you use mongoose for your project ?

**Comment by aaron832** [comment]
Thanks.  Nope, not urgent.  I was able to work around it by sending the ping myself.

`double lastping = mg_time();
        while (1) {
                mg_mgr_poll(&mgr, 1000);
                if(mg_time() > lastping + PING_FREQ_SEC)
                {
                        mg_mqtt_ping(my_mg_connection);
                        lastping = mg_time();
                }
        }
`

**Comment by aaron832** [comment]
Actually, I have noticed that sending a ping like this seems to be locking things up.  Not able to get publish messages when doing this.  Not sure why.  I have noticed also that after subscribing, the subscription complete message sometimes later after receiving a publish.

**Comment by mmikulicic** [comment]
Which server are you using?

**Comment by mmikulicic** [comment]
Fixed in 43709b4a86d7d0772c451f794bfdd5eb4a3a304

**Comment by mmikulicic** [comment]
FYI: you can also schedule pings inside your event handler (just react to MG_EV_POLL events), there is no need to do it in the main poll loop.

**Comment by TianyiChen** [comment]
I am seeing the same, apparently `mg_mqtt_ping` is not used and I didn't see the above commit in `master`, are MQTT clients still expected to do the ping explicitly?

**Comment by cpq** [comment]
Yeah, clients may initiate pings. You might setup a timer to do it.
