### ISSUE TITLE
HTTPS not working on one server

### ISSUE THREAD

**Issue by erappaport** [cesanta/mongoose#621]
I have two Windows 2012 servers (one in my test environment and one in a production environment at my client). My web server works properly on the test computer (https) but not on the production computer. When attempting to connect to the production computer, the following message comes up: Turn on TLS 1.0, TLS 1.1, and TLS 1.2 in Advanced settings and try connecting to ... again.

The same software and same PEM file are used on both machines.

My client used a debugging tool on the production server to get this screenshot:

![connection](https://cloud.githubusercontent.com/assets/4910185/13225565/6782bbf2-d95b-11e5-9878-6b34316f9eac.jpg)

Please let me know what might be going on. Thanks.

**Comment by erappaport** [comment]
My client might be willing to run some debugging on the server. It is important to them to have HTTPS running properly.

**Comment by cpq** [comment]
Thanks Ethan!
We will be able to jump on it in a week time.

**Comment by cpq** [comment]
We have done multiple changes to HTTPS support recently, do you still observe this?

**Comment by erappaport** [comment]
The client decided against HTTPS at this time, so I cannot verify the behavior - Ethan

**Comment by alashkin** [comment]
Ok, i'm closing issue, feel free to repoen if you'll face it again
