### ISSUE TITLE
grav on mongoose

### ISSUE THREAD

**Issue by shane0** [cesanta/mongoose#629]
Has anyone tried running grav on mongoose?

https://getgrav.org/

I'm attempting that now, I got the homepage to display but I think there's some permission issues

these are the requirements http://learn.getgrav.org/basics/requirements

**Comment by shane0** [comment]
I just updated (pro) and php isn't supported anymore closing issue

**Comment by mmikulicic** [comment]
FYI: php is still supported on mongoose via CGI
