### ISSUE TITLE
websocket client bug

### ISSUE THREAD

**Issue by cole-dda** [cesanta/mongoose#631]
the function  mg_http_common_url_parse(...) has a bug，when parse url, such as:
ws://localhost:8080/ws  => host=locahost:8080, path=/ws
now result is  => host=localhost:8080, path=ws   (that is error,not leading /)

the error occur because on the functio,code is:

    if (*url == '/') {
      url++;     ==> that is error
      break;
    }

**Comment by mmikulicic** [comment]
Thanks for reporting, this looks like a bug. Fixing
