### ISSUE TITLE
Close the connection when HTTP/1.0 and no Keep-Alive is used

### ISSUE THREAD

**Issue by cpq** [cesanta/mongoose#634]
See http://forum.cesanta.com/index.php?p=/discussion/38/mg-f-send-and-close-is-required-for-http-1-0

**Comment by cpq** [comment]
[ ] Write code for handling HTTP 1.0 keep-alive properly
[ ] Write unit test for it

**Comment by rojer** [comment]
should've been fixed by 61672c780540bd5bb8e12d4fa399aa5c2aa4e355
posted to forum, closing this
