### ISSUE TITLE
MG_EV_ACCEPT "missing" in a multithreaded server

### ISSUE THREAD

**Issue by chrishaig14** [cesanta/mongoose#645]
Hi! In [this example](https://github.com/cesanta/mongoose/tree/master/examples/multithreaded_restful_server) of a multithreaded server, if in the event handler I add something like:

```
if(ev == MG_EV_ACCEPT){
printf("New connection!\n");
}
```
(that's the only change in the entire code, I put that right above the if(ev == MG_EV_HTTP_REQUEST) ...)
absolutely nothing happens when I connect to the server. I mean, the MG_EV_ACCEPT never comes, or at least I can't see it, and I really need to handle this event to initialize a couple of things. What's going on?

**Comment by mccoysc** [comment]
problem same as issue 50

**Comment by chrishaig14** [comment]
@mccoysc How is that the same? And, if it is, how can I solve it? I don't get it...

**Comment by mccoysc** [comment]
all the problem are based on the bug "resource race"。
in the 6.4，conn is used in work thread，but also linked into main thread's nc->pre/next.
either main thread or work thread may do some thing on the same conn at a same time.
this would destroy some data saved in conn structure.

发自我的 iPhone
