### ISSUE TITLE
freed pointer used in  multithread mode

### ISSUE THREAD

**Issue by mccoysc** [cesanta/mongoose#646]
freed pointer used in  multithread mode.

on  line 4977:
mg_call(nc, (pd->endpoint_handler ? pd->endpoint_handler : nc->handler),
              MG_EV_HTTP_PART_END, &mp);

may be pd have been freed in somewhere when mg_call called.

**Comment by mccoysc** [comment]
![1](https://cloud.githubusercontent.com/assets/18025276/14553486/6c95d10a-0319-11e6-8ba3-58aa6b6c7d18.png)

**Comment by rojer** [comment]
it is a bug that any data race can occur. even in multi=threaded mode one connection is still supposed to only be accessed from only one thread. i'll take a look.

**Comment by mccoysc** [comment]
i'v found the key place:

at line 3889:
  c[1]->listener = nc->listener;
  c[1]->proto_handler = nc->proto_handler;
  c[1]->proto_data = nc->proto_data;
  c[1]->user_data = nc->user_data;

if in work thread,i set like this:
c->flags | =MG_F_SEND_AND_CLOSE;

and immediately the main thread found that the MG_F_SEND_AND_CLOSE is set,it will free the conn and the conn's proto_data.
but really,the proto_data is being used by work thread.

so,my resolve is add some code when create work thread:
  c[1]->proto_data_destructor = nc->proto_data_destructor;
  nc->proto_data = NULL;

**Comment by mccoysc** [comment]
and also add these code:

  if (c[1]->prev)
  {
	  c[1]->prev= c[1]->next;
  }

  if (c[1]->next)
  {
	  c[1]->next->prev = c[1]->prev;
  }

**Comment by alashkin** [comment]
Please, check with latest version
