### ISSUE TITLE
mg_conn_addr_to_str doesn't work with mg_enable_multithreading

### ISSUE THREAD

**Issue by kokole** [cesanta/mongoose#648]
In multithreaded HTTP event handler (MG_EV_HTTP_REQUEST):
```
char clientIPAddressStr[INET6_ADDRSTRLEN];
mg_conn_addr_to_str( nc, clientIPAddressStr, sizeof( clientIPAddressStr ), MG_SOCK_STRINGIFY_IP | MG_SOCK_STRINGIFY_REMOTE );
```
This returns "127.0.0.1", while it works if mg_enable_multithreading isn't called at startup.

Startup code:
```
void HTTP_Thread()
{
	mg_mgr mgr;
	mg_mgr_init( &mgr, NULL );
	mg_connection* cn = mg_bind( &mgr, "80", HTTP_EventHandler );
	mg_set_protocol_http_websocket( cn );
	mg_enable_multithreading( cn );

	while ( true )
		mg_mgr_poll( &mgr, 100 );

	mg_mgr_free( &mgr );
}
```

OS: Windows (Visual Studio)
Defines: MG_ENABLE_IPV6, MG_ENABLE_THREADS
Version: 6.4

**Comment by husless** [comment]
I have the same problem on RHEL 6.5, with the latest clone of mongoose.

**Comment by alashkin** [comment]
Try latest version, pls
Should be ok
