### ISSUE TITLE
CC3200: C linkage of symbols

### ISSUE THREAD

**Issue by kzyapkov** [cesanta/mongoose#653]
Please apply `extern "C"` to these:

https://github.com/cesanta/mongoose/blob/master/mongoose.h#L702-L713

Thanks!

**Comment by mmikulicic** [comment]
should be solved in 9939212379dd9b080bf73e3076fc058aa7d3468a

**Comment by kzyapkov** [comment]
Also functions in `CS_MONGOOSE_SRC_NET_IF_H_`. I wish I could reopen this instead of having to open a new one again.

**Comment by mmikulicic** [comment]
reopened :-)
