### ISSUE TITLE
websocket real-time send data (from server)

### ISSUE THREAD

**Issue by iauther** [cesanta/mongoose#654]
I use the samples code( refer to websocket_chat.c ) to test socket read/write, but found that the function didn't send the data to the websocket client, instead of to the buffer. Now I want to send the data out immediately, how to do? 

Perhaps here is no available api to use.

**Comment by rojer** [comment]
buffering data first is essential. data is buffered, the on next poll we check when socket is ready for data to be sent and send it. this is working as intended and should not result in appreciable delays (if your handlers don't block for long time, which they should not).
