### ISSUE TITLE
VC++ 2015 strdup error

### ISSUE THREAD

**Issue by pavel-pimenov** [cesanta/mongoose#655]
mongoose.c(7843): error C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\string.h(552): note: see declaration of 'strdup'

**Comment by ysc3839** [comment]
#if defined(_WIN32)
#define strdup _strdup
#endif

**Comment by OgreTransporter** [comment]
It's also an error in VS2013, so I use the following macro:
```C++
#ifdef _MSC_VER
#define strdup(s) _strdup(s)
#endif
```
I've tried several positions in code and header. The best option is arround line 7454 direct above mg_register_http_endpoint function.
