### ISSUE TITLE
cc3200 restful_client stuck when server is not available.

### ISSUE THREAD

**Issue by Leo-Dev** [cesanta/mongoose#658]
Hi,

We try to run **restful_client** example on cc3200, it works fine when server is available . 
Unfortunately, if server is not available, return value of connect() is -111, then not available to exit mg_mgr_poll(). 

Please help.

Leo Dev

**Comment by alashkin** [comment]
Hi!
It is possible, we have to answer a bit earlier, sorry.
But now we don't have restful_client cc3200 example.
We have 2 examples for CC3200, but both of them are servers:
https://github.com/cesanta/mongoose/tree/master/examples/CC3200/ccs
