### ISSUE TITLE
VS 15 Compiling with flag /MTd blocks all connections

### ISSUE THREAD

**Issue by lumyx2** [cesanta/mongoose#661]
Any idea why this is so? It's that by design? 

Reason being, I've used it in a few prototypes and this problem has caught me up several times. 

Thanks

**Comment by alashkin** [comment]
Hello, do you mean VS 2015 (aka VS 14) or VS 15 (aka VS 2017, currently in beta)?

**Comment by lumyx2** [comment]
Meant VS14.

**Comment by alashkin** [comment]
I tried to reproduce, but everything works for me.
Could you share more details? Your (mongoose related) code - is it something specific?

**Comment by alashkin** [comment]
What do you use for testing? I tried restful_client/restful_server

**Comment by alashkin** [comment]
Feel free to reopen if current master still has this issue
