### ISSUE TITLE
Multithreaded file server?

### ISSUE THREAD

**Issue by LubosD** [cesanta/mongoose#662]
Hi,

I'm trying to make a simple combination of these two examples:
https://github.com/cesanta/mongoose/blob/master/examples/multithreaded_restful_server/multithreaded_restful_server.c
https://github.com/cesanta/mongoose/blob/master/examples/simplest_web_server/simplest_web_server.c

in other words, serve files from a directory, but do it in multithreaded manner (+ loads of other functionality, which does not pertain to the problem at hand).

The problem is mg_serve_http seems completely unable to handle threading. I always end up with a crash like this:
````
(gdb) bt
#0  0x00007ffff1c95218 in raise () from /lib64/libc.so.6
#1  0x00007ffff1c9669a in abort () from /lib64/libc.so.6
#2  0x00007ffff1cd1c20 in ?? () from /lib64/libc.so.6
#3  0x00007ffff1cd7746 in ?? () from /lib64/libc.so.6
#4  0x00007ffff1cd7f3e in ?? () from /lib64/libc.so.6
#5  0x00007ffff1cc7a53 in fclose () from /lib64/libc.so.6
#6  0x00000000006e8c03 in mg_http_free_proto_data_file (d=0x7fffc8003080) at /home/lubos/Projects/fatrat/src/remote/mongoose.c:4249
#7  0x00000000006ea4f9 in mg_http_transfer_file_data (nc=0x7fffc8002f90) at /home/lubos/Projects/fatrat/src/remote/mongoose.c:4850
#8  0x00000000006ead94 in mg_http_handler (nc=0x7fffc8002f90, ev=4, ev_data=0x7fffd8c8dbc4) at /home/lubos/Projects/fatrat/src/remote/mongoose.c:5083
#9  0x00000000006e36b3 in mg_call (nc=0x7fffc8002f90, ev_handler=0x6eac14 <mg_http_handler>, ev=4, ev_data=0x7fffd8c8dbc4) at /home/lubos/Projects/fatrat/src/remote/mongoose.c:2176
#10 0x00000000006e4a97 in mg_if_sent_cb (nc=0x7fffc8002f90, num_sent=5120) at /home/lubos/Projects/fatrat/src/remote/mongoose.c:2705
#11 0x00000000006e68b8 in mg_write_to_socket (nc=0x7fffc8002f90) at /home/lubos/Projects/fatrat/src/remote/mongoose.c:3380
#12 0x00000000006e71fc in mg_mgr_handle_conn (nc=0x7fffc8002f90, fd_flags=2, now=1464969801.173003) at /home/lubos/Projects/fatrat/src/remote/mongoose.c:3570
#13 0x00000000006e7c76 in mg_mgr_poll (mgr=0xb0d170, timeout_ms=500) at /home/lubos/Projects/fatrat/src/remote/mongoose.c:3759
#14 0x00000000006ca0eb in HttpService::run (this=0xb0d120) at /home/lubos/Projects/fatrat/src/remote/HttpService.cpp:286
#15 0x00007ffff29b155c in ?? () from /usr/lib64/libQt5Core.so.5
#16 0x00007ffff79c0484 in start_thread () from /lib64/libpthread.so.0
#17 0x00007ffff1d49e7d in clone () from /lib64/libc.so.6
````

The problem is the argument for `mg_http_free_proto_data_file(struct mg_http_proto_data_file *)` is reused for all threads, so it very quickly clashes and crashes on `d->fp` becoming NULL inside the `if (d->fp != NULL)` condition.

Given how this is implemented, protecting `mg_serve_http()` with a mutex doesn't help at all.

Isn't this a bug?

**Comment by alashkin** [comment]
Hi, the similar problem was just solved in https://github.com/cesanta/mongoose/issues/685

I'd suggest to try latest version, and please reopen issue if problem still exists
