### ISSUE TITLE
Duplicated documentation files.

### ISSUE THREAD

**Issue by vladimir-poleh** [cesanta/mongoose#675]
Hi,

There are two files with same name but different characters case:
`/docs/c-api/util.h/MG_MK_STR.md`
`/docs/c-api/util.h/mg_mk_str.md`

This causes problems with Git on Windows as Windows uses case-insensitive file system and can't store both files in single directory.

**Comment by alashkin** [comment]
As I see, this is fixed
Feel free to reopen, if I see wrong =)
