### ISSUE TITLE
mongoose.c:1513: mbuf_insert: assertion "a->len <= a->size" failed

### ISSUE THREAD

**Issue by ray-pixar** [cesanta/mongoose#676]
I'm getting ```mongoose.c:1513: mbuf_insert: assertion "a->len <= a->size" failed``` in random situations. 
Currently I cannot provide what is the input link. I'll do it when I find it.

I'm using this commit from master branch: 290e5f83d43286c015feea0356a3aa0cf6e14e60

**Comment by ray-pixar** [comment]
the problem was in my code.

**Comment by FusEcho** [comment]
hello, I'm getting the same problem, Do you have ever found any solution for this?
