### ISSUE TITLE
Writting out of buffer in mg_http_common_url_parse

### ISSUE THREAD

**Issue by vov-crao** [cesanta/mongoose#677]
I have tried to make https connection with 'https://192.168.10.105' and have got an MSVC debug exception - writing out of buffer memory.
I have investigate this issue a little and found the problem in line 7069:
    `*addr = (char *) MG_REALLOC(*addr, addr_len + 5 /* space for port too. */);`
The value 5 is not enougth to allocate whole buffer, it shall be at least 6:

-  4 byte for string ":443"
-  1 byte for terminal zero
-  1 byte for current character, see line 7078:

    `(*addr)[addr_len++] = *url;`

I have tested with value 6 and it is working fine.

**Comment by rojer** [comment]
fixed, thank you!
