### ISSUE TITLE
mongoose creates zombies, when using php-cgi, or any cgi program..

### ISSUE THREAD

**Issue by mladinox** [cesanta/mongoose#679]
On linux..

Starting the browser creates 1 zombie,
and Refreshing the browser, creates +2 zombies by each refresh..

Running mongoose in background and setting the cgi program via param like:

s_http_server_opts.cgi_interpreter=argv[3]; //sCGIfullPATH

Thank you..

**Comment by cpq** [comment]
`signal(SIGCHLD, SIG_IGN);`

**Comment by mladinox** [comment]
Works..

Thank you..
