### ISSUE TITLE
How to properly disable MG_DISABLE_SOCKETPAIR in older builds

### ISSUE THREAD

**Issue by olignyf** [cesanta/mongoose#681]
Hi,

In slightly older version of mongoose.c, if I try to disable the ctl[] sockets I get build errors about ns_socketpair undefined
```

  // Try to create socketpair in a loop until success. ns_socketpair()
  // can be interrupted by a signal and fail.
  // TODO(lsm): use sigaction to restart interrupted syscall
  do {
    ns_socketpair(fds);
  } while (fds[0] == INVALID_SOCKET);
```
`mongoose.obj : error LNK2019: unresolved external symbol _ns_socketpair referenced in function _open_cgi_endpoint `

Why does mongoose needs extra socket for parsing CGI ? For this older version of moongoose, should I just comment out the creation of the ctr[] socket and keep ns_socketpair compiled ?

Thanks,
Francois

**Comment by cpq** [comment]
Please use the latest version - unfortunately we don't have free cycles to support older ones.
