### ISSUE TITLE
mg_serve_http parameter 'struct mg_serve_http_opts opts' should be a pointer

### ISSUE THREAD

**Issue by ysc3839** [cesanta/mongoose#682]
mongoose.c:7057 & :5163
`struct mg_serve_http_opts opts) {`
`opts` -> `*opts`

**Comment by rojer** [comment]
please explain why this is necessary? passing by value is not a bug, it's a choice we made.

**Comment by ysc3839** [comment]
In my thought structs should be passed by pointer. Passing by value will use more stack memory. If this is not a bug I will close it.
