### ISSUE TITLE
linker errors with msvc2013

### ISSUE THREAD

**Issue by firstblade** [cesanta/mongoose#686]
> mongoose.obj : error LNK2019: unresolved external symbol __imp__RegCloseKey@4 referenced in function _mg_get_ip_address_of_nameserver
> mongoose.obj : error LNK2019: unresolved external symbol __imp__RegEnumKeyA@16 referenced in function _mg_get_ip_address_of_nameserver
> mongoose.obj : error LNK2019: unresolved external symbol __imp__RegOpenKeyA@12 referenced in function _mg_get_ip_address_of_nameserver
> mongoose.obj : error LNK2019: unresolved external symbol __imp__RegQueryValueExA@24 referenced in function _mg_get_ip_address_of_nameserver

solution:
 add   

>  #pragma comment(lib, "advapi32")

```
 #ifdef _MSC_VER
 #pragma comment(lib, "ws2_32.lib") /* Linking with winsock library */
 #pragma comment(lib, "advapi32")  /* the newly added */
 #endif
```

**Comment by kidandcat** [comment]
Why closed this without response nor fix?
