### ISSUE TITLE
is there any max tcp connection limit ?

### ISSUE THREAD

**Issue by yzsand** [cesanta/mongoose#687]
i write a test console application to connect mongoose 6.1 on windows 7 x64

when it touch 36 connections, later connection is refused by server

**Comment by alashkin** [comment]
Do you mean 37 active connections or just 37th connection is refused?

**Comment by yzsand** [comment]
37th

**Comment by alashkin** [comment]
I.e. there aren't other active connections?
Are you sure, previous 36 are closed?

**Comment by yzsand** [comment]
seems 36 established connections is the  up limit. I didn't test linux version

**Comment by yzsand** [comment]
Not that problem. I mean 36 is the max concurrent number.
Impossible, isn't it? Maybe there's another problem cause this

**Comment by alashkin** [comment]
>Impossible, isn't it?

Why impossible? We use `seelect` call, on Windows it do have limit

**Comment by yzsand** [comment]
But it seems too small,some where to change?

**Comment by alashkin** [comment]
Do you build mongoose from sources? Or binaries?
What you app does?
Establish connection to itself? I.e. within the same mg manager?
Could you share this information with me?
Thanx

**Comment by yzsand** [comment]
sorry for not say it clear.
I mean mongoose as server app with thread enable 
A standalone tcp console exe as client 
Two applications.

Client send some string by http  post,mongoose server reply the same string.


Both build from source

**Comment by yzsand** [comment]
any update info？

**Comment by alashkin** [comment]
Hi, sorry for the long wait.
Just tried - works fine for me on Win10 x64 
But I've used current master,
could you try it? There are a lot of bug fixes in it

**Comment by alashkin** [comment]
Feel free to reopen, if current master still have this issue

**Comment by yzsand** [comment]
@alashkin
i try current master,the problem still exist
what do you mean " works fine",  any concurrent number explain or test play?
can you share me your test plan?

my test scenario:

server:
`
int main(){
	struct mg_mgr mgr;
	struct mg_connection *nc;

	mg_mgr_init(&mgr, NULL);
	nc = mg_bind(&mgr, s_http_port, ev_handler);
	mg_set_protocol_http_websocket(nc);
	mg_enable_multithreading(nc);

	printf("Starting multi-threaded server on port %s\n", s_http_port);
	for (;;) {
		mg_mgr_poll(&mgr, 3000);
	}
	mg_mgr_free(&mgr);
}
`
client : 
        a executable program do 1000 loop of sending http post one by one

action:
start to run client one by one, just to increase concurrent number
then after about 6 clients running, the 7th client will raise a excetion: connection refused by remote server

**Comment by yzsand** [comment]
tks for reopen this issue

**Comment by yzsand** [comment]
updated test scenario:

server code:

```
static void ev_handler(struct mg_connection *c, int ev, void *p) {
	if (ev == MG_EV_HTTP_REQUEST) {
		struct http_message *hm = (struct http_message *) p;
		char reply[100];

		/* 5 seconds Simulate long calculation to  increase client concurrent number*/
		sleep(5);

		/* Send the reply */
		snprintf(reply, sizeof(reply), "{ \"uri\": \"%.*s\" }\n",
			(int) hm->uri.len, hm->uri.p);
		mg_printf(c, "HTTP/1.1 200 OK\r\n"
			"Content-Type: text/plain\r\n"
			"Content-Length: %d\r\n"
			"\r\n"
			"%s",
			(int) strlen(reply), reply);
	}else if(ev==MG_EV_SSI_CALL){

	}
}

int main(void) {
	struct mg_mgr mgr;
	struct mg_connection *nc;

	mg_mgr_init(&mgr, NULL);
	nc = mg_bind(&mgr, s_http_port, ev_handler);
	mg_set_protocol_http_websocket(nc);
	mg_enable_multithreading(nc);

	printf("Starting multi-threaded server on port %s\n", s_http_port);
	for (;;) {
		mg_mgr_poll(&mgr, 3000);
	}
	mg_mgr_free(&mgr);

	return 0;
}
```

client code use libcurl:

```
static unsigned __stdcall clientAction( LPVOID WorkContext )
{
	ostringstream oss;
	oss << "http://192.168.0.118:8000/test/" << GetCurrentThreadId();

	CURL* pCurl=curl_easy_init();

	struct curl_slist *headers=NULL; 
	headers=curl_slist_append( headers, "Cache-Control: no-cache"); 
	headers=curl_slist_append( headers, "Pragma: no-cache"); 
	curl_easy_setopt (pCurl, CURLOPT_HTTPHEADER, headers);

	curl_easy_setopt (pCurl, CURLOPT_URL, oss.str().c_str());
	curl_easy_setopt(pCurl, CURLOPT_POSTFIELDS, "name=clientAction&project=curl");
	curl_easy_setopt(pCurl, CURLOPT_WRITEFUNCTION, noop_cb);

	long retcode=0;
	CURLcode pCurlRes = curl_easy_perform(pCurl);
	curl_easy_getinfo (pCurl, CURLINFO_HTTP_CODE, &retcode);
	curl_slist_free_all(headers);

	if(CURLE_OK != pCurlRes) {fprintf(stderr, "curl told us %d\n", pCurlRes);curl_easy_cleanup(pCurl);return 0;}
	else cout << GetCurrentThreadId() << "\t" << retcode << "\tOK" << endl;

	curl_easy_cleanup(pCurl);
	return 0;
}

int main(void) {
	curl_global_init(CURL_GLOBAL_ALL);

	for(int i=0;i<100;i++){
		UINT  nThreadID=0;
		HANDLE hThread = (HANDLE)_beginthreadex(NULL,
			0,clientAction,NULL,0,&nThreadID);	
	}

	string sTmp;
	cin >> sTmp;

	curl_global_cleanup();
	return EXIT_SUCCESS;
}
```

after 3 clients running,you will see libcurl output:
>  curl told us 7
which means:
> CURLE_COULDNT_CONNECT,         /* 7 */

connection refused by remote server

then i use 
> netstat -nao | find ":8000" >x:\1.txt
to see how many connctions are established

> 1        TCP    0.0.0.0:8000           0.0.0.0:0              LISTENING       23400
> 2	  TCP    192.168.0.118:8000     192.168.0.118:52022    CLOSE_WAIT      23400
> 3	  TCP    192.168.0.118:8000     192.168.0.118:52083    ESTABLISHED     23400
> 4	  TCP    192.168.0.118:8000     192.168.0.118:52084    ESTABLISHED     23400
> 5	  TCP    192.168.0.118:8000     192.168.0.118:52085    ESTABLISHED     23400
> 6	  TCP    192.168.0.118:8000     192.168.0.118:52086    ESTABLISHED     23400
> 7	  TCP    192.168.0.118:8000     192.168.0.118:52087    ESTABLISHED     23400
> 8	  TCP    192.168.0.118:8000     192.168.0.118:52088    ESTABLISHED     23400
> 9	  TCP    192.168.0.118:8000     192.168.0.118:52089    ESTABLISHED     23400
> 10	  TCP    192.168.0.118:8000     192.168.0.118:52090    ESTABLISHED     23400
> 11	  TCP    192.168.0.118:8000     192.168.0.118:52092    ESTABLISHED     23400
> 12	  TCP    192.168.0.118:8000     192.168.0.118:52094    ESTABLISHED     23400
> 13	  TCP    192.168.0.118:8000     192.168.0.118:52095    ESTABLISHED     23400
> 14	  TCP    192.168.0.118:8000     192.168.0.118:52098    ESTABLISHED     23400
> 15	  TCP    192.168.0.118:8000     192.168.0.118:52099    ESTABLISHED     23400
> 16	  TCP    192.168.0.118:8000     192.168.0.118:52101    ESTABLISHED     23400
> 17	  TCP    192.168.0.118:8000     192.168.0.118:52102    ESTABLISHED     23400
> 18	  TCP    192.168.0.118:8000     192.168.0.118:52104    ESTABLISHED     23400
> 19	  TCP    192.168.0.118:8000     192.168.0.118:52105    ESTABLISHED     23400
> 20	  TCP    192.168.0.118:8000     192.168.0.118:52106    ESTABLISHED     23400
> 21	  TCP    192.168.0.118:8000     192.168.0.118:52107    ESTABLISHED     23400
> 22	  TCP    192.168.0.118:8000     192.168.0.118:52108    ESTABLISHED     23400
> 23	  TCP    192.168.0.118:8000     192.168.0.118:52109    ESTABLISHED     23400
> 24	  TCP    192.168.0.118:8000     192.168.0.118:52110    ESTABLISHED     23400
> 25	  TCP    192.168.0.118:8000     192.168.0.118:52111    ESTABLISHED     23400
> 26	  TCP    192.168.0.118:8000     192.168.0.118:52112    ESTABLISHED     23400
> 27	  TCP    192.168.0.118:8000     192.168.0.118:52115    ESTABLISHED     23400
> 28	  TCP    192.168.0.118:8000     192.168.0.118:52116    ESTABLISHED     23400
> 29	  TCP    192.168.0.118:8000     192.168.0.118:52119    ESTABLISHED     23400
> 30	  TCP    192.168.0.118:8000     192.168.0.118:52120    ESTABLISHED     23400
> 31	  TCP    192.168.0.118:8000     192.168.0.118:52121    ESTABLISHED     23400
> 32	  TCP    192.168.0.118:8000     192.168.0.118:52124    ESTABLISHED     23400
> 33	  TCP    192.168.0.118:8000     192.168.0.118:52125    ESTABLISHED     23400
> 34	  TCP    192.168.0.118:8000     192.168.0.118:52126    ESTABLISHED     23400
> 35	  TCP    192.168.0.118:8000     192.168.0.118:52127    ESTABLISHED     23400
> 36	  TCP    192.168.0.118:8000     192.168.0.118:52128    ESTABLISHED     23400
> 37	  TCP    192.168.0.118:8000     192.168.0.118:52129    ESTABLISHED     23400
> 38	  TCP    192.168.0.118:8000     192.168.0.118:52130    ESTABLISHED     23400
> 39	  TCP    192.168.0.118:8000     192.168.0.118:52133    ESTABLISHED     23400
> 40	  TCP    192.168.0.118:8000     192.168.0.118:52134    ESTABLISHED     23400
> 41	  TCP    192.168.0.118:8000     192.168.0.118:52135    ESTABLISHED     23400
> 42	  TCP    192.168.0.118:8000     192.168.0.118:52136    ESTABLISHED     23400
> 43	  TCP    192.168.0.118:8000     192.168.0.118:52137    ESTABLISHED     23400
> 44	  TCP    192.168.0.118:8000     192.168.0.118:52138    ESTABLISHED     23400
> 45	  TCP    192.168.0.118:8000     192.168.0.118:52139    ESTABLISHED     23400
> 46	  TCP    192.168.0.118:8000     192.168.0.118:52142    ESTABLISHED     23400
> 47	  TCP    192.168.0.118:8000     192.168.0.118:52143    ESTABLISHED     23400
> 48	  TCP    192.168.0.118:8000     192.168.0.118:52144    ESTABLISHED     23400
> 49	  TCP    192.168.0.118:8000     192.168.0.118:52145    ESTABLISHED     23400
> 50	  TCP    192.168.0.118:8000     192.168.0.118:52146    ESTABLISHED     23400
> 51	  TCP    192.168.0.118:8000     192.168.0.118:52147    ESTABLISHED     23400
> 52	  TCP    192.168.0.118:8000     192.168.0.118:52148    ESTABLISHED     23400
> 53	  TCP    192.168.0.118:8000     192.168.0.118:52149    ESTABLISHED     23400
> 54	  TCP    192.168.0.118:8000     192.168.0.118:52150    ESTABLISHED     23400
> 55	  TCP    192.168.0.118:8000     192.168.0.118:52151    ESTABLISHED     23400
> 56	  TCP    192.168.0.118:8000     192.168.0.118:52152    ESTABLISHED     23400
> 57	  TCP    192.168.0.118:8000     192.168.0.118:52155    ESTABLISHED     23400
> 58	  TCP    192.168.0.118:8000     192.168.0.118:52156    ESTABLISHED     23400
> 59	  TCP    192.168.0.118:8000     192.168.0.118:52157    ESTABLISHED     23400
> 60	  TCP    192.168.0.118:8000     192.168.0.118:52158    ESTABLISHED     23400
> 61	  TCP    192.168.0.118:8000     192.168.0.118:52159    ESTABLISHED     23400
> 62	  TCP    192.168.0.118:8000     192.168.0.118:52160    ESTABLISHED     23400
> 63	  TCP    192.168.0.118:8000     192.168.0.118:52161    ESTABLISHED     23400
> 64	  TCP    192.168.0.118:8000     192.168.0.118:52162    ESTABLISHED     23400
> 65	  TCP    192.168.0.118:8000     192.168.0.118:52163    ESTABLISHED     23400
> 66	  TCP    192.168.0.118:8000     192.168.0.118:52164    ESTABLISHED     23400
> 67	  TCP    192.168.0.118:8000     192.168.0.118:52165    ESTABLISHED     23400
> 68	  TCP    192.168.0.118:8000     192.168.0.118:52166    ESTABLISHED     23400
> 69	  TCP    192.168.0.118:8000     192.168.0.118:52167    ESTABLISHED     23400
> 70	  TCP    192.168.0.118:8000     192.168.0.118:52168    ESTABLISHED     23400
> 71	  TCP    192.168.0.118:8000     192.168.0.118:52173    ESTABLISHED     23400
> 72	  TCP    192.168.0.118:8000     192.168.0.118:52174    ESTABLISHED     23400
> 73	  TCP    192.168.0.118:8000     192.168.0.118:52175    ESTABLISHED     23400
> 74	  TCP    192.168.0.118:8000     192.168.0.118:52176    ESTABLISHED     23400
> 75	  TCP    192.168.0.118:8000     192.168.0.118:52177    ESTABLISHED     23400
> 76	  TCP    192.168.0.118:8000     192.168.0.118:52178    ESTABLISHED     23400
> 77	  TCP    192.168.0.118:8000     192.168.0.118:52179    ESTABLISHED     23400
> 78	  TCP    192.168.0.118:8000     192.168.0.118:52180    ESTABLISHED     23400
> 79	  TCP    192.168.0.118:8000     192.168.0.118:52181    ESTABLISHED     23400
> 80	  TCP    192.168.0.118:8000     192.168.0.118:52182    ESTABLISHED     23400
> 81	  TCP    192.168.0.118:8000     192.168.0.118:52183    ESTABLISHED     23400
> 82	  TCP    192.168.0.118:8000     192.168.0.118:52184    ESTABLISHED     23400
> 83	  TCP    192.168.0.118:8000     192.168.0.118:52185    ESTABLISHED     23400
> 84	  TCP    192.168.0.118:8000     192.168.0.118:52186    ESTABLISHED     23400
> 85	  TCP    192.168.0.118:8000     192.168.0.118:52187    ESTABLISHED     23400
> 86	  TCP    192.168.0.118:8000     192.168.0.118:52188    ESTABLISHED     23400
> 87	  TCP    192.168.0.118:8000     192.168.0.118:52189    ESTABLISHED     23400
> 88	  TCP    192.168.0.118:8000     192.168.0.118:52190    ESTABLISHED     23400
> 89	  TCP    192.168.0.118:8000     192.168.0.118:52191    ESTABLISHED     23400
> 90	  TCP    192.168.0.118:8000     192.168.0.118:52192    ESTABLISHED     23400
> 91	  TCP    192.168.0.118:8000     192.168.0.118:52193    ESTABLISHED     23400
> 92	  TCP    192.168.0.118:8000     192.168.0.118:52194    ESTABLISHED     23400
> 93	  TCP    192.168.0.118:8000     192.168.0.118:52195    ESTABLISHED     23400
> 94	  TCP    192.168.0.118:8000     192.168.0.118:52196    ESTABLISHED     23400
> 95	  TCP    192.168.0.118:8000     192.168.0.118:52197    ESTABLISHED     23400
> 96	  TCP    192.168.0.118:8000     192.168.0.118:52198    ESTABLISHED     23400
> 97	  TCP    192.168.0.118:8000     192.168.0.118:52199    ESTABLISHED     23400
> 98	  TCP    192.168.0.118:8000     192.168.0.118:52200    ESTABLISHED     23400
> 99	  TCP    192.168.0.118:8000     192.168.0.118:52201    ESTABLISHED     23400
> 100	  TCP    192.168.0.118:8000     192.168.0.118:52202    ESTABLISHED     23400
> 101	  TCP    192.168.0.118:8000     192.168.0.118:52203    ESTABLISHED     23400
> 102	  TCP    192.168.0.118:8000     192.168.0.118:52204    ESTABLISHED     23400
> 103	  TCP    192.168.0.118:8000     192.168.0.118:52205    ESTABLISHED     23400
> 104	  TCP    192.168.0.118:8000     192.168.0.118:52206    ESTABLISHED     23400
> 105	  TCP    192.168.0.118:8000     192.168.0.118:52207    ESTABLISHED     23400
> 106	  TCP    192.168.0.118:8000     192.168.0.118:52208    ESTABLISHED     23400
> 107	  TCP    192.168.0.118:8000     192.168.0.118:52209    ESTABLISHED     23400
> 108	  TCP    192.168.0.118:8000     192.168.0.118:52210    ESTABLISHED     23400
> 109	  TCP    192.168.0.118:8000     192.168.0.118:52211    ESTABLISHED     23400
> 110	  TCP    192.168.0.118:8000     192.168.0.118:52212    ESTABLISHED     23400
> 111	  TCP    192.168.0.118:8000     192.168.0.118:52213    ESTABLISHED     23400
> 112	  TCP    192.168.0.118:8000     192.168.0.118:52214    ESTABLISHED     23400
> 113	  TCP    192.168.0.118:8000     192.168.0.118:52215    ESTABLISHED     23400
> 114	  TCP    192.168.0.118:8000     192.168.0.118:52216    ESTABLISHED     23400
> 115	  TCP    192.168.0.118:8000     192.168.0.118:52217    ESTABLISHED     23400
> 116	  TCP    192.168.0.118:8000     192.168.0.118:52218    ESTABLISHED     23400
> 117	  TCP    192.168.0.118:8000     192.168.0.118:52219    ESTABLISHED     23400
> 118	  TCP    192.168.0.118:8000     192.168.0.118:52220    ESTABLISHED     23400
> 119	  TCP    192.168.0.118:8000     192.168.0.118:52221    ESTABLISHED     23400
> 120	  TCP    192.168.0.118:8000     192.168.0.118:52222    ESTABLISHED     23400
> 121	  TCP    192.168.0.118:8000     192.168.0.118:52223    ESTABLISHED     23400
> 122	  TCP    192.168.0.118:8000     192.168.0.118:52224    ESTABLISHED     23400
> 123	  TCP    192.168.0.118:8000     192.168.0.118:52225    ESTABLISHED     23400
> 124	  TCP    192.168.0.118:8000     192.168.0.118:52226    ESTABLISHED     23400
> 125	  TCP    192.168.0.118:8000     192.168.0.118:52227    ESTABLISHED     23400
> 126	  TCP    192.168.0.118:8000     192.168.0.118:52228    ESTABLISHED     23400
> 127	  TCP    192.168.0.118:8000     192.168.0.118:52229    ESTABLISHED     23400
> 128	  TCP    192.168.0.118:8000     192.168.0.118:52230    ESTABLISHED     23400
> 129	  TCP    192.168.0.118:8000     192.168.0.118:52231    ESTABLISHED     23400
> 130	  TCP    192.168.0.118:8000     192.168.0.118:52232    ESTABLISHED     23400
> 131	  TCP    192.168.0.118:8000     192.168.0.118:52233    ESTABLISHED     23400
> 132	  TCP    192.168.0.118:8000     192.168.0.118:52234    ESTABLISHED     23400
> 133	  TCP    192.168.0.118:8000     192.168.0.118:52235    ESTABLISHED     23400
> 134	  TCP    192.168.0.118:8000     192.168.0.118:52236    ESTABLISHED     23400
> 135	  TCP    192.168.0.118:8000     192.168.0.118:52237    ESTABLISHED     23400
> 136	  TCP    192.168.0.118:8000     192.168.0.118:52238    ESTABLISHED     23400
> 137	  TCP    192.168.0.118:8000     192.168.0.118:52239    ESTABLISHED     23400
> 138	  TCP    192.168.0.118:8000     192.168.0.118:52240    ESTABLISHED     23400
> 139	  TCP    192.168.0.118:8000     192.168.0.118:52241    ESTABLISHED     23400
> 140	  TCP    192.168.0.118:8000     192.168.0.118:52242    ESTABLISHED     23400
> 141	  TCP    192.168.0.118:8000     192.168.0.118:52243    ESTABLISHED     23400
> 142	  TCP    192.168.0.118:8000     192.168.0.118:52244    ESTABLISHED     23400
> 143	  TCP    192.168.0.118:8000     192.168.0.118:52245    ESTABLISHED     23400
> 144	  TCP    192.168.0.118:8000     192.168.0.118:52246    ESTABLISHED     23400
> 145	  TCP    192.168.0.118:8000     192.168.0.118:52247    ESTABLISHED     23400
> 146	  TCP    192.168.0.118:8000     192.168.0.118:52248    ESTABLISHED     23400
> 147	  TCP    192.168.0.118:8000     192.168.0.118:52249    ESTABLISHED     23400
> 148	  TCP    192.168.0.118:8000     192.168.0.118:52250    ESTABLISHED     23400
> 149	  TCP    192.168.0.118:8000     192.168.0.118:52251    ESTABLISHED     23400
> 150	  TCP    192.168.0.118:8000     192.168.0.118:52252    ESTABLISHED     23400
> 151	  TCP    192.168.0.118:8000     192.168.0.118:52253    ESTABLISHED     23400
> 152	  TCP    192.168.0.118:8000     192.168.0.118:52254    ESTABLISHED     23400
> 153	  TCP    192.168.0.118:8000     192.168.0.118:52255    ESTABLISHED     23400
> 154	  TCP    192.168.0.118:8000     192.168.0.118:52256    ESTABLISHED     23400
> 155	  TCP    192.168.0.118:8000     192.168.0.118:52257    ESTABLISHED     23400
> 156	  TCP    192.168.0.118:8000     192.168.0.118:52258    ESTABLISHED     23400
> 157	  TCP    192.168.0.118:8000     192.168.0.118:52259    ESTABLISHED     23400
> 158	  TCP    192.168.0.118:8000     192.168.0.118:52260    ESTABLISHED     23400
> 159	  TCP    192.168.0.118:8000     192.168.0.118:52261    ESTABLISHED     23400
> 160	  TCP    192.168.0.118:8000     192.168.0.118:52262    ESTABLISHED     23400
> 161	  TCP    192.168.0.118:8000     192.168.0.118:52263    ESTABLISHED     23400
> 162	  TCP    192.168.0.118:8000     192.168.0.118:52264    ESTABLISHED     23400
> 163	  TCP    192.168.0.118:8000     192.168.0.118:52265    ESTABLISHED     23400
> 164	  TCP    192.168.0.118:8000     192.168.0.118:52266    ESTABLISHED     23400
> 165	  TCP    192.168.0.118:8000     192.168.0.118:52267    ESTABLISHED     23400
> 166	  TCP    192.168.0.118:8000     192.168.0.118:52268    ESTABLISHED     23400
> 167	  TCP    192.168.0.118:8000     192.168.0.118:52269    ESTABLISHED     23400
> 168	  TCP    192.168.0.118:8000     192.168.0.118:52270    ESTABLISHED     23400
> 169	  TCP    192.168.0.118:8000     192.168.0.118:52271    ESTABLISHED     23400
> 170	  TCP    192.168.0.118:8000     192.168.0.118:52272    ESTABLISHED     23400
> 171	  TCP    192.168.0.118:8000     192.168.0.118:52273    ESTABLISHED     23400
> 172	  TCP    192.168.0.118:8000     192.168.0.118:52274    ESTABLISHED     23400
> 173	  TCP    192.168.0.118:8000     192.168.0.118:52275    ESTABLISHED     23400
> 174	  TCP    192.168.0.118:8000     192.168.0.118:52276    ESTABLISHED     23400
> 175	  TCP    192.168.0.118:8000     192.168.0.118:52277    ESTABLISHED     23400
> 176	  TCP    192.168.0.118:8000     192.168.0.118:52278    ESTABLISHED     23400
> 177	  TCP    192.168.0.118:8000     192.168.0.118:52279    ESTABLISHED     23400
> 178	  TCP    192.168.0.118:8000     192.168.0.118:52280    ESTABLISHED     23400
> 179	  TCP    192.168.0.118:8000     192.168.0.118:52281    ESTABLISHED     23400
> 180	  TCP    192.168.0.118:8000     192.168.0.118:52282    ESTABLISHED     23400
> 181	  TCP    192.168.0.118:8000     192.168.0.118:52283    ESTABLISHED     23400
> 182	  TCP    192.168.0.118:8000     192.168.0.118:52284    ESTABLISHED     23400
> 183	  TCP    192.168.0.118:8000     192.168.0.118:52285    ESTABLISHED     23400
> 184	  TCP    192.168.0.118:8000     192.168.0.118:52286    ESTABLISHED     23400
> 185	  TCP    192.168.0.118:8000     192.168.0.118:52287    ESTABLISHED     23400
> 186	  TCP    192.168.0.118:8000     192.168.0.118:52288    ESTABLISHED     23400
> 187	  TCP    192.168.0.118:8000     192.168.0.118:52289    ESTABLISHED     23400
> 188	  TCP    192.168.0.118:8000     192.168.0.118:52290    ESTABLISHED     23400
> 189	  TCP    192.168.0.118:8000     192.168.0.118:52291    ESTABLISHED     23400
> 190	  TCP    192.168.0.118:8000     192.168.0.118:52292    ESTABLISHED     23400
> 191	  TCP    192.168.0.118:8000     192.168.0.118:52293    ESTABLISHED     23400
> 192	  TCP    192.168.0.118:8000     192.168.0.118:52294    ESTABLISHED     23400
> 193	  TCP    192.168.0.118:8000     192.168.0.118:52295    ESTABLISHED     23400
> 194	  TCP    192.168.0.118:8000     192.168.0.118:52296    ESTABLISHED     23400
> 195	  TCP    192.168.0.118:8000     192.168.0.118:52297    ESTABLISHED     23400
> 196	  TCP    192.168.0.118:8000     192.168.0.118:52298    ESTABLISHED     23400
> 197	  TCP    192.168.0.118:8000     192.168.0.118:52299    ESTABLISHED     23400
> 198	  TCP    192.168.0.118:8000     192.168.0.118:52300    ESTABLISHED     23400
> 199	  TCP    192.168.0.118:8000     192.168.0.118:52301    ESTABLISHED     23400
> 200	  TCP    192.168.0.118:8000     192.168.0.118:52302    ESTABLISHED     23400
> 201	  TCP    192.168.0.118:8000     192.168.0.118:52303    ESTABLISHED     23400
> 202	  TCP    192.168.0.118:8000     192.168.0.118:52304    ESTABLISHED     23400
> 203	  TCP    192.168.0.118:8000     192.168.0.118:52305    ESTABLISHED     23400
> 204	  TCP    192.168.0.118:8000     192.168.0.118:52306    ESTABLISHED     23400
> 205	  TCP    192.168.0.118:8000     192.168.0.118:52307    ESTABLISHED     23400
> 206	  TCP    192.168.0.118:8000     192.168.0.118:52308    ESTABLISHED     23400
> 207	  TCP    192.168.0.118:8000     192.168.0.118:52309    ESTABLISHED     23400
> 208	  TCP    192.168.0.118:8000     192.168.0.118:52310    ESTABLISHED     23400
> 209	  TCP    192.168.0.118:8000     192.168.0.118:52311    ESTABLISHED     23400
> 210	  TCP    192.168.0.118:8000     192.168.0.118:52312    ESTABLISHED     23400
> 211	  TCP    192.168.0.118:8000     192.168.0.118:52313    ESTABLISHED     23400
> 212	  TCP    192.168.0.118:8000     192.168.0.118:52314    ESTABLISHED     23400
> 213	  TCP    192.168.0.118:8000     192.168.0.118:52315    ESTABLISHED     23400
> 214	  TCP    192.168.0.118:8000     192.168.0.118:52316    ESTABLISHED     23400
> 215	  TCP    192.168.0.118:8000     192.168.0.118:52317    ESTABLISHED     23400
> 216	  TCP    192.168.0.118:8000     192.168.0.118:52318    ESTABLISHED     23400
> 217	  TCP    192.168.0.118:8000     192.168.0.118:52319    ESTABLISHED     23400
> 218	  TCP    192.168.0.118:8000     192.168.0.118:52320    ESTABLISHED     23400
> 219	  TCP    192.168.0.118:8000     192.168.0.118:52321    ESTABLISHED     23400
> 220	  TCP    192.168.0.118:8000     192.168.0.118:52322    ESTABLISHED     23400
> 221	  TCP    192.168.0.118:8000     192.168.0.118:52323    ESTABLISHED     23400
> 222	  TCP    192.168.0.118:8000     192.168.0.118:52324    ESTABLISHED     23400
> 223	  TCP    192.168.0.118:8000     192.168.0.118:52325    ESTABLISHED     23400
> 224	  TCP    192.168.0.118:8000     192.168.0.118:52326    ESTABLISHED     23400
> 225	  TCP    192.168.0.118:8000     192.168.0.118:52327    ESTABLISHED     23400
> 226	  TCP    192.168.0.118:8000     192.168.0.118:52328    ESTABLISHED     23400
> 227	  TCP    192.168.0.118:8000     192.168.0.118:52329    ESTABLISHED     23400
> 228	  TCP    192.168.0.118:8000     192.168.0.118:52330    ESTABLISHED     23400
> 229	  TCP    192.168.0.118:8000     192.168.0.118:52331    ESTABLISHED     23400
> 230	  TCP    192.168.0.118:8000     192.168.0.118:52332    ESTABLISHED     23400
> 231	  TCP    192.168.0.118:8000     192.168.0.118:52333    ESTABLISHED     23400
> 232	  TCP    192.168.0.118:8000     192.168.0.118:52334    ESTABLISHED     23400
> 233	  TCP    192.168.0.118:8000     192.168.0.118:52335    ESTABLISHED     23400
> 234	  TCP    192.168.0.118:8000     192.168.0.118:52336    ESTABLISHED     23400
> 235	  TCP    192.168.0.118:8000     192.168.0.118:52337    ESTABLISHED     23400
> 236	  TCP    192.168.0.118:8000     192.168.0.118:52338    ESTABLISHED     23400
> 237	  TCP    192.168.0.118:8000     192.168.0.118:52339    ESTABLISHED     23400
> 238	  TCP    192.168.0.118:8000     192.168.0.118:52340    ESTABLISHED     23400
> 239	  TCP    192.168.0.118:8000     192.168.0.118:52341    ESTABLISHED     23400
> 240	  TCP    192.168.0.118:8000     192.168.0.118:52342    ESTABLISHED     23400
> 241	  TCP    192.168.0.118:8000     192.168.0.118:52343    ESTABLISHED     23400
> 242	  TCP    192.168.0.118:8000     192.168.0.118:52344    ESTABLISHED     23400

the data above means about 241 concurrent

@alashkin 
tks for reading this long post, waiting for your suggestion  :)

**Comment by alashkin** [comment]
Since it is Windows, 
Don't you just achieve sockets/select/FD_SET limit?
It is 64 on windows by default. Could you try to increase it?
https://msdn.microsoft.com/en-us/library/windows/desktop/ms739169(v=vs.85).aspx

I tried on my Ubuntu linux, works for ~500 connection and then stops to accept new connections - which i s ok for _my_ system

**Comment by yzsand** [comment]
@alashkin Tks ;)
It seems i forget mongoose is based on select mode.
Any IOCP plan on Windows?

**Comment by alashkin** [comment]
Oh.... we've already used 'epoll' for Linux once but later deleted this code  (read the whole story here: https://github.com/cesanta/mongoose/issues/722)
So, I think we don't have any plans for IOCP....

**Comment by yzsand** [comment]
That's OK
Thanks for this great project!
