### ISSUE TITLE
Mongoose MQTT broker example was crashed

### ISSUE THREAD

**Issue by spot62** [cesanta/mongoose#692]
Mongoose MQTT broker example was crashed by connecting the mosquitto clients (pub or sub)
Mongoose MQTT broker is not supported the side MQTT clients?

**Comment by alashkin** [comment]
Hi!
Just tried pub/sub with current master - seems work OK
Could you put repro steps here?

**Comment by alashkin** [comment]
Feel free to reopen this issue if current master still have this issue
