### ISSUE TITLE
Couple compilation warnings

### ISSUE THREAD

**Issue by vomikan** [cesanta/mongoose#694]
Using VS2015
mongoose.c(8969): warning C4706
mongoose.c(6923): warning C4100: envp:
mongoose.c(3283): warning C4456
mongoose.c(2338): warning C4245

1>..\..\3rd\mongoose\mongoose.c(2305): warning C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2238): note:  см. объявление "gethostbyname"
1>..\..\3rd\mongoose\mongoose.c(2317): warning C4996: 'inet_ntoa': Use inet_ntop() or InetNtop() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1868): note:  см. объявление "inet_ntoa"
1>..\..\3rd\mongoose\mongoose.c(2734): warning C4996: 'inet_ntoa': Use inet_ntop() or InetNtop() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1868): note:  см. объявление "inet_ntoa"
1>..\..\3rd\mongoose\mongoose.c(3285): warning C4996: 'inet_ntoa': Use inet_ntop() or InetNtop() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1868): note:  см. объявление "inet_ntoa"
1>..\..\3rd\mongoose\mongoose.c(3401): warning C4996: 'inet_ntoa': Use inet_ntop() or InetNtop() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1868): note:  см. объявление "inet_ntoa"
1>..\..\3rd\mongoose\mongoose.c(6923): warning C4100: envp: неиспользованный формальный параметр
1>..\..\3rd\mongoose\mongoose.c(7738): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
1>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\string.h(552): note:  см. объявление "strdup"
1>..\..\3rd\mongoose\mongoose.c(7909): warning C4996: 'inet_ntoa': Use inet_ntop() or InetNtop() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings

webserver.cpp(49): warning C4189: ret:

mongoose.c(1937): warning C4311: 
mongoose.c(149): warning C4244: функция: преобразование "int" в "char"
mongoose.c(1105): warning C4267: функция: преобразование из "size_t" в "int";

**Comment by alashkin** [comment]
Should be fixed in https://github.com/cesanta/mongoose/commit/238bf1a29e5121b42a084a810b8f9775a8299243
