### ISSUE TITLE
Support for HTTP/2 ?

### ISSUE THREAD

**Issue by patlecat** [cesanta/mongoose#695]
Do you have any plans to offer support for the upcoming protocol update on HTTP/2? Would be nice to know.

**Comment by cpq** [comment]
Yes we plan to implement HTTP/2, but that is not yet in our immediate schedule.
@patlecat can you elaborate more your interest please - are you working on a specific project that can benefit from HTTP/2 support ?

**Comment by patlecat** [comment]
I have planned to use mongoose for my project of an application server, it would be serving the HTML output in cases where the users do not want to use Apache or nginx. It is still in the planning phase yet. For users that want to create a webapp, security and speed of delivery will be important, that's why I asked for HTTP/2.

**Comment by himanshuPatel1973** [comment]
Does mongoose support HTTP 1.2 protocol

**Comment by cpq** [comment]
HTTP/2 is not yet on the roadmap.
Mongoose is primarily used on embedded devices, where low footprint is more important than performance.

**Comment by himanshuPatel1973** [comment]
Our application is to develop Apple push notification server and which works  on HTTP 2.0 and TLS 1.2. So that is  what  our  main requirement   to having both in Mongoose. is there  any alternate available to make it work?

**Comment by cpq** [comment]
We'd be happy to implement that on the commercial basis. Please contact us at support@cesanta.com if interested.

**Comment by himanshuPatel1973** [comment]
ok thanks!
