### ISSUE TITLE
Please add FTP client and server support.

### ISSUE THREAD

**Issue by Sanji008** [cesanta/mongoose#715]
No text xD

**Comment by ramstein74** [comment]
No news? bad news! I need an ftp client in Mongoose OS otherwise i wont mongoose any more...

**Comment by Sanji008** [comment]
Are there any News about FTP server/client or do you have plans to add it in the future?

**Comment by cpq** [comment]
Implementing FTP client is not the roadmap, since this is a very rarely asked feature.
However, we can do it on the commercial basis. Please https://mongoose-os.com/contact.html for that.
