### ISSUE TITLE
Why version 6.5 multithread use socket_pair?

### ISSUE THREAD

**Issue by xitaotao1991** [cesanta/mongoose#720]
In version 6.5, the mg_enable_multithreading enables multithread mode, and it uses mg_socketpair to create a socket pair,which sp[0] stays in main thread and used for copying data from current connection to sp[1],and another thread monitor sp[1] .
Why doesn't new thread monitor current connection after MG_ACCEPT,but use sockpair as transfer?

**Comment by alashkin** [comment]
Not sure I fully understand, what you mean by 
>Why doesn't new thread monitor current connection after MG_ACCEPT,but use sockpair as transfer?

But MG_ACCEPT issue was resolved in 6.6/current master

**Comment by alashkin** [comment]
Closed due to inactivity
