### ISSUE TITLE
load_balancer.c Segmentation fault under seige

### ISSUE THREAD

**Issue by shsssc** [cesanta/mongoose#725]
I did a stress test. Put the load_balancer example under siege. When I stop the Siege process, the load_balancer process stopped

> # ./load_balancer -p 8080 -b / 138.68.55.1:80
> Adding backend for / : 138.68.55.1:80 [redirect=0,prefix_replacement=/]
> Starting LB on port 8080
> Segmentation fault

**Comment by cpq** [comment]
Could you elaborate on your environment please?

**Comment by shsssc** [comment]
I am running on kali2 
>\# uname -a
Linux **** 4.7.0-kali1-amd64 \#1 SMP Debian 4.7.6-1kali1 (2016-10-17) x86_64 GNU/Linux

I also tested on ubuntu 16 and it worked well
It doesn't look like a common problem
It's weird that the program crash only when I stop siege, instead of under it

**Comment by cpq** [comment]
@shsssc we have a new API for making reverse proxying, with relevant example.
@alex let's kill this example and close this bug

**Comment by alashkin** [comment]
Example deleted
