### ISSUE TITLE
Improvements to docs consumability - sort API names alphabetically

### ISSUE THREAD

**Issue by nkolban** [cesanta/mongoose#726]
I find myself a little frustrated when working with the documentation on mongoose.  For example,
visit here:

https://docs.cesanta.com/mongoose/master/#/c-api/http_server.h//

And we see a list of API function names on the left.  This is great.  However notice that they are not sorted alphabetically.  When I am reading and looking for something, I find I have to parse/scan the whole list and often miss what I am looking for.  I believe that if they were sorted alphabetically, they would be more consumable.   Here is an example screen shot of what I am seeing today:

![2016-10-25_14-00-38](https://cloud.githubusercontent.com/assets/3421732/19700249/3be56f3a-9abc-11e6-9948-8de98cf1184d.jpg)

**Comment by harivasista** [comment]
Is the above documentation moved ?? Or is this a part of different license ??
