### ISSUE TITLE
Version 6.6 cs_log_set_level() no longer accessible

### ISSUE THREAD

**Issue by dlkeng** [cesanta/mongoose#730]
After upgrading to Mongoose Version 6.6 from Version 6.5, code fails to compile when calling `cs_log_set_level()`. It appears the prototype for `cs_log_set_level()` and its companion `enum cs_log_level` values are no longer in `mongoose.h`, but are now in `mongoose.c` and are no longer externally accessible!

**Comment by alashkin** [comment]
Yes, `cs_log_set_level()` is an internal API.
To control mongoose debug output use `CS_ENABLE_STDIO`, `CS_ENABLE_DEBUG` and `CS_LOG_TS_DIFF` pre-processor macros.
