### ISSUE TITLE
use of mqtt broker over websocket and QOS

### ISSUE THREAD

**Issue by cordovapolymer** [cesanta/mongoose#737]
Hi, mongoose is very promissing,
could it's mqtt broker be used over secure websocket? 
What QOS levels does the MQTT implementation support?

**Comment by alashkin** [comment]
Hi!
At this moment, MQTT implementation doesn't support MQTT over WebSocket - only over TCP, but it supports SSL though 
As for QoS, can say it supports QoS 1, but keep in mind, that Mongoose is not MQTT just broker - it is Networking Library, thus, it can be expanded to support  QoS 0 and 2 as well.

**Comment by mmikulicic** [comment]
@cordovapolymer, in which environment/platform do need a MQTT broker with WebSocket support ?

**Comment by cordovapolymer** [comment]
I'd like to use it on Debian linux jessie/stretch as a broker for android clients which are written in javascript so its very convenient to use MQTT over WebSocket.

**Comment by alashkin** [comment]
@cordovapolymer Can we close this issue? Or you have additional questions?

**Comment by cpq** [comment]
@cordovapolymer could you elaborate on your project please? What is the use case? Is your project commercial/personal? Thanks!

**Comment by cpq** [comment]
We have put together an example for mqtt over websocket server.
https://github.com/cesanta/mongoose/tree/dev/examples/mqtt_over_websocket_server
Only QOS0 is supported.

**Comment by cordovapolymer** [comment]
@cpq Do you plan to support QOS1&2?
