### ISSUE TITLE
Segmentation fault with "multithreaded restful server" example (Linux + Windows)

### ISSUE THREAD

**Issue by ffilipus** [cesanta/mongoose#738]
When trying to connect server from "multithreaded restful server" example SIGSEGV appears on the same line for Linux and Windows:
```
(gdb) continue 
Continuing.
Starting multi-threaded server on port 8000

Program received signal SIGSEGV, Segmentation fault.
0x0000000000407e2c in mg_create_connection_base (mgr=0x7fffffffcef0, callback=0x40c6ab <forwarder_ev_handler>, opts=...)
    at ../../mongoose.c:2236
2236	        (opts.iface != NULL ? opts.iface : mgr->ifaces[MG_MAIN_IFACE]);
```
After connection SIGSEGV signal is thrown.
Linux: Fedora21 x64, gcc 4.9.2
Windows: Windows 2008 R2 x64,  mingw64 gcc 7.0.0

**Comment by alashkin** [comment]
Fixed in f45d9832a884374f6f9ea3f2e0a8c9465f214896
