### ISSUE TITLE
multipart messages and MG_EV_HTTP_PART_END 

### ISSUE THREAD

**Issue by jvalenzu** [cesanta/mongoose#743]
Howdy;

Based on the big_upload example code and the comments in mongoose.h for mg_set_protocol_http_websocket, I expected the following sequence of events when handling incoming multipart connections:

  MG_EV_HTTP_PART_BEGIN - multipart encoded boundary initiating part 1
  MG_EV_HTTP_PART_DATA  - continuation of data for part 1
  MG_EV_HTTP_PART_BEGIN - multipart encoded boundary initiating part 2
  MG_EV_HTTP_PART_DATA  - continuation of data for part 2
  MG_EV_HTTP_PART_END   - finalization receipt of all data, close connection

mg_http_multipart_process_boundary, however, contains the following block which gets called for all but the first boundaries:

```
      if (pd->mp_stream.processing_part != 0) {
         mg_http_multipart_call_handler(c, MG_EV_HTTP_PART_END, NULL, 0);
      }
```

processing_part is incremented each time a boundary is encountered and never cleared or decremented - this implies (to me anyway) that it expects MG_EV_HTTP_PART_END to be sent to indicate the close of each part.  If that were the case, though, it's not clear on which MG_EV_HTTP_PART_END the connection is meant to be closed.

For my immediate purposes I commented out the quoted test and handled the events as detailed above.  I'm not super familiar with mongoose so I expect I'm probably just misunderstanding something about the API.  If that's the case I'm hoping y'all can set me straight.  Thanks.

**Comment by rojer** [comment]
it's actually like this:
MULTIPART_REQUEST
PART_BEGIN
PART_DATA (1 or more times)
PART_END
PART_BEGIN
PART_DATA (1 or more times)
PART_END
...
REQUEST_END
