### ISSUE TITLE
Missing Unit Test Suite

### ISSUE THREAD

**Issue by jonahharris** [cesanta/mongoose#745]
First, I'd like to say thank you for committing your amalgamation tools; they are *extremely* helpful! Honestly, you should publish those as separate tools altogether. As a longtime C developer, I've used and written several amalgamation tools, but none as good as yours.

Second, on the topic of this issue, would you be able to commit your Mongoose unit tests? At present, I'm testing using a modified version of the old Fossa unit test suite, which works but isn't consistent with what you have internally.

Thanks again!

**Comment by mmikulicic** [comment]
would it be acceptable for you if you had to clone a submodule containing the test utils ?

**Comment by osDanielLee** [comment]
@jonahharris I totally agree with you about add unit test suite thing, even it isn't useful for user, but here, all the people wants to commit code for this project would be happy to see that.

**Comment by jonahharris** [comment]
@mmikulicic any way we to get a copy of the unit test suite?

**Comment by jonahharris** [comment]
You guys rock. Thanks!

**Comment by dimonomid** [comment]
Actually, even though I added tests to the public repo, I realized they don't work from the public repo due to a few differences between public and private repo. :) Hopefully will fix it soon.

**Comment by dimonomid** [comment]
Now, finally, tests work from the public repo. :)
