### ISSUE TITLE
Add a method to modify connect default time in non-blocking mode

### ISSUE THREAD

**Issue by datonli** [cesanta/mongoose#749]
When I used mongoose in my project, I found a client try to connect a server with a wrong ip didn't exist, the timeout returned need a minute at least. Then I learnt the source code and know the reason. Due to control the timeout by user setting, I add some code in mongoose.c and mongoose.h,  and pull a request but no one handle. So I create a issue here for knowing if anyone else also need this feature, and hope the members of mongoose project to take a note for it.

Any question including assisting test is welcome and feel free to talk me that.

My pull request (https://github.com/cesanta/mongoose/pull/747)

**Comment by psykokwak-com** [comment]
Seems this PR does not work.
Does any one has a solution for that ?

**Comment by psykokwak-com** [comment]
Ok. I "fixed" this issue using a timer : 

```
void TCVideoClientStonkam::mgHandler(struct mg_connection *nc, int ev, void *evdata)
{
  switch (ev) {
  case MG_EV_CONNECT:
    SDL_Log("TCVideoClientStonkam::MG_EV_CONNECT");
    break;

  case MG_EV_CLOSE:
    _connectionWasClosed = true;
    break;

  case MG_EV_TIMER:
    if (nc->flags & MG_F_CONNECTING)
      nc->flags |= MG_F_CLOSE_IMMEDIATELY;
    break;
  }
}
```


```
    mg_connection *nc = mg_connect_ws_opt(&mgr, _mghandlerfn, opts, url.c_str(), "MyApp", NULL);
    if (!nc)
      continue;

    mg_set_timer(nc, 1000));

    _connectionWasClosed = false;
    while (_networkThreadRunning && !_connectionWasClosed)
    {
      mg_mgr_poll(&mgr, 100);
    }
```

**Comment by cpq** [comment]
Closing this.
Using timers is a correct way to handle the issue.
