### ISSUE TITLE
Second NTLM Response from browser not being sent as web socket handshake request

### ISSUE THREAD

**Issue by tfgsupport** [cesanta/mongoose#750]
Hi,

This is a follow up to #734 . 

I amended the 401 challenge to return the NTLM WWW-Authenticate header before it returns the Negotiate WWW-Authenticate header as below. The initial NTLM authorization header response generated by the browser is now received by Mongoose as a MG_EV_WEBSOCKET_HANDSHAKE_REQUEST.

I am using the authorisation header to generate a second challenge for the browser as below. The second NTLM authorization header response generated by the browser is being received by Mongoose as MG_EV_RECV (Data has been received) but never as  MG_EV_WEBSOCKET_HANDSHAKE_REQUEST which is what I was expecting. Why is this? Any help is much appreciated.

**Initial Challenge to browser**

```
HTTP/1.1 401 Unauthorized
WWW-Authenticate: NTLM
WWW-Authenticate: Negotiate
Connection: close
Content-Type: text/html
Content-Length: 0

```
**Initial Response from browser**

```
GET / HTTP/1.1
Origin: http://127.0.0.1:8000
Sec-WebSocket-Key: MOCwFiVuCQL0mGy+7BxjhQ==
Connection: Upgrade
Upgrade: Websocket
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Host: 127.0.0.1:8000
DNT: 1
Cache-Control: no-cache
Authorization: NTLM ********************************************
```

**Second Challenge to browser**
```

HTTP/1.1 401 Unauthorized
WWW-Authenticate: NTLM ***************************************************
Connection: keep-alive
Keep-Alive: timeout=15, max=4996Content-Type: text/html
Content-Length: 0
```

**Second Response from browser**

```
GET / HTTP/1.1
Origin: http://127.0.0.1:8000
Sec-WebSocket-Key: MOCwFiVuCQL0mGy+7BxjhQ==
Connection: Upgrade
Upgrade: Websocket
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Host: 127.0.0.1:8000
DNT: 1
Cache-Control: no-cache
Authorization: NTLM 

**************************************************************************************
```

**Comment by tfgsupport** [comment]
Thankyou Deomid for helping to resolve.

A short summary of the resolution:

As it takes two roundtrips to perform the authentication, you need to close the connection after the first one. If you need more roundtrips, you should respond with 401, close the connection to force client to re-connect and mg websocket handling to re-init, then on second request (in a new connection), if you're happy with th challenge repsonse this time, allow the handshake to proceed. The handshake is a one time event in the life of a websocket connection! If it is accepted, there will be no further HTTP requests of any kind.

You should mg-printf the http response and |= MG_F_SEND_AND_CLOSE flag. This will flush send_mbuf and close the connection.

**Comment by rojer** [comment]
yes, this was resolved on chat.
thanks for the summary!
