### ISSUE TITLE
user_data assigned to an mg_mgr not available through a new connection in multithreaded mode

### ISSUE THREAD

**Issue by dsmccall** [cesanta/mongoose#756]
I've tried to attach some user_data to an mg_mgr object.  I then try to retrieve that data in my event_handler - this works absolutely fine in single-threaded mode, but the c->mgr->user_data pointer is null is multi-threaded mode.

    #include "mongoose.h"

    static const char *s_http_port = "8000";

    static void ev_handler(struct mg_connection *c, int ev, void *p) {
        if (ev == MG_EV_HTTP_REQUEST) {
            struct http_message *hm = (struct http_message *) p;
            char reply[100];

            // Get user data from connection manager
            int* simple_user_data = (int*)c->mgr->user_data;

            /* Send the reply */
            snprintf(reply, sizeof(reply), "{ \"simple user data\": \"%i\" }\n", *simple_user_data);
            mg_printf(c,
                "HTTP/1.1 200 OK\r\n"
                "Content-Type: application/json\r\n"
                "Content-Length: %d\r\n"
                "\r\n"
                "%s",
                (int)strlen(reply), reply);
        }
    }

    int main(void) {
        struct mg_mgr mgr;
        struct mg_connection *nc;

        int simple_user_data = 12345;

        mg_mgr_init(&mgr, (void*)&simple_user_data);
        nc = mg_bind(&mgr, s_http_port, ev_handler);
        mg_set_protocol_http_websocket(nc);

        /* For each new connection, execute ev_handler in a separate thread */
        //mg_enable_multithreading(nc);

        printf("Starting multi-threaded server on port %s\n", s_http_port);
        for (;;) {
            mg_mgr_poll(&mgr, 3000);
        }
        mg_mgr_free(&mgr);

        return 0;
    }

**Comment by mat007** [comment]
Hi,

I don't know whether this issue is a bug or not, however you can work around it by using the connection user data, e.g. binding like this:

    mg_bind_opts opts;
    memset( &opts, 0, sizeof( opts ) );
    opts.user_data = &simple_user_data;
    nc = mg_bind_opt( &mgr, s_http_port, ev_handler, opts );

Then in the event handler you simply retrieve the user data like this:

    int* simple_user_data = (int*)c->user_data;

I hope this helps.

**Comment by dsmccall** [comment]
It does indeed help, and I can also work around it by attaching directly to the user_data pointer of the new connection after the call.

    nc->user_data = (void*)this;

You may be right that this isn't a bug - however, it seems inconsistent that it works in single-threaded mode but not in multi-threaded.  That may well be the intended operation!

Thank you for your help, very much appreciated.

**Comment by cpq** [comment]
Closing, as multithreaded mode is no more.
