### ISSUE TITLE
ESP32 Support

### ISSUE THREAD

**Issue by forthlightning** [cesanta/mongoose#760]
Hello! 

I read around your docs, and see that there is ESP32 support forthcoming. So happy to hear that.

Any timeline on when this functionality will be available?

**Comment by rojer** [comment]
it is being actively worked on, some basic functionality should be available at the end of this week.

**Comment by rojer** [comment]
ESP32 is now fully supported by mongoose networking library and there is basic support for mongoose-iot as well.
