### ISSUE TITLE
windows 6.5 binary in windows 10 x64 unable to handle non-latin characters

### ISSUE THREAD

**Issue by JugglerLKR** [cesanta/mongoose#763]
It just returns Open failed

**Comment by MrDolch** [comment]
I've got the same problem when I try to deliver files with french or spanish letters like è or ñ. Even if I use encoded URIs.

**Comment by dimonomid** [comment]
Can't reproduce on Mongoose 6.9 so I assume it's fixed, could you confirm please?

**Comment by cpq** [comment]
Please use the latest binary.
