### ISSUE TITLE
External runloop integration

### ISSUE THREAD

**Issue by wenq1** [cesanta/mongoose#764]
We're using mongoose to get data from a websocket connection. Mongoose acts as a client. The data arrives at a variable rate, so we don't know beforehand what's the best timeout to use. The range is usually be between 10ms and 2000ms.

````
        mg_mgr_init (&mgr, NULL);
        for (;;) {
                mg_mgr_poll (&mgr, 10); // timeout cannot be determined for most optimized results
        }
````

On the thread of interest we actually have a epoll based custom event loop. I wonder if there is a fd that can be exposed so that we could simply add that to the epoll watch list, ie is the following pattern feasible?

````
    mg_mgr_init (&mgr, NULL);
    mg_nc = mg_connect_ws (&mgr, ev_handler, "ws://samplews.org, NULL, NULL);  
    int     epfd   = epoll_create (1);
    epoll_ctl (epfd, EPOLL_CTL_ADD, mg_nc->sock_fd, &ep_event)
    for (;;) {
        epoll_wait (...)
        if (got_event && is_mg_event) {
             mg_mgr_poll (&mgr, 0);   // to invoke handlers
        }
    }

````

**Comment by cpq** [comment]
You can traverse all mongoose connections and add fds to your epoll.
