### ISSUE TITLE
Is json-rpc ditched? 

### ISSUE THREAD

**Issue by wtiandong** [cesanta/mongoose#777]
Hi,
I notice that json-rpc has been ditched since Jul 1, 2016. Could anyone tell me why? I use it in my project and feel it's good. It's lightweight, easy to use. (Although the json APIs are hard to use ... but it's still good).

BR,
Tiandong

**Comment by cpq** [comment]
JSON-RPC was refactored into a separate library:
https://github.com/cesanta/frozen
