### ISSUE TITLE
CGI should use _exit instead of exit

### ISSUE THREAD

**Issue by stromnet** [cesanta/mongoose#779]
If the CGI execle fails (in child process), it will respond with a 500 error, and then call exit(EXIT_FAILURE);
This is bad in a C++ program, which may have global destructors and/or other atexit functions registered in the parent process, which we most likely do not want to call.

For example, I have a program which uses another library (Qpid) which has a static global object, who's destructor is called in case of any request to a non-existing CGI file.

Solution: _exit() should be used instead of exit()

http://www.unixguide.net/unix/programming/1.1.3.shtml

**Comment by cpq** [comment]
Makes sense!
@alashkin  could you make a change please?
