### ISSUE TITLE
WinCE EAGAIN not defined

### ISSUE THREAD

**Issue by Ataginsky** [cesanta/mongoose#792]
Hi,

For **Windows CE** Plateform, the **EAGAIN** is not defined.

**Solutions:**
1) Define it like you do it for **ENOENT**, **EACCES** and **ENOMEM** directly in mongoose.h (section WINCE).

Or

2)
Include the errno.h in **WINCE** section (at line 1222 for ex.)
**#include <errno.h>**

**Comment by cpq** [comment]
@alashkin please take this!

**Comment by alashkin** [comment]
Fixed in e9a7a2af1800955c808749bf9ed93e30ebd96ea2
