### ISSUE TITLE
Does Mongoose close the TCP connection using MG_EV_CLOSE shortly in bad network conditions?

### ISSUE THREAD

**Issue by sfutcha** [cesanta/mongoose#798]
Hello,

I have a setup where the use case is in the mining industry, there fore, subject to poor network coverage. I am using Mongoose 6.0, a server on an electronic device located behind a switch + router. Clients (on Chrome browser), outside the router communicate with the mongoose server.  I did several tests scenarios.

Scenario 1: Using a tablet (client) to access webpage info through the server.
The tablet was connected to the server locally (ie no internet) using wireless. I walked far from the server to simulate poor network and then close. Loosing the connectivity for around 18 seconds or more resulted in the client not being able to receive updates from server even when it is close.

Scenario 2: Simulating poor network on a desktop
From a client desktop physically connected to the server via router + switch, I unplugged the cable between the router and the switch ( so not shutting down directly the network interface of the client) I was able to replicate what I saw in scenario 1 ie that the mongoose server shuts down the TCP connection after approximately 18 seconds which is too short.

My questions:
1. Under which condition Mongoose closes the connection using MG_EV_CLOSE (network connectivity poor)? In my setup, the client sends a heartbeat to the server every 15 seconds to make sure communication is still alive between client and server.  When I simulated a lost of connectivity of about 5 seconds, it was fine ( ie lost of  1 client heartbeat). The issue raised when I do not receive the client's hearbeat for 2 times.

2. Is it possible to configure that timeout (18 sec more or less) to be longer, for example 1 minute?

Thanks.

**Comment by cpq** [comment]
1. The question is for the TCP/IP stack, not mongoose. It depends on various parameters of the OS
2. It might be possible using TCP keep-alive functionality - some OSes provide API for setting timeouts.
