### ISSUE TITLE
mongoose.c: PVS-Studio: CWE-476 Dereferencing of the null pointer 'nc' might take place.

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [cesanta/mongoose#801]
We have found a weakness using PVS-Studio tool. [PVS-Studio](https://www.viva64.com/en/pvs-studio/) is a static code analyzer for C, C++ and C#.

We suggests having a look at the emails, sent from @pvs-studio.com.

Analyzer warning: [V522](https://www.viva64.com/en/w/V522/) Dereferencing of the null pointer 'nc' might take place. mongoose.c 2562

```
void mg_if_recv_udp_cb(struct mg_connection *nc, void *buf, int len,
                       union socket_address *sa, size_t sa_len) {
  ....
  if (nc != NULL) {                      // <=
    mg_recv_common(nc, buf, len, 1);
  } else {
    /* Drop on the floor. */
    MG_FREE(buf);
    nc->iface->vtable->recved(nc, len);  // <= ???
  }
}
```

**Comment by dimonomid** [comment]
Thanks, fixed in https://github.com/cesanta/mongoose/commit/228984a3fc6171cc6804951c1cbb22b922eaca51
