### ISSUE TITLE
mongoose.c: PVS-Studio: CWE-476 The 'path_info' pointer was utilized before it was verified against nullptr.

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [cesanta/mongoose#802]
We have found a weakness using PVS-Studio tool. [PVS-Studio](https://www.viva64.com/en/pvs-studio/) is a static code analyzer for C, C++ and C#.

We suggests having a look at the emails, sent from @pvs-studio.com.

Analyzer warning: [V595](https://www.viva64.com/en/w/V595/) The 'path_info' pointer was utilized before it was verified against nullptr. Check lines: 8125, 8135. mongoose.c 8125

```
static void mg_prepare_cgi_environment(....) {
  ....

  s = hm->uri.p + hm->uri.len - path_info->len - 1; // <= ???
  if (*s == '/') {
    ....
  }

  if (path_info != NULL && path_info->len > 0) {    // <=
    mg_addenv(blk, "PATH_INFO=%.*s", (int) path_info->len, path_info->p);
    /* Not really translated... */
    mg_addenv(blk, "PATH_TRANSLATED=%.*s", (int) path_info->len, path_info->p);
  }
  ....
}
```

**Comment by dimonomid** [comment]
Thanks, fixed in https://github.com/cesanta/mongoose/commit/ce8657f12f215f910dbbce754f515baaf29f7994
