### ISSUE TITLE
SSI functions do not respect MG_MAX_HTTP_REQUEST_SIZE

### ISSUE THREAD

**Issue by anyn99** [cesanta/mongoose#803]
The SSI handling functions are basically putting the whole request into send_mbuf. This can lead to oom failures on memory constrained devices quite easily, especially when the ssi #includes stack up.

I'm about to refactor the code to work with the mechanisms of mg_http_transfer_file_data(),which is streaming the files over multiple polls.

**Comment by cpq** [comment]
Closing this. Feel free to reopen when refactoring is done.
