### ISSUE TITLE
Requested file transfer size in log file can't be right

### ISSUE THREAD

**Issue by Sum-Guy** [cesanta/mongoose#805]
I'm using mongoose on a windows 98 machine to serve dummy php pages to scanning bots to see if they will choke on large files when they request various php files, robots.txt, the default file, etc.  My files are 50 mb and 100 mb.  I'm seeing some bots access the files as intended, but the mongoose log file seems to indicate they are getting the entire file in a matter of seconds, which can't be right.

So I'm wondering if the byte-size in the mongoose log file is just the file-size and not necessarily the number of bytes that was transfered to the requesting system.

**Comment by cpq** [comment]
Mongoose is open source, you can always check the source.
