### ISSUE TITLE
undefined reference to `cs_md5' with mongoose + v7 

### ISSUE THREAD

**Issue by grodansparadis** [cesanta/mongoose#806]
With the head code I get 

undefined reference to `cs_md5'

on Linux when compiling a project where both mongoose.c and v7 is present and are compile with 
-D EXCLUDE_COMMON 

As far as I can see 

char *cs_md5(char buf[33], ...)

should be declared outside the EXCLUDE_COMMON block in mongoose.c

**Comment by cpq** [comment]
Please use cs_md5_init / cs_md5_transform / cs_md5_final , which have the same signatures as MD5_*

**Comment by grodansparadis** [comment]
OK will do.  mongoose.c will still complain though about undefined cs_md5 when EXCLUDE_COMMON is defined.
