### ISSUE TITLE
mg_http_check_digest_auth() fails with libcurl client

### ISSUE THREAD

**Issue by andrewkirillov** [cesanta/mongoose#813]
I had a client application based on libcurl and it was failing to do digest authentication with mongoose web server. Enabling verbose mode in libcurl and checking HTTP headers, found that it sends longer client nonce than mongoose could handle. libcurl was sending 44 characters long client nonce. While mg_http_check_digest_auth() expects maximum 32 characters long.

**Comment by cpq** [comment]
Closing this.
The latest code has only basic auth.
