### ISSUE TITLE
using connect opts

### ISSUE THREAD

**Issue by rollen1960** [cesanta/mongoose#817]
I am writing a client with http and / or ws protocols.

If I use
		c = mg_connect_http(Mongoose_mgr, Mongoose_ev_handler, url.c_str(), headers.c_str(), request.c_str());

work but if I use

	        struct mg_connect_opts opts;
	        memset(&opts, '\0', sizeof(struct mg_connect_opts));
		c = mg_connect_http_opt(Mongoose_mgr, Mongoose_ev_handler, opts, url.c_str(), headers.c_str(), request.c_str());

it crash.

Why ?

**Comment by PpvAlx** [comment]
Try to set mg_connect_opts.error_string.

**Comment by rollen1960** [comment]
I probe:

        struct mg_connect_opts opts;
        memset(&opts, '\0', sizeof(struct mg_connect_opts));
        const char* error;
        opts.error_string = &error;
	c = mg_connect_http_opt(Mongoose_mgr, Mongoose_ev_handler, opts, url.c_str(), headers.c_str(), request.c_str());

but I receive c == NULL 

Why ? How can I read the error message ?

**Comment by dimonomid** [comment]
You can read the error message by printing it:
```
printf("%s", error);
```

**Comment by rollen1960** [comment]
I can no read the message because it crash in the mg_connect_http_opt routine.

**Comment by dimonomid** [comment]
Previously you said

> but I receive c == NULL

So I assumed that `mg_connect_http_opt` actually returns.

**Comment by cpq** [comment]
Closing this.

Note that the API has changed since 7.0 release.
