### ISSUE TITLE
Query-string in reverse proxy

### ISSUE THREAD

**Issue by mortegai** [cesanta/mongoose#818]
In a reverse proxy (either with the _mg_http_reverse_proxy_ function method or with the _url_rewrites_ option method) the query string (such as _parm1=val1&parm2=val2_ in /api?parm1=val1&parm2=val2) are not passed to the backend server.

What is the way to do it?

**Comment by cpq** [comment]
I believe https://github.com/cesanta/mongoose/commit/fea648496cf134a1aedddd81ee35bbc05e39853a fixes it.

**Comment by mortegai** [comment]
I don't think so. Tests do not work.
I think something must be done in:

7316    / * Send request upstream * /
 7317  mg_printf(be, "%.*s %.*s HTTP/1.1\r\n", (int) hm->method.len, hm->method.p,
  7318                   (int) path.len, path.p);
