### ISSUE TITLE
Documentation of ev_data for multipart events

### ISSUE THREAD

**Issue by nkolban** [cesanta/mongoose#820]
I'm studying the documentation on HTTP events found here:
https://docs.cesanta.com/mongoose/master/#/http/events.md/

As I read about MG_EV_HTTP_MULTIPART_REQUEST, MG_EV_HTTP_PART_BEGIN, MG_EV_HTTP_PART_DATA and MG_EV_HTTP_PART_END ... the docs don't tell me what I can expect to find in the ev_data for the callback.

This issue suggests that this be documented at this section of the documentation.

**Comment by cpq** [comment]
Closing this.

Since 7.0, mongoose does not offer multipart handling. File upload mechanism is described at https://cesanta.com/docs/#mg_http_upload
