### ISSUE TITLE
select vs poll

### ISSUE THREAD

**Issue by rollen1960** [cesanta/mongoose#839]
I try to open more then 1024 connection on the same server. It crash or don't works.

The library use select, is 1024  a limit for open connection (FD_SETSIZE) ?
Is possible to increment this limit ?
Is possible use poll that has no limit ?

Thank you Mario

**Comment by zhaojh329** [comment]
Evmongoose based on the libev  is recommended.
[evmongoose](https://github.com/zhaojh329/evmongoose)

**Comment by cpq** [comment]
On POSIX, mongoose uses select.
You can implement your own multiplexing mechanism,  see mg_socket_if_poll()
