### ISSUE TITLE
Mongoose (Windows, 6.5) can't serve content with non-ascii path/file name.

### ISSUE THREAD

**Issue by RadarNyan** [cesanta/mongoose#846]
**Can't start mongoose server if the executable is placed under a path ends with non-ascii character**

> I placed mongoose executable (mongoose-free-6.5.exe) under "B:\测试", when I run the program I got the following message:
> 
> ```text
> ---------------------------
> Warning
> ---------------------------
> Invalid path for document_root: [B:\豬玖ｯ・]: (No such file or directory). Make sure that path is either absolute, or it is relative to mongoose executable.
> ---------------------------
> OK   
> ---------------------------
> ```
> And then Mongoose still runs, the tray menu shows a wrong path "B:\测试**E**"
> Even if I manually select the path after mongoose is started, it still won't work.
> So I tried to rename the folder and found out that if the path ends with ascii character, even if it contains non-ascii characters, for example: "B:\测试a" then mongoose will work. **However, it only works when mongoose executable is placed under that folder** - "Set shared directory" from tray menu won't work in this case.

**Can't serve any content if it has non-ascii file name.**

> I started mongoose from a full ascii path (B:\test) with no problem.
> If I try access any content with non-ascii file name, like "http://192.168.2.31:8080/测试.html" it will return 404 with message "Open failed".
> In this case, even if the file name ends with ascii character, as long as there is non-ascii characters in the file name, it won't be served, only full ascii file name works.

**Comment by dimonomid** [comment]
Can't reproduce on Mongoose 6.9 under Windows (I copy-pasted the name you provided).
