### ISSUE TITLE
WebServer SSL handshake failure

### ISSUE THREAD

**Issue by tfgsupport** [cesanta/mongoose#847]
Hi,
I have an exisiting Mongoose WebServer using HTTP and NTLM authentication. I need to extend the functionality to have connection over HTTPS. I am now using 6.7

I have tried a various ways to get an active connection but they all seem to fail.
When sending a REST message, a connection is opened and it tries to process the incoming buffer, but mg_http_get_request_len always returns -1, malformed request. The connect is then closed.

I tried using openssl client to see if the certificate was being sent, but I get a handsake error
openssl.exe s_client -ssl2 -connect localhost:8443
Loading 'screen' into random state - done
CONNECTED(000001E8)
1476:error:1407F0E5:SSL routines:SSL2_WRITE:ssl handshake failure:.\ssl\s2_pkt.c:428:

I have now just tried mimicking the simple ssl solution from the provided examples, but I get the same result. 
I assume I have missed something obvious, but I just can't overcome this one.

#define MG_ENABLE_SSL 1

#include "mongoose.h"
using namespace std;

static const char *s_http_port = "8443";
static const char *s_ssl_cert = "server.pem";
static const char *s_ssl_key = "server.key";
static struct mg_serve_http_opts s_http_server_opts;

static void ev_handler(struct mg_connection *nc, int ev, void *p) {
	if (ev == MG_EV_HTTP_REQUEST) {
		mg_serve_http(nc, (struct http_message *) p, s_http_server_opts);
	}
	if (ev == MG_EV_CONNECT)
	{
		std::cout << "connected " << std::endl;
	}
	if (ev == MG_EV_SEND)
	{
		std::cout << "SEND " << std::endl;
		struct http_message *hm = static_cast<struct http_message *>(p);
		const std::string data(hm->body.p, hm->body.len);
		std::cout << data.c_str() << std::endl;
	}
	if (ev == MG_EV_CLOSE)
	{
		std::cout << "closed conn" << std::endl;
	}

	if (ev == MG_EV_ACCEPT)
	{
		std::cout << "accept conn" << std::endl;
	}

}

int APIENTRY WinMain(HINSTANCE /* hInstance */,
	HINSTANCE /* hPrevInstance */,
	LPTSTR /* lpCmdLine */,
	int /* nCmdShow */)
{
	struct mg_mgr mgr;
	struct mg_connection *nc;
	struct mg_bind_opts bind_opts;
	const char *err;

	mg_mgr_init(&mgr, NULL);
	memset(&bind_opts, 0, sizeof(bind_opts));
	bind_opts.ssl_cert = s_ssl_cert;
	bind_opts.ssl_key = s_ssl_key;
	bind_opts.error_string = &err;

	printf("Starting SSL server on port %s, cert from %s, key from %s\n",
		s_http_port, bind_opts.ssl_cert, bind_opts.ssl_key);
	nc = mg_bind_opt(&mgr, s_http_port, ev_handler, bind_opts);
	if (nc == NULL) {
		printf("Failed to create listener: %s\n", err);
		return 1;
	}

	// Set up HTTP server parameters
	mg_set_protocol_http_websocket(nc);
	s_http_server_opts.document_root = ".";  // Serve current directory
	s_http_server_opts.enable_directory_listing = "yes";

	for (;;) {
		mg_mgr_poll(&mgr, 1000);
	}
	mg_mgr_free(&mgr);

	return 0;
}

**Comment by marcelwirtz** [comment]
@yezhang Could you solve this problem? I am facing the same issue.
