### ISSUE TITLE
permanently crashing on https GET on ESP32

### ISSUE THREAD

**Issue by di9it** [cesanta/mongoose#852]
1. Get empty project
2. Update config
 config_schema:
   - ["device.id", "UUID"]
   - ["wifi.sta.enable", true]
   - ["wifi.sta.ssid", "XXXX"]
   - ["wifi.sta.pass", "****"]
   - ["wifi.ap.enable", false]
3. Paste [main.cpp](https://goo.gl/nB1aoa) contents
4. Build and flash firmware (i.e.): 
mos build --local --repo ~/src/mongoose-os \
--platform esp32 && mos flash --port /dev/tty.SLAB_USBtoUART \
--platform esp32 && mos console --port /dev/tty.SLAB_USBtoUART
@cesantabot

**Comment by dimonomid** [comment]
Couldn't reproduce this.

I had to adjust the code a bit because the mgos API have diverged, so the actual code I tried is there: https://gist.github.com/dimonomid/9d51ec2ac117fd089338dcb39029e78f

Worked as intended.
