### ISSUE TITLE
"Invalid option: [enable_directory_listing]" in 6.9

### ISSUE THREAD

**Issue by MasterGroosha** [cesanta/mongoose#858]
As title says, I have the following error in version 6.9, however, it works fine with 6.5
The latest documentation for 6.9 states, that this is a valid option: https://docs.cesanta.com/mongoose_binary/master/#/config-reference/enable_directory_listing.md/

Currently, I have `enable_directory_listing no` in my config.

**Comment by cpq** [comment]
Use `enable_dir_listing`
