### ISSUE TITLE
Two-way SSL

### ISSUE THREAD

**Issue by hendrikw01** [cesanta/mongoose#861]
I have some trouble to get two-way ssl working.
After i configured the server with `bind_opts->ssl_ca_cert`, only the first request is successful. Every subsequent request like css, js ,... fails with an ssl error.
With the following change, I can fix this issue:
```
-   SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER | SSL_VERIFY_FAIL_IF_NO_PEER_CERT, 0);
+   SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER | SSL_VERIFY_FAIL_IF_NO_PEER_CERT | SSL_VERIFY_CLIENT_ONCE, 0);
```

But it doesn´t fix secure webSockets. 

`WebSocket network error: The operation couldn’t be completed. (OSStatus error -9829.)`

It is possible to get webSockets with two-way ssl to work?

**Comment by cpq** [comment]
Yes, sure.

Note that SSL setup API has changed, see example at https://github.com/cesanta/mongoose/tree/master/examples/http-client
