### ISSUE TITLE
Documentation: broken link in captive_dns_server comment.

### ISSUE THREAD

**Issue by willmoffat** [cesanta/mongoose#866]
The goo.gl link on this line is broken:
https://github.com/cesanta/mongoose/blob/master/examples/captive_dns_server/captive_dns_server.c#L47

**Comment by dimonomid** [comment]
Hmm indeed, I'm not sure how we managed to paste broken goo.gl URL
Need to re-google it

**Comment by cpq** [comment]
Refactored https://github.com/cesanta/mongoose/tree/master/examples/captive-dns-server
Closing this
