### ISSUE TITLE
Read User Guide and API reference link broken

### ISSUE THREAD

**Issue by passwordleak** [cesanta/mongoose#873]
Read User Guide and API reference

https://docs.cesanta.com/mongoose

I can't seem to get the compiled "server" to use a certain directory, and the --help flag doesn't even work. Can't set the port either with the -p flag. 

so much for quick and easy to use. this shit sucks more than cancer lol

Windows Server 2008R2

**Comment by dimonomid** [comment]
Thanks, fixed ( now the link references https://cesanta.com/docs/overview/intro.html )
