### ISSUE TITLE
License: some more explanation required

### ISSUE THREAD

**Issue by sbabic** [cesanta/mongoose#885]
Hi Sergey,

I need (sorry for that) an additional information about licensing for Mongoose Webserver. I admit that I have not fully understood and I beg your pardon if the issue was already cleared for most people. I am using an old version (still released under MIT), just because I am not sure about your licensing model.

This is clear for me:
https://github.com/cesanta/mongoose/blob/master/LICENSE

Mongoose is licensed under GPLv2 and "alternatively" under commercial. As usual, if I take mongoose and I respect GPLv2 in my GPLv2 project, this is allowed. The file  LICENSE fits very well with GPLv2.

What is worrying me is your answer here:
https://github.com/cesanta/mongoose/issues/457

and the "LIcensing" in the README file. You said:
"That means that if your project is not commercial (open source), then GPLv2 covers it perfectly, and the usage is free.
On the other hand, if mongoose is used commercially (e.g. in a paid product that ships to customers) then a license fee should be paid to us (Cesanta Software)."

A project can be commercial even if it is open source - I think we both are paid for commercial support, even if we not ask for runtime license. The phrase "a paid product that ships to customer" raises some questions. A commercial product (=a physical device) can contains a lot of GPLv2 code (first of them, the Linux Kernel) and nevertheless nothing is due as runtime licenses if the manufacturer obeys to GPLv2, providing sources, maintaining Copyright, etc. So should we understand your phrase as "if you take mongoose in a closed source software (that is, you are not GPLv2 compliant), then a license fee should be paid to us (Cesanta Software)."  ? Please clarify this, thanks.

Best regards,
Stefano

**Comment by cpq** [comment]
Hi Stefano!

I am not a lawyer thus cannot advise on the license question.
All I could say that if GPLv2 covers your end-product, whatever it is, then use it.
If not - ask us for a commercial license.

Whether GPLv2 covers your end-product or not, ask for an independent advise.
