### ISSUE TITLE
How to compile ssl webserver on ESP32

### ISSUE THREAD

**Issue by onepas** [cesanta/mongoose#895]
Dear,
I found example:
https://github.com/cesanta/mongoose/tree/master/examples/simplest_web_server_ssl

but on esp32 how can I embedded pem files? or can I use cert as string content?

`
  bind_opts.ssl_cert = s_ssl_cert;
  bind_opts.ssl_key = s_ssl_key;
`

**Comment by snahmad** [comment]
Have you sort out this compilation error?

**Comment by cpq** [comment]
Please see https://github.com/cesanta/mongoose/tree/master/examples/http-client for an example.
There is an example for ESP32, too.
