### ISSUE TITLE
How to password protect access to index_files?

### ISSUE THREAD

**Issue by smoochy** [cesanta/mongoose#898]
Hello,

I am using a little statistics tool for Bitcoin trading (PTTracker), which is built on mongoose server. I am using a Windows Server 2016 on a VPS. Currently using the free version of mongoose server.

I am access the statistics file remotely via http://[IPofVPS]:[Port]

I tried to figure out, how to tell mongoose to password protect the access to the file. I came across https://github.com/GerHobbelt/mongoose-vanilla/wiki/Windows-Usage and was able to create a password file, but I don't know how to tell mongoose to use this file. https://github.com/octo/mongoose/blob/master/win32/mongoose.conf is not working.

Help would be appreciated, thank you.

**Comment by cpq** [comment]
You could protect directory access, not file access.
