### ISSUE TITLE
Windows version is flagged by 24 antivirus....

### ISSUE THREAD

**Issue by propergol** [cesanta/mongoose#901]
Something in the code of the Windows install file is flagged by 24 AV on Virustotal : 
https://www.virustotal.com/fr/file/6d0931422494e66aefc96ac4d76808ce6da274c120350bad86ff4df6f9e64623/analysis/1519051920/

I did test the trial install file and bought the pro version : same issue.

Can you please comment?

**Comment by Seikilos** [comment]
Same happened here. The file differs from v6.5 significantly as it is only ~144kb in size, where 6.5 was ~532kb

**Comment by group131** [comment]
Any fix?

**Comment by icie-y** [comment]
+1 because the file mongoose-free-6.9.exe was marked as malicious by the security team in my university

**Comment by group131** [comment]
In my case I ended up using version 6.5. So my question is: Why is version 6.5 not flagged? What's the difference?

**Comment by rojer** [comment]
nothing substantial. we use the same toolchain to build binaries, nothing really changed since 6.5 (apart from features and bugfixes).

**Comment by cpq** [comment]
@group131 , you've been told that mongoose.exe has no malicuous code inside.

If you're paranoid, don't use the binary, it is that simple.

**Comment by AdminUser0** [comment]
> 
> 
> @group131 , you've been told that mongoose.exe has no malicuous code inside.
> 
> If you're paranoid, don't use the binary, it is that simple.

nice answer!
