### ISSUE TITLE
where is the  mongoose — lightweight web server ?

### ISSUE THREAD

**Issue by sergiomb2** [cesanta/mongoose#904]
/usr/bin/mongoose from version 3.1  have one man page [1] in the newest version where is it ? 
or what happened ?

[1] 
NAME
     mongoose — lightweight web server

SYNOPSIS
     mongoose [config_file] [OPTIONS]
     mongoose -A htpasswd_file domain_name user_name password

DESCRIPTION
     mongoose is small, fast and easy to use web server with CGI, SSL, MD5 authorization, and basic SSI support.

**Comment by cpq** [comment]
Hi.

It is right here, in this repository.
