### ISSUE TITLE
Memory corrupted when tries to send data to an unreachable address

### ISSUE THREAD

**Issue by paladin-t** [cesanta/mongoose#905]
Environment: Windows 7 64bit, Visual C++ 2015 (Debug), either latest stable release or head master revision

I'm just messing with the `udp_client.c`, when I pass `127.0.0.1:17000 hello` to the program (the address is unreachable), it invokes the callback with freed memory where has been tagged `0xdddddddd...`.

![1](https://user-images.githubusercontent.com/2062224/37330529-5927a13c-26dc-11e8-975d-5a3bd8914699.png)

![2](https://user-images.githubusercontent.com/2062224/37330535-5e6727a8-26dc-11e8-9b19-086d20390395.png)

Furthermore, it tries to free that chunk of memory at `mbuf_free` (during `mg_mgr_free`), which already has been freed, when I modify the source to only polling once.

![3](https://user-images.githubusercontent.com/2062224/37330542-66504aee-26dc-11e8-8a8f-4e3dd3e4ab99.png)

Thanks.

**Comment by cpq** [comment]
Could you reproduce this with the latest code ?

**Comment by paladin-t** [comment]
The corruption is gone. It's infinite wait now, I suppose it is expected behaviour.

![图片](https://user-images.githubusercontent.com/2062224/102180423-ce071100-3ee3-11eb-908b-18f03a4badcb.png)

**Comment by cpq** [comment]
Excellent, thank you for investing time into it.

Closing this issue.
