### ISSUE TITLE
Files missing from src/

### ISSUE THREAD

**Issue by numo68** [cesanta/mongoose#906]
Quite a few of `cs_*` header and source files such as `common/cs_base64.c`, `common/cs_sha1.c` and similar are missing from the unamalgamated copy. `amalgam.py --strict` reports errors.

The `mongoose.h`/`.c` files als contain inconsistent file names - sometimes with the `src` prefix, sometimes not. That means that using `unamalgam.py` produces something else than what is committed.

I wonder what the workflow of the developers at Cesanta actually is - do you edit the amalgamated file and generate the unamalgamated ones, or the opposite? Where is the "master"?

**Comment by cpq** [comment]
Fixed, thanks for reporting.
