### ISSUE TITLE
connect to server failed with websocket in safari on macos

### ISSUE THREAD

**Issue by junbrave1** [cesanta/mongoose#908]
hi all,
i am using mongoose to set up a local websocket server, and then connect it with websocket on the browser. 
it is pretty good on firefox or chrome, but it is not working on safari. 

will you plan to support sarari some day?

**Comment by cpq** [comment]
Please use the latest code. It works with Safari just fine.

Note that Safari has a strict mixed content rules, so if you serve your HTML pages via HTTPS, then your websocket calls also should use TLS/SSL.
