### ISSUE TITLE
Incorrect parameters to mg_bind sample also mentioned in #590

### ISSUE THREAD

**Issue by sanyaade-iot** [cesanta/mongoose#914]
Hi Everybody,

**doesn't seem to have gone/done though!**

I had the same problem but surprisingly work if ev_handler and NULL are swapped e.g.
**nc = mg_bind(&mgr, s_http_port, NULL, ev_handler);**

For me: **nc = mg_bind(&mgr, s_http_port, ev_handler);** and **nc = mg_bind(&mgr, s_http_port, ev_handler, NULL);**  both raises compilation errors. So I have to use the above arguments.

**BTW:** Is there a way to disable **-Werror** from mos tools?
Also can mos tool generate makefile? Or being passed a -f makefile on command line?
These features are needed by developers.

Many thanks!

God blesses!!!

Best regards,
Sanyaade

**Comment by cpq** [comment]
Closing this.
Please use the latest code, which has a slight API change.
