### ISSUE TITLE
can't send data over function width the same adress pointer over websocket!

### ISSUE THREAD

**Issue by bnadem** [cesanta/mongoose#916]
websocket_chat (websocket server) communicate with client websocket , with normat  buffer from terminal

question how i send data from other file to websocket client with function mg_send_websocket_frame, i have the pointer adress nc, but i cann'T send data

**Comment by cpq** [comment]
Closing this.
Not sure what you're asking about - please be more specific.
Feel free to reopen, in which case, use the latest code.
