### ISSUE TITLE
Cannot connect to WIFI with SSID having 32 characters

### ISSUE THREAD

**Issue by jgesser** [cesanta/mongoose#918]
Mongoose gives an error while trying to connect to WIFI with SSID having 32 characters.
It is possible and valid to have an SSID with 32 characters.

My device is an NoceMCU Esp8266.

The same error was happening while using the standard Wifi library and flashing via Arduino IDE.
I have found and fixed the problem there:
https://github.com/esp8266/Arduino/pull/4691

The pull request was not accepted, but this fix was working for me.

**Comment by cpq** [comment]
Closing this.

WiFi connection has nothing to do with Mongoose.
