### ISSUE TITLE
How can I extract  the POST request string? 

### ISSUE THREAD

**Issue by wynter-wang** [cesanta/mongoose#921]
As title, I want to extract  the POST request JSON strings, the http request headers like this:
<pre>
/json/login HTTP/1.1
Host: 192.168.1.100:8088
Connection: keep-alive
Content-Length: 65
Accept: application/json, text/javascript, */*; q=0.01
Origin: http://192.168.1.100:8088
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: http://192.168.1.100:8088/
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9

{"params":{"cmd":"Login","username":"admin","password":"123456"}}
</pre>

So, how can I extract  the json string completely? <pre>{"params":{"cmd":"Login","username":"admin","password":"123456"}}</pre>

The mongoose api `mg_get_http_var` can get a variable only, here:  
<pre>
static void login(struct mg_connection *nc, struct http_message *hm)
{
	char username[32] = {0};
	char password[32] = {0};
	int *error = 0;
	
	mg_get_http_var(&hm->body, "username", username, sizeof(username));
	mg_get_http_var(&hm->body, "password", password, sizeof(password));
        ....  
</pre>

**Comment by harivasista** [comment]
@wynter-wang  were you able to figure out this ? If so, please do let me know.
