### ISSUE TITLE
Websockets client on ESP-IDF

### ISSUE THREAD

**Issue by janoist1** [cesanta/mongoose#923]
I'm trying to use the [websocket_chat_client example ](https://github.com/cesanta/mongoose/blob/master/examples/websocket_chat_client/websocket_chat_client.c)on ESP-IDF platform but the value of `status` on `MG_EV_CONNECT` event is always `-1`, which is a Connection error. What I've done so far is I took the [esp32-idf example](https://github.com/cesanta/mongoose/tree/master/examples/ESP32_IDF), merged it with the websocket-client one, set the chat_server_url to a host where a WS server is listening.

I did not use Docker to compile it, simply run `make -f Makefile.build defconfig && make -f Makefile.build`. Which I guess shouldn't be an issue since the original ESP32_IDF example works properly with the same compilation way.

I'm new in this area, how to start investigating? How to debug?

**Comment by bakhshizadeh** [comment]
may someone give me websocket client example for esp-idf?

**Comment by cpq** [comment]
Closing this.
Please use the latest esp32 example: https://github.com/cesanta/mongoose/tree/master/examples/esp32
You could integrate a websocket client example there : https://github.com/cesanta/mongoose/tree/master/examples/websocket-client
