### ISSUE TITLE
How to use http client for ip connecting other device

### ISSUE THREAD

**Issue by nickypeh** [cesanta/mongoose#930]
Hi , 

I have another apache web server on my computer. 
Using ip on browser i can connect via other devices but using the http client for the mongoose library cannot connect. However, it can connect for the normal url. 

Example  

> static const char *url = "http://www.google.com"

 can work. 
but 

> static const char *url = "http://192.168.1.24:8000"

 cant work. 

I am using the function as follow : 
```
/* Starting Mongoose */
   struct mg_mgr mgr;

  mg_mgr_init(&mgr, NULL);
  mg_connect_http(&mgr, ev_handler, url, NULL, NULL);


  while (exit_flag == 0) {
    mg_mgr_poll(&mgr, 1000);
  }
  mg_mgr_free(&mgr);
```

Please help to advise where did i do wrong ?

**Comment by cpq** [comment]
Please check that you're using the right port. Use `curl` utility to verify.
