### ISSUE TITLE
Shall mg_write_to_socket deal with errno when MG_SEND_FUNC return -1

### ISSUE THREAD

**Issue by sigusr1** [cesanta/mongoose#933]
Hi, on my platform, Amba armv7-a, which use NetX as its TCP/IP stack, although select indicate socket is writable, sometime function send return -1 with errno EAGIN， especially when send lots of data.

So, to handle similar scenarios, shall we deal with errno when MG_SEND_FUNC return -1 ?

**Comment by cpq** [comment]
Closing this.
EAGAIN should be handled transparently, there shouldn't be an issue.
Could you check with the latest code, please?
