### ISSUE TITLE
Windows get dns ip address bug.

### ISSUE THREAD

**Issue by chrisniael** [cesanta/mongoose#946]
https://github.com/cesanta/mongoose/blob/1f5c3fac31804e2129e07f54c6422da2fc3f10da/mongoose.c#L11442

I think getting DNS address by reading registry in windows is not a good way, because in my computer register has an invalid `DhcpNameServer` value in it.

![image](https://user-images.githubusercontent.com/5593254/42885014-75ed6fd6-8ad2-11e8-800c-f853273fa8a0.png)

https://github.com/cesanta/mongoose/blob/1f5c3fac31804e2129e07f54c6422da2fc3f10da/mongoose.c#L11477
And I found, if I have multi DNS address in an entry, it is separated by `space`, not `,`.

![image](https://user-images.githubusercontent.com/5593254/42884984-5ed357fc-8ad2-11e8-9a95-cc6962d16c28.png)

**Comment by cpq** [comment]
Closing this.
The current version does not actually look up DNS server IP, it should be set manually.
