### ISSUE TITLE
CS_PLATFORM for Keil/LWIP

### ISSUE THREAD

**Issue by ksdavis1121** [cesanta/mongoose#947]
I am trying to compile mongoose for use in a stm32 system using Keil and LWIP. Is there a CS_PLATFORM I can select that will work for my needs?

**Comment by cpq** [comment]
We have ported Mongoose OS to the STM32: on L4, F4 and F7 lines.
Meaning, Mongoose Web Server, which is a networking core of Mongoose OS, definitely works on STM32. The environment is GCC, LWIP, FreeRTOS.

We don't have ready-to-go example for Keil, though.

**Comment by cpq** [comment]
Closing this.
Please reopen if that's still an issue for you - in which case, please state your environment - target hardware, OS and compiler version.
