### ISSUE TITLE
Resurrect #753: support for PUT, DELETE, etc methods

### ISSUE THREAD

**Issue by Bklyn** [cesanta/mongoose#949]
I'd like to revisit #753. 

What you've suggested as a solution for #753 is a pretty large amount of code for something that seems like it should be very simple.  In my code I can either:

1. Expose the private function ``mg_connect_http_base`` and reproduce the rest of ``mg_connect_http_opt`` verbatim, which is about 25-30 LOC
2. Copy the logic of ``mg_connect_http_base`` and then call ``mg_connect_opt`` and then reproduce the rest of ``mg_connect_http_opt``, so probably 50-60 LOC.

As a user of this wonderful library I'd much rather have a variant of ``mg_connect_http`` or ``mg_connect_http_opt`` that lets me pass the method explicitly.

**Comment by demsking** [comment]
Any update for this issue?

**Comment by LeafHCode** [comment]
> I'd like to revisit #753.
> 
> What you've suggested as a solution for #753 is a pretty large amount of code for something that seems like it should be very simple. In my code I can either:
> 
> 1. Expose the private function `mg_connect_http_base` and reproduce the rest of `mg_connect_http_opt` verbatim, which is about 25-30 LOC
> 2. Copy the logic of `mg_connect_http_base` and then call `mg_connect_opt` and then reproduce the rest of `mg_connect_http_opt`, so probably 50-60 LOC.
> 
> As a user of this wonderful library I'd much rather have a variant of `mg_connect_http` or `mg_connect_http_opt` that lets me pass the method explicitly.

Any update for this issue? Any pr or example?

**Comment by LeafHCode** [comment]
> I'd like to revisit #753.
> 
> What you've suggested as a solution for #753 is a pretty large amount of code for something that seems like it should be very simple. In my code I can either:
> 
> 1. Expose the private function `mg_connect_http_base` and reproduce the rest of `mg_connect_http_opt` verbatim, which is about 25-30 LOC
> 2. Copy the logic of `mg_connect_http_base` and then call `mg_connect_opt` and then reproduce the rest of `mg_connect_http_opt`, so probably 50-60 LOC.
> 
> As a user of this wonderful library I'd much rather have a variant of `mg_connect_http` or `mg_connect_http_opt` that lets me pass the method explicitly.

Any update for this issue? Any pr or example?

**Comment by cpq** [comment]
Closing this - as the current API is pretty must what you're asked for.
