### ISSUE TITLE
Compilation error in coap examples

### ISSUE THREAD

**Issue by razzorre** [cesanta/mongoose#950]
While compliling in Ubuntu server, there are some errors and warnings showing on the screen

> coapc.c: In function ‘coap_handler’:
> coapc.c:9:30: error: storage size of ‘cm’ isn’t known
>        struct mg_coap_message cm;
>                               ^
> coapc.c:13:21: error: ‘MG_COAP_MSG_CON’ undeclared (first use in this function)
>        cm.msg_type = MG_COAP_MSG_CON;
>                      ^
> coapc.c:13:21: note: each undeclared identifier is reported only once for each function it appears in
> coapc.c:14:7: warning: implicit declaration of function ‘mg_coap_send_message’ [-Wimplicit-function-declaration]
>        mg_coap_send_message(nc, &cm);
>        ^
> coapc.c:17:10: error: ‘MG_EV_COAP_ACK’ undeclared (first use in this function)
>      case MG_EV_COAP_ACK:
>           ^
> coapc.c:18:10: error: ‘MG_EV_COAP_RST’ undeclared (first use in this function)
>      case MG_EV_COAP_RST: {
>           ^
> coapc.c:20:67: error: dereferencing pointer to incomplete type ‘struct mg_coap_message’
>        printf("ACK/RST for message with msg_id = %d received\n", cm->msg_id);
>                                                                    ^
> coapc.c: In function ‘main’:
> coapc.c:42:3: warning: implicit declaration of function ‘mg_set_protocol_coap’ [-Wimplicit-function-declaration]
>    mg_set_protocol_coap(nc);
>    ^

Is there any other library that has to be installed or any software?
Please help

**Comment by cpq** [comment]
Closing this - the COAP support has been removed from the latest codebase.
