### ISSUE TITLE
How to make a multi-thread server

### ISSUE THREAD

**Issue by shelif** [cesanta/mongoose#956]
I 've noticed that in 6.7 there is  an examples, however the **mg_enable_multithreading** is continuously building and destroying thread,I wonder how an more suitable program works,like a threadpool. Besides, in the latest code , I don't found the **mg_enable_multithreading**,instead of an example of multithread which is different  

Just want an example of multi-thread server.

poor-English,sorry

**Comment by CfirTsabari** [comment]
that because the mutli-threading was left out,
i think you should take care of it yourself mg_broadcast could help you do that
