### ISSUE TITLE
[Question]How to make poll to return immediately?

### ISSUE THREAD

**Issue by nezen** [cesanta/mongoose#957]
I'm using mongoose like this
`
while (!s_done) {
        mg_mgr_poll(&mgr, 1000);
    }
`
If I want to make a connection to a server, I have to wait 1sec until the action of connection really starts.
So is there anyway to make poll to return immediately from blocking?

**Comment by nezen** [comment]
``

**Comment by cpq** [comment]
Set the second parameter to 1
