### ISSUE TITLE
[Question]How to make a timer-only "connections" ?

### ISSUE THREAD

**Issue by nezen** [cesanta/mongoose#959]
How to make a timer-only "connections" ?

**Comment by PuKathy** [comment]
Do you mean that using a connection as a timer ?

mg_add_sock(&mgr, INVALID_SOKCET, timer_ev_handler)

**Comment by cpq** [comment]
The new codebase has a separate timer API, which is decoupled from connections.
Please see https://github.com/cesanta/mongoose/tree/master/examples/timers
