### ISSUE TITLE
received SIGSEGV when  call mg_mgr_free

### ISSUE THREAD

**Issue by netexplorer** [cesanta/mongoose#965]
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5ce9700 (LWP 16401)]
0x00000000004099fc in mg_mgr_poll (m=0x629980 <m_opt>, timeout_ms=0) at mongoose.c:2407
2407	    now = m->ifaces[i]->vtable->poll(m->ifaces[i], timeout_ms);
(gdb) bt
#0  0x00000000004099fc in mg_mgr_poll (m=0x629980 <m_opt>, timeout_ms=0) at mongoose.c:2407
#1  0x000000000040986f in mg_mgr_free (m=0x629980 <m_opt>) at mongoose.c:2372
#2  0x0000000000403658 in m_conn_stop (m_opt=0x629980 <m_opt>) at maudio.c:386
#3  0x000000000040374a in mgr_poll_routine (args=0x629980 <m_opt>) at maudio.c:412
#4  0x00007ffff78be184 in start_thread (arg=0x7ffff5ce9700) at pthread_create.c:312
#5  0x00007ffff75eb03d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by cpq** [comment]
Please use the latest codebase
