### ISSUE TITLE
HTTP files larger than 4GB on 32-bit Linux machines

### ISSUE THREAD

**Issue by DavidNovoa** [cesanta/mongoose#973]
When a 32-bit linux system serves files larger than 4GB using HTTP, the files download incomplete.

I think the problem is in the functions "mg_http_transfer_file_data" and "mg_http_serve_file". These functions use variables "size_t" to store file size, in the case of 32-bit systems I think this is wrong.

**Comment by cpq** [comment]
Closing this. I believe it works correctly in the latest codebase.
Feel free to reopen if it does not.
