### ISSUE TITLE
cookie_auth example code have a bug

### ISSUE THREAD

**Issue by heyingjie** [cesanta/mongoose#975]
in get_session function
![image](https://user-images.githubusercontent.com/11901953/45877256-ca04eb00-bdcf-11e8-9592-809ab7164f51.png)
if cookie_header is NULL,will goto clean,but ssid and ret haven't initial yet,then it will cause a segment fault.

**Comment by cpq** [comment]
Thank you.
Fetching credentials is now an API function, `mg_http_creds()`.
There is an example, https://github.com/cesanta/mongoose/tree/master/examples/multiple-logins
Closing this.
