### ISSUE TITLE
The Mg_file_upload_handler function is not very compatible under Windows

### ISSUE THREAD

**Issue by VKingi** [cesanta/mongoose#977]
If uploading a binary file will cause damage to the file, the following is part of the code for mg_file_upload_handler, Mg_fopen The second parameter seems to use  "wb" because the Windows platform line break is  \r\n
~~~c
      ...
      if (lfn.p != mp->file_name) MG_FREE((char *) lfn.p);
      LOG(LL_DEBUG,
          ("%p Receiving file %s -> %s", nc, mp->file_name, fus->lfn));
      fus->fp = mg_fopen(fus->lfn, "w");
      ...
~~~

**Comment by cpq** [comment]
The current HEAD is fixed already:

https://github.com/cesanta/mongoose/blob/dev/src/mg_http.c#L2765

We plan to make a release today or tomorrow, you can fetch it (6.13) or use HEAD.
