### ISSUE TITLE
mg_bind error handling

### ISSUE THREAD

**Issue by feedhandler** [cesanta/mongoose#983]
Hi, just wondering how I can get some kind of error info message if mg_bind() fails? I couldn't find anything in the documentation or examples

e.g from examples/simplest_web_server/simplest_web_server.c
```
  nc = mg_bind(&mgr, s_http_port, ev_handler);
  if (nc == NULL) {
    printf("Failed to create listener\n");
    printf("Error:%s\n", mg_getError()); // <<<<<<<< how to get something like this?
    return 1;
  }
```

**Comment by lennytmp** [comment]
You can do this with `mg_bind_opt()` already:
```
struct mg_bind_opts opts;
memset(&opts, 0, sizeof(opts));
const char *err = NULL;
opts.error_string = &err;

nc = mg_bind_opt(&mgr, s_http_port, ev_handler, opts);
if (nc == NULL) {
  fprintf(stderr, "mg_bind(%s) failed: %s\n", s_http_port, err);
  return 1;
}
```

The error at times is not very useful though :( For example, it was "failed to open listener" when the real issue was that the port was already in use.

**Comment by cpq** [comment]
Please use the system's `errno`.
