### ISSUE TITLE
reopen TCP port( mg_bind) after close port open by TCP client application (running on windows)

### ISSUE THREAD

**Issue by snahmad** [cesanta/mongoose#985]
11:09PM in Mongoose Networking Library
Reopen TCP port after close and stop

on ESP32.

see this example : https://github.com/cesanta/mongoose/blob/master/examples/tcp_echo_server/echo_server

after I stop using mg_mgr_free and do mg_mgr_init again then mg_bind failed.

**Comment by snahmad** [comment]
This works on Windows but fail on esp32. when client is connected,

**Comment by snahmad** [comment]
I get this failed to open listener

**Comment by snahmad** [comment]
Mongoose error description:
failed to open listener

Only failed on ESP32. LWIP

**Comment by snahmad** [comment]
I raise same issue with more detail explanation on ESP32 forum as well.

https://esp32.com/viewtopic.php?f=13&t=8972

**Comment by cpq** [comment]
Please use the latest code.
