### ISSUE TITLE
Occasionally high CPU occupancy rate for HTTPS requests by using CGI

### ISSUE THREAD

**Issue by guangjung** [cesanta/mongoose#988]
My platform: unix ;  CPU memory is only 126M.
I have the following experiment.
step1.  start web server that supports https and CGI;
step2.  visit web server by https.  Google browser is loading index.html , including the follow size files:
index.html (about 6 KB); main.css (about 160 KB);  index.css	(about 36.7 KB); 	
*.js	(about 200 KB); *.js  (about 230 KB) ; etc.
**At this time, CPU occupancy rate is up to 96%.**
step3. after a while , CPU  occupancy rate is down to 1%.
step4. send CGI request (about 600 bytes)by https every 30s.   CPU occupancy rate will be up to 96% again at some time. **Why ?**

linux top command log:
/*(1)loading index.html or  problem occurs*/
Mem: 48048K used, 71736K free, 0K shrd, 344K buff, 10852K cached
CPU: 91.8% usr  5.7% sys  0.0% nic  0.0% idle  0.0% io  2.3% irq  0.0% sirq
Load average: 0.80 0.35 0.23 2/39 851
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
   85     1 sshuser  R     4728  3.9   0 96.2 /usr/bin/mongoose
   
Mem: 48048K used, 71736K free, 0K shrd, 344K buff, 10852K cached
CPU: 91.3% usr  4.9% sys  0.0% nic  0.0% idle  0.0% io  3.7% irq  0.0% sirq
Load average: 1.00 0.43 0.26 2/39 858
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
   85     1 sshuser  R     4728  3.9   0 95.4 /usr/bin/mongoose

/*(2)normal CPU occupancy rate*/
Mem: 48016K used, 71768K free, 0K shrd, 344K buff, 10860K cached
CPU:  1.7% usr  2.9% sys  0.0% nic 93.2% idle  0.0% io  1.7% irq  0.1% sirq
Load average: 0.76 0.49 0.29 1/39 873
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
   85     1 sshuser  S     4728  3.9   0  1.1 /usr/bin/mongoose

**Comment by guangjung** [comment]
I used openssl-1.0.2p.  open MG_ENABLE_DEBUG.  when the question occurs , mg_ssl_if_ssl_err  calls failed .  debug log as follows:

mg_mgr_handle_conn   0x102449e8 after fd=7 nc_flags=0x830 rmbl=0 smbl=0
mg_mgr_handle_conn   0x10230c30 fd=5 fd_flags=1 nc_flags=0x11 rmbl=0 smbl=0
mg_add_conn          0xbfcfef04 0x1026a700
mg_if_accept_new_con 0x10230c30 0x1026a700 -1 16
mg_accept_conn       0x1026a700 conn from xx.xx.xx.xx:59458
mg_socket_if_sock_se 0x1026a700 9
mg_if_accept_tcp_cb  0x1026a700 tcp://xx.xx.xx.xx:59458
**mg_ssl_if_ssl_err    0x1026a700 0x10230d88 SSL error: 0 5**
mg_mgr_handle_conn   0x10230c30 after fd=5 nc_flags=0x11 rmbl=0 smbl=0
mg_mgr_handle_conn   0x1026a700 fd=9 fd_flags=1 nc_flags=0x810 rmbl=0 smbl=0
mg_call              0x1026a700 proto ev=5 ev_data=(nil) flags=0x810 rmbl=0 smbl=0
mg_call              0x1026a700 user ev=5 ev_data=(nil) flags=0x810 rmbl=0 smbl=0
mg_call              0x1026a700 after user flags=0x810 rmbl=0 smbl=0
mg_call              0x1026a700 after proto flags=0x810 rmbl=0 smbl=0
mg_mgr_handle_conn   0x10244930 fd=8 fd_flags=1 nc_flags=0x30 rmbl=0 smbl=0
mg_ssl_if_read       0x10244930 1460 -> 0
mg_recv_tcp          0x10244930 <- 0 bytes (SSL)
mg_mgr_handle_conn   0x10244930 after fd=8 nc_flags=0x830 rmbl=0 smbl=0
mg_mgr_handle_conn   0x102449e8 fd=7 fd_flags=1 nc_flags=0x830 rmbl=0 smbl=0
mg_call              0x102449e8 proto ev=5 ev_data=(nil) flags=0x830 rmbl=0 smbl=0
mg_call              0x102449e8 user ev=5 ev_data=(nil) flags=0x830 rmbl=0 smbl=0
mg_call              0x102449e8 after user flags=0x830 rmbl=0 smbl=0
mg_call              0x102449e8 after proto flags=0x830 rmbl=0 smbl=0
mg_mgr_handle_conn   0x10230c30 fd=5 fd_flags=1 nc_flags=0x11 rmbl=0 smbl=0
mg_add_conn          0xbfcfef04 0x1026a700
mg_if_accept_new_con 0x10230c30 0x1026a700 -1 16
mg_accept_conn       0x1026a700 conn from xx.xx.xx.xx:59468
mg_socket_if_sock_se 0x1026a700 7
mg_if_accept_tcp_cb  0x1026a700 tcp://xx.xx.xx.xx:59468
mg_ssl_if_ssl_err    0x1026a700 0x10230d88 SSL error: 0 5
mg_mgr_handle_conn   0x10230c30 after fd=5 nc_flags=0x11 rmbl=0 smbl=0
mg_mgr_handle_conn   0x1026a700 fd=7 fd_flags=1 nc_flags=0x810 rmbl=0 smbl=0
mg_call              0x1026a700 proto ev=5 ev_data=(nil) flags=0x810 rmbl=0 smbl=0
mg_call              0x1026a700 user ev=5 ev_data=(nil) flags=0x810 rmbl=0 smbl=0
mg_call              0x1026a700 after user flags=0x810 rmbl=0 smbl=0
mg_call              0x1026a700 after proto flags=0x810 rmbl=0 smbl=0
mg_mgr_handle_conn   0x10244930 fd=8 fd_flags=1 nc_flags=0x830 rmbl=0 smbl=0
mg_call              0x10244930 proto ev=5 ev_data=(nil) flags=0x830 rmbl=0 smbl=0
mg_call              0x10244930 user ev=5 ev_data=(nil) flags=0x830 rmbl=0 smbl=0
mg_call              0x10244930 after user flags=0x830 rmbl=0 smbl=0
mg_call              0x10244930 after proto flags=0x830 rmbl=0 smbl=0
mg_mgr_handle_conn   0x10230c30 fd=5 fd_flags=1 nc_flags=0x11 rmbl=0 smbl=0
mg_add_conn          0xbfcfef04 0x10244b68
mg_if_accept_new_con 0x10230c30 0x10244b68 -1 16
mg_accept_conn       0x10244b68 conn from xx.xx.xx.xx:59477

**Comment by cpq** [comment]
Closing this, as there is no CGI support anymore in the latest codebase.
