### ISSUE TITLE
Error when Make

### ISSUE THREAD

**Issue by nickypeh** [cesanta/mongoose#995]
**Computer OS:**
Mac OS Mojave (version: 10.14.2) 

**Problem:**
Compile the simplest_web_server via terminal and it fails to compile.

**Command inside the examples/simplest_web_server :**

> $ make

**Error :**
`cc simplest_web_server.c ../../mongoose.c -o simplest_web_server -g -W -Wall -Werror -I../.. -Wno-unused-function  -DMG_DISABLE_DAV_AUTH -DMG_ENABLE_FAKE_DAVLOCK -pthread
Undefined symbols for architecture x86_64:
  "_mg_bind", referenced from:
      _main in simplest_web_server-9f53f1.o
  "_mg_mgr_init", referenced from:
      _main in simplest_web_server-9f53f1.o
  "_mg_mgr_poll", referenced from:
      _main in simplest_web_server-9f53f1.o
  "_mg_serve_http", referenced from:
      _ev_handler in simplest_web_server-9f53f1.o
  "_mg_set_protocol_http_websocket", referenced from:
      _main in simplest_web_server-9f53f1.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [simplest_web_server] Error 1
`

Not sure is it i missing some setup ? 

please help.

**Comment by cpq** [comment]
Closing this - the example builds on macos as part of the unit test,
`cd examples/http-restful-server && make`
