### ISSUE TITLE
References to FILE exist when MG_ENABLE_FILESYSTEM is defined to 0

### ISSUE THREAD

**Issue by mill1000** [cesanta/mongoose#996]
There are still references to FILE when MG_ENABLE_FILESYSTEM is defined to 0. This causes compiler errors when compiling against a standard library that does not contain file system support. i.e. IAR's DLib when set to Normal

Currently working around by adding to the platform.
`typedef void FILE;`

**Comment by cpq** [comment]
Thank you.
The latest codebase builds clean with `-DMG_ENABLE_FS=0`
