### ISSUE TITLE
Many warnings during compile

### ISSUE THREAD

**Issue by ustraub** [cesanta/mongoose#997]
Hi,
your code (moongoose.c) is used in the project mympd. In this project the compile step shows many warnings refering to moongoose (see https://github.com/jcorporation/myMPD/issues/79). The author of mympd tells me these warnings should be fixed by the author of moongoose. I agree.
 
Enclosed please find the file mkrelease_out.txt. This file contains the warnings with respect to moongoose in lines 63 to 503. Please ignore the other compiler warnings above that section. The porject mympd was compiled on a raspberry under debian stretch

[mkrelease_out.txt](https://github.com/cesanta/mongoose/files/2730721/mkrelease_out.txt)

**Comment by cpq** [comment]
Please use the latest version.
