### ISSUE TITLE
Handling file uploads example - multipart request end

### ISSUE THREAD

**Issue by ImrichFischer** [cesanta/mongoose#999]
I think it's necessary to add case _MG_EV_HTTP_MULTIPART_REQUEST_END_ in https://github.com/cesanta/mongoose/blob/master/docs/http/upload.md in order uploads to be ended.

```
void ev_handler(struct mg_connection *c, int ev, void *ev_data) {
  switch (ev) {
    ...
    case MG_EV_HTTP_PART_BEGIN:
    case MG_EV_HTTP_PART_DATA:
    case MG_EV_HTTP_PART_END:
    case MG_EV_HTTP_MULTIPART_REQUEST_END:
      mg_file_upload_handler(c, ev, ev_data, cb);
      break;
  }
}
```

**Comment by snahmad** [comment]
Multi-part stop working in latest source. It is working with 1 year old code base.

When I upload file. I don't get MG_EV_HTTP_PART_BEGIN.

**Comment by cpq** [comment]
The multipart handling is not provided by the latest API.
Please use the alternative upload method, see https://github.com/cesanta/mongoose/tree/master/examples/file-upload
